force-app/main/default/objects/Firm__c/Firm__c.object-meta.xml
<CustomObject>
    <label>Firm</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm__c/fields/Date_of_Update__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Update__c</fullName>
    <label>Date of Update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Firm__c/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Firms</relationshipLabel>
    <relationshipName>Firms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Firm__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Firms</relationshipLabel>
    <relationshipName>Firms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Firm__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Firms</relationshipLabel>
    <relationshipName>Firms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FirmHandler.cls
public with sharing class FirmHandler {
	
	public static void createActivityHistory(Map<Id,Opportunity> newMap){
        
        List<Firm__c> lstFirm = new List<Firm__c>();

        Map<Id, Opportunity> opportunitiesMap = new Map<Id, Opportunity>([SELECT Id, (SELECT Id FROM Firms__r) FROM Opportunity WHERE Id IN: newMap.keySet() LIMIT 200]);
        
        for(Opportunity opp : newMap.values()){
            Opportunity oppr = (Opportunity)Trigger.oldMap.get(opp.Id);
            
            if(opp.Law_Firm__c != oppr.Law_Firm__c ||
               opp.Lawyer__c != oppr.Lawyer__c 
               ){
                Firm__c firm = new Firm__c();
                firm.Law_Firm__c = opp.Law_Firm__c;
                firm.Lawyer__c = opp.Lawyer__c;
                firm.Date_of_Update__c = Date.today();
                firm.Opportunity__c = opp.Id;

                if(opportunitiesMap.get(opp.Id).Firms__r.isEmpty()){
                    Firm__c oldFirm = new Firm__c();
                    oldFirm.Law_Firm__c = oppr.Law_Firm__c;
                    oldFirm.Lawyer__c = oppr.Lawyer__c;
                    oldFirm.Date_of_Update__c = Date.today();
                    oldFirm.Opportunity__c = oppr.Id;
                    lstFirm.add(oldFirm);
                }

                lstFirm.add(firm);
            }
        }

        if(lstFirm.size() > 0){
            insert lstFirm; 
        }
    }
}