force-app/main/default/objects/Financial_Summary_Report__c/Financial_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to store filter dates on financial summary report.</description>
    <label>Financial Summary Report</label>
</CustomObject>

force-app/main/default/objects/User/fields/Critical_Items_Dates__c.field-meta.xml
<CustomField>
    <fullName>Critical_Items_Dates__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls the visibility of critical items &amp; dates
 report to the user.</description>
    <label>Critical Items &amp; Dates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Financial_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Financial_Summary_Report__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls the visibility of financial summary report to the user.</description>
    <label>Financial Summary Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Law_Firm_Summary__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm_Summary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls the visibility of law firm summary report to the user.</description>
    <label>Law Firm Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Lawyer_Summary__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Summary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls visibility of lawyer summary report to the user.</description>
    <label>Lawyer Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ReportingViewComponentCtlrTest.cls
@isTest
public class ReportingViewComponentCtlrTest {
    
    public static testMethod void mainTest(){
        
        Test.startTest();
        
        UserRole userRole = new UserRole(DeveloperName = 'TestCustomRole', Name = 'Test Role');
        insert userRole;
        
        User testUser = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'ELFI - Case Management'].Id,
            LastName = 'last',
            Email = 'testuser@example.com',
            Username = 'testuser@example.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            UserRoleId = userRole.Id,
			Lawyer_Summary__c = false, 
            Law_Firm_Summary__c = false,
            Critical_Items_Dates__c = false,
            Financial_Summary_Report__c = false           
        );
        insert testUser;
        
        system.runAs(testUser){
            User currentUser = ReportingViewComponentCtlr.getCurrentUserInfo();
            
            system.assertEquals(false, currentUser.Lawyer_Summary__c);
        }
        
        Test.stopTest();
    }
}