force-app/main/default/objects/Contact_History__c/Contact_History__c.object-meta.xml
<CustomObject>
    <label>Contact History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Contact History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_History__c/fields/Alternate_Phone__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Phone__c</fullName>
    <label>Alternate Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activity_Historys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_History__c/fields/Date_of_update__c.field-meta.xml
<CustomField>
    <fullName>Date_of_update__c</fullName>
    <label>Date of update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/contactTriggerHandler.cls
public without sharing class contactTriggerHandler {
    
    public static void createActivityHistory(Map<Id,Contact> newMap){
        
        List<Contact_History__c> lstActivity = new List<Contact_History__c>();
        
        for(Contact con : newMap.values()){

            contact cnt = (Contact)Trigger.oldMap.get(con.Id);
            
            if(con.Email != cnt.Email ||
               con.Phone != cnt.Phone ||
               con.OtherPhone != cnt.OtherPhone ||
               con.MailingCity != cnt.MailingCity ||
               con.MailingState != cnt.MailingState ||
               con.MailingStreet != cnt.MailingStreet ||
               con.MailingPostalCode != cnt.MailingPostalCode
               ){

                Contact_History__c activity = new Contact_History__c();
                //activity.Address__c =con.MailingCity + ', ' + con.MailingCountry + ', ' + con.MailingState + ', ' + con.MailingStreet + ', ' +con.MailingPostalCode;
                activity.Address__c = con.MailingStreet + '<br/>' + con.MailingCity + ', ' + con.MailingState + '<br/>' + con.MailingPostalCode;
                activity.Email__c = con.Email;
                activity.Alternate_Phone__c = con.OtherPhone;
                activity.Phone__c = con.Phone;
                activity.Date_of_update__c = Date.today();
                activity.Contact__c = con.Id;

                lstActivity.add(activity);
            }
        }

        if(lstActivity.size() > 0){
            insert lstActivity; 
        }
    }
}