force-app/main/default/objects/Actual_Sales_by_Month_Report__c/Actual_Sales_by_Month_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Actual Sales by Month Report</label>
</CustomObject>

force-app/main/default/objects/Bad_Debt_Summary_Report__c/Bad_Debt_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bad Debt Summary Report</label>
</CustomObject>

force-app/main/default/objects/Financial_Summary_Report__c/Financial_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to store filter dates on financial summary report.</description>
    <label>Financial Summary Report</label>
</CustomObject>

force-app/main/default/objects/Funding_Summary__c/Funding_Summary__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Funding Summary</label>
</CustomObject>

force-app/main/default/objects/Law_Firm_Sales_Summary_Report__c/Law_Firm_Sales_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Law Firm Sales Summary Report</label>
</CustomObject>

force-app/main/default/objects/Payment_Summary_Report__c/Payment_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to store filter dates on payment summary report.</description>
    <label>Payment Summary Report</label>
</CustomObject>

force-app/main/default/objects/User/fields/Actual_Sales_By_Month_Report__c.field-meta.xml
<CustomField>
    <fullName>Actual_Sales_By_Month_Report__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Actual Sales By Month Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Bad_Debt_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Bad_Debt_Summary_Report__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Bad Debt Summary Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Critical_Items_Dates__c.field-meta.xml
<CustomField>
    <fullName>Critical_Items_Dates__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls the visibility of critical items &amp; dates
 report to the user.</description>
    <label>Critical Items &amp; Dates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Drawdowns__c.field-meta.xml
<CustomField>
    <fullName>Drawdowns__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Drawdowns</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Financial_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Financial_Summary_Report__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls the visibility of financial summary report to the user.</description>
    <label>Financial Summary Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Financing_Statement_Details__c.field-meta.xml
<CustomField>
    <fullName>Financing_Statement_Details__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Financing Statement Details</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Funding_Dashboard__c.field-meta.xml
<CustomField>
    <fullName>Funding_Dashboard__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Funding Dashboard</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Funding_Summary__c.field-meta.xml
<CustomField>
    <fullName>Funding_Summary__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Funding Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Law_Firm_Sales_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm_Sales_Summary_Report__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Law Firm Sales Summary Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Law_Firm_Summary__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm_Summary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls the visibility of law firm summary report to the user.</description>
    <label>Law Firm Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Lawyer_Sales_Summary__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Sales_Summary__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lawyer Sales Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Lawyer_Summary__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Summary__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field controls visibility of lawyer summary report to the user.</description>
    <label>Lawyer Summary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Loan_Set_up__c.field-meta.xml
<CustomField>
    <fullName>Loan_Set_up__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Loan Set-up</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Lump_Sum_drawdowns__c.field-meta.xml
<CustomField>
    <fullName>Lump_Sum_drawdowns__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Lump Sum drawdowns</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Payment_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Payment_Summary_Report__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Payment Summary Report</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Payments_tab__c.field-meta.xml
<CustomField>
    <fullName>Payments_tab__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Payments tab</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Payout_Details__c.field-meta.xml
<CustomField>
    <fullName>Payout_Details__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Payout Details</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ReportingViewComponentCtlr.cls
public with sharing class ReportingViewComponentCtlr {
    
    @AuraEnabled
    public static User getCurrentUserInfo(){
        User currentUser = [SELECT Id,isActive,ProfileId, Lawyer_Summary__c, Law_Firm_Summary__c, Critical_Items_Dates__c,
                            Financial_Summary_Report__c, Payment_Summary_Report__c,Actual_Sales_By_Month_Report__c, 
                            Drawdowns__c, Loan_Overview_Edit__c,Law_Firm_Sales_Summary_Report__c,Lawyer_Sales_Summary__c,
                            Financing_Statement_Details__c, Loan_Set_up__c, Lump_Sum_drawdowns__c, Payments_tab__c,
                            Funding_Summary__c,Funding_Dashboard__c,
                            Bad_Debt_Summary_Report__c, Payout_Details__c FROM User Where Id = :UserInfo.getUserId()];
        return currentUser;
    } 
}