force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Prospective Lawyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Treatment Provider Firm</fullName>
            </value>
            <value>
                <fullName>Assessment Funding</fullName>
            </value>
            <value>
                <fullName>Litigation Lender</fullName>
            </value>
            <value>
                <fullName>Assessment Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/How_did_you_hear_about_us__c.field-meta.xml
<CustomField>
    <fullName>How_did_you_hear_about_us__c</fullName>
    <label>How did you hear about us</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the key person to contact about inquiries related to this account: loan related, additional information, payments, receivables, etc.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>There are no contacts under this account that matches the search criteria.</errorMessage>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Please select the contact that will serve as primary contact for this account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Related_Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Related_Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Web_to_Lead_From__c.field-meta.xml
<CustomField>
    <fullName>Web_to_Lead_From__c</fullName>
    <label>Web to Lead From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <description>Mapped from the lead conversion process</description>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/How_did_you_hear_about_us__c.field-meta.xml
<CustomField>
    <fullName>How_did_you_hear_about_us__c</fullName>
    <label>How did you hear about us</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Better Business Bureau Website</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Google/Bing Search</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>friend</fullName>
            </value>
            <value>
                <fullName>MoneySaver</fullName>
            </value>
            <value>
                <fullName>Shoppers Source</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Related_Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Related_Law_Firm__c</fullName>
    <formula>Account.Related_Law_Firm__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related Law Firm</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Web_To_Lead_From__c.field-meta.xml
<CustomField>
    <fullName>Web_To_Lead_From__c</fullName>
    <label>Web To Lead From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application Form</fullName>
            </value>
            <value>
                <fullName>Get Help Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Funding_Requested__c.field-meta.xml
<CustomField>
    <fullName>Funding_Requested__c</fullName>
    <label>Funding Requested</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/How_did_you_hear_about_us__c.field-meta.xml
<CustomField>
    <fullName>How_did_you_hear_about_us__c</fullName>
    <label>How did you hear about us</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Better Business Bureau Website</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Google/Bing Search</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Friend</fullName>
            </value>
            <value>
                <fullName>MoneySaver</fullName>
            </value>
            <value>
                <fullName>Shoppers Source</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Law_Firm_Name_new__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm_Name_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Web_To_Lead_From__c.field-meta.xml
<CustomField>
    <fullName>Web_To_Lead_From__c</fullName>
    <label>Web To Lead From</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Application Form</fullName>
            </value>
            <value>
                <fullName>Get Help Form</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT( Account.Account_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Funding_Requested__c.field-meta.xml
<CustomField>
    <fullName>Funding_Requested__c</fullName>
    <label>Funding Requested</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/leadHelper.cls
public with sharing class leadHelper {

    public static void convertToContact(List<Lead> lstLead, Map<Id, Lead> oldMap) {

       if(trigger.isUpdate) {
            RecordType customerType = [Select Id FROM RecordType WHERE SObjectType = 'Lead' AND DeveloperName LIKE '%Customer%' LIMIT 1];
            Map<Id, Lead> mapLead = new Map<Id, Lead>();
            Map<Id, Lead> mapForLeadToOpp = new Map<Id, Lead>();
            Map<Id, Lead> mapForLeadToAccount = new Map<Id, Lead>();

            for(Lead ld : lstLead) {
                // AppCentrica 2017-04-05 - If Lead Record Type is not Customer or blank, skip it!
                // AppCentrica 2017-04-05 - Also restrict to only just-converted Leads
                Boolean justConverted = ld.IsConverted && !oldmap.get(ld.id).IsConverted;
                Boolean rightType = ld.RecordTypeId == null || ld.RecordTypeId == customerType.Id;
                if (!justConverted || !rightType) continue;
                
                mapLead.put(ld.ConvertedContactId,ld);  
                mapForLeadToOpp.put(ld.ConvertedOpportunityId,ld);
                mapForLeadToAccount.put(ld.ConvertedAccountId,ld);              
            }
           
            // AppCentrica 2017-04-05 - if no Leads were retained, quit
            if (mapLead.size() == 0) return;
           
            List<Contact> lstCon = new List<Contact>();         
            List<Contact> lstCont = [select Id, Birthdate,
                                            Phone,
                                            Company__c,
                                            OtherPhone,
                                            How_did_you_hear_about_us__c,
                                            Web_To_Lead_From__c,
                                            Status__c
                                            from Contact 
                                            where Id IN : mapLead.keySet()];

            List<Opportunity> lstOp = new List<Opportunity>();          
            List<Opportunity> lstOpp = [select Id, 
                                               Amount, 
                                               Funding_Requested__c 
                                               from Opportunity 
                                               where Id IN : mapForLeadToOpp.keySet()];

            List<Account> lstAc = new List<Account>();          
            List<Account> lstAcc = [select Id, 
                                           Account_Type__c 
                                           from Account 
                                           where Id IN : mapForLeadToAccount.keySet()];
            
            if(lstCont.size() > 0){
                for(Contact cn : lstCont) {
                    cn.Birthdate = mapLead.get(cn.Id).DOB__c;
                    cn.Phone = mapLead.get(cn.Id).Phone;
                    cn.Company__c = mapLead.get(cn.Id).Company;
                    cn.OtherPhone = mapLead.get(cn.Id).MobilePhone;
                    cn.How_did_you_hear_about_us__c = mapLead.get(cn.Id).How_did_you_hear_about_us__c;
                    cn.Web_To_Lead_From__c = mapLead.get(cn.Id).Web_To_Lead_From__c;
                    cn.Status__c = mapLead.get(cn.Id).Status;
                    lstCon.add(cn);
                }
            }           
            update lstcon;

            if(lstOpp.size() > 0){
                for(Opportunity op : lstOpp) {
                    op.Amount = mapForLeadToOpp.get(op.Id).Loan_Amount__c;
                    op.Funding_Requested__c = mapForLeadToOpp.get(op.Id).Funding_Requested__c;
                    //op.Primary_Contact__c = mapForLeadToOpp.get(op.Id).Primary_Contact__c;                    
                    /**
                     * Wendy's feedback on 7/26
                     */
                    op.Primary_Contact__c = lstcon[0].Id;
                    op.Amount= 0;
                    lstOp.add(op);
                }
            }           
            update lstOp;

            if(lstAcc.size() > 0){
                for(Account ac : lstAcc) {
                    ac.Account_Type__c = mapForLeadToAccount.get(ac.Id).Account_Type__c;
                    ac.Related_Law_Firm__c = mapForLeadToAccount.get(ac.Id).Law_Firm_Name_new__c;
                    lstAc.add(ac);
                }
            }           
            update lstAc;
        }
    }
}