force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Prospective Lawyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Treatment Provider Firm</fullName>
            </value>
            <value>
                <fullName>Assessment Funding</fullName>
            </value>
            <value>
                <fullName>Litigation Lender</fullName>
            </value>
            <value>
                <fullName>Assessment Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Authorization_Clause__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Clause__c</fullName>
    <description>This field is used to dynamically show the &#39;conflict/interest&#39; clause in the loan document.</description>
    <label>Authorization Clause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the key person to contact about inquiries related to this account: loan related, additional information, payments, receivables, etc.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>There are no contacts under this account that matches the search criteria.</errorMessage>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Please select the contact that will serve as primary contact for this account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client Accounts</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Lawyer, Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Payout_Date_Lawyer_Summary_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lawyers.recordType-meta.xml
<RecordType>
    <fullName>Lawyers</fullName>
    <active>true</active>
    <description>Use this record type to track lawyers</description>
    <label>Lawyers</label>
</RecordType>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
    <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
    <label>Minimum Interest Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
    <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lump-Sum Admin Fee</fullName>
            </value>
            <value>
                <fullName>Lump-Sum Amount Paid to Borrower</fullName>
            </value>
            <value>
                <fullName>Facility Drawdown</fullName>
                <default>true</default>
                <label>Facility Drawdown</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/Drawdown_Payment_Allocation__c.object-meta.xml
<CustomObject>
    <description>All Payment allocations to Drawdowns.</description>
    <label>Drawdown Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdown Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <inlineHelpText>The Payout Date replicated down from the Opportunity.  It&#39;s required hear for the DLRS to trigger aggregation.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT( Account.Account_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DrawdownPaymentAllocatorTest.cls
@isTest
public class DrawdownPaymentAllocatorTest {
@TestSetup
    static void initailizeTestData(){        
        List<Account> accountList = new List<Account>();
        List<Contact> contactList = new List<Contact>();
        
        accountList.add( new Account(Name = 'Test Client Account', Authorization_Clause__c = 'No', 
                                     RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId()));
        accountList.add( new Account(Name = 'Test LawFirm Account', Authorization_Clause__c = 'No', 
                                     RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId()));
        accountList.add( new Account(Name = 'Firm Account', Account_Type__c = 'Treatment Provider Firm',
                                     RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('General Business').getRecordTypeId()));
        
        insert accountList;
        
        contactList.add( new Contact(LastName = 'Test Client Contact', AccountId = accountList[0].Id,
                                     RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId()));
        contactList.add( new Contact(LastName = 'Test Lawyer Contact', AccountId = accountList[1].Id,
                                     RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lawyers').getRecordTypeId()));
        insert contactList;
        
        List<Opportunity> oppList = new List<Opportunity>();        
        for(Integer i=0; i < 1; i++){
            oppList.add(new Opportunity(AccountId = accountList[0].Id,
                                        Name = 'Test Opportunity ' + i,
                                        Lawyer__c = contactList[1].Id,
                                        CloseDate = Date.today().addDays(14),
                                        StageName = 'Closed With Loan',
                                        Law_Firm__c = accountList[1].Id,
                                        Stage_Status__c = 'Approved',
                                        Payout_Date__c = Date.newInstance(2018,01,01),
                                        Type_of_Loan__c = 'Facility Loan',
                                        Primary_Contact__c = contactList[0].Id,
                                        Minimum_Interest_Period__c = '0 months',
                                        Compounding_Interest__c = 'Monthly',
                                        Interest_Compounding_Period__c = 'Compounding Interest',
                                        Interest_Rate__c = 15.0,
                                        RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId()
                                       ));
            
        }                
        insert oppList;        
        insertDrawdowns(oppList);
    }
    public static void insertDrawdowns(List<Opportunity> oppList){
        List<Drawdown__c> drawdownList = new List<Drawdown__c>();
        for(Opportunity opp : oppList){
            
            drawdownList.add(new Drawdown__c(Type__c = 'Facility Drawdown', Date__c = Date.newInstance(2018,01,01), Opportunity__c = opp.Id,
                                             Amount__c = 10000, Payment_Method__c ='e-Transfer', Payout_Date__c = Date.newInstance(2018,01,01),
                                             Reference_Notes__c = 'Payment to Client')); 
            
            drawdownList.add(new Drawdown__c(Type__c = 'Facility Drawdown', Date__c = Date.newInstance(2018,01,01), Opportunity__c = opp.Id,
                                             Amount__c = 2000, Payment_Method__c ='Payment', Payout_Date__c = Date.newInstance(2018,01,01),
                                             Reference_Notes__c = 'Partial Payment'));            
            
        }
        
        if(drawdownList.size() > 0){
            insert drawdownList;
        }
    }
    
    public static testMethod void testUpdatePayoutDateOnInsert(){
        Test.startTest();
        List<Opportunity> opps = [select Id from Opportunity];
        List<Drawdown__c> drawdowns = new List<Drawdown__c>();
        Date dt = Date.newInstance(2019,01,01);
        Opportunity opp = opps[0];
        //for (Opportunity opp : opps)
        {
            Drawdown__c drawdown = new Drawdown__c(Type__c = 'Facility Drawdown', Date__c = dt, Opportunity__c = opp.Id,
                                             Amount__c = 2000, Payment_Method__c ='Payment', Payout_Date__c = Date.newInstance(2018,01,01),
                                             Reference_Notes__c = 'Partial Payment');
            drawdowns.add(drawdown);
        }
        insert drawdowns;
        opps = [select Id, Payout_Date__c from Opportunity];        
        System.assertEquals(false, opps.isEmpty() );
    	opp = opps[0];
        //for (Opportunity opp : opps)
        {
            System.assertEquals(dt, opp.Payout_Date__c);
        }
        Test.stopTest();
    }
    public static testMethod void testUpdatePayoutDateOnUpdate(){
        Test.startTest();
        List<Opportunity> opps = [select Id from Opportunity];
        List<Drawdown__c> drawdowns = [select Id, Date__c, Opportunity__c from Drawdown__c where Payment_Method__c='Payment' LIMIT 2];
        List<Id> oppIds = new List<Id>();
        System.assertEquals(false, drawdowns.isEmpty() );
        Date dt = Date.newInstance(2019,01,01);
        for (Drawdown__c drawdown : drawdowns){
            drawdown.Date__c = dt;
            oppIds.add(drawdown.Opportunity__c);
        }        
        update drawdowns;
        opps = [select Id, Payout_Date__c from Opportunity where Id in :oppIds];        
        System.assertEquals(false, opps.isEmpty() );
        for (Opportunity opp : opps){
            System.assertEquals(dt, opp.Payout_Date__c);
        }
        Test.stopTest();
    }
    
    public static testMethod void testDeletePaymentAllocationsOnAmountChange(){
        Test.startTest();
        List<Opportunity> opps = [select Id from Opportunity];
        List<Drawdown__c> drawdowns = [select Id, Date__c, Amount__c from Drawdown__c where Payment_Method__c='Payment' LIMIT 1];
        System.assertEquals(false, drawdowns.isEmpty() );
        List<Drawdown_Payment_Allocation__c> paymentAllocations = [select Id, payment__c from Drawdown_Payment_Allocation__c];
        System.assertEquals(false, paymentAllocations.isEmpty() );
        drawdowns[0].Amount__c = drawdowns[0].Amount__c + 1;
        List<Id> updatedIDs = new List<Id>();
        updatedIDs.add(drawdowns[0].Id);
        paymentAllocations = [select Id from Drawdown_Payment_Allocation__c where payment__c in :updatedIDs];    
        System.assertEquals(false, paymentAllocations.isEmpty() );                
        update drawdowns;
        List<Drawdown_Payment_Allocation__c> paymentAllocationsAfterUpdate = [select Id, Payment__c from Drawdown_Payment_Allocation__c where payment__c in :updatedIDs];
    	System.assertEquals(false, paymentAllocationsAfterUpdate.isEmpty() );        
        System.assertNotEquals(paymentAllocationsAfterUpdate[0], paymentAllocations[0]);

        Test.stopTest();
    }
    
    public static testMethod void testDeletePaymentAllocationsOnPaymentMethodChange(){
        Test.startTest();
        List<Opportunity> opps = [select Id from Opportunity];
        List<Drawdown__c> drawdowns = [select Id, Date__c, Amount__c from Drawdown__c where Payment_Method__c='Payment' LIMIT 1];
        System.assertEquals(false, drawdowns.isEmpty() );
        List<Drawdown_Payment_Allocation__c> paymentAllocations = [select Id, payment__c from Drawdown_Payment_Allocation__c];
        System.assertEquals(false, paymentAllocations.isEmpty() );
        drawdowns[0].Payment_Method__c = 'e-Transfer';
        List<Id> updatedIDs = new List<Id>();
        updatedIDs.add(drawdowns[0].Id);
        paymentAllocations = [select Id from Drawdown_Payment_Allocation__c where payment__c in :updatedIDs];    
        System.assertEquals(false, paymentAllocations.isEmpty() );                
        update drawdowns;
        List<Drawdown_Payment_Allocation__c> paymentAllocationsAfterUpdate = [select Id, Payment__c from Drawdown_Payment_Allocation__c where payment__c in :updatedIDs];
    	System.assertEquals(true, paymentAllocationsAfterUpdate.isEmpty() );        
        Test.stopTest();
    }
    
    public static testMethod void testDeletePaymentAllocationsOnDateChange(){
        Test.startTest();
        List<Opportunity> opps = [select Id from Opportunity];
        List<Drawdown__c> drawdowns = [select Id, Date__c, Amount__c from Drawdown__c where Payment_Method__c='Payment' LIMIT 1];
        System.assertEquals(false, drawdowns.isEmpty() );
        List<Drawdown_Payment_Allocation__c> paymentAllocations = [select Id, payment__c from Drawdown_Payment_Allocation__c];
        System.assertEquals(false, paymentAllocations.isEmpty() );
        drawdowns[0].Date__c = Date.newInstance(2019, 1, 1);
        List<Id> updatedIDs = new List<Id>();
        updatedIDs.add(drawdowns[0].Id);
        paymentAllocations = [select Id from Drawdown_Payment_Allocation__c where payment__c in :updatedIDs];    
        System.assertEquals(false, paymentAllocations.isEmpty() );                
        update drawdowns;
        List<Drawdown_Payment_Allocation__c> paymentAllocationsAfterUpdate = [select Id, Payment__c from Drawdown_Payment_Allocation__c where payment__c in :updatedIDs];
    	System.assertEquals(false, paymentAllocationsAfterUpdate.isEmpty() );        
        System.assertNotEquals(paymentAllocationsAfterUpdate[0], paymentAllocations[0]);

        Test.stopTest();
    }

    
    public static testMethod void testRemoveLoanSetup(){
        Test.startTest();
        List<Opportunity> opps = [select Id from Opportunity];
        List<Drawdown__c> drawdowns = [select Id, Date__c, Amount__c from Drawdown__c where Payment_Method__c='Payment'];        
        for (Drawdown__c drawdown : drawdowns){
            drawdown.Interest_Rate__c = 24;
            drawdown.Compounding_Interest__c = true;
            drawdown.Compounding_Frequency__c = 2.0;
        }                
        update drawdowns;
        drawdowns = [select Id, Compounding_Frequency__c, Compounding_Interest__c, Interest_Deferral_Period__c, Interest_Rate__c, 
                     Minimum_Interest_Period__c, Payout_Date__c, Temp_Payout_Date__c from Drawdown__c where Payment_Method__c='Payment'];        
        for (Drawdown__c drawdown : drawdowns){
            System.assertEquals(null, drawdown.Compounding_Frequency__c);
            System.assertEquals(false, drawdown.Compounding_Interest__c);
            System.assertEquals(null, drawdown.Interest_Deferral_Period__c);            
            System.assertEquals(null, drawdown.Interest_Rate__c);            
            System.assertEquals(null, drawdown.Minimum_Interest_Period__c);            
            System.assertEquals(null, drawdown.Payout_Date__c);            
            System.assertEquals(null, drawdown.Temp_Payout_Date__c);
        }
        Test.stopTest();
    }
    
    public static testMethod void testAllocatePayments(){
        Test.startTest();
        List<Drawdown__c> drawdowns = [select Id from Drawdown__c where Payment_Method__c='Payment']; 
        List<Id> drawdownIds = new List<Id>();
        for (Drawdown__c d : drawdowns){
            drawdownIds.add(d.Id);
        }
        List<Drawdown_Payment_Allocation__c> paymentAllocations = [select Id, payment__c from Drawdown_Payment_Allocation__c where Payment__c in :drawdownIds];
        System.assertEquals(false, paymentAllocations.isEmpty());
        System.assertEquals(paymentAllocations.size(), drawdowns.size());
        Test.stopTest();
    }
    
    public static testMethod void testClearAllocationFlag(){
        Test.startTest();
        List<Drawdown__c> drawdowns = [select Id, Allocate_Payment__c from Drawdown__c where Payment_Method__c='Payment' LIMIT 2]; 
        List<Id> drawdownIds = new List<Id>();
        for (Drawdown__c d : drawdowns){
            d.Allocate_Payment__c = true;
            drawdownIds.add(d.Id);
        }
        update drawdowns;
        drawdowns = [select Id, Allocate_Payment__c from Drawdown__c where Payment_Method__c='Payment' and Id in :drawdownIds];
        for (Drawdown__c d : drawdowns){
            System.assertEquals(false, d.Allocate_Payment__c);
        }
        Test.stopTest();
    }

    
}