force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Prospective Lawyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Treatment Provider Firm</fullName>
            </value>
            <value>
                <fullName>Assessment Funding</fullName>
            </value>
            <value>
                <fullName>Litigation Lender</fullName>
            </value>
            <value>
                <fullName>Assessment Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/General_Business.recordType-meta.xml
<RecordType>
    <fullName>General_Business</fullName>
    <active>true</active>
    <description>Service Provider Facility, Litigation Lender, Contractor, Vendor &amp; Other Account Types</description>
    <label>General Business</label>
</RecordType>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT( Account.Account_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/Opportunity_Service_Provider__c.object-meta.xml
<CustomObject>
    <label>Opportunity Service Provider</label>
    <nameField>
        <displayFormat>OSP-{00000}</displayFormat>
        <label>OSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Service Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Allowance__c.field-meta.xml
<CustomField>
    <fullName>Allowance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Allowance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Service_Provider_Facility__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>General Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Treatment Provider Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting to Send Schedule</fullName>
                <default>true</default>
                <label>Waiting to Send Schedule</label>
            </value>
            <value>
                <fullName>Schedule Sent</fullName>
            </value>
            <value>
                <fullName>Schedule Signed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Total_Scheduled_Payments__c.field-meta.xml
<CustomField>
    <fullName>Total_Scheduled_Payments__c</fullName>
    <description>Total of unpaid scheduled payments. (Field to be rolled up with declaritive rollup class)</description>
    <label>Total Scheduled Payments</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Drawdown_Created__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Drawdown Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/First_Scheduled_Payment__c.field-meta.xml
<CustomField>
    <fullName>First_Scheduled_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to track which Scheduled Payment is the first occurring scheduled payment</description>
    <label>First Scheduled Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&#39;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ScheduledPaymentTriggerHandlerTest.cls
/**
 * @File Name          : ScheduledPaymentTriggerHandlerTest.cls
 * @Description        : 
 * @Author             : Seth Boyd
 * @Group              : 
 * @Last Modified By   : Seth Boyd
 * @Last Modified On   : 5/10/2019, 1:06:14 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    5/10/2019, 10:46:16 AM   Seth Boyd     Initial Version
**/
@isTest
public with sharing class ScheduledPaymentTriggerHandlerTest {

    @isTest
    static void validateFirstSetOnInsert() {
        Bank_Account__c bankRec = TestDataFactory.getBankAccountObjects(1)[0];

        Opportunity opp = TestDataFactory.getOpportunityObjects(1)[0];

        FObject spConfig = TestDataFactory.getScheduledPaymentConfig(1);
        spConfig.setDefinition('Amount__c', 'static value(0)');
        spConfig.setDefinition('Status__c', 'static value(Scheduled)');
        spConfig.setDefinition('Scheduled_Date__c', 'static value(2018-01-01)');
        Scheduled_Payment__c sp1 = TestDataFactory.getScheduledPaymentObjects(spConfig, true)[0];
        sp1 = [Select First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp1.Id];

        System.assertEquals(true, sp1.First_Scheduled_Payment__c, 'Inserted payment should be marked as first');

        spConfig = TestDataFactory.getScheduledPaymentConfig(1);
        spConfig.setDefinition('Amount__c', 'static value(0)');
        spConfig.setDefinition('Status__c', 'static value(Scheduled)');
        spConfig.setDefinition('Scheduled_Date__c', 'static value(2018-01-02)');
        Scheduled_Payment__c sp2 = TestDataFactory.getScheduledPaymentObjects(spConfig, true)[0];
        sp1 = [Select First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp1.Id];
        sp2 = [Select First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp2.Id];

        System.assertEquals(true, sp1.First_Scheduled_Payment__c, 'First inserted payment should be marked as first');
        System.assertEquals(false, sp2.First_Scheduled_Payment__c, 'Second inserted payment should not be marked as first');

        spConfig = TestDataFactory.getScheduledPaymentConfig(1);
        spConfig.setDefinition('Amount__c', 'static value(0)');
        spConfig.setDefinition('Status__c', 'static value(Scheduled)');
        spConfig.setDefinition('Scheduled_Date__c', 'static value(2017-01-02)');
        Scheduled_Payment__c sp3 = TestDataFactory.getScheduledPaymentObjects(spConfig, true)[0];
        sp1 = [Select Scheduled_Date__c, First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp1.Id];
        sp2 = [Select Scheduled_Date__c, First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp2.Id];
        sp3 = [Select Scheduled_Date__c, First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp3.Id];

        System.assertEquals(false, sp1.First_Scheduled_Payment__c, 'First inserted payment should no longer be marked as first');
        System.assertEquals(false, sp2.First_Scheduled_Payment__c, 'Second inserted payment should not be marked as first');
        System.assertEquals(true, sp3.First_Scheduled_Payment__c, 'Third inserted payment should be marked as first');

        sp1.Scheduled_Date__c = sp3.Scheduled_Date__c.addDays(-1);
        update sp1;

        sp1 = [Select Scheduled_Date__c, First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp1.Id];
        sp2 = [Select Scheduled_Date__c, First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp2.Id];
        sp3 = [Select Scheduled_Date__c, First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp3.Id];

        System.assertEquals(true, sp1.First_Scheduled_Payment__c, 'First inserted payment should once again be marked as first');
        System.assertEquals(false, sp2.First_Scheduled_Payment__c, 'Second inserted payment should not be marked as first');
        System.assertEquals(false, sp3.First_Scheduled_Payment__c, 'Third inserted payment should no longer be marked as first');

        delete sp1;

        sp2 = [Select Scheduled_Date__c, First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp2.Id];
        sp3 = [Select Scheduled_Date__c, First_Scheduled_Payment__c From Scheduled_Payment__c Where Id = :sp3.Id];

        System.assertEquals(false, sp2.First_Scheduled_Payment__c, 'Second inserted payment should not be marked as first');
        System.assertEquals(true, sp3.First_Scheduled_Payment__c, 'Third inserted payment should once again be marked as first');

    }

    @isTest
    static void validateOppServiceProviderRollup() {

        Opportunity opp = TestDataFactory.getOpportunityObjects(1)[0];

        FObject accConfig = TestDataFactory.getAccountConfig(1);
        accConfig.setDefinition('Name', 'static value("Treatment Firm ")');
        accConfig.setDefinition('Name', 'serial type(number) from(1) step(1) scale(0)');
        accConfig.setDefinition('ShippingStreet', 'random type(street) group(shipping)');
        accConfig.setDefinition('ShippingPostalCode', 'random type(postalcode) group(shipping)');
        accConfig.setDefinition('ShippingCity', 'random type(city) group(shipping)');
        accConfig.setDefinition('ShippingState', 'random type(state) group(shipping)');
        accConfig.setDefinition('ShippingCountry', 'random type(country) group(shipping)');
        accConfig.setDefinition('RecordTypeId', 'static value(General_Business)');
        accConfig.setDefinition('Account_Type__c', 'static value(Treatment Provider Firm)');
        Account acc = TestDataFactory.getAccountObjects(accConfig, true)[0];

        FObject ospConfig = TestDataFactory.getOpportunityServiceProviderConfig(1);
        ospConfig.setDefinition('Allowance__c', 'static value(1000)');
        //ospConfig.setDefinition('Service_Provider_Facility__c', 'random lookup(Opportunity) source(forceea)');
        ospConfig.setDefinition('Opportunity__c', 'random lookup(Opportunity) source(forceea)');
        Opportunity_Service_Provider__c osp = TestDataFactory.getOpportunityServiceProviderObjects(ospConfig, false)[0];
        osp.Service_Provider_Facility__c = acc.Id;
        osp = TestDataFactory.getOpportunityServiceProviderObjects(ospConfig, true)[0];

        FObject spConfig = TestDataFactory.getScheduledPaymentConfig(1);
        spConfig.setDefinition('Amount__c', 'static value(500)');
        spConfig.setDefinition('Status__c', 'static value(Scheduled)');
        spConfig.setDefinition('Scheduled_Date__c', 'static value(2018-01-01)');
        spConfig.setDefinition('Opportunity_Service_Provider__c', 'random lookup(Opportunity_Service_Provider__c) source(forceea)');
        Scheduled_Payment__c sp = TestDataFactory.getScheduledPaymentObjects(spConfig, true)[0];

        osp = [Select Total_Scheduled_Payments__c From Opportunity_Service_Provider__c Where Id = :osp.Id];
        System.assertEquals(500, osp.Total_Scheduled_Payments__c, 'Total Scheduled Payments should be set on creation');

        /*
        sp.Drawdown_Created__c = true;
        update sp;
        osp = [Select Total_Scheduled_Payments__c From Opportunity_Service_Provider__c Where Id = :osp.Id];
        System.assertEquals(0, osp.Total_Scheduled_Payments__c, 'Scheduled Payments should not be included after DrawdownsCreated__c is set to true');

        sp.Drawdown_Created__c = false;
        */
        sp.Amount__c = 400;
        update sp;
        osp = [Select Total_Scheduled_Payments__c From Opportunity_Service_Provider__c Where Id = :osp.Id];
        System.assertEquals(400, osp.Total_Scheduled_Payments__c, 'Total Scheduled Payments should be recalculated on edit');

        delete sp;
        osp = [Select Total_Scheduled_Payments__c From Opportunity_Service_Provider__c Where Id = :osp.Id];
        System.assertEquals(0, osp.Total_Scheduled_Payments__c, 'Total Scheduled Payments should be recalculated on delete');
    }
}