force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Prospective Lawyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Treatment Provider Firm</fullName>
            </value>
            <value>
                <fullName>Assessment Funding</fullName>
            </value>
            <value>
                <fullName>Litigation Lender</fullName>
            </value>
            <value>
                <fullName>Assessment Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Authorization_Clause__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Clause__c</fullName>
    <description>This field is used to dynamically show the &#39;conflict/interest&#39; clause in the loan document.</description>
    <label>Authorization Clause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client Accounts</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Lawyer, Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Payout_Date_Lawyer_Summary_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lawyers.recordType-meta.xml
<RecordType>
    <fullName>Lawyers</fullName>
    <active>true</active>
    <description>Use this record type to track lawyers</description>
    <label>Lawyers</label>
</RecordType>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Drawdown_Amount__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Amount__c</fullName>
    <formula>IF(OR(ISPICKVAL(Payment_Method__c,&#39;e-Transfer&#39;),ISPICKVAL(Payment_Method__c,&#39;Cheque&#39;)), Total_Amount__c,IF(ISPICKVAL(Payment_Method__c,&#39;Admin Fee&#39;),0,(0-Principal_Repaid__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drawdown Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lump-Sum Admin Fee</fullName>
            </value>
            <value>
                <fullName>Lump-Sum Amount Paid to Borrower</fullName>
            </value>
            <value>
                <fullName>Facility Drawdown</fullName>
                <default>true</default>
                <label>Facility Drawdown</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT( Account.Account_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Day_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Month__c</fullName>
    <label>Day of Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>15th</fullName>
            </value>
            <value>
                <fullName>Last</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drawdown_Amount__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Amount__c</fullName>
    <label>Drawdown Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Allotted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Allotted_Amount__c</fullName>
    <label>Payment Schedule Allotted Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Mode__c</fullName>
    <label>Payment Schedule Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Send_First_Immediately__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Send_First_Immediately__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send First Payment Immediately</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Use_Primary_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Use_Primary_Bank_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Do Scheduled Facility Payments use the Primary Bank Account?</description>
    <label>Payment Use Primary Bank Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PaymentControllerTest.cls
/**
*    @description : Test class for PaymentController
**/
@isTest(seeAllData=false)
private with sharing class PaymentControllerTest {

    /**
    *    @description : Set up test data
    **/
    @testSetup
    static void setupTestData(){
        List<Account> accountList = new List<Account>();
        List<Contact> contactList = new List<Contact>();
        
        accountList.add( new Account(Name = 'Test Client Account', Authorization_Clause__c = 'No', 
                                             RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId()));
        accountList.add( new Account(Name = 'Test LawFirm Account', Authorization_Clause__c = 'No', 
                                             RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId()));
        accountList.add( new Account(Name = 'Firm Account', Account_Type__c = 'Treatment Provider Firm',
                                    RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('General Business').getRecordTypeId()));
        
        insert accountList;
        
        contactList.add( new Contact(LastName = 'Test Client Contact', AccountId = accountList[0].Id,
                                            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId()));
        contactList.add( new Contact(LastName = 'Test Lawyer Contact', AccountId = accountList[1].Id,
                                            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lawyers').getRecordTypeId()));
        insert contactList;
        
        Opportunity Opp = new Opportunity(Name = 'Test Opportunity', RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId(),
                                          AccountId = accountList[0].Id);
        Opp.Payment_Schedule__c = 'Yes';
        Opp.Payment_Schedule_Mode__c = Constants.PAYMENT_MODE_AMOUNT;
        Opp.Payment_Use_Primary_Bank_Account__c = true;
        Opp.Payment_Schedule_Allotted_Amount__c = 5000.00;
        Opp.Day_of_Month__c = 'Last';
        Opp.Start_Date__c = DateUtil.today();
        Opp.Payment_Schedule_Send_First_Immediately__c = false;
        Opp.Drawdown_Amount__c = 1000.00;
        Opp.Lawyer__c = contactList[1].Id;
        Opp.CloseDate = DateUtil.today().addDays(14);
        Opp.StageName = 'Closed With Loan';
        Opp.Law_Firm__c = accountList[1].Id;        
        Opp.Stage_Status__c = 'Approved';
        Opp.Amount = 5375.00;
        Opp.Admin_Fee__c = 375.00;
        Opp.Payout_Date__c = DateUtil.today();
        Opp.Type_of_Loan__c = 'Facility Loan';
        Opp.Primary_Contact__c = contactList[0].Id;
        Opp.Minimum_Interest_Period__c = '0 months';
        Opp.Compounding_Interest__c = 'Monthly';
        Opp.Interest_Compounding_Period__c = 'Compounding Interest';
        Opp.Interest_Rate__c = 15.0;
        insert Opp;
    }

    /**
    *    @description : Create drawdown
    **/
    public static void insertDrawdown(String OppId, Integer noOfPayments){
        List<Drawdown__c> drawdownList = new List<Drawdown__c>();
        for(Integer i=0; i < noOfPayments; i++){
            drawdownList.add(new Drawdown__c(Type__c = 'Facility Drawdown', Date__c = DateUtil.today(), Opportunity__c = OppId,
                                            Amount__c = 1500, Payment_Method__c ='Payment', Payout_Date__c = DateUtil.today(),
                                            Reference_Notes__c = 'Partial Payment'));
        }
        if(drawdownList.size() > 0){
            insert drawdownList;
        }
    }

    /**
    *    @description : Test calculate payments for amount mode
    **/
    @isTest
    static void test_calculatePaymentsForAmountMode(){
        Test.startTest();
        // get opportunity 
        List<Opportunity> opportunityList = [SELECT Id, Payment_Schedule_Mode__c, Drawdown_Amount__c, Start_Date__c, End_Date__c, Day_of_Month__c FROM Opportunity];

           // see payment schedule 
           //System.assertEquals(0,[SELECT count() FROM Scheduled_Payment__c]);

           // create schedule 
           opportunityList[0].Payment_Schedule_Mode__c = Constants.PAYMENT_MODE_AMOUNT;
           opportunityList[0].Day_of_Month__c = 'Last';
           opportunityList[0].Drawdown_Amount__c = 1000.00;
           opportunityList[0].Start_Date__c = DateUtil.today();
           update opportunityList;
           System.assertEquals(5,PaymentController.calculatePayments(opportunityList[0].Id).size());
        Test.stopTest();
    }

    /**
    *    @description : Test calculate payments for date mode
    **/
    /* Not needed or working. FacilitySchedulingTests cover this and more
    @isTest
    static void test_calculatePaymentsForDateMode(){
        Test.startTest();
        // get opportunity 
        List<Opportunity> opportunityList = [
            SELECT 
                Payment_Schedule_Version_Number__c,
                AccountId,
                Payment_Scheduled_Allotment_Remaining__c,
                Day_of_Month__c,
                Start_Date__c,
                End_Date__c,
                Drawdown_Amount__c,
                Payment_Schedule_Mode__c,
                Payment_Use_Primary_Bank_Account__c,
                Payment_Default_Bank_Account__c,
                Payment_Schedule_Send_First_Immediately__c,
                Amount_Available_for_Scheduled_Payments__c,
                Payment_Schedule_Allotted_Amount__c,
                Amount_sent_from_current_Schedule__c
            FROM Opportunity];

        // see payment schedule 
        //System.assertEquals(0,[SELECT count() FROM Scheduled_Payment__c]);

        // create schedule 
        opportunityList[0].Payment_Schedule_Mode__c = Constants.PAYMENT_MODE_DATE;
        opportunityList[0].Day_of_Month__c = 'Last';
        opportunityList[0].Start_Date__c = DateUtil.today();
        opportunityList[0].End_Date__c = DateUtil.today().addMonths(5);
        update opportunityList;
        opportunityList = [
            SELECT 
                Payment_Schedule_Version_Number__c,
                AccountId,
                Payment_Scheduled_Allotment_Remaining__c,
                Day_of_Month__c,
                Start_Date__c,
                End_Date__c,
                Drawdown_Amount__c,
                Payment_Schedule_Mode__c,
                Payment_Use_Primary_Bank_Account__c,
                Payment_Default_Bank_Account__c,
                Payment_Schedule_Send_First_Immediately__c,
                Amount_Available_for_Scheduled_Payments__c,
                Payment_Schedule_Allotted_Amount__c,
                Amount_sent_from_current_Schedule__c
            FROM Opportunity];
        System.assertEquals(5,PaymentController.calculatePayments(opportunityList[0].Id).size());
        Test.stopTest();
    }
    */

   
    /**
    *    @description : Test delete payments
    **/
    @isTest
    static void test_deletePayments(){
        Test.startTest();
        // get opportunity 
        List<Opportunity> opportunityList = [SELECT Id, Payment_Schedule_Mode__c, Drawdown_Amount__c, Start_Date__c, End_Date__c, Day_of_Month__c FROM Opportunity];

           // create schedule 
           opportunityList[0].Payment_Schedule_Mode__c = Constants.PAYMENT_MODE_AMOUNT;
           opportunityList[0].Day_of_Month__c = 'Last';
           opportunityList[0].Drawdown_Amount__c = 1000.00;
           opportunityList[0].Start_Date__c = DateUtil.today();
           update opportunityList;
           List<Scheduled_Payment__c> paymentsList = PaymentController.calculatePayments(opportunityList[0].Id);
           //insert paymentsList;
           System.assertEquals(5,[SELECT count() FROM Scheduled_Payment__c]);
           opportunityList[0].Payment_Schedule__c = 'No';
           update opportunityList;

           PaymentController.deletePayments(opportunityList[0].Id);
           System.assertEquals(0,[SELECT count() FROM Scheduled_Payment__c]);
        Test.stopTest();
    }

    /**
    *    @description : Test create payments
    **/
    @isTest
    static void test_createPayments(){
        Test.startTest();
        // get opportunity 
        List<Opportunity> opportunityList = [SELECT Id, Payment_Schedule_Mode__c, Drawdown_Amount__c, Start_Date__c, End_Date__c, Day_of_Month__c FROM Opportunity];

           // create schedule 
           opportunityList[0].Payment_Schedule_Mode__c = Constants.PAYMENT_MODE_AMOUNT;
           opportunityList[0].Day_of_Month__c = 'Last';
           opportunityList[0].Drawdown_Amount__c = 1000.00;
           opportunityList[0].Start_Date__c = DateUtil.today();
           update opportunityList;
           List<Scheduled_Payment__c> paymentsList = PaymentController.calculatePayments(opportunityList[0].Id);
           //System.assertEquals(0,[SELECT count() FROM Scheduled_Payment__c]);
           //PaymentController.createPayments(opportunityList[0].Id,paymentsList);
           System.assertEquals(5,[SELECT count() FROM Scheduled_Payment__c]);
        Test.stopTest();
    }

    /**
    *    @description : Test get payments
    **/
    @isTest
    static void test_getPayments(){
        Test.startTest();
        // get opportunity 
        List<Opportunity> opportunityList = [SELECT Id, Payment_Schedule_Mode__c, Drawdown_Amount__c, Start_Date__c, End_Date__c, Day_of_Month__c FROM Opportunity];

           // create schedule 
           opportunityList[0].Payment_Schedule_Mode__c = Constants.PAYMENT_MODE_AMOUNT;
           opportunityList[0].Day_of_Month__c = 'Last';
           opportunityList[0].Drawdown_Amount__c = 1000.00;
           opportunityList[0].Start_Date__c = DateUtil.today();
           update opportunityList;
           List<Scheduled_Payment__c> paymentsList = PaymentController.calculatePayments(opportunityList[0].Id);
           //insert paymentsList;
           Map<String, Object> objectsMap = PaymentController.getPayments(opportunityList[0].Id,'ViewPayments');
           List<Object> recordsList = (List<Object>)objectsMap.get('records');
           System.assertEquals(5,recordsList.size());
        Test.stopTest();
    }

    /**
    *    @description : Test get payments
    **/
    @isTest
    static void test_getScheduledPayments(){
        Test.startTest();
        // get opportunity 
        List<Opportunity> opportunityList = [SELECT Id, Payment_Schedule_Mode__c, Drawdown_Amount__c, Start_Date__c, End_Date__c, Day_of_Month__c FROM Opportunity];
        opportunityList[0].Payment_Schedule_Send_First_Immediately__c = true;
        update opportunityList;
        Scheduled_Payment__c sp = new Scheduled_Payment__c(Opportunity__c=opportunityList[0].Id, Amount__c=3000.00);
        insert sp;
        System.assert(0 <= PaymentController.getScheduledPayments(opportunityList[0].Id).size());
        System.assertEquals(0,PaymentController.getPreviousLoans(opportunityList[0].Id).size());
        System.assertEquals(0,PaymentController.getBankAccountOptions(opportunityList[0].Id).size());
        Test.stopTest();
    }
}