force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Prospective Lawyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Treatment Provider Firm</fullName>
            </value>
            <value>
                <fullName>Assessment Funding</fullName>
            </value>
            <value>
                <fullName>Litigation Lender</fullName>
            </value>
            <value>
                <fullName>Assessment Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client Accounts</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT( Account.Account_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subsequent_Drawdowns__c.field-meta.xml
<CustomField>
    <fullName>Subsequent_Drawdowns__c</fullName>
    <label>Subsequent Drawdowns</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RDS_CustomerDisapatcherTest.cls
@isTest
public with sharing class RDS_CustomerDisapatcherTest {
	public RDS_CustomerDisapatcherTest() {
		
	}
	static testMethod void CustomerDispatcherForLawFirm(){

		Account account1 = new Account();
       
        account1.Name='Jackie';
       
        account1.billingcountry='America';
        account1.shippingcountry='England';
        account1.Account_Type__c = 'Law Firm';
        insert account1;

        PageReference pageRef = Page.RDS_CustomerDispatcher;
		Test.setCurrentPage(pageRef); 
		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(account1); 
		ApexPages.currentPage().getParameters().put('Id',account1.Id);
		RDS_CustomerDispatcher Le = new RDS_CustomerDispatcher(sc);

		System.assertNotEquals(null,pageRef);

		String nextPage = Le.dispatch().getUrl();
	}
	static testMethod void CustomerDispatcherForClient(){

		Account account1 = new Account();
       
        account1.Name='Jackie';
       
        account1.billingcountry='America';
        account1.shippingcountry='England';
        account1.Account_Type__c = 'Client';
        insert account1;

        PageReference pageRef = Page.RDS_CustomerDispatcher;
		Test.setCurrentPage(pageRef); 
		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(account1); 
		ApexPages.currentPage().getParameters().put('Id',account1.Id);
		RDS_CustomerDispatcher Le = new RDS_CustomerDispatcher(sc);

		System.assertNotEquals(null,pageRef);

		String nextPage = Le.dispatch().getUrl();
	}

	static testMethod void CustomerDispatcherForContact(){

		Account account1 = new Account();

       
        account1.Name='Jackie';
       
        account1.billingcountry='America';
        account1.shippingcountry='England';
        account1.Account_Type__c = 'Client';
        insert account1;

        Contact con = ELUtilTest.createContact(account1.Id);

        PageReference pageRef = Page.RDS_CustomerDispatcher;
		Test.setCurrentPage(pageRef); 
		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(con); 
		ApexPages.currentPage().getParameters().put('Id',con.Id);
		RDS_CustomerDispatcher Le = new RDS_CustomerDispatcher(sc);

		System.assertNotEquals(null,pageRef);

		String nextPage = Le.dispatch().getUrl();
	}

	static testMethod void CustomerDispatcherForOpportunity(){

		Account acc = new Account();

       
        acc.Name='Jackie';
       
        acc.billingcountry='America';
        acc.shippingcountry='England';
        acc.Account_Type__c = 'Client';
        insert acc;

        Contact con = ELUtilTest.createContact(acc.Id);

        Opportunity o = new Opportunity(
          
        Name = 'Test',
        AccountId = acc.Id,
        Lawyer__c = con.id,
        CloseDate = Date.today(),
        StageName = 'ENTERED',
        Amount = 120.00,
        Subsequent_Drawdowns__c = 12.00   
        );
           
        insert o;

        PageReference pageRef = Page.RDS_CustomerDispatcher;
		Test.setCurrentPage(pageRef); 
		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(o); 
		ApexPages.currentPage().getParameters().put('Id',o.Id);
		RDS_CustomerDispatcher Le = new RDS_CustomerDispatcher(sc);

		System.assertNotEquals(null,pageRef);

		String nextPage = Le.dispatch().getUrl();
	}
	/*static testMethod void CustomerDispatcherForOther(){

		Account account1 = new Account();
       
        account1.Name='Jackie';
      
        account1.billingcountry='Russia';
        account1.shippingcountry='England';
        account1.Account_Type__c = 'Client';
        insert account1;

        PageReference pageRef = Page.RDS_CustomerDispatcher;
		Test.setCurrentPage(pageRef); 
		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(account1); 
		ApexPages.currentPage().getParameters().put('Id',account1.Id);
		RDS_CustomerDispatcher Le = new RDS_CustomerDispatcher(sc);

		System.assertNotEquals(null,pageRef);


		String nextPage = Le.dispatch().getUrl();
	}*/

}