force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Prospective Lawyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Treatment Provider Firm</fullName>
            </value>
            <value>
                <fullName>Assessment Funding</fullName>
            </value>
            <value>
                <fullName>Litigation Lender</fullName>
            </value>
            <value>
                <fullName>Assessment Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Lawyer, Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT( Account.Account_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Financing_Statement_Done__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Done__c</fullName>
    <label>Date Financing Statement Done</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Financing_Statement_Expires__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Expires__c</fullName>
    <label>Date Financing Statement Expires</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FirmHandlerTest.cls
@isTest
public with sharing class FirmHandlerTest {

	static testMethod void FirmHandlerTestMethod() {

		Account account = ELUtilTest.createAccount();
        Contact con = ELUtilTest.createContact(account.Id);

        RDS_CustomerCtlr.runFirstTime = true;

        Id RecordTypeIdAccount = 
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('General Business').getRecordTypeId();
        
        Account serviceAcc = new Account();
        serviceAcc.Name='Sparrow';
        serviceAcc.BillingStreet = 'Testtest';
        serviceAcc.BillingState = 'AK';
        serviceAcc.BillingCity = 'City';
        serviceAcc.BillingPostalCode = '10001';
        serviceAcc.Billingcountry='Canada';
        serviceAcc.ShippingStreet = 'Test';
        serviceAcc.ShippingState = 'New York';
        serviceAcc.ShippingCountry = 'UNITED STATES';
        serviceAcc.ShippingPostalCode = '10001';
        serviceAcc.ShippingCity = 'Lake Trees';
        serviceAcc.Account_Type__c = 'Treatment Provider Firm';
        serviceAcc.RecordTypeId = RecordTypeIdAccount;
        insert serviceAcc;

        Contact cont = new Contact(
        AccountId = serviceAcc.Id,
        LastName = 'Testtest1',
        FirstName = 'Testtest1',
        Phone = '(91) 5019 0000111',
        Email = 'test@testtest.com',
        MailingStreet = '123 Testtest1.',
        MailingCity = 'Testtest1',
        MailingState = 'AK',
        MailingCountry = 'UNITED STATES',
        MailingPostalCode = '10001'
        );
        insert cont;

		Opportunity opp = new Opportunity(
      	Name = 'Test1',
        AccountId = account.Id,
        CloseDate = Date.today(),
        StageName = 'Loan Approval',
        Lawyer__c = con.Id,
        Law_Firm__c = account.id,
        Date_Financing_Statement_Done__c = Date.today(),
        Date_Financing_Statement_Expires__c = Date.today().addDays(1),
        Amount = 2000
        );
        insert opp;
		/*
        Opportunity opprt = new Opportunity();
        opprt.Name = 'Test2';
        opprt.AccountId = serviceAcc.Id;
        opprt.CloseDate = Date.today();
        opprt.StageName = 'Intake';
        opprt.Lawyer__c = cont.Id;
        opprt.Law_Firm__c = serviceAcc.Id;
        opprt.Date_Financing_Statement_Done__c = Date.today().addDays(1);
        opprt.Date_Financing_Statement_Expires__c = Date.today().addDays(2);
        opprt.Amount = 5000;
        insert opprt;

        Opportunity oppr = new Opportunity();
        oppr.id = opp.id;
        oppr.Law_Firm__c = serviceAcc.Id;
        oppr.StageName = 'Prospecting';
        update oppr;
		*/
        opp.Law_Firm__c = serviceAcc.id;
        
        update opp;
    }
}