force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Prospective Lawyer</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
            <value>
                <fullName>Treatment Provider Firm</fullName>
            </value>
            <value>
                <fullName>Assessment Funding</fullName>
            </value>
            <value>
                <fullName>Litigation Lender</fullName>
            </value>
            <value>
                <fullName>Assessment Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
    <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
    <label>Compounding Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Deferral_Period__c.field-meta.xml
<CustomField>
    <fullName>Interest_Deferral_Period__c</fullName>
    <description>The Interest Deferral Period from the Opportunity, replicated here to avoid cross object formula size limitations.  Also converted to an number from a picklist value so it&#39;s readily usable in formulas.</description>
    <inlineHelpText>The months to defer interest on this Drawdown.</inlineHelpText>
    <label>Interest Deferral Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
    <inlineHelpText>Loan Interest Rate</inlineHelpText>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
    <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
    <label>Minimum Interest Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT( Account.Account_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <label>Interest Compounding Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Compounding_Period__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Compounding_Period__c.field-meta.xml
<CustomField>
    <fullName>Interest_Compounding_Period__c</fullName>
    <label>Interest Compounding Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple Interest</fullName>
            </value>
            <value>
                <fullName>Compounding Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Deferral_Period__c.field-meta.xml
<CustomField>
    <fullName>Interest_Deferral_Period__c</fullName>
    <label>Interest Deferral Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Annual Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <label>Minimum Interest Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 months</fullName>
            </value>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>2 months</fullName>
            </value>
            <value>
                <fullName>3 months</fullName>
            </value>
            <value>
                <fullName>4 months</fullName>
            </value>
            <value>
                <fullName>5 months</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
                <default>true</default>
                <label>6 months</label>
            </value>
            <value>
                <fullName>7 months</fullName>
            </value>
            <value>
                <fullName>8 months</fullName>
            </value>
            <value>
                <fullName>9 months</fullName>
            </value>
            <value>
                <fullName>10 months</fullName>
            </value>
            <value>
                <fullName>11 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/Opportunity_Service_Provider__c.object-meta.xml
<CustomObject>
    <label>Opportunity Service Provider</label>
    <nameField>
        <displayFormat>OSP-{00000}</displayFormat>
        <label>OSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Service Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Allowance__c.field-meta.xml
<CustomField>
    <fullName>Allowance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Allowance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Service_Provider_Facility__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>General Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Treatment Provider Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting to Send Schedule</fullName>
                <default>true</default>
                <label>Waiting to Send Schedule</label>
            </value>
            <value>
                <fullName>Schedule Sent</fullName>
            </value>
            <value>
                <fullName>Schedule Signed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CSL_OpportunityServiceProviderCtlrTest.cls
@isTest
public class CSL_OpportunityServiceProviderCtlrTest {
    
    static testMethod void ServiceProviderTest(){
        Account acc = ELUtilTest.createAccount();
        Contact con = ELUtilTest.createContact(acc.Id);
        
        Opportunity o = new Opportunity(
            Name = 'Test',
            AccountId = acc.Id,
            Lawyer__c = con.id,
            CloseDate = Date.today(),
            StageName = 'ENTERED',
            Amount = 120.00,
            Minimum_Interest_Period__c = '0 months',
            Compounding_Interest__c = 'Monthly',
            Interest_Compounding_Period__c = 'Simple Interest',
            Interest_Deferral_Period__c = '0',
            Interest_Rate__c = 15.0
        );
        insert o;

        // Create contact for lookup
        // Account serviceAcc = ELUtilTest.createAccount();
        
        Id RecordTypeIdAccount = 
            Schema.SObjectType.Account.getRecordTypeInfosByName().get('General Business').getRecordTypeId();
        
        Account serviceAcc = new Account();
        serviceAcc.Name='Sparrow';
        serviceAcc.BillingStreet = 'Testtest';
        serviceAcc.BillingState = 'AK';
        serviceAcc.BillingCity = 'City';
        serviceAcc.BillingPostalCode = '10001';
        serviceAcc.Billingcountry='Canada';
        serviceAcc.ShippingStreet = 'Test';
        serviceAcc.ShippingState = 'New York';
        serviceAcc.ShippingCountry = 'UNITED STATES';
        serviceAcc.ShippingPostalCode = '10001';
        serviceAcc.ShippingCity = 'Lake Trees';
        serviceAcc.Account_Type__c = 'Treatment Provider Firm';
        serviceAcc.RecordTypeId = RecordTypeIdAccount;
        insert serviceAcc;
        
        Contact c = new Contact(
            FirstName = 'Super',
            LastName = 'Mario',
            AccountId = serviceAcc.Id
        );
        insert c;

        Opportunity_Service_Provider__c sp = new Opportunity_Service_Provider__c();
        
        sp.Allowance__c = 1;
        sp.Opportunity__c = o.id;
        sp.Status__c = 'Waiting To Send Schedule';
        sp.Service_Provider_Facility__c = serviceAcc.id;
        
        insert sp;

        PageReference pageRef = Page.CSL_OpportunityServiceProvider;
        Test.setCurrentPage(pageRef); 
        System.assertNotEquals(null,pageRef);

        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(sp); 
        ApexPages.currentPage().getParameters().put('oppId', o.Id);

        CSL_OpportunityServiceProviderCtlr osp = new CSL_OpportunityServiceProviderCtlr(sc);
        System.assertEquals(1, osp.providers.size());
        System.assertNotEquals(null, osp.oppId);


        // add new
        osp.provider.Service_Provider_Facility__c = acc.Id;
        osp.createNew();
        osp.init();
        

        // check the provider count
        System.assertEquals(1, osp.providers.size());


        // update the service prodider allowance
        osp.providers.get(0).Allowance__c = 1000;
        osp.saveProviderList();
        osp.init();

        //System.assertEquals(1000, osp.providers.get(0).Allowance__c);

        // add drawdown
        ApexPages.currentPage().getParameters().put('pId', osp.providers.get(0).Id);
        osp.addDrawdown();
        osp.init();

        // check the drawdown count for the first prodider
        //System.assertEquals(1, osp.providers.get(0).Drawdowns__r.size());

        // change drawdown ammount
        osp.providers.get(0).Drawdowns__r.get(0).Amount__c = 500;
        osp.saveProviderList();
        osp.init();

        //System.assertEquals(500, osp.providers.get(0).Drawdowns__r.get(0).Amount__c);

        // delete drawdown
        ApexPages.currentPage().getParameters().put('dId', osp.providers.get(0).Drawdowns__r.get(0).Id);
        osp.deleteDrawdown();
        osp.init();        

        //System.assertEquals(0, osp.providers.get(0).Drawdowns__r.size());

        // delete proivder
        ApexPages.currentPage().getParameters().put('pId', osp.providers.get(0).Id);
        osp.deleteProvider();
        osp.init();

        //System.assertEquals(0, osp.providers.size());
    }
}