force-app/main/default/objects/Account/fields/All_Payout_Balance__c.field-meta.xml
<CustomField>
    <fullName>All_Payout_Balance__c</fullName>
    <label>All Payout Balance</label>
    <summarizedField>Opportunity.Payout_Balance__c</summarizedField>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Authorization_Clause__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Clause__c</fullName>
    <description>This field is used to dynamically show the &#39;conflict/interest&#39; clause in the loan document.</description>
    <label>Authorization Clause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client Accounts</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_Payout_Date__c</fullName>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF(  ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),0,(Outstanding_Balance_as_of_Payout_Date__c-Amount_Adjusted_for_Repayments__c)+Interest_up_to_Last_Repayment__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Interest Accrued up to Payout Date</inlineHelpText>
    <label>Accrued Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
    <inlineHelpText>Loan Interest Rate</inlineHelpText>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_Payout_Date__c</fullName>
    <description>NOTE: Used EXP and LN as the normal exponent function does not handle fractional numbers:  See: https://developer.salesforce.com/forums/?id=906F00000008vDHIAY</description>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF(  ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),Sum_of_Payment_Allocations__c - Amount__c,
IF(Compounding_Interest__c,(Amount_Adjusted_for_Repayments__c*(EXP(LN(1 + (Interest_Rate__c/Compounding_Frequency__c))*   
(Compounding_Frequency__c*Interest_Accrual_Years__c)))),Amount_Adjusted_for_Repayments__c*(1+((Interest_Rate__c/365)* Interest_Accrual_Days__c)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Outstanding Balance as it will be at the Payout Date.  This Accounts for compounding interest or Simple Interest depending on the Loan.  This is set to zero when Drawdown is Payment.   For Payments, negative amounts represent unallocated payment amounts.</inlineHelpText>
    <label>Outstanding Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
    <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Per_Diem_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_as_of_Payout_Date__c</fullName>
    <description>o	The daily interest rate (using a 365 base) on the total outstanding balance (Principle + Interest) at the payout date.   The Per Diem will be adjusted to zero in two scenarios:
1.	When the payout date is less than the minimum interest date.  In this situation, the interest accrued to 6 months is already included in the payout and therefore charging Per Diem would be double charging.  
2.	When the payout date is still within the interest deferral period.</description>
    <formula>If(
    OR((Payout_Date__c&lt;(ADDMONTHS(Date__c,Interest_Deferral_Period__c))),
       (Payout_Date__c&lt;(ADDMONTHS(Date__c,Minimum_Interest_Period__c))),
	    ISPICKVAL(Payment_Method__c , &quot;Payment&quot;))   
    ,0,
	(Interest_Rate__c/365)*Outstanding_Balance_as_of_Payout_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The daily interest rate on the total outstanding balance at the payout date. The Per Diem will be adjusted to zero when the payout date is less than the minimum interest date and when payout date is within the interest deferral period.</inlineHelpText>
    <label>Per Diem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Total_Per_Diem__c.field-meta.xml
<CustomField>
    <fullName>Total_Per_Diem__c</fullName>
    <formula>Per_Diem_as_of_Payout_Date__c  + NULLVALUE(  Admin_Per_Diem__c , 0.0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Per Diem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Annual Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanSimulatorController.cls
/**
*    @description : Apex class to calculate the interest and balance for the loan simualtor
**/
public with sharing class LoanSimulatorController {
	
	/**
	* @description Method to calculate the interest and balance for the loan simulator
	* @param opportunity Loan inforamtion
	* @param drawdownsList List of drawdowns 
	* @return List<Payment__c> List of payments to create
	**/
	@AuraEnabled
	public static Map<String, Object> calculateLoanInterestAndBalance(Opportunity opportunity, List<Drawdown__c> drawdownsList){
		Map<String, Object> objectMap = new Map<String, Object>();
		Decimal principal = 0.00;
		Savepoint savePointInstance = Database.setSavePoint();

		try{

			// calculate Amount 
			for(Drawdown__c drawdown : drawdownsList){
				principal += drawdown.Amount__c;
			}	

			// Create account 
			Account clientAccount = createAccount(Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId(),'Test Company');
			Account lawFirmAccount = createAccount(Schema.SObjectType.Account.getRecordTypeInfosByName().get('Law Firm').getRecordTypeId(),'Test Company Lawyer');

			// Create Opporutunity
			opportunity.Name = 'Test Opportunity';
			opportunity.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId();
			opportunity.StageName = 'Loan Approved';
			opportunity.CloseDate = Date.today().addDays(14);
			opportunity.AccountId = clientAccount.Id;
			opportunity.Amount = principal;
			//opportunity.Law_Firm__c = lawFirmAccount.Id;  
			opportunity.Type_of_Loan__c = 'Facility Loan';
			insert opportunity; 

			// create drawdowns 
			for(Drawdown__c drawdown : drawdownsList){
				drawdown.Opportunity__c = opportunity.Id;
				drawdown.Payout_Date__c = opportunity.Payout_Date__c;
			}	
			insert drawdownsList;

			drawdownsList = [SELECT Id, Amount__c, Interest_Rate__c, Date__c, Accrued_Interest_as_of_Payout_Date__c, Per_Diem_as_of_Payout_Date__c, Total_Per_Diem__c, Outstanding_Balance_as_of_Payout_Date__c FROM Drawdown__c WHERE Id IN: drawdownsList];

			// fetch account 
			List<Account> accountList = [SELECT Id, All_Payout_Balance__c FROM Account WHERE Id =: clientAccount.Id LIMIT 1];
			return new Map<String, Object>{	'principal' => principal,
											'interest' => accountList[0].All_Payout_Balance__c - principal,
											'balance'	=> accountList[0].All_Payout_Balance__c,
											'drawdowns' => drawdownsList
										};
		}catch(Exception ex){

		}finally{
			Database.rollback(savePointInstance);
		}

		return null;
	}

	/**
	* @description Method to create dummy account
	* @return List<Payment__c> List of payments to create
	**/
	private static Account createAccount(Id recordTypeId,String accountName){
		Account account  =  new Account(Name = accountName, Authorization_Clause__c = 'No', RecordTypeId = recordTypeId,Phone='123456789');
		insert account;
		return account;
	}
}