force-app/main/default/objects/Account/fields/Authorization_Clause__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Clause__c</fullName>
    <description>This field is used to dynamically show the &#39;conflict/interest&#39; clause in the loan document.</description>
    <label>Authorization Clause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Additional_Notes_Law_Firm_Report__c.field-meta.xml
<CustomField>
    <fullName>Email_Additional_Notes_Law_Firm_Report__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Email_Additional_Notes_Law_Firm_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email Additional Notes Law Firm Report</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payout_Date_Law_Firm_Report__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date_Law_Firm_Report__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Payout_Date_Law_Firm_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date Law Firm Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Report_Date_Law_Firm_Report__c.field-meta.xml
<CustomField>
    <fullName>Report_Date_Law_Firm_Report__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Report_Date_Law_Firm_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Report Date Law Firm Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client Accounts</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Conga_batch_setting__c/Conga_batch_setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom conga batch setting to store Report Date, Payout Date, Email body and conga template query selector</description>
    <label>Conga batch setting</label>
</CustomObject>

force-app/main/default/objects/Conga_batch_setting__c/fields/Conductor_Id_Law_Firm_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Conductor_Id_Law_Firm_Summary_Report__c</fullName>
    <label>Conductor Id Law Firm Summary Report</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Email_Additional_Notes_Law_Firm_Report__c.field-meta.xml
<CustomField>
    <fullName>Email_Additional_Notes_Law_Firm_Report__c</fullName>
    <label>Email Additional Notes Law Firm Report</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Email_To_Id_Law_Firm_Summary__c.field-meta.xml
<CustomField>
    <fullName>Email_To_Id_Law_Firm_Summary__c</fullName>
    <label>Email To Id Law Firm Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Payout_Date_Law_Firm_Report__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date_Law_Firm_Report__c</fullName>
    <label>Payout Date Law Firm Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Query_Selector_Law_Firm_Report__c.field-meta.xml
<CustomField>
    <fullName>Query_Selector_Law_Firm_Report__c</fullName>
    <description>Will be used to select Query Id for conga template to send law firm report summary.</description>
    <label>Query Selector Law Firm Report</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Report_Date_Law_Firm_Report__c.field-meta.xml
<CustomField>
    <fullName>Report_Date_Law_Firm_Report__c</fullName>
    <label>Report Date Law Firm Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Lawyer, Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lawyers.recordType-meta.xml
<RecordType>
    <fullName>Lawyers</fullName>
    <active>true</active>
    <description>Use this record type to track lawyers</description>
    <label>Lawyers</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LawfirmSummaryCtlrTest.cls
@isTest 
public class LawfirmSummaryCtlrTest {
    
    @TestSetup
    static void initailizeTestData(){
        
        RecordType lawFirmRTAccount = [SELECT Id FROM RecordType Where SobjectType = 'Account' AND Name = 'Law Firm'];
        RecordType lawyerRTContact = [SELECT Id FROM RecordType Where SobjectType = 'Contact' AND Name = 'Lawyers'];
        RecordType clientOppoRT = [SELECT Id FROM RecordType Where SobjectType = 'Opportunity' AND Name = 'Client Opportunity Record Type'];
        
        Account LawFirmAccount = new Account(Name = 'Test Lawfirm Account', Authorization_Clause__c = 'No', RecordTypeId = lawFirmRTAccount.Id);
        insert LawFirmAccount;
        
        Contact LawyerContact = new Contact(LastName = 'Test Lawyer Contact', AccountId = LawFirmAccount.Id, RecordTypeId = lawyerRTContact.Id);
        insert LawyerContact;
        
        Opportunity clientOpp = new Opportunity(Name = 'Test Client Opportunity', RecordTypeId = clientOppoRT.Id, AccountId = LawFirmAccount.Id);
        clientOpp.CloseDate = Date.today().addDays(14);
        clientOpp.StageName = 'Closed With Loan';
        clientOpp.Law_Firm__c = LawFirmAccount.Id;        
        clientOpp.Stage_Status__c = 'Approved';
        insert clientOpp; 
        
        insert new Conga_batch_setting__c(SetupOwnerId=UserInfo.getUserId(), Payout_Date_Law_Firm_Report__c = Date.today(),
                                          Report_Date_Law_Firm_Report__c = Date.today().addDays(5), Email_To_Id_Law_Firm_Summary__c = '',
                                  		  Email_Additional_Notes_Law_Firm_Report__c = '', Query_Selector_Law_Firm_Report__c = '',
                                          Conductor_Id_Law_Firm_Summary_Report__c = '');
    }
    
    public static testMethod void mainTest(){
        
        Test.startTest();
        
        String strQuery = 'SELECT Id, Name FROM Account WHERE RecordType.Name = \'Law Firm\' AND Id in (SELECT Law_Firm__c FROM Opportunity WHERE accountId !=null)';
        LawfirmSummaryCtlr.getLawfirmAccounts(strQuery, 'All', 'ELFI');
        LawfirmSummaryCtlr.getLawfirmAccounts(strQuery, 'Active', 'ELFI');
        LawfirmSummaryCtlr.getPickListValues('Account', 'Business_Unit__c');
        
        LawfirmSummaryCtlr.AccountInfo accInfo = new LawfirmSummaryCtlr.AccountInfo();
        accInfo.checked = true;
        
        //throwing exception to cover cath block
        strQuery = 'SELECT Id Name FROM Account WHERE RecordType.Name = \'Law Firm\' AND Id in (SELECT Law_Firm__c FROM Opportunity WHERE accountId !=null)';
        
        try{
            LawfirmSummaryCtlr.getLawfirmAccounts(strQuery, 'All', 'ELFI');
        }catch(Exception e){
            System.debug('success');
        }
        
        Test.stopTest();
    }
    public static testMethod void sendMethodTest(){
        
        Test.startTest();
        
        String strQuery = 'SELECT Id, Name FROM Account WHERE RecordType.Name = \'Law Firm\' AND Id in (SELECT Law_Firm__c FROM Opportunity WHERE accountId !=null)';
        
        Contact cc = [SELECT Id from Contact limit 1];
        List<String> selId = new List<String>{cc.Id};
        LawfirmSummaryCtlr.send(strQuery, selId, Date.today() + '' , Date.today() + '', '', 'Email body', 'All', 'ELFI');
        
        Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());
        system.assertNotEquals(customSettings.Conductor_Id_Law_Firm_Summary_Report__c, null);
        
        LawfirmSummaryCtlr.send('', selId, Date.today() + '' , Date.today() + '', '', 'Email body', 'All', 'ELFI');
        
        Test.stopTest();
    }
    
    public static testMethod void generateMethodTest(){
        
        Test.startTest();
        
        String strQuery = 'SELECT Id, Name FROM Account WHERE RecordType.Name = \'Law Firm\' AND Id in (SELECT Law_Firm__c FROM Opportunity WHERE accountId !=null)';
        
        Contact cc = [SELECT Id from Contact limit 1];
        List<String> selId = new List<String>{cc.Id};
            
        LawfirmSummaryCtlr.generate(strQuery, selId, Date.today() + '' , Date.today() + '', 'All', 'ELFI');
        
        Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());
        system.assertNotEquals(customSettings.Conductor_Id_Law_Firm_Summary_Report__c, null);
        
        LawfirmSummaryCtlr.generate('', selId, Date.today() + '' , Date.today() + '', 'All', 'ELFI');
        
        Test.stopTest();
    }
}