force-app/main/default/objects/Account/fields/Authorization_Clause__c.field-meta.xml
<CustomField>
    <fullName>Authorization_Clause__c</fullName>
    <description>This field is used to dynamically show the &#39;conflict/interest&#39; clause in the loan document.</description>
    <label>Authorization Clause</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Client.recordType-meta.xml
<RecordType>
    <fullName>Client</fullName>
    <active>true</active>
    <description>Client Accounts</description>
    <label>Client</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Payout_Date_Lawyer_Summary_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RDS_DispatcherComponentControllerTest.cls
@isTest
public class RDS_DispatcherComponentControllerTest {
    public static testMethod void dispatcherComponentTest(){
        Test.startTest();
        Account account;
        Account acc = new Account(Name = 'Test Client Account', Authorization_Clause__c = 'No', 
                                  RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Client').getRecordTypeId());
        
        insert acc;
        account = RDS_DispatcherComponentControllerApex.getAccount(acc.Id);
        system.assertEquals(acc.Id, account.Id);
        
        Contact con = new Contact(LastName = 'Test Client Contact', AccountId = acc.Id,
                                  RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Client Contact').getRecordTypeId());
        insert con;
        
        account = RDS_DispatcherComponentControllerApex.getAccount(con.Id);
        system.assertEquals(acc.Id, account.Id);
        
        
        Opportunity opp = new Opportunity(AccountId = acc.Id,
                                          Name = 'Test Opportunity ',
                                          Lawyer__c = con.Id,
                                          CloseDate = Date.today().addDays(14),
                                          StageName = 'Closed With Loan',
                                          Stage_Status__c = 'Approved',
                                          Payout_Date__c = Date.newInstance(2018,01,01),
                                          Type_of_Loan__c = 'Facility Loan',
                                          RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId()
                                         );
        
        insert opp;
        
        account = RDS_DispatcherComponentControllerApex.getAccount(opp.Id);
        system.assertEquals(acc.Id, account.Id);
        
        Test.stopTest();
        
    }
    
}