force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Sum_of_Repayments__c.field-meta.xml
<CustomField>
    <fullName>Sum_of_Repayments__c</fullName>
    <inlineHelpText>Sum of payments applied to this Drawdown</inlineHelpText>
    <label>Sum of Repayments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/Drawdown_Payment_Allocation__c.object-meta.xml
<CustomObject>
    <description>All Payment allocations to Drawdowns.</description>
    <label>Drawdown Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdown Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <inlineHelpText>Amount of Transaction (negative for payments)</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/fields/Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Drawdown__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Drawdown that this applies to</inlineHelpText>
    <label>Drawdown</label>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Payments Allocated to this Drawdown</relationshipLabel>
    <relationshipName>Payments_Allocated_to_this_Drawdown</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The Opportunity the parent Drawdown is linked to.   This is required to allow efficient replication down from Opportunity.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdown Payment Allocations</relationshipLabel>
    <relationshipName>Drawdown_Payment_Allocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Requests__c.field-meta.xml
<CustomField>
    <fullName>Loan_Requests__c</fullName>
    <label>Loan Requests</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Loan</fullName>
            </value>
            <value>
                <fullName>2nd Loan</fullName>
            </value>
            <value>
                <fullName>3rd Loan</fullName>
            </value>
            <value>
                <fullName>4th Loan</fullName>
            </value>
            <value>
                <fullName>5th Loan</fullName>
            </value>
            <value>
                <fullName>6th Loan</fullName>
            </value>
            <value>
                <fullName>7th Loan</fullName>
            </value>
            <value>
                <fullName>8th Loan</fullName>
            </value>
            <value>
                <fullName>9th Loan</fullName>
            </value>
            <value>
                <fullName>10th Loan</fullName>
            </value>
            <value>
                <fullName>11th Loan</fullName>
            </value>
            <value>
                <fullName>12th Loan</fullName>
            </value>
            <value>
                <fullName>13th Loan</fullName>
            </value>
            <value>
                <fullName>14th Loan</fullName>
            </value>
            <value>
                <fullName>15th Loan</fullName>
            </value>
            <value>
                <fullName>16th Loan</fullName>
            </value>
            <value>
                <fullName>17th Loan</fullName>
            </value>
            <value>
                <fullName>18th Loan</fullName>
            </value>
            <value>
                <fullName>19th Loan</fullName>
            </value>
            <value>
                <fullName>20th Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SumOfRepaymentsController.cls
public with sharing class SumOfRepaymentsController {
    public List<RepaymentInfo> incorrectRepayments{get; set;}
    public SumOfRepaymentsController(){
        incorrectRepayments = getIncorrectSumOfRepayments();
    }
    public List<RepaymentInfo> getIncorrectSumOfRepayments(){
        List<RepaymentInfo> result = new List<RepaymentInfo>();
        List<Drawdown__c> drds = [select Id,Name,Opportunity__r.AccountId, Opportunity__r.Account.Business_Unit__c, Opportunity__r.Id, Opportunity__r.Name, Opportunity__r.Loan_Requests__c, Sum_Of_Repayments__c, (select Id, Amount__c from Payments_Allocated_to_this_Drawdown__r) from Drawdown__c where Payment_Method__c <> 'Payment' and Sum_Of_Repayments__c > 0.0];
        Integer count = 0;
        for (Drawdown__c d : drds){
            Double sm = 0.0;    
            if (d.Payments_Allocated_to_this_Drawdown__r.size() > 0){
                for (Drawdown_Payment_Allocation__c al : d.Payments_Allocated_to_this_Drawdown__r ){
                    sm += al.Amount__c;
                }
                if (sm != d.Sum_Of_Repayments__c){
                    count += 1;
                    System.debug('Incorrect ' + d.Id + ',' + d.Name + ', ' + d.Opportunity__r.AccountId + ',' + d.Opportunity__r.Name + ',' + d.Opportunity__r.Loan_Requests__c+ ',' + d.Sum_Of_Repayments__c);
                    //if (result.size() < 1000)
                    	result.add(new RepaymentInfo(d.Id, d.Name, d.Opportunity__r.AccountId, d.Opportunity__r.Id, d.Opportunity__r.Name, d.Opportunity__r.Loan_Requests__c, d.Sum_Of_Repayments__c, sm, d.Opportunity__r.Account.Business_Unit__c ));
                }
            }    
            else{
                count += 1;                
                System.debug(d.Id + ',' + d.Name + ', ' + d.Opportunity__r.AccountId + ',' + d.Opportunity__r.Name + ',' + d.Opportunity__r.Loan_Requests__c+ ',' + d.Sum_Of_Repayments__c);
                //if (result.size() < 1000)
                	result.add(new RepaymentInfo(d.Id, d.Name, d.Opportunity__r.AccountId, d.Opportunity__r.Id, d.Opportunity__r.Name, d.Opportunity__r.Loan_Requests__c, d.Sum_Of_Repayments__c, sm, d.Opportunity__r.Account.Business_Unit__c ));
            }
        }
        
        System.debug('Count ' + count);
        
        return result;
    }
    
    public class RepaymentInfo{
        public String id{ get; set; }
        public String drawdownName{ get; set; }
        public String accountId{ get; set; }
        public String oppName{ get; set; }
        public String oppId{ get; set; }
        public String loanRequests{ get; set; }
        public String businessUnit{ get; set; }
        public Decimal sumOfRepayments{ get; set; }
        public Decimal correctSumOfRepayments{ get; set; }
        
        public RepaymentInfo(String id, String drawdownName, String accountId, String oppId, String oppName, String loanRequests, Decimal sumOfRepayments, Decimal correctSumOfRepayments, String businessUnit ){
            this.id = id;
            this.drawdownName = drawdownName;
            this.accountId = accountId;
            this.oppId = oppId;
            this.oppName = oppName;
            this.loanRequests = loanRequests;
            this.sumOfRepayments = sumOfRepayments;
            this.correctSumOfRepayments = correctSumOfRepayments;
            this.businessUnit = businessUnit;
        }
    }
}