force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/Conga_batch_setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom conga batch setting to store Report Date, Payout Date, Email body and conga template query selector</description>
    <label>Conga batch setting</label>
</CustomObject>

force-app/main/default/objects/Conga_batch_setting__c/fields/Business_Unit_Lawyer_Summary__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Lawyer_Summary__c</fullName>
    <label>Business Unit Lawyer Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Conductor_Id_Lawyer_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Conductor_Id_Lawyer_Summary_Report__c</fullName>
    <label>Conductor Id Lawyer Summary Report</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Email_Additional_Notes_Lawyer_Summary__c.field-meta.xml
<CustomField>
    <fullName>Email_Additional_Notes_Lawyer_Summary__c</fullName>
    <label>Email Additional Notes Lawyer Summary</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Payout_Date_Lawyer_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date_Lawyer_Summary_Report__c</fullName>
    <label>Payout Date Lawyer Summary Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Query_Selector_Lawyer_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Query_Selector_Lawyer_Summary_Report__c</fullName>
    <description>Will be used to select Query Id for conga template to send lawyer summary.</description>
    <label>Query Selector Lawyer Summary Report</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conga_batch_setting__c/fields/Report_Date_Lawyer_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Report_Date_Lawyer_Summary_Report__c</fullName>
    <label>Report Date Lawyer Summary Report</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Conga_Batch_Lawyer_Summary__c.field-meta.xml
<CustomField>
    <fullName>Conga_Batch_Lawyer_Summary__c</fullName>
    <description>##Conga created button:00b21000000I7t9</description>
    <formula>&quot;&amp;solmgr=1&quot; + 
&quot;&amp;id=&quot; + Id +
&quot;&amp;queryid=&quot; + IF($Setup.Conga_batch_setting__c.Query_Selector_Lawyer_Summary_Report__c  = &quot;Active&quot;,  IF( $Setup.Conga_batch_setting__c.Business_Unit_Lawyer_Summary__c = &quot;ELFI&quot;, &quot;[LawyerActiveClient]a0p0L00000JZyFw&quot;,  IF($Setup.Conga_batch_setting__c.Business_Unit_Lawyer_Summary__c = &quot;Rhino&quot;, &quot;[LawyerActiveClient]a0p0L00000JZyG1&quot;, &quot;[LawyerActiveClient]a0p0L00000JSOko&quot;) ) , IF($Setup.Conga_batch_setting__c.Business_Unit_Lawyer_Summary__c = &quot;ELFI&quot;, &quot;[LawyerClient]a0p0L00000JZyFmQAL&quot;,  IF($Setup.Conga_batch_setting__c.Business_Unit_Lawyer_Summary__c = &quot;Rhino&quot;, &quot;[LawyerClient]a0p0L00000JZyFrQAL&quot;, &quot;[LawyerClient]a0p0L00000JSOktQAH&quot;) ) )  + &quot;?pv0=&quot; + Id +
&quot;&amp;templateid=&quot; +  IF( $Setup.Conga_batch_setting__c.Business_Unit_Lawyer_Summary__c = &quot;Rhino&quot;, &quot;a0x0L00000PH6QI&quot;, &quot;a0x0L00000PVUFQ&quot;) + 
&quot;&amp;defaultpdf=1&quot; + 
&quot;&amp;attachmentparentid=&quot; + Id +
&quot;&amp;ac0=1&quot; + 
&quot;&amp;sc0=1&quot; + 
&quot;&amp;sc1=SalesforceFile&quot; + 
&quot;&amp;DS7=5&quot; + 
&quot;&amp;qmode=Attachments&quot; + 
&quot;&amp;returnpath=/lightning/n/Custom_Reports?0.source=alohaHeader&quot;</formula>
    <label>Conga Batch Lawyer Summary</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Conga_Batch_Lawyer_Summary_Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Conga_Batch_Lawyer_Summary_Send_Email__c</fullName>
    <formula>SUBSTITUTE( Conga_Batch_Lawyer_Summary__c , &quot;&amp;qmode=Attachments&quot;, &quot;&amp;qmode=SendEmail&quot;)  &amp;
&quot;&amp;CongaEmailTemplateId=a0o0L00000L4wsr&quot;&amp;
&quot;&amp;EmailToId=&quot;&amp; BLANKVALUE( $Setup.Conga_batch_setting__c.Test_Recipient_of_Lawyer_Summary__c , Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Batch Lawyer Summary Send Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lawyers.recordType-meta.xml
<RecordType>
    <fullName>Lawyers</fullName>
    <active>true</active>
    <description>Use this record type to track lawyers</description>
    <label>Lawyers</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Law_Firm_Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm_Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm Lawyer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Onboarding Opportunity</relationshipLabel>
    <relationshipName>Onboarding_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Available_to_Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Loan_Available_to_Drawdown__c</fullName>
    <formula>IF(ISPICKVAL(Stage_Status__c,&#39;Paid Off&#39;), 0, Amount - Drawdown_Total__c + Principal_Reversed__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Available to Drawdown</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LawyerSummaryCtlr.cls
public class LawyerSummaryCtlr {
    /******************* Method to return all lawyers *********************/
    @AuraEnabled
    public static List<ContactInfo> getLawyersContacts(String strQuery, String LoanFilter, String businessUnitFilter) {
        try{
            LoanFilter = String.isEmpty(LoanFilter) ? 'All' : LoanFilter;
            businessUnitFilter = String.isEmpty(businessUnitFilter) ? 'ELFI' :businessUnitFilter;
            system.debug('LoanFilter ' + LoanFilter);
            
            // Initializing the contact variable
            List<ContactInfo> contactInfo = new List<ContactInfo>();
            List<Contact> contacts = new List<Contact>();
            
             system.debug(strQuery);           
            // *** Still need to handle exceptions ***
            // Executing the query to retrieve the account information
            contacts = Database.query(strQuery);        
            
            
            Set<Id> contactIds = new Map<Id,Contact>(contacts).keySet();
            for(contact con : contacts)
            {
                System.debug('## getLawyersContacts - RESULT: ' + con.Id);
            }
            
            strQuery = 'Select Law_Firm_Lawyer__c, Lawyer__c, AccountId, Loan_Available_to_Drawdown__c from Opportunity where Lawyer__c in :contactIds ';
            strQuery += LoanFilter == 'Active'? ' AND isClosed = true AND isWon = true AND Stage_Status__c != \'Paid Off\'' : '';
            strQuery += (businessUnitFilter == '' || businessUnitFilter == null) ? ' AND Account.Business_Unit__c = \'ELFI\'' : ' AND Account.Business_Unit__c = :businessUnitFilter';
            List<Opportunity> oppties = new List<Opportunity>();
            oppties = Database.query(strQuery);
            System.debug('Oppty: Query: '+strQuery);
            Map<Id,Set<Id>> lawyerToClients = new Map<Id,Set<Id>>();
            
            for(Opportunity opp : oppties)
            {
                if(!lawyerToClients.containsKey(opp.Lawyer__c))
                {
                    lawyerToClients.put(opp.Lawyer__c, new Set<Id>());
                }
                lawyerToClients.get(opp.Lawyer__c).add(opp.AccountId);
            }
            
            for(contact c : contacts)
            {
                ContactInfo info = new ContactInfo();
                info.contact = c;
                info.noOfFiles = lawyerToClients.containsKey(c.Id) ? lawyerToClients.get(c.Id).size() : 0;
                if(info.noOfFiles > 0)
                {
                    contactInfo.add(info);
                }
            }
            return contactInfo;
        }
        catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage());
        }
    }  
    /******************* Method to get all picklists values for Account *********************/  
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    @AuraEnabled
    public static Id send(String query, List<String> selectedIds, String payoutDate, String reportDate, String emailBody, String LoanFilter, String businessUnitFilter){       
        try{
            system.debug('-Here in Send function -');
            system.debug(selectedIds);
            APXT_BPM__Conductor__c conductor;
            APXTConga4__Conga_Merge_Query__c congaQuery;        
            String ids = '';
            
            if(String.isEmpty(query) || query == null) {
                ids = String.Join(selectedIds,',');
                query = 'select id from contact WHERE Id in ('+ ids +')';
            }
            
            Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());        
            customSettings.Payout_Date_Lawyer_Summary_Report__c = (!String.isEmpty(payoutDate) && payoutDate != null) ? Date.valueOf(payoutDate) : customSettings.Payout_Date_Lawyer_Summary_Report__c;
            customSettings.Report_Date_Lawyer_Summary_Report__c = (!String.isEmpty(reportDate) && reportDate != null) ? Date.valueOf(reportDate) : customSettings.Report_Date_Lawyer_Summary_Report__c;
            customSettings.Business_Unit_Lawyer_Summary__c = (!String.isEmpty(businessUnitFilter) && businessUnitFilter != null) ? businessUnitFilter : 'ELFI';
            customSettings.Email_Additional_Notes_Lawyer_Summary__c = emailBody;
            customSettings.Query_Selector_Lawyer_Summary_Report__c = LoanFilter;        
            
            if(String.isEmpty(customSettings.Conductor_Id_Lawyer_Summary_Report__c)){
                congaQuery = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Lawyer summary conductor query - ' + UserInfo.getName(),
                                                                  APXTConga4__Description__c = 'Query of lawyer summary custom report for conga conductor.',
                                                                  APXTConga4__Query__c = query);
                insert congaQuery;
                conductor = new APXT_BPM__Conductor__c(APXT_BPM__Title__c = 'Mass Lawyer Summary - ' + UserInfo.getName(), APXT_BPM__Query_Id__c = congaQuery.Id,
                                                       APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Lawyer_Summary_Send_Email__c');
                insert conductor;            
                customSettings.Conductor_Id_Lawyer_Summary_Report__c = conductor.Id;
            }else{
                conductor = [SELECT Id, APXT_BPM__Query_Id__c, APXT_BPM__URL_Field_Name__c FROM APXT_BPM__Conductor__c WHERE Id =:customSettings.Conductor_Id_Lawyer_Summary_Report__c];
                congaQuery = [SELECT Id, APXTConga4__Query__c FROM APXTConga4__Conga_Merge_Query__c WHERE Id =:conductor.APXT_BPM__Query_Id__c];
                conductor.APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Lawyer_Summary_Send_Email__c';
                update conductor;
                congaQuery.APXTConga4__Query__c = query;
                update congaQuery;
            }
            upsert customSettings;
            return conductor.id;
        }
        catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        }
    }
    
    @AuraEnabled
    public static Id generate(String query, List<String> selectedIds, String payoutDate, String reportDate, String LoanFilter, String businessUnitFilter){
        try{
            APXT_BPM__Conductor__c conductor;
            APXTConga4__Conga_Merge_Query__c congaQuery;        
            String ids = '';
            
            if(String.isEmpty(query) || query == null) {
                ids = String.Join(selectedIds,',');
                query = 'select id from contact WHERE Id in ('+ ids +')';
            }
            
            Conga_batch_setting__c customSettings = Conga_batch_setting__c.getInstance(UserInfo.getUserId());        
            customSettings.Payout_Date_Lawyer_Summary_Report__c = (!String.isEmpty(payoutDate) && payoutDate != null) ? Date.valueOf(payoutDate) : customSettings.Payout_Date_Lawyer_Summary_Report__c;
            customSettings.Report_Date_Lawyer_Summary_Report__c = (!String.isEmpty(reportDate) && reportDate != null) ? Date.valueOf(reportDate) : customSettings.Report_Date_Lawyer_Summary_Report__c;
            customSettings.Business_Unit_Lawyer_Summary__c = (!String.isEmpty(businessUnitFilter) && businessUnitFilter != null) ? businessUnitFilter : 'ELFI';
            customSettings.Query_Selector_Lawyer_Summary_Report__c = LoanFilter;
            
            if(String.isEmpty(customSettings.Conductor_Id_Lawyer_Summary_Report__c)){
                congaQuery = new APXTConga4__Conga_Merge_Query__c(APXTConga4__Name__c = 'Lawyer summary conductor query - ' + UserInfo.getName(),
                                                                  APXTConga4__Description__c = 'Query of lawyer summary custom report for conga conductor.',
                                                                  APXTConga4__Query__c = query);
                insert congaQuery;
                conductor = new APXT_BPM__Conductor__c(APXT_BPM__Title__c = 'Mass Lawyer Summary - ' + UserInfo.getName(), APXT_BPM__Query_Id__c = congaQuery.Id,
                                                       APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Lawyer_Summary__c');
                insert conductor;            
                customSettings.Conductor_Id_Lawyer_Summary_Report__c = conductor.Id;
            }else{
                conductor = [SELECT Id, APXT_BPM__Query_Id__c, APXT_BPM__URL_Field_Name__c FROM APXT_BPM__Conductor__c WHERE Id =:customSettings.Conductor_Id_Lawyer_Summary_Report__c];
                congaQuery = [SELECT Id, APXTConga4__Query__c FROM APXTConga4__Conga_Merge_Query__c WHERE Id =:conductor.APXT_BPM__Query_Id__c];
                conductor.APXT_BPM__URL_Field_Name__c = 'Conga_Batch_Lawyer_Summary__c';
                update conductor;
                congaQuery.APXTConga4__Query__c = query;
                update congaQuery;
            }
            upsert customSettings;
            return conductor.id;	
        }
        catch(Exception e){
            throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        }
    }
    
    public class ContactInfo{
        @AuraEnabled
        public Contact contact{get;set;}
        
        @AuraEnabled
        public Integer noOfFiles{get;set;} 
        
        @AuraEnabled
        public Boolean checked{get;set;} 
    }
}