force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the key person to contact about inquiries related to this account: loan related, additional information, payments, receivables, etc.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>There are no contacts under this account that matches the search criteria.</errorMessage>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Please select the contact that will serve as primary contact for this account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Bank Account Number</description>
    <inlineHelpText>May have spaces or dashes to group the numbers</inlineHelpText>
    <label>Account #</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank #</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Mark_as_Primary__c.field-meta.xml
<CustomField>
    <fullName>Mark_as_Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If set, marks as primary bank account on the Client Account before resetting to false.</description>
    <label>Mark as Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Transit__c.field-meta.xml
<CustomField>
    <fullName>Transit__c</fullName>
    <description>The transaction routing number of the
payor/payee’s financial institution</description>
    <label>Transit #</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ELF_File_No__c.field-meta.xml
<CustomField>
    <fullName>ELF_File_No__c</fullName>
    <label>File No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Deferral_Period__c.field-meta.xml
<CustomField>
    <fullName>Interest_Deferral_Period__c</fullName>
    <description>The Interest Deferral Period from the Opportunity, replicated here to avoid cross object formula size limitations.  Also converted to an number from a picklist value so it&#39;s readily usable in formulas.</description>
    <inlineHelpText>The months to defer interest on this Drawdown.</inlineHelpText>
    <label>Interest Deferral Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
    <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
    <label>Minimum Interest Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EFT_File_Setting__c/EFT_File_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>EFT File Setting</label>
</CustomObject>

force-app/main/default/objects/EFT_File_Setting__c/fields/Account_Number_For_Returns__c.field-meta.xml
<CustomField>
    <fullName>Account_Number_For_Returns__c</fullName>
    <label>Account Number For Returns</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_File_Setting__c/fields/Originator_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Originator_Short_Name__c</fullName>
    <label>Originator Short Name</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_File_Setting__c/fields/Transit_Number_For_Returns__c.field-meta.xml
<CustomField>
    <fullName>Transit_Number_For_Returns__c</fullName>
    <label>Transit Number For Returns</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <label>Minimum Interest Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 months</fullName>
            </value>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>2 months</fullName>
            </value>
            <value>
                <fullName>3 months</fullName>
            </value>
            <value>
                <fullName>4 months</fullName>
            </value>
            <value>
                <fullName>5 months</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
                <default>true</default>
                <label>6 months</label>
            </value>
            <value>
                <fullName>7 months</fullName>
            </value>
            <value>
                <fullName>8 months</fullName>
            </value>
            <value>
                <fullName>9 months</fullName>
            </value>
            <value>
                <fullName>10 months</fullName>
            </value>
            <value>
                <fullName>11 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/Opportunity_Service_Provider__c.object-meta.xml
<CustomObject>
    <label>Opportunity Service Provider</label>
    <nameField>
        <displayFormat>OSP-{00000}</displayFormat>
        <label>OSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Service Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(
ISBLANK(Service_Provider_Facility__r.Primary_Contact__c)
, HYPERLINK(&quot;/&quot;&amp; Service_Provider_Facility__r.Id &amp; &quot;/e?retURL=/&quot; &amp; Service_Provider_Facility__r.Id, &quot;Click Here to Add&quot;, &quot;_blank&quot;)
, HYPERLINK(&quot;/&quot;&amp; Service_Provider_Facility__r.Primary_Contact__r.Id ,Service_Provider_Facility__r.Primary_Contact__r.FirstName &amp;&quot; &quot;&amp; Service_Provider_Facility__r.Primary_Contact__r.LastName,&quot;_blank&quot;) 
)</formula>
    <label>Primary Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that payment should be sent to (will default to Opportunity Account if not set)</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @File Name          : TestDataFactory.cls
 * @Description        : 
 * @Author             : Seth Boyd
 * @Group              : 
 * @Last Modified By   : Seth Boyd
 * @Last Modified On   : 5/13/2019, 6:51:51 AM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    5/1/2019, 1:05:57 PM   Seth Boyd     Initial Version
**/
@isTest
public class TestDataFactory {
    private static EFT_File_Setting__c eftSettings;

    public static EFT_File_Setting__c getEFTFileSettings() {
        if (eftSettings == null) {
            eftSettings = new EFT_File_Setting__c();
            eftSettings.Account_Number_For_Returns__c = '06905521363';
            eftSettings.Transit_Number_For_Returns__c = '000410202';
            eftSettings.Originator_Short_Name__c = 'EasyLegalFinana';
            insert eftSettings;
        }
        return eftSettings;
    }

    public static FObject getUserConfig(Integer count) {
        FObject userConfig = new Fobject('User', count);
        return userConfig;
    }

    public static User[] getUserObjects(FObject userConfig, Boolean doInsert) {
        if (doInsert) {
            userConfig.insertRecords(true);
        }
        return (List<User>)userConfig.getRecords();
    }

    public static User[] getUserObjects(Integer count) {
        return getUserObjects(getUserConfig(count), true);
    }

    public static FObject getContactConfig(Integer count) {
        FObject conConfig = new Fobject('Contact', count);
        Contact acc = new Contact();
        conConfig.setDefinition('ELF_File_No__c', 'random type(string) minlength(4) maxlength(5) startwith(digit) include(digit)');
        conConfig.setDefinition('MailingStreet', 'random type(street) group(mailing)');
        conConfig.setDefinition('MailingPostalCode', 'random type(postalcode) group(mailing)');
        conConfig.setDefinition('MailingCity', 'random type(city) group(mailing)');
        conConfig.setDefinition('MailingState', 'random type(state) group(mailing)');
        conConfig.setDefinition('MailingCountry', 'random type(country) group(mailing)');
        return conConfig;
    }

    public static Contact[] getContactObjects(FObject conConfig, Boolean doInsert) {
        if (doInsert) {
            conConfig.insertRecords(true);
        }
        return (List<Contact>)conConfig.getRecords();
    }

    public static Contact[] getContactObjects(Integer count) {
        return getContactObjects(getContactConfig(count), true);
    }

    public static FObject getAccountConfig(Integer count) {
        FObject accConfig = new Fobject('Account', count);
        Account acc = new Account();
        accConfig.setDefinition('Business_Unit__c', 'static value(Elfi)');
        accConfig.setDefinition('ShippingStreet', 'random type(street) group(shipping)');
        accConfig.setDefinition('ShippingPostalCode', 'random type(postalcode) group(shipping)');
        accConfig.setDefinition('ShippingCity', 'random type(city) group(shipping)');
        accConfig.setDefinition('ShippingState', 'random type(state) group(shipping)');
        accConfig.setDefinition('ShippingCountry', 'random type(country) group(shipping)');
        accConfig.setDefinition('BillingStreet', 'random type(street) group(billing)');
        accConfig.setDefinition('BillingPostalCode', 'random type(postalcode) group(billing)');
        accConfig.setDefinition('BillingCity', 'random type(city) group(billing)');
        accConfig.setDefinition('BillingState', 'random type(state) group(billing)');
        accConfig.setDefinition('BillingCountry', 'random type(country) group(billing)');
        //accConfig.setDefinition('Primary_Contact__c', 'random lookup(Contact) source(forceea)');
        return accConfig;
    }

    public static Account[] getAccountObjects(FObject accConfig, Boolean doInsert) {
        if (doInsert) {
            accConfig.insertRecords(true);
        }
        return (List<Account>)accConfig.getRecords();
    }

    public static Account[] getAccountObjects(Integer count) {
        return getAccountObjects(getAccountConfig(count), true);
    }

    public static FObject getBankAccountConfig(Integer count) {
        FObject baConfig = new Fobject('Bank_Account__c', count);
        baConfig.setDefinition('Name', 'static value(First Last)');
        baConfig.setDefinition('Account__c', 'static value(222-222-222)');
        baConfig.setDefinition('Bank__c', 'static value(0333)');
        baConfig.setDefinition('Transit__c', 'static value(44444)');
        baConfig.setDefinition('Mark_as_Primary__c', 'static value(true)');
        return baConfig;
    }

    public static Bank_Account__c[] getBankAccountObjects(FObject baConfig, Boolean doInsert) {
        if (doInsert) {
            baConfig.insertRecords(true);
        }
        return (List<Bank_Account__c>)baConfig.getRecords();
    }

    public static Bank_Account__c[] getBankAccountObjects(Integer count) {
        return getBankAccountObjects(getBankAccountConfig(count), true);
    }

    public static FObject getOpportunityConfig(Integer count) {
        FObject oppConfig = new Fobject('Opportunity', count);
        oppConfig.setDefinition('Amount', 'random type(number) from(10000) to(50000) scale(0)');
        oppConfig.setDefinition('Admin_Fee__c', 'static value(475)');
        oppConfig.setDefinition('StageName', 'static value(Loan Approved)');
        oppConfig.setDefinition('Stage_Status__c', 'static value(File Sent for EFT)');
        oppConfig.setDefinition('AccountId', 'random lookup(Account) source(forceea)');
        //accConfig.setDefinition('Primary_Contact__c', 'random lookup(Contact) source(forceea)');
        oppConfig.setDefinition('Minimum_Interest_Period__c', 'random type(picklist)');
        oppConfig.setDefinition('Interest_Deferral_Period__c', 'random type(picklist)');
        oppConfig.setDefinition('Interest_Rate__c', 'static value(0.245)');
        oppConfig.setDefinition('Interest_Compounding_Period__c', 'static value(Simple Interest)');
        return oppConfig;
    }

    public static Opportunity[] getOpportunityObjects(FObject oppConfig, Boolean doInsert) {
        if (doInsert) {
            oppConfig.insertRecords(true);
        }
        return (List<Opportunity>)oppConfig.getRecords();
    }

    public static Opportunity[] getOpportunityObjects(Integer count) {
        return getOpportunityObjects(getOpportunityConfig(count), true);
    }

    public static FObject getScheduledPaymentConfig(Integer count) {
        FObject spConfig = new Fobject('Scheduled_Payment__c', count);
        return spConfig;
    }

    public static Scheduled_Payment__c[] getScheduledPaymentObjects(FObject spConfig, Boolean doInsert) {
        if (doInsert) {
            spConfig.insertRecords(true);
        }
        return (List<Scheduled_Payment__c>)spConfig.getRecords();
    }

    public static Scheduled_Payment__c[] getScheduledPaymentObjects(Integer count) {
        return getScheduledPaymentObjects(getScheduledPaymentConfig(count), true);
    }

    public static FObject getOpportunityServiceProviderConfig(Integer count) {
        FObject ospConfig = new Fobject('Opportunity_Service_Provider__c', count);
        return ospConfig;
    }

    public static Opportunity_Service_Provider__c[] getOpportunityServiceProviderObjects(FObject ospConfig, Boolean doInsert) {
        if (doInsert) {
            ospConfig.insertRecords(true);
        }
        return (List<Opportunity_Service_Provider__c>)ospConfig.getRecords();
    }

    public static Opportunity_Service_Provider__c[] getOpportunityServiceProviderObjects(Integer count) {
        return getOpportunityServiceProviderObjects(getOpportunityServiceProviderConfig(count), true);
    }

    public static FObject getDrawdownDrawdownConfig(Integer count) {
        FObject ddConfig = new Fobject('Drawdown__c', count);
        return ddConfig;
    }

    public static Drawdown__c[] getDrawdownDrawdownObjects(FObject ddConfig, Boolean doInsert) {
        if (doInsert) {
            ddConfig.insertRecords(true);
        }
        return (List<Drawdown__c>)ddConfig.getRecords();
    }

    public static Drawdown__c[] getDrawdownDrawdownObjects(Integer count) {
        return getDrawdownDrawdownObjects(getDrawdownDrawdownConfig(count), true);
    }
}
/*
BankAccountsControllerTest,CSL_OpportunityServiceProviderCtlrTest,CustomerViewComponentCtlrTest,DrawdownHelperTest,EFTFileTest,FundingDetailsComponentCtlrTest,OpportunityViewComponentCtlrTest,PaymentControllerTest,ScheduledPaymentHelperTest,ScheduledPaymentTriggerHandlerTest,TriggerHandler_Test,dlrs_OpportunityTest,dlrs_Opportunity_Service_ProviderTest,dlrs_Scheduled_PaymentTest
*/