force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ProvinceResidency__c.field-meta.xml
<CustomField>
    <fullName>ProvinceResidency__c</fullName>
    <label>Province of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provinces</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bad_Debt_Summary_Report__c/Bad_Debt_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bad Debt Summary Report</label>
</CustomObject>

force-app/main/default/objects/Bad_Debt_Summary_Report__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Report.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bad_Debt_Summary_Report__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Report.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Bad_Debt_Summary_Report_Print_All__c.field-meta.xml
<CustomField>
    <fullName>Conga_Bad_Debt_Summary_Report_Print_All__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&quot;&amp; 
&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_370&amp; 
&quot;&amp;Id=&quot;&amp;Id&amp; 
&quot;&amp;QueryId=&quot;&amp;IF( $Setup.Bad_Debt_Summary_Report__c.BusinessUnit__c = &#39;Rhino&#39;, &#39;[BadDebtSummaryView]a0p0L00000J9Opv&#39;,IF( $Setup.Bad_Debt_Summary_Report__c.BusinessUnit__c = &#39;ELFI&#39;, &#39;[BadDebtSummaryView]a0p0L00000J9Opu&#39;,&#39;[BadDebtSummaryView]a0p0L00000J9Opz&#39;))&amp;&quot;%3Fpv0%3D&quot;&amp;Conga_Bad_Debt_Summary_Rpt_Start_Date__c &amp;&quot;~pv1%3D&quot;&amp;Conga_Bad_Debt_Summary_Rpt_End_Date__c&amp; 
&quot;&amp;TemplateId=a0x0L00000PYLgk&amp;DS7=3&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Bad Debt Summary Report Print All</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Bad_Debt_Summary_Report_View_All__c.field-meta.xml
<CustomField>
    <fullName>Conga_Bad_Debt_Summary_Report_View_All__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&quot;&amp; 
&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_370&amp; 
&quot;&amp;Id=&quot;&amp;Id&amp; 
&quot;&amp;QueryId=&quot;&amp;IF( $Setup.Bad_Debt_Summary_Report__c.BusinessUnit__c = &#39;Rhino&#39;, &#39;[BadDebtSummaryView]a0p0L00000J9Opp&#39;,IF( $Setup.Bad_Debt_Summary_Report__c.BusinessUnit__c = &#39;ELFI&#39;, &#39;[BadDebtSummaryView]a0p0L00000J9Opg&#39;,&#39;[BadDebtSummaryView]a0p0L00000J9Opf&#39;))&amp;&quot;%3Fpv0%3D&quot;&amp;Conga_Bad_Debt_Summary_Rpt_Start_Date__c &amp;&quot;~pv1%3D&quot;&amp;Conga_Bad_Debt_Summary_Rpt_End_Date__c&amp; 
&quot;&amp;TemplateId=a0x0L00000PYLgp&amp;DS7=3&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Bad Debt Summary Report View All</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Payment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Provinces.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Ontario</fullName>
    </customValue>
    <customValue>
        <fullName>Manitoba</fullName>
    </customValue>
    <customValue>
        <fullName>New Brunswick</fullName>
    </customValue>
    <customValue>
        <fullName>Newfoundland &amp; Labrador</fullName>
    </customValue>
    <customValue>
        <fullName>Northwest Territories</fullName>
    </customValue>
    <customValue>
        <fullName>Nova Scotia</fullName>
    </customValue>
    <customValue>
        <fullName>Nunavut</fullName>
    </customValue>
    <customValue>
        <fullName>Prince Edward Island</fullName>
    </customValue>
    <customValue>
        <fullName>Quebec</fullName>
    </customValue>
    <customValue>
        <fullName>Saskatchewan</fullName>
    </customValue>
    <customValue>
        <fullName>Yukon Territory</fullName>
    </customValue>
    <masterLabel>Provinces</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BadDebtSummaryReportCtlr.cls
public with sharing class BadDebtSummaryReportCtlr {
    @AuraEnabled
    public static list<Wrapper> getPaymentsGroupByProvince(String startDate, String endDate, string BusinessUnit){
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            String strQuery = '';            
            
            string payment = 'Payment';
            string ClosedWithLoan = 'Closed With Loan';
            String badDebt = 'Bad Debt';
            String paymentShortfall = 'Payment Shortfall';
            
            string filterByBusinessUnit = '';
            string Rhino = 'Rhino';
            string Elfi = 'ELFI';
            
            if(BusinessUnit == 'ELFI'){
                
                filterByBusinessUnit = 'ELFI';
            }else if(BusinessUnit == 'Rhino'){
                
                filterByBusinessUnit = 'Rhino';
            }else if(BusinessUnit == 'Consolidated'){
                
                filterByBusinessUnit = 'Consolidated';
            }
            
            strQuery = 'Select Opportunity__r.Account.ProvinceResidency__c province,Opportunity__r.Account.Business_Unit__c businessunit, COUNT_DISTINCT(Opportunity__r.AccountId) file,'; 
            strQuery += ' COUNT_DISTINCT(Opportunity__c) opptyCount, SUM(Amount__c) amt';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            //strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            //strQuery += ' AND Payment_Method__c =:payment';
            strQuery += ' AND';
            strQuery += (filterByBusinessUnit == 'Consolidated') ? 
                ' (Opportunity__r.Account.Business_Unit__c =:Elfi OR Opportunity__r.Account.Business_Unit__c =:Rhino)':
            ' Opportunity__r.Account.Business_Unit__c =:filterByBusinessUnit';
            strQuery += ' AND Reference_Notes__c =:badDebt';
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += ' Group by Opportunity__r.Account.ProvinceResidency__c,Opportunity__r.Account.Business_Unit__c';
            strQuery += ' Order by SUM(Amount__c) desc NULLS LAST';
            
            List<AggregateResult> aggResult = Database.query(strQuery);
            if(!aggResult.isEmpty()){
                map<string, wrapper> agrMap = new map<string, wrapper>();
                
                for(AggregateResult agr : aggResult){
                    
                    if(agrMap.containsKey(String.ValueOf(agr.get('province')))){
                        // if province exists 
                        wrapper w = agrMap.get(String.ValueOf(agr.get('province')));
                        
                        if(String.valueof(agr.get('businessunit')) == 'Rhino'){
                            
                            w.rhinoAccountCount = Integer.valueof(agr.get('file'));
                            w.rhinoOpptyCount = Integer.valueof(agr.get('opptyCount'));
                            w.rhinoAmount = Double.valueof(agr.get('amt'));
                        }else if(String.valueof(agr.get('businessunit')) == 'ELFI'){
                            
                            w.elfiAccountCount = Integer.valueof(agr.get('file'));
                            w.elfiOpptyCount = Integer.valueof(agr.get('opptyCount'));
                            w.elfiAmount = Double.valueof(agr.get('amt'));
                        }
                        
                        agrMap.put(String.ValueOf(agr.get('province')), w);
                        
                    }else{
                        // new province
                        wrapper w;
                        if(String.valueof(agr.get('businessunit')) == 'Rhino'){
                            
                            w = new wrapper(String.ValueOf(agr.get('province')),
                                            Integer.valueof(agr.get('file')),
                                            Integer.valueof(agr.get('opptyCount')),
                                            Double.valueof(agr.get('amt')),0,0,0.00);
                            
                        }else if(String.valueof(agr.get('businessunit')) == 'ELFI'){
                            
                            w = new wrapper(String.ValueOf(agr.get('province')),0,0,0.00,
                                            Integer.valueof(agr.get('file')),
                                            Integer.valueof(agr.get('opptyCount')),
                                            Double.valueof(agr.get('amt')));
                        }
                        agrMap.put(String.ValueOf(agr.get('province')), w);
                    }
                }
                
                
                list<Wrapper> finalWrapper = new list<Wrapper>(); 
                
                for(string key : agrMap.keyset()){
                    
                    Wrapper w = agrMap.get(key);
                    
                    if(w == null) continue;
                    
                    finalWrapper.add(new Wrapper(w.province, 
                                                 w.rhinoAccountCount, w.rhinoOpptyCount, w.rhinoAmount, 
                                                 w.elfiAccountCount, w.elfiOpptyCount, w.elfiAmount));
                    
                    
                }
                
                //system.debug('Wrapper records are:');
                //system.debug(finalWrapper);
                
                return finalWrapper;
                //return aggResult;
            }
            return null;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled 
    public static Drawdown__c getDrawdown(){
        List<Drawdown__c> congaUrlHolder = [Select Conga_Bad_Debt_Summary_Report_Print_All__c,
                                            Conga_Bad_Debt_Summary_Report_View_All__c 
                                            from Drawdown__c limit 1];
        return congaUrlHolder[0];
    }
    
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    @AuraEnabled
    public static void saveDateCustomSettings(String startDate, String endDate){
        try{
            
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            Bad_Debt_Summary_Report__c bdr = Bad_Debt_Summary_Report__c.getOrgDefaults();
            
            bdr.End_Date__c = endDt;
            bdr.Start_Date__c = startDt;
            
            upsert bdr;
            
            
            
        }catch(Exception ex){
            
            throw new AuraHandledException(ex.getMessage());
        }
        
        
    }
    @AuraEnabled
    public static void saveBusinessUnitCustomSettings(String BusinessUnit){
        try{
            
            // Bad_Debt_Summary_Report__c bdr = Bad_Debt_Summary_Report__c.getInstance(UserInfo.getUserId());
            Bad_Debt_Summary_Report__c bdr = Bad_Debt_Summary_Report__c.getOrgDefaults();
            
            bdr.BusinessUnit__C = BusinessUnit;
            
            upsert bdr;
            
            
            
        }catch(Exception ex){
            
            throw new AuraHandledException(ex.getMessage());
        }
        
        
    }
    @AuraEnabled
    public static Bad_Debt_Summary_Report__c getCustomSetting(){
        // Bad_Debt_Summary_Report__c bDSR = Bad_Debt_Summary_Report__c.getInstance(UserInfo.getUserId());
        Bad_Debt_Summary_Report__c bDSR = Bad_Debt_Summary_Report__c.getOrgDefaults();
        return bDSR;
    }
    
    public class Wrapper {
        @AuraEnabled
        string province {get; set;}
        @AuraEnabled
        integer rhinoAccountCount {get; set;}
        @AuraEnabled
        integer rhinoOpptyCount {get; set;}
        @AuraEnabled
        decimal rhinoAmount {get; set;}
        @AuraEnabled
        integer elfiAccountCount {get; set;}
        @AuraEnabled
        integer elfiOpptyCount {get; set;}
        @AuraEnabled
        decimal elfiAmount {get; set;}
        
        wrapper(string p, integer rc, integer roc, decimal ra, integer ec, integer eoc, decimal ea){
            
            province = p;
            
            rhinoAccountCount = rc;
            rhinoOpptyCount = roc;
            rhinoAmount = ra;
            
            elfiAccountCount = ec;
            elfiOpptyCount = eoc;
            elfiAmount = ea;
        }
        
    }
}