force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Closed_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Closed_Date__c</fullName>
    <label>Opportunity Closed Date</label>
    <summarizedField>Drawdown__c.Date__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Reference_Notes__c</field>
        <operation>equals</operation>
        <value>Loan Payout, Payment Shortfall, Payment Surplus</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>equals</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LawfirmSalesSummaryPayoutReportCtlr.cls
public with sharing class LawfirmSalesSummaryPayoutReportCtlr {
    public Date startDate{get;set;}
    public Date endDate{get;set;}
    public String businessUnit{get;set;}
    public String contentType{get;set;}
    public String renderAs{get;set;}
    
    public LawfirmSalesSummaryPayoutReportCtlr(){
        Date dt = Date.today();
        contentType = '';
        renderAs = '';
        
        Date startDt = Date.valueOf(startDate);
        Date endDt = Date.valueOf(endDate);
        
        String paramBusinessUnit = ApexPages.currentPage().getParameters().get('BusinessUnit');
        String paramStartDate = ApexPages.currentPage().getParameters().get('StartDate');
        String paramEndDate = ApexPages.currentPage().getParameters().get('EndDate');
        String paramContentType = ApexPages.currentPage().getParameters().get('ContentType');
        
        if(paramContentType == 'PDF'){
            renderAs = 'PDF';
        }else{
            contentType = 'application/x-excel#LawfirmSalesSummaryPayoutViewAll.xls';
        }
        
        this.businessUnit = !String.isEmpty(paramBusinessUnit) ? paramBusinessUnit : 'ELFI';
        this.startDate = !String.isEmpty(paramStartDate)? Date.valueOf(paramStartDate) : dt.addDays(-30);
            this.endDate = !String.isEmpty(paramEndDate)? Date.valueOf(paramEndDate) : dt;
    }
    
    public List<Wrapper> getPayoutDrawdowns(){
        
        List<Drawdown__c> drawdowns = new List<Drawdown__c>();
        List<Wrapper> result = new List<Wrapper>();
        
        string eTransfer = 'e-Transfer';
        String payment = 'Payment';
        String loanPayout = 'Loan Payout';
        String partialPayment = 'Partial Payment';
        String paymentShortfall = 'Payment Shortfall';
        String paymentSurplus = 'Payment Surplus';
        string Cheque = 'Cheque';
        string AdminFee = 'Admin Fee';
        String ClosedWithLoan = 'Closed With Loan';
        String closedPaid = 'Closed - Paid';
        String closedShortfall = 'Closed - Shortfall';
        String closedSurplus = 'Closed - Surplus';
        
        String strQuery = 'SELECT Opportunity__r.Law_Firm__c';
        strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDate'; 
        strQuery += ' AND Date__c <= :endDate'; 
        strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan AND ((Payment_Method__c =:eTransfer)';
        strQuery += ' OR (Payment_Method__c =:Cheque)';
        strQuery += ' OR (Payment_Method__c =:AdminFee))';
        strQuery += ' AND Is_Rejected__c = false';
        strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit';
        strQuery += ' AND Opportunity__r.Law_firm__c != \'\''; 
        
        drawdowns = Database.query(strQuery);
        
        Set<Id> lawfirmIdsSet = new Set<Id>();
        
        for(Drawdown__c drawdown: drawdowns){
            lawfirmIdsSet.add(drawdown.Opportunity__r.Law_Firm__c);
        }
        
        
        if(!lawfirmIdsSet.isEmpty()){
            
            strQuery = 'SELECT Id, Name, Opportunity__r.Account.Name,';
            strQuery += ' Opportunity__r.Account.Business_Unit__c, Opportunity__r.Law_Firm__c,';
            strQuery += ' Opportunity__r.Law_Firm__r.Name, Date__c, Amount__c,Payment_Method__c';
            strQuery += ' FROM Drawdown__c WHERE Opportunity__r.Opportunity_Closed_Date__c >= :startDate'; 
            strQuery += ' AND Opportunity__r.Opportunity_Closed_Date__c <= :endDate'; 
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND Payment_Method__c =:payment';  
            strQuery += ' AND (Reference_Notes__c =:loanPayout OR Reference_Notes__c =:partialPayment'; 
            strQuery += ' OR Reference_Notes__c =:paymentShortfall OR Reference_Notes__c =:paymentSurplus)'; 
            strQuery += ' AND (Opportunity__r.Stage_Status__c =:closedPaid';
            strQuery += ' OR Opportunity__r.Stage_Status__c =:closedShortfall';
            strQuery += ' OR Opportunity__r.Stage_Status__c =:closedSurplus)';
            strQuery += ' AND Opportunity__r.Law_firm__c in :lawfirmIdsSet';
            strQuery += ' AND Is_Rejected__c = false';   
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit';
            strQuery += ' order by Opportunity__r.Law_Firm__r.Name asc NULLS LAST, Opportunity__r.Account.Business_Unit__c NULLS LAST , Date__c desc, Opportunity__r.Account.Name asc';
            
            drawdowns.clear();
            drawdowns = Database.query(strQuery);
            
            Map<String,List<Drawdown__c>> lawfirmDrawdownsMap = new Map<String,List<Drawdown__c>>();
            for(Drawdown__c drawdown : drawdowns){
                if(!lawfirmDrawdownsMap.containsKey(drawdown.Opportunity__r.Law_Firm__r.Name))
                    lawfirmDrawdownsMap.put(drawdown.Opportunity__r.Law_Firm__r.Name, new List<Drawdown__c>());
				lawfirmDrawdownsMap.get(drawdown.Opportunity__r.Law_Firm__r.Name).add(drawdown);                
            }
            
            if(!lawfirmDrawdownsMap.isEmpty()){
                for(String firmName : lawfirmDrawdownsMap.keySet()){
                    result.add(new Wrapper(firmName, lawfirmDrawdownsMap.get(firmName)));
                }
            }
            
        }
        
        return result;
        
    }
    
    public class Wrapper {
        public String Lawfirm {get;set;}
        public List<Drawdown__c> drawdowns{get;set;}
        
        public Wrapper(string lawfirmName, List<Drawdown__c> drawdownList){
            Lawfirm = lawfirmName;
            drawdowns = drawdownList;
        }
    }
}