force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Name_Formula__c</fullName>
    <formula>IF(CONTAINS( TRIM(Name)   , &#39;- Account # &#39;),  SUBSTITUTE(Name, &#39;- Account # &#39;, &#39;- 0000&#39;),  IF(CONTAINS( TRIM(Name)   , &#39;-Account # &#39;), SUBSTITUTE(Name, &#39;-Account # &#39;, &#39;- 0000&#39;), IF(CONTAINS( TRIM(Name)   , &#39;- Account #&#39;), SUBSTITUTE(Name, &#39;- Account #&#39;, &#39;- 0000&#39;),  IF(CONTAINS( TRIM(Name)   , &#39;-Account #&#39;), SUBSTITUTE(Name, &#39;-Account #&#39;, &#39;- 0000&#39;), TRIM(Name)) ) ) )</formula>
    <label>Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Available_Credit__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit__c</fullName>
    <formula>Approved_Credit_Limit__c - Utilized_Credit_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Lawyer, Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Name_Formula__c</fullName>
    <description>contacts having middle name cannot be queried using name like&#39;%Patricia Jean Shroeder%&#39; This field is desgned to be used in where clause of contact query in custom lookup LEX component.</description>
    <formula>IF( ISBLANK( TEXT(Salutation )), &#39;&#39; , TEXT(Salutation ) &amp; &#39; &#39; )&amp;
IF( ISBLANK( FirstName ), &#39;&#39; , FirstName &amp; &#39; &#39; )&amp;
IF( ISBLANK( MiddleName ), &#39;&#39; , MiddleName &amp; &#39; &#39; )&amp;
IF( ISBLANK( LastName ), &#39;&#39; , LastName )</formula>
    <label>Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Name_Formula__c</fullName>
    <formula>Name</formula>
    <label>Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessment Provider Referred Cases</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>

</CustomField>

force-app/main/default/objects/Opportunity/fields/Available_Credit__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit__c</fullName>
    <formula>IF((Amount -  Admin_Fee__c -  Amount_Paid_to_Client__c )  &lt; 0 , 0 , (Amount -  Admin_Fee__c -  Amount_Paid_to_Client__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PreApprovedInvoiceCtlr.cls
public with sharing class PreApprovedInvoiceCtlr {
    
    public String businessUnit{get;set;}
    public String searchText{get;set;}
    public String contentType{get;set;}
    public String renderAs{get;set;}
    
    public class PreApprovedInvoiceWrapper{
        @AuraEnabled
        public string lawyer {get; set;}
        @AuraEnabled
        public string lawyerId {get; set;}
        @AuraEnabled
        public string firm {get; set;}
        @AuraEnabled
        public string firmId {get; set;}        
        @AuraEnabled
        public string assessmentProvider {get; set;}
        @AuraEnabled
        public string assessmentProviderId {get; set;}
        @AuraEnabled
        public Date preApprovedDate{get;set;}
        
        @AuraEnabled
        public Decimal amountElfi{get;set;}
        @AuraEnabled
        public Decimal amountRhino{get;set;}
        
        @AuraEnabled
        public Decimal availableCredit{get;set;}
        
        @AuraEnabled
        public Boolean checked {get; set;}
       
        
        public PreApprovedInvoiceWrapper(){
            lawyer = '';
            lawyerId = '';
            firm = '';
            firmId = '';  
            assessmentProvider = '';
            assessmentProviderId = '';
            preApprovedDate = null;
            amountElfi = 0;
            amountRhino = 0;
            availableCredit = 0;
            checked = false;
        }
    }
    
    public PreApprovedInvoiceCtlr(){
        contentType = '';
        renderAs = '';
        string businessUnitParam = Apexpages.currentPage().getParameters().get('businessUnit');
        searchText = Apexpages.currentPage().getParameters().get('searchByName');        
        this.businessUnit = businessUnitParam != null && !String.isEmpty(businessUnitParam)? businessUnitParam : 'ELFI';
        
        String paramContentType = ApexPages.currentPage().getParameters().get('ContentType');
        
        if(paramContentType == 'PDF'){
            renderAs = 'PDF';
        }else{
            contentType = 'application/x-excel#Pre-ApprovedInvoices.xls';
        }
        
    }
    
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    
    public List<PreApprovedInvoiceWrapper> getPreApprovedInvoicesVF(){
        return getPreApprovedInvoices(this.searchText, this.businessUnit, 'Opportunity__r.Lawyer__r.Name','ASC');
    }
    
    @AuraEnabled
    public static List<PreApprovedInvoiceWrapper> getPreApprovedInvoices(String searchByName, String BusinessUnit, String field, String direction){
        
        Map<String, PreApprovedInvoiceWrapper>  preApprovedInvoicesMap = new Map<String, PreApprovedInvoiceWrapper>();
        
        try{
            String filterByBusinessUnit = '';
            string Rhino = 'Rhino';
            string Elfi = 'ELFI';
            String assessment = 'Assessment';
            
            if(BusinessUnit == 'ELFI'){                
                filterByBusinessUnit = 'ELFI';
            }else if(BusinessUnit == 'Rhino'){                
                filterByBusinessUnit = 'Rhino';
            }else if(BusinessUnit == 'Consolidated'){                
                filterByBusinessUnit = 'Consolidated';
            }
            
            String strQuery = '';
            strQuery += 'SELECT Opportunity__r.Lawyer__c lawyerId, Opportunity__r.Lawyer__r.Name lawyerName,';
            strQuery += ' Opportunity__r.Law_Firm__c lawfirmId, Opportunity__r.Law_Firm__r.Name lawfirm,';
            strQuery += ' Opportunity__r.Assessment_Provider__c assessmentProviderId, Opportunity__r.Assessment_Provider__r.Name assessmentProvider,';
            strQuery += ' Opportunity__r.Account.Business_Unit__c businessUnit, Max(Date__c) preApprovedDate,';
            strQuery += ' Sum(Amount__c) amt FROM Drawdown__c';
            strQuery += ' WHERE Opportunity__r.Stage_Status__c = \'Invoice Pre-Approved\'';
            strQuery += ' AND Opportunity__r.Type_of_Loan__c = \'Assessment\'';
            strQuery += ' AND Is_Rejected__c = false AND Reference_Notes__c != \'Payment Rejected\'';
            strQuery += (filterByBusinessUnit == 'Consolidated') ? 
                ' AND (Opportunity__r.Account.Business_Unit__c =:Elfi OR Opportunity__r.Account.Business_Unit__c =:Rhino)':
            ' AND Opportunity__r.Account.Business_Unit__c =:filterByBusinessUnit';
            strQuery += !String.isEmpty(searchByName) && searchByName != null ? ' AND (Opportunity__r.Lawyer__r.Name_Formula__c LIKE \'%' + searchByName + '%\''  : '';
            strQuery += !String.isEmpty(searchByName) && searchByName != null ? ' OR Opportunity__r.Law_Firm__r.Name LIKE \'%' + searchByName + '%\')'  : '';
            strQuery += ' GROUP BY Opportunity__r.Lawyer__c, Opportunity__r.Lawyer__r.Name, Opportunity__r.Law_Firm__c,';
            strQuery += ' Opportunity__r.Law_Firm__r.Name, Opportunity__r.Assessment_Provider__c, Opportunity__r.Assessment_Provider__r.Name, Opportunity__r.Account.Business_Unit__c';
            strQuery += ' ORDER BY ' + field + ' ' + direction + ' NULLS LAST';
            
            List<AggregateResult> aggrResult = Database.query(strQuery);
            
            Set<Id> lawyerIds = new Set<Id>();
            for(AggregateResult aggResult : aggrResult){
                lawyerIds.add((Id)aggResult.get('lawyerId'));
            }
            
            Map<Id, Contact> LawyersMap = new Map<Id, Contact>([
                SELECT Id, Available_Credit__c
                FROM Contact
                WHERE Id in :lawyerIds
            ]);
            
            PreApprovedInvoiceWrapper preApprovedInvoice = null;
            for(AggregateResult aggResult : aggrResult){
                
                String lawyerId = (String) aggResult.get('lawyerId');
                String lawfirmId = (String) aggResult.get('lawfirmId');
                String assessmentProviderId = (String) aggResult.get('assessmentProviderId');
                String key = lawyerId + '-' + lawfirmId + '-' + assessmentProviderId;
                
                preApprovedInvoice = new PreApprovedInvoiceWrapper();
                if(preApprovedInvoicesMap.containsKey(key))
                    preApprovedInvoice = preApprovedInvoicesMap.get(key);
                
                preApprovedInvoice.lawyerId = lawyerId;
                preApprovedInvoice.lawyer = (String) aggResult.get('lawyerName');
                preApprovedInvoice.firmId = lawfirmId;
                preApprovedInvoice.firm = (String) aggResult.get('lawfirm');
                preApprovedInvoice.assessmentProviderId = assessmentProviderId;
                preApprovedInvoice.assessmentProvider = (String) aggResult.get('assessmentProvider');
                
                preApprovedInvoice.preApprovedDate = aggResult.get('preApprovedDate') != null? Date.valueOf(aggResult.get('preApprovedDate')) : null;
                
                preApprovedInvoice.availableCredit = LawyersMap.ContainsKey(lawyerId)? LawyersMap.get(lawyerId).Available_Credit__c != null? LawyersMap.get(lawyerId).Available_Credit__c : 0 : 0;
                
                preApprovedInvoice.amountElfi += aggResult.get('businessUnit') == 'ELFI'? aggResult.get('amt') != null? (Decimal)aggResult.get('amt') : 0 : 0;
                preApprovedInvoice.amountRhino += aggResult.get('businessUnit') == 'Rhino'? aggResult.get('amt') != null? (Decimal)aggResult.get('amt') : 0 : 0;
                
                preApprovedInvoicesMap.put(key, preApprovedInvoice);
            }
            
           
            
        }catch(Exception e){
            system.System.debug(e.getMessage() + ' ' + e.getLineNumber());
            system.System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getMessage() + ' ' + e.getLineNumber());
        }
        
        return preApprovedInvoicesMap.values();
    }
}