force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ProvinceResidency__c.field-meta.xml
<CustomField>
    <fullName>ProvinceResidency__c</fullName>
    <label>Province of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provinces</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Scenario__c.field-meta.xml
<CustomField>
    <fullName>Scenario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Indicates which type of loan document template should be generated for this Opportunity</inlineHelpText>
    <label>Document Scenario</label>
    <referenceTo>Scenario__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scenario__c/Scenario__c.object-meta.xml
<CustomObject>
    <description>Used to model the differences between documents under different scenarios such as region, loan type or legal professional.</description>
    <label>Scenario</label>
    <nameField>
        <label>Scenario Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scenario__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/LoanType__c.field-meta.xml
<CustomField>
    <fullName>LoanType__c</fullName>
    <label>Loan Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scenario__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Region</label>
    <referenceTo>Scenario_Region__c</referenceTo>
    <relationshipLabel>Scenarios</relationshipLabel>
    <relationshipName>Scenarios</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scenario_Region__c/Scenario_Region__c.object-meta.xml
<CustomObject>
    <label>Scenario Region</label>
    <nameField>
        <label>Scenario Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scenario Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scenario_Region__c/fields/Provinces__c.field-meta.xml
<CustomField>
    <fullName>Provinces__c</fullName>
    <label>Provinces</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provinces</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Provinces.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Ontario</fullName>
    </customValue>
    <customValue>
        <fullName>Manitoba</fullName>
    </customValue>
    <customValue>
        <fullName>New Brunswick</fullName>
    </customValue>
    <customValue>
        <fullName>Newfoundland &amp; Labrador</fullName>
    </customValue>
    <customValue>
        <fullName>Northwest Territories</fullName>
    </customValue>
    <customValue>
        <fullName>Nova Scotia</fullName>
    </customValue>
    <customValue>
        <fullName>Nunavut</fullName>
    </customValue>
    <customValue>
        <fullName>Prince Edward Island</fullName>
    </customValue>
    <customValue>
        <fullName>Quebec</fullName>
    </customValue>
    <customValue>
        <fullName>Saskatchewan</fullName>
    </customValue>
    <customValue>
        <fullName>Yukon Territory</fullName>
    </customValue>
    <masterLabel>Provinces</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AC_ScenarioTool.cls
public class AC_ScenarioTool {
    @InvocableMethod(label='Assign Scenarios' description='Assigns Scenario to Opportunities')
    public static void assignScenarios(Opportunity[] opps){
        // This can be invoked from a Process Builder; have to extract IDs as a result
        Set<ID> ids = new Map<ID, Opportunity>(opps).keySet();
         
        Scenario__c[] scenarios = [SELECT Id, LoanType__c, Business_Unit__c, Region__c, Region__r.Provinces__c FROM Scenario__c];
        Opportunity[] allOpps = [SELECT Id, Type_of_Loan__c, Account.Business_Unit__c, Account.ProvinceResidency__c,
                                 Scenario__r.LoanType__c, Scenario__r.Region__c, Scenario__r.Region__r.Provinces__c, Scenario__r.Business_Unit__c
                                   FROM Opportunity
                                   WHERE Id IN :ids];
        Opportunity[] targetOpps = (new Opportunity[]{});
        
        // try to match Opportunities to Scenarios
        for (Opportunity o : allOpps){
            // get existing scenario
            Scenario__c os = o.Scenario__r;
            // coalesce nulls
            String sProvinces = (os == null ? '' : o.Scenario__r.Region__r.Provinces__c);
            String sBusinessUnit = (os == null ? '' : o.Scenario__r.Business_Unit__c);
            system.debug('Business Unit ; ' + sBusinessUnit);
            String sLoanType = (os == null ? '' : o.Scenario__r.LoanType__c);
            // Avoid false positive
            String oProvince = 'zzzzzz';
            String oBusinessUnit = 'zzzzzz';
            if (o.AccountId != null && !String.isBlank(o.Account.ProvinceResidency__c) && !String.isBlank(o.Account.Business_Unit__c) && o.Account.Business_Unit__c != null){
                oProvince = o.Account.ProvinceResidency__c;
                oBusinessUnit = o.Account.Business_Unit__c;
                system.debug(oBusinessUnit);
            }
                
            // skip if already matches
            if (o.Type_of_Loan__c == sLoanType && sProvinces.contains(oProvince) && sBusinessUnit.contains(oBusinessUnit)){ continue; }
            // otherwise null it and then search for a match
            o.Scenario__c = null;
            targetOpps.add(o);
            // find matching scenario if exists
            for (Scenario__c s : scenarios){
                if (o.Type_of_Loan__c == s.LoanType__c && s.Region__r.Provinces__c != null && s.Region__r.Provinces__c.contains(oProvince) &&
                   s.Business_Unit__c == o.Account.Business_Unit__c){
                    o.Scenario__c = s.Id;

                    // exit inner loop when a match is found
                    break;
                }
            }
        }
        
        // update identified Opportunities
        if (targetOpps.size() > 0)
        	update targetOpps;
    }
}
/*
public class AC_ScenarioTool {
    @InvocableMethod(label='Assign Scenarios' description='Assigns Scenario to Opportunities')
    public static void assignScenarios(Opportunity[] opps){
        // This can be invoked from a Process Builder; have to extract IDs as a result
        Set<ID> ids = new Map<ID, Opportunity>(opps).keySet();
         
        Scenario__c[] scenarios = [SELECT Id, LoanType__c, Region__c, Region__r.Provinces__c FROM Scenario__c];
        Opportunity[] allOpps = [SELECT Id, Type_of_Loan__c, Account.ProvinceResidency__c
                                 , Scenario__r.LoanType__c, Scenario__r.Region__c, Scenario__r.Region__r.Provinces__c
                                   FROM Opportunity
                                   WHERE Id IN :ids];
        Opportunity[] targetOpps = (new Opportunity[]{});
        
        // try to match Opportunities to Scenarios
        for (Opportunity o : allOpps){
            // get existing scenario
            Scenario__c os = o.Scenario__r;
            // coalesce nulls
            String sProvinces = (os == null ? '' : o.Scenario__r.Region__r.Provinces__c);
            String sLoanType = (os == null ? '' : o.Scenario__r.LoanType__c);
            // Avoid false positive
            String oProvince = 'zzzzzz';
            if (o.AccountId != null && !String.isBlank(o.Account.ProvinceResidency__c))
                oProvince = o.Account.ProvinceResidency__c;
            // skip if already matches
            if (o.Type_of_Loan__c == sLoanType && sProvinces.contains(oProvince)){ continue; }
            // otherwise null it and then search for a match
            o.Scenario__c = null;
            targetOpps.add(o);
            // find matching scenario if exists
            for (Scenario__c s : scenarios){
                if (o.Type_of_Loan__c == s.LoanType__c && s.Region__r.Provinces__c != null && s.Region__r.Provinces__c.contains(oProvince)){
                    o.Scenario__c = s.Id;

                    // exit inner loop when a match is found
                    break;
                }
            }
        }
        
        // update identified Opportunities
        if (targetOpps.size() > 0)
        	update targetOpps;
    }
}*/