force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ProvinceResidency__c.field-meta.xml
<CustomField>
    <fullName>ProvinceResidency__c</fullName>
    <label>Province of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provinces</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bad_Debt_Summary_Report__c/Bad_Debt_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Bad Debt Summary Report</label>
</CustomObject>

force-app/main/default/objects/Bad_Debt_Summary_Report__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>End Date of Report.</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bad_Debt_Summary_Report__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Start Date of Report.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_In_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_In_Reporting_Period__c</fullName>
    <formula>Accrued_Interest_as_of_To_Date__c -  Accrued_Interest_as_of_From_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accrued Interest In Reporting Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Financial_Summary_Report_Print_2__c.field-meta.xml
<CustomField>
    <fullName>Conga_Financial_Summary_Report_Print_2__c</fullName>
    <formula>&quot;,[pPaymentElfi]a0p0L00000JaYzu%3Fpv0%3D&quot; &amp; Conga_Financial_Summary_Rpt_Start_Date__c 
 &amp; &quot;~pv1%3D&quot; &amp; Conga_Financial_Summary_Rpt_End_Date__c 

&amp; &quot;,[pPaymentRhino]a0p0L00000IzuS8%3Fpv0%3D&quot; &amp; Conga_Financial_Summary_Rpt_Start_Date__c 
 &amp; &quot;~pv1%3D&quot; &amp; Conga_Financial_Summary_Rpt_End_Date__c

&amp; &quot;,[AccruedElfi]a0p0L00000Jajk9&quot; 

&amp; &quot;,[AccruedRhino]a0p0L00000IzuSD&quot; 

&amp; &quot;&amp;TemplateId=&quot; &amp;  IF( $Setup.Financial_Summary_Report__c.BusinessUnit__c = &#39;ELFI&#39;,&#39;a0x0L00000PHA1f&#39;,  IF($Setup.Financial_Summary_Report__c.BusinessUnit__c = &#39;Rhino&#39;, &#39;a0x0L00000PEZq2&#39;, &#39;a0x0L00000PEZq7&#39;) ) &amp; &quot;&amp;DS7=3&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Financial Summary Report Print 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Financial_Summary_Report_Print__c.field-meta.xml
<CustomField>
    <fullName>Conga_Financial_Summary_Report_Print__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&quot;
&amp;&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_370
&amp;&quot;&amp;Id=&quot;&amp;Id

&amp;&quot;&amp;QueryId=[reportByProvince]&quot; &amp; IF($Setup.Financial_Summary_Report__c.BusinessUnit__c = &#39;Rhino&#39;,&#39;a0p0L00000JaYzo&#39;,  IF($Setup.Financial_Summary_Report__c.BusinessUnit__c = &#39;ELFI&#39;, &#39;a0p0L00000IzuRt&#39;, &#39;a0p0L00000IzuRy&#39;)) 
 
&amp; &quot;%3Fpv0%3D&quot; &amp; Conga_Financial_Summary_Rpt_Start_Date__c &amp; &quot;~pv1%3D&quot; &amp; Conga_Financial_Summary_Rpt_End_Date__c 

&amp; &quot;,[fAggrElfi]a0p0L00000JaYzt%3Fpv0%3D&quot; &amp; Conga_Financial_Summary_Rpt_Start_Date__c &amp; &quot;~pv1%3D&quot; &amp; Conga_Financial_Summary_Rpt_End_Date__c 

&amp; &quot;,[fAggrRhino]a0p0L00000IzuS3%3Fpv0%3D&quot; &amp; Conga_Financial_Summary_Rpt_Start_Date__c &amp; &quot;~pv1%3D&quot; &amp; Conga_Financial_Summary_Rpt_End_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Financial Summary Report Print</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Temp_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Temp_Payout_Date__c</fullName>
    <inlineHelpText>Used to calculate outstanding balance and date as of a scratch date.  This field should not be updated directly on the Drawdown, instead update from Opportunity and let it replicate down.  Used for Payment Allocation and Reporting From/To amount calc.</inlineHelpText>
    <label>Temp Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Summary_Report__c/Financial_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to store filter dates on financial summary report.</description>
    <label>Financial Summary Report</label>
</CustomObject>

force-app/main/default/objects/Financial_Summary_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <description>Date when batch job is run to calculate accrued interest on financial summary custom report.</description>
    <label>Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Financial_Summary_Report__c/fields/Since_Inception__c.field-meta.xml
<CustomField>
    <fullName>Since_Inception__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Since Inception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Payment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Provinces.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Ontario</fullName>
    </customValue>
    <customValue>
        <fullName>Manitoba</fullName>
    </customValue>
    <customValue>
        <fullName>New Brunswick</fullName>
    </customValue>
    <customValue>
        <fullName>Newfoundland &amp; Labrador</fullName>
    </customValue>
    <customValue>
        <fullName>Northwest Territories</fullName>
    </customValue>
    <customValue>
        <fullName>Nova Scotia</fullName>
    </customValue>
    <customValue>
        <fullName>Nunavut</fullName>
    </customValue>
    <customValue>
        <fullName>Prince Edward Island</fullName>
    </customValue>
    <customValue>
        <fullName>Quebec</fullName>
    </customValue>
    <customValue>
        <fullName>Saskatchewan</fullName>
    </customValue>
    <customValue>
        <fullName>Yukon Territory</fullName>
    </customValue>
    <masterLabel>Provinces</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FinancialSummaryReportCtrl.cls
public with sharing class FinancialSummaryReportCtrl {
     @AuraEnabled
    public static void saveDateCustomSettings(String startDate, String endDate){
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            Financial_Summary_Report__c fsr = Financial_Summary_Report__c.getOrgDefaults();
            
            fsr.End_date__c = endDt;
            fsr.Start_Date__c = startDt;
            
            update fsr;
            
            
            
        }catch(Exception ex){
            
            throw new AuraHandledException(ex.getMessage());
        }
        
        
    }
    @AuraEnabled
    public static list<Wrapper> getReportDataByProvince(String startDate, String endDate, string BusinessUnit){
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            string filterByBusinessUnit = '';
            string Rhino = 'Rhino';
            string Elfi = 'ELFI';
            
            // Business Unit Filter

            if(BusinessUnit == 'ELFI'){
                
                filterByBusinessUnit = 'ELFI';
            }else if(BusinessUnit == 'Rhino'){
                
                filterByBusinessUnit = 'Rhino';
            }else if(BusinessUnit == 'Consolidated'){
                
                filterByBusinessUnit = 'Consolidated';
            }
            
            String strQuery = '';
            
            string cheque = 'Cheque';
            string eTransfer = 'e-Transfer';
            string adminFee = 'Admin Fee';
            string otherFee = 'Other Fee';
            string activePartialPayment = 'Active - Partial Payment';
        	String closedWithLoan = 'Closed With Loan';
        	String statusActive = 'Active';
            
            strQuery = 'Select Opportunity__r.Account.Business_Unit__c businessunit, Opportunity__r.Account.ProvinceResidency__c province,'; 
            strQuery += ' COUNT_DISTINCT(Opportunity__r.AccountId) file, COUNT_DISTINCT(Opportunity__c) opptyCount,';
            strQuery += ' SUM(Amount__c) amt';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt';
            strQuery += ' AND Opportunity__r.StageName =:closedWithLoan';
            strQuery += ' AND (Opportunity__r.Stage_Status__c =:statusActive OR Opportunity__r.Stage_Status__c =:activePartialPayment)';
            strQuery += ' AND (Payment_Method__c =:cheque or Payment_Method__c =:eTransfer)'; 
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += (filterByBusinessUnit == 'Consolidated') ?
                ' AND (Opportunity__r.Account.Business_Unit__c =:Elfi OR Opportunity__r.Account.Business_Unit__c =:Rhino)':
            ' AND Opportunity__r.Account.Business_Unit__c =:filterByBusinessUnit';
            //strQuery += ' (Reference_Notes__c !=:adminFee and Reference_Notes__c !=:otherFee)';
            strQuery += ' Group by Opportunity__r.Account.ProvinceResidency__c, Opportunity__r.Account.Business_Unit__c';
            
            List<AggregateResult> aggResult = Database.query(strQuery);
            
            list<Wrapper> finalWrapper = new List<Wrapper>();
            if(!aggResult.isEmpty()){
                
                map<string, wrapper> agrMap = new map<string, wrapper>();
                
                for(AggregateResult agr : aggResult){
                    
                    if(agrMap.containsKey(String.ValueOf(agr.get('province')))){
                       // if province exists 
                       wrapper w = agrMap.get(String.ValueOf(agr.get('province')));
                        
                        if(String.valueof(agr.get('businessunit')) == 'Rhino'){
                            
                            w.rhinoFileCount = Integer.valueof(agr.get('file'));
                            w.rhinoOpptyCount = Integer.valueof(agr.get('opptyCount'));
                            w.rhinoAmount = Double.valueof(agr.get('amt'));
                        }else if(String.valueof(agr.get('businessunit')) == 'ELFI'){
                            
                            w.elfiFileCount = Integer.valueof(agr.get('file'));
                            w.elfiOpptyCount = Integer.valueof(agr.get('opptyCount'));
                            w.elfiAmount = Double.valueof(agr.get('amt'));
                        }
                        
                        agrMap.put(String.ValueOf(agr.get('province')), w);
                        
                    }else{
                        // new province
                        wrapper w;
                        if(String.valueof(agr.get('businessunit')) == 'Rhino'){
                            
                            w = new wrapper(String.ValueOf(agr.get('province')),
                                            Integer.valueof(agr.get('file')),
                                            Integer.valueof(agr.get('opptyCount')),
                                                   Double.valueof(agr.get('amt')),0,0, 0.00);
                            
                        }else if(String.valueof(agr.get('businessunit')) == 'ELFI'){
                            
                            w = new wrapper(String.ValueOf(agr.get('province')),0,0,0.00,
                                            Integer.valueof(agr.get('file')),
                                            Integer.valueof(agr.get('opptyCount')),
                                                   Double.valueof(agr.get('amt')));
                        }
                        agrMap.put(String.ValueOf(agr.get('province')), w);
                    }
                }
                finalWrapper = new list<Wrapper>(agrMap.values());
                return finalWrapper;                
            }
            return finalWrapper;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        
    }
    
    @AuraEnabled
    public static Boolean validateReport(String startDate, String endDate){
        String strQuery = '';
        String closedWithLoan = 'Closed With Loan';
        String active = '';
        String activePartialPayment = 'Active - Partial Payment';
        List<Drawdown__c> dList = new List<Drawdown__c>();
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            strQuery = 'Select Id'; 
            strQuery += ' FROM Drawdown__c';
            strQuery += ' WHERE (temp_payout_date__c != :endDt)';
            strQuery += ' AND Opportunity__r.StageName =:closedWithLoan'; 
            strQuery += ' AND (Opportunity__r.Stage_Status__c =:active OR Opportunity__r.Stage_Status__c =:activePartialPayment)';
            strQuery += ' AND Is_Rejected__c = false AND Reference_Notes__c != \'Payment Rejected\'';
            dList = Database.query(strQuery);
            if(!dList.isEmpty()){
                return false;
            }
            
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        return true;
    }
    
    @AuraEnabled 
    public static void abortBatchJobs(){
        for(AsyncApexJob aJob : [SELECT id FROM AsyncApexJob WHERE Status!='Aborted' AND Status!='Completed'
                                 AND ApexClass.Name = 'FinancialReportCalculateData'] ){                                     
                                     System.AbortJob(aJob.Id);                                     
                                 }
    }
    
    @AuraEnabled 
    public static Id executeBatchJob(Boolean sinceInception, String startDate, String endDate){
        try{
            abortBatchJobs();
            Financial_Summary_Report__c fSR_CustomSetting = Financial_Summary_Report__c.getOrgDefaults();
            fSR_CustomSetting.Start_Date__c = !String.isEmpty(startDate) && startDate != null? Date.valueOf(startDate) : fSR_CustomSetting.Start_Date__c;
            fSR_CustomSetting.End_Date__c = !String.isEmpty(endDate) && endDate != null? Date.valueOf(endDate) : fSR_CustomSetting.End_Date__c;
            fSR_CustomSetting.Report_Date__c = Date.today();
            fSR_CustomSetting.Since_Inception__c = sinceInception;
            upsert fSR_CustomSetting;
            return Database.executeBatch(new FinancialReportCalculateData(Date.valueOf(startDate),
                                                                          Date.valueOf(endDate), sinceInception));
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static FinancialReportDataWrapper getFinancialReportData(String startDate, String endDate, String BusinessUnit){
        
        FinancialReportDataWrapper fReportDataW = new FinancialReportDataWrapper();
        String strQuery = '';
        string cheque = 'Cheque';
        string eTransfer = 'e-Transfer';
        string adminFee = 'Admin Fee';
        string otherFee = 'Other Fee';
        string payment = 'Payment';
        string activePartialPayment = 'Active - Partial Payment';
        String partialPayment = 'Partial Payment';
        String closedWithLoan = 'Closed With Loan';
        String active = 'Active';
        
        BusinessUnit = (!String.isEmpty(BusinessUnit) && BusinessUnit != null)? BusinessUnit : 'ELFI';
        
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            strQuery = 'Select COUNT_DISTINCT(Opportunity__r.AccountId) noOfFiles, COUNT_DISTINCT(Opportunity__c) noOfOppties,'; 
            strQuery += ' SUM(Amount__c) amt,';
            strQuery += ' SUM(Accrued_Interest_In_Reporting_Period__c) accruedInterest,';
            strQuery += ' SUM(Admin_Fee__c) adminFee';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += ' AND Opportunity__r.StageName =:closedWithLoan';
            strQuery += ' AND (Opportunity__r.Stage_Status__c =:active OR Opportunity__r.Stage_Status__c =:activePartialPayment)';
            strQuery += ' AND (Payment_Method__c =:cheque or Payment_Method__c =:eTransfer)'; 
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += ' AND (Opportunity__r.Account.Business_Unit__c =:BusinessUnit)'; 
            
            //strQuery += ' AND (Reference_Notes__c !=:adminFee and Reference_Notes__c !=:otherFee)';			
            AggregateResult aggResult = Database.query(strQuery); 
            
            if(aggResult != null){
                fReportDataW.noOfFiles = aggResult.get('noOfFiles') != null? (Integer)aggResult.get('noOfFiles') : 0;
                fReportDataW.amountOfAdvances = aggResult.get('amt') != null? (Decimal)aggResult.get('amt') : 0.0;
                //fReportDataW.accruedInterest = aggResult.get('accruedInterest') !=null? (Decimal)aggResult.get('accruedInterest') : 0.0;
                fReportDataW.adminFee = aggResult.get('adminFee') != null? (Decimal)aggResult.get('adminFee') : 0.0;                
            }            
            strQuery = 'SELECT SUM(Amount__c) amount';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt';
            strQuery += ' AND Opportunity__r.StageName =:closedWithLoan';
            strQuery += ' AND (Opportunity__r.Stage_Status__c =:active OR Opportunity__r.Stage_Status__c =:activePartialPayment)';
            strQuery += ' AND (Payment_Method__c =:payment AND Reference_Notes__c =:partialPayment)'; 
            strQuery += ' AND Is_Rejected__c = false AND Reference_Notes__c != \'Payment Rejected\'';
            strQuery += ' AND (Opportunity__r.Account.Business_Unit__c =:BusinessUnit)';            
            
            aggResult = Database.query(strQuery); 
            system.debug(aggResult);
            if(aggResult != null){
                fReportDataW.partialPayment = aggResult.get('amount') != null? (Decimal)aggResult.get('amount') : 0.0;
            }            
            
            strQuery = 'SELECT SUM(Accrued_Interest_In_Reporting_Period__c) accruedInterest';
            strQuery += ' FROM Drawdown__c'; 
            strQuery += ' WHERE Opportunity__r.StageName =:closedWithLoan';
            strQuery += ' AND (Opportunity__r.Stage_Status__c =:active OR Opportunity__r.Stage_Status__c =:activePartialPayment)'; 
            strQuery += ' AND Is_Rejected__c = false AND Reference_Notes__c != \'Payment Rejected\'';
            strQuery += ' AND (Opportunity__r.Account.Business_Unit__c =:BusinessUnit)';
            
            aggResult = Database.query(strQuery);
            if(aggResult != null){
                fReportDataW.accruedInterest = aggResult.get('accruedInterest') != null? (Decimal)aggResult.get('accruedInterest') : 0.0;
            }
            
            fReportDataW.total = fReportDataW.amountOfAdvances;
            fReportDataW.total += fReportDataW.accruedInterest;
            fReportDataW.total += fReportDataW.adminFee;            
            fReportDataW.total -= fReportDataW.partialPayment;
            
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        List<Drawdown__c> congaUrlHolder = [Select Conga_Financial_Summary_Report_Print__c, Conga_Financial_Summary_Report_Print_2__c,Conga_Financial_Summary_Report_View_All__c 
                                            from Drawdown__c limit 1];
        fReportDataW.congaViewAllURL = congaUrlHolder.isEmpty() ? '' : congaUrlHolder[0].Conga_Financial_Summary_Report_View_All__c;
        fReportDataW.congaPrintReportURL = congaUrlHolder.isEmpty() ? '' : congaUrlHolder[0].Conga_Financial_Summary_Report_Print__c + congaUrlHolder[0].Conga_Financial_Summary_Report_Print_2__c;
        return fReportDataW;        
    }
    
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    
    @AuraEnabled
    public static void saveBusinessUnitCustomSettings(String BusinessUnit){
        try{
            
           // Bad_Debt_Summary_Report__c bdr = Bad_Debt_Summary_Report__c.getInstance(UserInfo.getUserId());
            Financial_Summary_Report__c fsr = Financial_Summary_Report__c.getOrgDefaults();
            
            fsr.BusinessUnit__C = BusinessUnit;
            
            upsert fsr;

        }catch(Exception ex){
            
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static AsyncApexJob getBatchJobStatus(){
        List<AsyncApexJob> aaj = null;
        try{
            aaj = [SELECT Id, ApexClassId, Status, NumberOfErrors, TotalJobItems, JobItemsProcessed, createdDate FROM AsyncApexJob
                   WHERE ApexClass.Name = 'FinancialReportCalculateData' order by CreatedDate DESC LIMIT 1];
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }        
        return (aaj.size() > 0 )? aaj[0] : null;
    }
    
    @AuraEnabled
    public static Financial_Summary_Report__c getCustomSetting(){
        Financial_Summary_Report__c fSR_CustomSetting = Financial_Summary_Report__c.getOrgDefaults();
        return fSR_CustomSetting;
    }
    
    public class Wrapper {
        @AuraEnabled
        string province {get; set;}
        @AuraEnabled
        integer rhinoFileCount {get; set;}
        @AuraEnabled
        integer rhinoOpptyCount {get; set;}
        @AuraEnabled
        decimal rhinoAmount {get; set;}
        @AuraEnabled
        integer elfiFileCount {get; set;}
        @AuraEnabled
        integer elfiOpptyCount {get; set;}
        @AuraEnabled
        decimal elfiAmount {get; set;}
        
        wrapper(string p, integer rc, integer roc, decimal ra, integer ec, integer eoc, decimal ea){
            
            province = p;
            
            rhinoFileCount = rc;
            rhinoOpptyCount = roc;
            rhinoAmount = ra;
            
            elfiFileCount = ec;
            elfiOpptyCount = eoc;
            elfiAmount = ea;
        }
        
    }
    
    /******************* Wrapper Class for Financial Report Data *********************/
    public Class FinancialReportDataWrapper {
        
        @AuraEnabled
        public Integer noOfFiles{get;set;}
        @AuraEnabled
        public Decimal amountOfAdvances{get;set;}
        @AuraEnabled
        public Decimal adminFee{get;set;}
        @AuraEnabled
        public Decimal accruedInterest{get;set;}
        @AuraEnabled
        public Decimal partialPayment{get;set;}
        @AuraEnabled
        public Decimal total{get;set;}
        @AuraEnabled
        public String congaViewAllURL{get;set;}
        @AuraEnabled
        public String congaPrintReportURL{get;set;}
        
        public FinancialReportDataWrapper(){
            noOfFiles = 0;
            amountOfAdvances = 0.0;
            adminFee = 0.0;
            accruedInterest = 0.0;
            partialPayment = 0.0;
        }
    }    
}