force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Actual_Sales_by_Month_Report__c/Actual_Sales_by_Month_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Actual Sales by Month Report</label>
</CustomObject>

force-app/main/default/objects/Actual_Sales_by_Month_Report__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Created_Month__c.field-meta.xml
<CustomField>
    <fullName>Created_Month__c</fullName>
    <formula>Text(YEAR( ( Date__c ))) + &#39; - &#39; + ( IF( MONTH( ( Date__c ) ) &lt; 10, &#39;0&#39;, &#39;&#39;)) + TEXT( MONTH( ( Date__c ) ) ) + &#39; (&#39;+ 
CASE( MONTH( ( Date__c ) ) , 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
&quot;December&quot;)+&#39;)&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Conga_Actual_Sale_By_Month_Rpt_View_All__c.field-meta.xml
<CustomField>
    <fullName>Conga_Actual_Sale_By_Month_Rpt_View_All__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&quot;&amp;
&quot;&amp;serverUrl=API.Partner_Server_URL_370&quot;&amp;
&quot;&amp;Id=&quot;&amp; Id &amp;

&quot;&amp;QueryId=&quot;&amp;
&quot;[AllLeads]a0p19000002P2Vb%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; $Setup.Actual_Sales_by_Month_Report__c.Business_Unit__c &amp;
&quot;~pv1%3D&quot;&amp; Act_Sale_by_Month_Report_Start_Date__c &amp;
&quot;~pv2%3D&quot;&amp; Act_Sale_by_Month_Report_End_Date__c &amp;

&quot;,[ConvertedLeads]a0p19000002P2Vg%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; $Setup.Actual_Sales_by_Month_Report__c.Business_Unit__c &amp;
&quot;~pv1%3D&quot;&amp; Act_Sale_by_Month_Report_Start_Date__c &amp;
&quot;~pv2%3D&quot;&amp; Act_Sale_by_Month_Report_End_Date__c &amp;

&quot;,[drawdowns]a0p19000002P2Vv%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; $Setup.Actual_Sales_by_Month_Report__c.Business_Unit__c &amp;
&quot;~pv1%3D&quot;&amp; Act_Sale_by_Month_Report_Start_Date__c &amp;
&quot;~pv2%3D&quot;&amp; Act_Sale_by_Month_Report_End_Date__c &amp;

&quot;&amp;TemplateId=a0x190000013s3P,a0x190000013tTl,a0x190000013tTq&quot;&amp;

&quot;&amp;OFN={Template.Label}&quot;&amp;
&quot;&amp;APDF=1&amp;DS7=3&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Actual Sale By Month Rpt View All</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Created_Month__c.field-meta.xml
<CustomField>
    <fullName>Created_Month__c</fullName>
    <formula>Text(YEAR( DATEVALUE( CreatedDate  ))) + &#39; - &#39; + ( IF( MONTH( DATEVALUE( CreatedDate ) ) &lt; 10, &#39;0&#39;, &#39;&#39;)) + TEXT( MONTH( DATEVALUE( CreatedDate ) ) ) + &#39; (&#39;+
CASE( MONTH( DATEVALUE( CreatedDate ) ) , 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
&quot;December&quot;)+&#39;)&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Created_Month__c.field-meta.xml
<CustomField>
    <fullName>Created_Month__c</fullName>
    <formula>Text(YEAR( DATEVALUE( CreatedDate  ))) + &#39; - &#39; + ( IF( MONTH( DATEVALUE( CreatedDate ) ) &lt; 10, &#39;0&#39;, &#39;&#39;)) + TEXT( MONTH( DATEVALUE( CreatedDate ) ) ) + &#39; (&#39;+
CASE( MONTH( DATEVALUE( CreatedDate ) ) , 
1, &quot;January&quot;, 
2, &quot;February&quot;, 
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;, 
7, &quot;July&quot;, 
8, &quot;August&quot;, 
9, &quot;September&quot;, 
10, &quot;October&quot;, 
11, &quot;November&quot;, 
&quot;December&quot;)+&#39;)&#39;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Created Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Payment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadsPerMonthReportCtlr.cls
public with sharing class LeadsPerMonthReportCtlr {
    @AuraEnabled
    public static Lead getSampleLead()
    {
        return [Select id, Conga_Actual_Sale_By_Month_Rpt_View_All__c from Lead limit 1];
    }
    @AuraEnabled
    public static Actual_Sales_by_Month_Report__c getCustomSetting(){
        Actual_Sales_by_Month_Report__c LFSR = Actual_Sales_by_Month_Report__c.getOrgDefaults();
        return LFSR;
    }    
    @AuraEnabled
    public static void saveCustomSettings(String startDate, String endDate, String businessUnit){
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            Actual_Sales_by_Month_Report__c psr = Actual_Sales_by_Month_Report__c.getOrgDefaults();
            
            psr.End_date__c = endDt;
            psr.Start_Date__c = startDt;
            psr.Business_Unit__c = businessUnit;
            
            upsert psr; 
        }catch(Exception ex){
            
            throw new AuraHandledException(ex.getMessage());
        }
    }
    @AuraEnabled
    public static List<wrapperClass> getLeadsByMonth(String startDate, String endDate, String businessUnit) {
        
        Date startDt = Date.valueOf(startDate);
        Date endDt = Date.valueOf(endDate);
        
        List<wrapperClass> result = new List<wrapperClass>();
        Set<String> months = new Set<String>();
        
        List<Lead> leads = Database.query(
            ' SELECT Created_Month__c, IsConverted, Id, Business_Unit__c FROM Lead Where Business_Unit__c LIKE \'%'+(businessUnit == 'Consolidated' ? '' : businessUnit)+'%\''+
            ' AND CreatedDate >= :startDt and CreatedDate<= :endDt '
        );        
        Map<String, List<Lead>> leadsByMonth = new Map<String, List<Lead>>();
        Map<String, List<Lead>> convertedLeadsByMonth = new Map<String, List<Lead>>();
        for(lead ld : leads){
            months.add(ld.Created_Month__c);
            String key = ld.Created_Month__c + '-' + ld.Business_Unit__c;
            if(ld.IsConverted){
                if(!convertedLeadsByMonth.containsKey(key)){
                    convertedLeadsByMonth.put(key, new List<Lead>());
                }
                convertedLeadsByMonth.get(key).add(ld);
            }else{
                if(!leadsByMonth.containsKey(key)){
                    leadsByMonth.put(key, new List<Lead>());
                }
                leadsByMonth.get(key).add(ld);
            }
        }
        
        List<Drawdown__c> drawdowns = Database.query(
            'SELECT Created_Month__c, Amount__c, Opportunity__r.Account.Business_Unit__c FROM Drawdown__c WHERE ' +
            '( Payment_Method__c = \'Cheque\' OR Payment_Method__c =\'e-Transfer\' OR '+
            'Payment_Method__c = \'Admin Fee\' OR Reference_Notes__c = \'Admin Fee\' OR Reference_Notes__c = \'Assessment Fee\') '+
            ' AND Is_Rejected__c = false' +
            ' AND Opportunity__r.Account.Business_Unit__c LIKE \'%'+(businessUnit == 'Consolidated' ? '' : businessUnit)+'%\' '+
            ' AND Date__c >= :startDt and Date__c<= :endDt and Opportunity__r.StageName = \'Closed with Loan\' '
        );        
        
        Map<String, List<Drawdown__c>> drawdownsByMonth = new Map<String, List<Drawdown__c>>();        
        for(Drawdown__c dd : drawdowns){
            String key = dd.Created_Month__c + '-' + dd.Opportunity__r.Account.Business_Unit__c;
            if(!drawdownsByMonth.containsKey(key)){
                drawdownsByMonth.put(key, new List<Drawdown__c>());
            }
            months.add(dd.Created_Month__c);
            drawdownsByMonth.get(key).add(dd);
        }
        
        //sorting months in asc order
        List<String> sortedMonths = new List<String>(months);
        sortedMonths.sort();
        
        wrapperClass wrr;
        //loop on months in des order
        for(Integer i = sortedMonths.size() - 1; i >= 0; i--){
            String rhinokey = sortedMonths[i]+'-Rhino';
            String elfikey = sortedMonths[i]+'-ELFI';
            wrr = new wrapperClass();
            wrr.CreatedDate = sortedMonths[i];
            if(drawdownsByMonth.containsKey(rhinokey)){
                wrr.SumofAmountPaidtoClientRhino = calculateSumOfAmount(drawdownsByMonth.get(rhinokey));
            }
            if(drawdownsByMonth.containsKey(elfikey)){
                wrr.SumofAmountPaidtoClientELFI = calculateSumOfAmount(drawdownsByMonth.get(elfikey));
            }
            
            if(convertedLeadsByMonth.containsKey(rhinokey)){
                wrr.SumofConvertedLeadsRhino = convertedLeadsByMonth.get(rhinokey).size();
            }
            if(convertedLeadsByMonth.containsKey(elfikey)){
                wrr.SumofConvertedLeadsELFI = convertedLeadsByMonth.get(elfikey).size();
            }
            wrr.RecordCountRhino = wrr.SumofConvertedLeadsRhino + (leadsByMonth.containsKey(rhinokey) ? leadsByMonth.get(rhinokey).size() :  0);
            wrr.RecordCountELFI = wrr.SumofConvertedLeadsELFI + (leadsByMonth.containsKey(elfikey) ? leadsByMonth.get(elfikey).size() :  0);
            result.add(wrr);
        }
        
        return result;
    }
    
    
    public static Decimal calculateSumOfAmount(List<Drawdown__c> ddList){
        Decimal totalAmount = 0.00;
        if(!ddList.isEmpty()){
            for(Drawdown__c dd : ddList){
                
                totalAmount += dd.Amount__c != null ? dd.Amount__c : 0.00;
            }
        }
        return totalAmount;
    }
    
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    
    public class wrapperClass{
        @AuraEnabled
        public String CreatedDate{get;set;}
        @AuraEnabled
        public String businessUnit{get;set;}
        @AuraEnabled
        public Decimal SumofAmountPaidtoClientRhino{get;set;}
        @AuraEnabled
        public Decimal SumofAmountPaidtoClientELFI{get;set;}
        @AuraEnabled
        public Integer SumofConvertedLeadsRhino{get;set;}
        @AuraEnabled
        public Integer SumofConvertedLeadsELFI{get;set;}
        @AuraEnabled
        public Integer RecordCountRhino{get;set;}
        @AuraEnabled
        public Integer RecordCountELFI{get;set;}
        
        public wrapperClass(){
            CreatedDate = '';
            SumofAmountPaidtoClientRhino = 0.00;
            SumofConvertedLeadsRhino = 0;
            RecordCountRhino = 0;
            
            SumofAmountPaidtoClientELFI = 0.00;
            SumofConvertedLeadsELFI = 0;
            RecordCountELFI = 0;
        }
    }
}