force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Name_Formula__c</fullName>
    <formula>IF(CONTAINS( TRIM(Name)   , &#39;- Account # &#39;),  SUBSTITUTE(Name, &#39;- Account # &#39;, &#39;- 0000&#39;),  IF(CONTAINS( TRIM(Name)   , &#39;-Account # &#39;), SUBSTITUTE(Name, &#39;-Account # &#39;, &#39;- 0000&#39;), IF(CONTAINS( TRIM(Name)   , &#39;- Account #&#39;), SUBSTITUTE(Name, &#39;- Account #&#39;, &#39;- 0000&#39;),  IF(CONTAINS( TRIM(Name)   , &#39;-Account #&#39;), SUBSTITUTE(Name, &#39;-Account #&#39;, &#39;- 0000&#39;), TRIM(Name)) ) ) )</formula>
    <label>Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Selected_for_Assessment_Payout__c.field-meta.xml
<CustomField>
    <fullName>Selected_for_Assessment_Payout__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selected for Assessment Payout</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Total_Outstanding__c</fullName>
    <formula>All_Payout_Balance__c - Total_Rebate_Discount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Rebate_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Rebate_Discount__c</fullName>
    <label>Total Rebate Discount</label>
    <summarizedField>Opportunity.Rebate_to_Lawyer__c</summarizedField>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Assessment_Summary_Report__c/Assessment_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Assessment Summary Report</label>
</CustomObject>

force-app/main/default/objects/Assessment_Summary_Report__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Name_Formula__c</fullName>
    <description>contacts having middle name cannot be queried using name like&#39;%Patricia Jean Shroeder%&#39; This field is desgned to be used in where clause of contact query in custom lookup LEX component.</description>
    <formula>IF( ISBLANK( TEXT(Salutation )), &#39;&#39; , TEXT(Salutation ) &amp; &#39; &#39; )&amp;
IF( ISBLANK( FirstName ), &#39;&#39; , FirstName &amp; &#39; &#39; )&amp;
IF( ISBLANK( MiddleName ), &#39;&#39; , MiddleName &amp; &#39; &#39; )&amp;
IF( ISBLANK( LastName ), &#39;&#39; , LastName )</formula>
    <label>Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Payout_Date_Lawyer_Summary_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Conga_Formula_Amount__c.field-meta.xml
<CustomField>
    <fullName>Conga_Formula_Amount__c</fullName>
    <formula>IF( ISPICKVAL(Payment_Method__c, &#39;Payment&#39;) , 
IF( OR(ISPICKVAL(Reference_Notes__c, &#39;Payment Surplus&#39;), ISPICKVAL(Reference_Notes__c, &#39;Payment Shortfall&#39;), ISPICKVAL(Reference_Notes__c, &#39;Bad Debt&#39;)), Formula_Amount__c, 
(0 - Principal_Repaid__c)) 
, Formula_Amount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Formula Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Formula_Interest__c.field-meta.xml
<CustomField>
    <fullName>Conga_Formula_Interest__c</fullName>
    <formula>IF( ISPICKVAL(Payment_Method__c, &#39;Payment&#39;) , 
IF( OR(ISPICKVAL(Reference_Notes__c, &#39;Payment Surplus&#39;), ISPICKVAL(Reference_Notes__c, &#39;Payment Shortfall&#39;), ISPICKVAL(Reference_Notes__c, &#39;Bad Debt&#39;)), 0, 
(0 -  Interest_Repaid__c )) 
, Total_Accrued_Interest__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Formula Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Formula_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Conga_Formula_Outstanding__c</fullName>
    <formula>IF( ISPICKVAL(Payment_Method__c, &#39;Payment&#39;) , 0, Total_Outstanding_Balance__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Formula Outstanding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Formula_Per_Diem__c.field-meta.xml
<CustomField>
    <fullName>Conga_Formula_Per_Diem__c</fullName>
    <formula>IF( ISPICKVAL(Payment_Method__c, &#39;Payment&#39;) , 0, Total_Per_Diem__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Formula Per Diem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Name_Formula__c</fullName>
    <formula>Name</formula>
    <label>Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
    <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate_Formula__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate_Formula__c</fullName>
    <formula>IF( ISBLANK( Interest_Rate__c )  , &#39;&#39; , TEXT(Interest_Rate__c*100)&amp;&quot;%&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest Rate Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/GenerateConsolidatedAssessmentPayoutCtlr.cls
public with sharing class GenerateConsolidatedAssessmentPayoutCtlr {
    
    public String businessUnit{get; set;}
    private String lawyerId{get;set;} 
    public Date payoutDate{get;set;}
    public Date today{get;set;}
    public Contact lawyer{get;set;}
    List<PayoutWrapper> clientPayouts;
    
    public GenerateConsolidatedAssessmentPayoutCtlr(){
        string businessUnitParam = Apexpages.currentPage().getParameters().get('businessUnit');
        lawyerId = Apexpages.currentPage().getParameters().get('lawyerId');        
        this.businessUnit = businessUnitParam != null && !String.isEmpty(businessUnitParam)? businessUnitParam : 'ELFI';
        
        //lawyer and lawfirm info
        lawyer = [SELECT Id, Name, Account.Id, Account.Name 
                  FROM Contact 
                  WHERE Id =:lawyerId];
        
        Assessment_Summary_Report__c customSettings = Assessment_Summary_Report__c.getInstance(UserInfo.getUserId());        
        payoutDate = customSettings.Payout_Date__c;
        today = Date.today();
    }
    
    public List<PayoutWrapper> getPayOutData(){
        
        clientPayouts = new List<PayoutWrapper>();
        
        //get clients
        Map<Id, Account> clientAccounts = new Map<Id, Account>(
            [SELECT Id, Name, Name_Formula__c, BillingStreet, 
             BillingCity, BillingState, BillingPostalCode,
             Total_Outstanding__c, Total_Rebate_Discount__c
             FROM Account
             WHERE Selected_for_Assessment_Payout__c = true 
             AND Id In (SELECT AccountId FROM Opportunity WHERE Lawyer__c =:lawyerId 
                        AND isClosed = true AND isWon = true 
                        AND Stage_Status__c != 'Paid Off' 
                        AND Account.Business_Unit__c = 'ELFI' 
                        AND Type_of_Loan__c = 'Assessment')]
        );
        
        Map<Id, List<Drawdown__c>> accountToDrawdownMap = new Map<Id, List<Drawdown__c>>();
        for(Drawdown__c drawdown : [SELECT Id, date__c, Conga_Formula_Amount__c,
                                    Opportunity__r.Interest_Rate_Formula__c,
                                    Conga_Formula_Interest__c, Conga_Formula_Outstanding__c, 
                                    Conga_Formula_Per_Diem__c, Opportunity__r.Loan_Requests__c,
                                    Opportunity__r.AccountId
                                    FROM Drawdown__c
                                    WHERE reference_notes__c != 'Referral Fee'
                                    AND reference_notes__c != 'Admin Fee'
                                    AND reference_notes__c != 'Assessment Fee'
                                    AND Opportunity__r.AccountId IN :clientAccounts.keySet()
                                    ORDER BY Opportunity__r.Loan_Requests__c asc, Date__c asc]){
                                        if(!accountToDrawdownMap.containsKey(drawdown.Opportunity__r.AccountId))
                                            accountToDrawdownMap.put(drawdown.Opportunity__r.AccountId, new List<Drawdown__c>());
                                        accountToDrawdownMap.get(drawdown.Opportunity__r.AccountId).add(drawdown);
                                    }
        
        for(Id accId : clientAccounts.keySet()){
            
            if(accountToDrawdownMap.containsKey(accId)){
                
                Decimal tPrincipal = 0.0, 
                    tAccruedInterest = 0.0,
                    tOutstanding = 0.0, 
                    tPerDiem = 0.0;
                
                for(Drawdown__c drawdown :accountToDrawdownMap.get(accId)){
                    tPrincipal += drawdown.Conga_Formula_Amount__c;
                    tAccruedInterest += drawdown.Conga_Formula_Interest__c;
                    tOutstanding += drawdown.Conga_Formula_Outstanding__c;
                    tPerDiem += drawdown.Conga_Formula_Per_Diem__c;
                }
                
                clientPayouts.add(new PayoutWrapper(
                    clientAccounts.get(accId),
                    payoutDate,
                    accountToDrawdownMap.get(accId),
                    tPrincipal,
                    tAccruedInterest,
                    tOutstanding,
                    tPerDiem
                ));
            }
        }
        
        return clientPayouts;
        
    }
    
    public Integer getClientPayoutsSize(){
        return this.clientPayouts.size();
    }
    
    public class PayoutWrapper{
        
        public Account account{get;set;}
        public Date payoutDate{get;set;}
        public List<Drawdown__c> drawdowns{get;set;}
        public Decimal totalPrincipalBorrowed{get;set;}
        public Decimal totalAccruedInterest{get;set;}
        public Decimal totalOutstandingBalance{get;set;}
        public Decimal totalPerDiem{get;set;}
        
        PayoutWrapper(Account acc, Date pDate, List<Drawdown__c> dd, Decimal tPrincipal, Decimal tAccruedInterest, Decimal tOutstanding, Decimal tPerDiem){
            account = acc;
            payoutDate = pDate;
            drawdowns = dd;
            totalPrincipalBorrowed = tPrincipal;
            totalAccruedInterest = tAccruedInterest;
            totalOutstandingBalance = tOutstanding;
            totalPerDiem = tPerDiem;
        }
    }
}