force-app/main/default/objects/Account/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <description>Mapped from the Lead</description>
    <label>Business Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Business_Unit</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ProvinceResidency__c.field-meta.xml
<CustomField>
    <fullName>ProvinceResidency__c</fullName>
    <label>Province of Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Provinces</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Payment_Summary_Report_Print_All_2__c.field-meta.xml
<CustomField>
    <fullName>Conga_Payment_Summary_Report_Print_All_2__c</fullName>
    <formula>&quot;[payoutsps]a0p0L00000J8lTz%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;Rhino&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;&amp;



&quot;[otherpaymentsps]a0p0L00000J8lU1%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;Rhino&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;&amp;



&quot;[adminfeeps]a0p0L00000J8lUF%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;Rhino&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;</formula>
    <label>Conga Payment Summary Report Print All 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Payment_Summary_Report_Print_All_3__c.field-meta.xml
<CustomField>
    <fullName>Conga_Payment_Summary_Report_Print_All_3__c</fullName>
    <formula>&quot;[shortfallpaymentps]a0p0L00000J8lUA%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp;Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;Rhino&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;&amp;


&quot;[surpluspaymentsps]a0p0L00000J8lU5%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;Rhino&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;&amp;


&quot;[miscellaneousps]a0p0L00000J8lUE%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;Rhino&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;</formula>
    <label>Conga Payment Summary Report Print All 3</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Payment_Summary_Report_Print_All_4__c.field-meta.xml
<CustomField>
    <fullName>Conga_Payment_Summary_Report_Print_All_4__c</fullName>
    <formula>&quot;[outstandingpsELFI]a0p0L00000J8lU9%3F&quot;&amp; 
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp; 
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp; 
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;ELFI&#39;,&#39;xxx&#39;) &amp;&quot;,&quot;&amp; 


&quot;[principalpaidpsELFI]a0p0L00000J8lU0%3F&quot;&amp; 
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp; 
&quot;~pv1%3D&quot;&amp;Conga_Payment_Summary_Rpt_End_Date__c&amp; 
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;ELFI&#39;,&#39;xxx&#39;) &amp;&quot;,&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Payment Summary Report Print All 4</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Payment_Summary_Report_Print_All_5__c.field-meta.xml
<CustomField>
    <fullName>Conga_Payment_Summary_Report_Print_All_5__c</fullName>
    <formula>&quot;[payoutspsELFI]a0p0L00000J8lTz%3F&quot;&amp; 
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp; 
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp; 
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;ELFI&#39;,&#39;xxx&#39;) &amp;&quot;,&quot;&amp; 



&quot;[otherpaymentspsELFI]a0p0L00000J8lU1%3F&quot;&amp; 
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp; 
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp; 
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;ELFI&#39;,&#39;xxx&#39;) &amp;&quot;,&quot;&amp; 



&quot;[adminfeepsELFI]a0p0L00000J8lUF%3F&quot;&amp; 
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp; 
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp; 
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;ELFI&#39;,&#39;xxx&#39;) &amp;&quot;,&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Payment Summary Report Print All 5</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Payment_Summary_Report_Print_All_6__c.field-meta.xml
<CustomField>
    <fullName>Conga_Payment_Summary_Report_Print_All_6__c</fullName>
    <formula>&quot;[shortfallpmtpsELFI]a0p0L00000J8lUA%3F&quot;&amp; 
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp; 
&quot;~pv1%3D&quot;&amp;Conga_Payment_Summary_Rpt_End_Date__c&amp; 
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;ELFI&#39;,&#39;xxx&#39;) &amp;&quot;,&quot;&amp; 


&quot;[surpluspmtspsELFI]a0p0L00000J8lU5%3F&quot;&amp; 
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp; 
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp; 
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;ELFI&#39;,&#39;xxx&#39;) &amp;&quot;,&quot;&amp; 


&quot;[miscellaneouspsELFI]a0p0L00000J8lUE%3F&quot;&amp; 
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp; 
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp; 
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;ELFI&#39;,&#39;xxx&#39;) &amp; 

&quot;&amp;TemplateId=&quot;&amp;IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;a0x0L00000PEbn6&#39;,&#39;a0x0L00000PYJV7&#39;)&amp;
&quot;&amp;DS7=3&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conga Payment Summary Report Print All 6</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Conga_Payment_Summary_Report_Print_All__c.field-meta.xml
<CustomField>
    <fullName>Conga_Payment_Summary_Report_Print_All__c</fullName>
    <formula>&quot;/apex/APXTConga4__Conga_Composer?SolMgr=1&quot;&amp;
&quot;&amp;serverUrl=&quot;&amp;$Api.Partner_Server_URL_370&amp;
&quot;&amp;Id=&quot;&amp;Id&amp;
&quot;&amp;QueryId=&quot;&amp;

&quot;[byprovinceps]a0p0L00000J8lU4%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;&amp;


&quot;[outstandingps]a0p0L00000J8lU9%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp; Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;Rhino&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;&amp;


&quot;[principalpaidps]a0p0L00000J8lU0%3F&quot;&amp;
&quot;pv0%3D&quot;&amp; Conga_Payment_Summary_Rpt_Start_Date__c&amp;
&quot;~pv1%3D&quot;&amp;Conga_Payment_Summary_Rpt_End_Date__c&amp;
&quot;~pv2%3D&quot;&amp; IF($Setup.Payment_Summary_Report__c.Business_Unit__c == &#39;Consolidated&#39;,&#39;Rhino&#39;,$Setup.Payment_Summary_Report__c.Business_Unit__c) &amp;&quot;,&quot;</formula>
    <label>Conga Payment Summary Report Print All</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Outstanding_Days__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Days__c</fullName>
    <formula>(Payout_Date__c+1) - Date_of_advance__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Summary_Report__c/Payment_Summary_Report__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom setting to store filter dates on payment summary report.</description>
    <label>Payment Summary Report</label>
</CustomObject>

force-app/main/default/objects/Payment_Summary_Report__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Business_Unit.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ELFI</fullName>
    </customValue>
    <customValue>
        <fullName>Rhino</fullName>
    </customValue>
    <masterLabel>Business Unit</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Provinces.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Ontario</fullName>
    </customValue>
    <customValue>
        <fullName>Manitoba</fullName>
    </customValue>
    <customValue>
        <fullName>New Brunswick</fullName>
    </customValue>
    <customValue>
        <fullName>Newfoundland &amp; Labrador</fullName>
    </customValue>
    <customValue>
        <fullName>Northwest Territories</fullName>
    </customValue>
    <customValue>
        <fullName>Nova Scotia</fullName>
    </customValue>
    <customValue>
        <fullName>Nunavut</fullName>
    </customValue>
    <customValue>
        <fullName>Prince Edward Island</fullName>
    </customValue>
    <customValue>
        <fullName>Quebec</fullName>
    </customValue>
    <customValue>
        <fullName>Saskatchewan</fullName>
    </customValue>
    <customValue>
        <fullName>Yukon Territory</fullName>
    </customValue>
    <masterLabel>Provinces</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PaymentSummaryComponentCtlr.cls
public with sharing class PaymentSummaryComponentCtlr {
    public class wrapperClass{
        @AuraEnabled
        public String prov{get;set;}
        @AuraEnabled
        public String businessUnit{get;set;}
        @AuraEnabled
        public Decimal amountRhino{get;set;}
        @AuraEnabled
        public Decimal amountELFI{get;set;}
        @AuraEnabled
        public Integer numAccountsRhino{get;set;}
        @AuraEnabled
        public Integer numOpptiesRhino{get;set;}
        @AuraEnabled
        public Integer numAccountsELFI{get;set;}
        @AuraEnabled
        public Integer numOpptiesELFI{get;set;}
        
        public wrapperClass(){
            prov = '';
            businessUnit = '';
            amountRhino = 0;
            amountELFI = 0;
            
            numAccountsRhino = 0;
            numAccountsELFI = 0;
            
            numOpptiesRhino = 0;
            numOpptiesELFI = 0;
        }
    }
    @AuraEnabled
    public static wrapperClass[] getPaymentsGroupByProvince(String startDate, String endDate, String businessUnit){
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            String strQuery = '';            
            
            string payment = 'Payment';
            string ClosedWithLoan = 'Closed With Loan';
            String PartialPayment = 'Partial Payment';
            String LoanPayout = 'Loan Payout';
            
            strQuery = 'Select Opportunity__r.Account.ProvinceResidency__c prov, Opportunity__r.Account.Business_Unit__c bunit, COUNT_DISTINCT(Opportunity__r.AccountId) file,'; 
            strQuery += ' COUNT_DISTINCT(Opportunity__c) opptyCount, SUM(Amount__c) amt';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit'; 
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND Payment_Method__c =:payment';
            strQuery += ' AND (Reference_Notes__c =:PartialPayment OR Reference_Notes__c =:LoanPayout)';
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += ' Group by Opportunity__r.Account.ProvinceResidency__c, Opportunity__r.Account.Business_Unit__c ';
            strQuery += ' Order by SUM(Amount__c) desc NULLS LAST';
            
              

            List<AggregateResult> aggResult = Database.query(strQuery);
            if(!aggResult.isEmpty()){
                List<wrapperClass> result = new List<wrapperClass>();
                List<String> provs = new List<String>();
                Set<String> provSet = new Set<String>();
                Map<String, wrapperClass> resultMap = new Map<String, wrapperClass>();
                for(AggregateResult ar : aggResult)
                {
                    String prov = (String)ar.get('prov');
                    String bunit = (String)ar.get('bunit');
                    if(!provSet.contains(prov))
                    {
                        provSet.add(prov);
                        provs.add(prov);
                    }
                    
                    if(!resultMap.containsKey(prov))	resultMap.put(prov, new wrapperClass());
                    wrapperClass r = resultMap.get(prov);
                    r.prov = prov;
                    if(bunit == 'ELFI')		r.numAccountsELFI = (Integer)ar.get('file');
                    if(bunit == 'ELFI')		r.numOpptiesELFI = (Integer)ar.get('opptyCount');
                    if(bunit == 'ELFI')		r.amountELFI = (Double)ar.get('amt');
                    if(bunit == 'Rhino')		r.numAccountsRhino = (Integer)ar.get('file');
                    if(bunit == 'Rhino')		r.numOpptiesRhino = (Integer)ar.get('opptyCount');
                    if(bunit == 'Rhino')		r.amountRhino = (Double)ar.get('amt');
                }
                for(String p : provs)
                {
                    if(resultMap.containsKey(p))
                    {
                        result.add(resultMap.get(p));
                    }
                }
                return result;
            }
            return null;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static PartialPaymentsWrapper getPartialPayments(String startDate, String endDate, String businessUnit){
        PartialPaymentsWrapper partialPaymentsW = new PartialPaymentsWrapper();
        //List<AggregateResult> aggResult = new List<AggregateResult>();
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            String strQuery = ''; 
            
            // total payouts
            string payment = 'Payment';
            string ClosedWithLoan = 'Closed With Loan';
            String PartialPayment = 'Partial Payment';
            String LoanPayout = 'Loan Payout';
            
            strQuery = 'Select'; 
            strQuery += ' COUNT(Opportunity__c) payouts, Opportunity__r.Account.Business_Unit__c unit ';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit ';
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND Payment_Method__c =:payment';
            strQuery += ' AND (Reference_Notes__c =:PartialPayment OR Reference_Notes__c =:LoanPayout)';
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += ' group by Opportunity__r.Account.Business_Unit__c ';
            
            List<AggregateResult> aggResultPayouts = Database.query(strQuery); 
            
            // Average number of days outstanding
            strQuery = ''; 
            
            strQuery = 'Select'; 
            strQuery += ' AVG(Outstanding_Days__c) outstanding, Account.Business_Unit__c unit ';
            strQuery += ' FROM Opportunity WHERE id in ( Select Opportunity__c from Drawdown__c where Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit ';
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += ' AND Payment_Method__c =:payment';
            strQuery += ' AND (Reference_Notes__c =:PartialPayment OR Reference_Notes__c =:LoanPayout))';
            strQuery += ' group by Account.Business_Unit__c ';
            
            List<AggregateResult> aggResultOutstanding = Database.query(strQuery);
            
            // total principal paid
            strQuery = '';
            
            String Cheque = 'Cheque';
            String eTransfer = 'e-Transfer';
            
            strQuery = 'Select'; 
            strQuery += ' SUM(Amount__c) principalPaid, Opportunity__r.Account.Business_Unit__c unit ';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit ';
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND (Payment_Method__c =:eTransfer OR Payment_Method__c =:Cheque)';
            strQuery += ' group by Opportunity__r.Account.Business_Unit__c ';
            //strQuery += ' AND (Reference_Notes__c =:PartialPayment OR Reference_Notes__c =:LoanPayout)';
            
            List<AggregateResult> aggResultPrincipal = Database.query(strQuery);
            
            // total interest paid
               // yet to be decided, question marks added
            
			// total admin fee
            strQuery = '';
            
            String AdminFee = 'Admin Fee';
            
            strQuery = 'Select'; 
            strQuery += ' SUM(Amount__c) adminFee, Opportunity__r.Account.Business_Unit__c unit ';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit ';
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND (Payment_Method__c =:AdminFee)';
            strQuery += ' group by Opportunity__r.Account.Business_Unit__c ';
            //strQuery += ' AND (Reference_Notes__c =:PartialPayment OR Reference_Notes__c =:LoanPayout)';
            
            List<AggregateResult> aggResultAdminfee = Database.query(strQuery); 
            
            // total other changes
            strQuery = '';
            
            String Other = 'Other';
            
            strQuery = 'Select'; 
            strQuery += ' SUM(Amount__c) other, Opportunity__r.Account.Business_Unit__c unit ';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit ';
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND (Payment_Method__c =:Other)';
            strQuery += ' AND Is_Rejected__c = false AND Reference_Notes__c != \'Payment Rejected\'';
            strQuery += ' group by Opportunity__r.Account.Business_Unit__c ';
            // strQuery += ' AND (Reference_Notes__c =:PartialPayment OR Reference_Notes__c =:LoanPayout)';
            
            List<AggregateResult> aggResultOther = Database.query(strQuery); 
            
            // total shortfall paid
            strQuery = '';
            
            String Shortfall = 'Payment Shortfall';
            
            strQuery = 'Select'; 
            strQuery += ' SUM(Amount__c) shortfall, Opportunity__r.Account.Business_Unit__c unit ';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit ';
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND Reference_Notes__c =:Shortfall';
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += ' group by Opportunity__r.Account.Business_Unit__c ';
            
            List<AggregateResult> aggResultShortfall = Database.query(strQuery); 
            
            // total surplus paid
            strQuery = '';

            String Surplus = 'Payment Surplus';

            strQuery = 'Select'; 
            strQuery += ' SUM(Amount__c) surplus, Opportunity__r.Account.Business_Unit__c unit ';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit ';
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND Reference_Notes__c =:Surplus';
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += ' group by Opportunity__r.Account.Business_Unit__c ';
            
            List<AggregateResult> aggResultSurplus = Database.query(strQuery);
            
            // total misc paid
            strQuery = '';
            
            String Misc = 'Miscellaneous Payment';
            
            strQuery = 'Select'; 
            strQuery += ' SUM(Amount__c) misc, Opportunity__r.Account.Business_Unit__c unit ';
            strQuery += ' FROM Drawdown__c WHERE Date__c >= :startDt'; 
            strQuery += ' AND Date__c <= :endDt'; 
            strQuery += businessUnit == 'Consolidated' ? '' : ' AND Opportunity__r.Account.Business_Unit__c = :businessUnit ';
            strQuery += ' AND Opportunity__r.StageName =:ClosedWithLoan';
            strQuery += ' AND Reference_Notes__c =:Misc';
            strQuery += ' AND Is_Rejected__c = false';
            strQuery += ' group by Opportunity__r.Account.Business_Unit__c ';
            
            List<AggregateResult> aggResultMisc = Database.query(strQuery);

            if(!aggResultPayouts.isEmpty()){
                for(AggregateResult aggResult : aggResultPayouts)
                {
                    String unit = (string)aggResult.get('unit');
                    if(unit == 'ELFI')	partialPaymentsW.noOfPayoutsELFI = aggResult.get('payouts') != null? (Integer)aggResult.get('payouts') : 0;
                    if(unit == 'Rhino')	partialPaymentsW.noOfPayoutsRhino = aggResult.get('payouts') != null? (Integer)aggResult.get('payouts') : 0;
                }
                
            }
            
            if(!aggResultoutstanding.isEmpty()){
                for(AggregateResult aggResult : aggResultoutstanding)
                {
                    String unit = (string)aggResult.get('unit');
                    if(unit == 'ELFI')	partialPaymentsW.avgNoOfDaysOutstandingELFI = aggResult.get('outstanding') != null? (Decimal)aggResult.get('outstanding') : 0;
                    if(unit == 'Rhino')	partialPaymentsW.avgNoOfDaysOutstandingRhino = aggResult.get('outstanding') != null? (Decimal)aggResult.get('outstanding') : 0;
                }
                
            }
            if(!aggResultPrincipal.isEmpty()){
                for(AggregateResult aggResult : aggResultPrincipal)
                {
                    String unit = (string)aggResult.get('unit');
                    if(unit == 'ELFI')	partialPaymentsW.totalPrincipalPaidELFI = aggResult.get('principalPaid') != null? (Decimal)aggResult.get('principalPaid') : 0.00;
                    if(unit == 'Rhino')	partialPaymentsW.totalPrincipalPaidRhino = aggResult.get('principalPaid') != null? (Decimal)aggResult.get('principalPaid') : 0.00;
                }
                
            }
            if(!aggResultAdminfee.isEmpty()){
                for(AggregateResult aggResult : aggResultAdminfee)
                {
                    String unit = (string)aggResult.get('unit');
                    if(unit == 'ELFI')	partialPaymentsW.totalAdminFeePaidELFI = aggResult.get('adminFee') != null? (Decimal)aggResult.get('adminFee') : 0.00;
                    if(unit == 'Rhino')	partialPaymentsW.totalAdminFeePaidRhino = aggResult.get('adminFee') != null? (Decimal)aggResult.get('adminFee') : 0.00;
                }
                
            }
            if(!aggResultOther.isEmpty()){
                for(AggregateResult aggResult : aggResultOther)
                {
                    String unit = (string)aggResult.get('unit');
                    if(unit == 'ELFI')	partialPaymentsW.totalOtherELFI = aggResult.get('other') != null? (Decimal)aggResult.get('other') : 0.00;
                    if(unit == 'Rhino')	partialPaymentsW.totalOtherRhino = aggResult.get('other') != null? (Decimal)aggResult.get('other') : 0.00;
                }
                
            }
            if(!aggResultShortfall.isEmpty()){
                for(AggregateResult aggResult : aggResultShortfall)
                {
                    String unit = (string)aggResult.get('unit');
                    if(unit == 'ELFI')	partialPaymentsW.totalShortfallELFI = aggResult.get('shortfall') != null? (Decimal)aggResult.get('shortfall') : 0.00;
                    if(unit == 'Rhino')	partialPaymentsW.totalShortfallRhino = aggResult.get('shortfall') != null? (Decimal)aggResult.get('shortfall') : 0.00;
                }
                
            }
            if(!aggResultSurplus.isEmpty()){
                for(AggregateResult aggResult : aggResultSurplus)
                {
                    String unit = (string)aggResult.get('unit');
                    if(unit == 'ELFI')	partialPaymentsW.totalSurplusELFI = aggResult.get('surplus') != null? (Decimal)aggResult.get('surplus') : 0.00;
                    if(unit == 'Rhino')	partialPaymentsW.totalSurplusRhino = aggResult.get('surplus') != null? (Decimal)aggResult.get('surplus') : 0.00;
                }
                
            }
            if(!aggResultMisc.isEmpty()){
                for(AggregateResult aggResult : aggResultMisc)
                {
                    String unit = (string)aggResult.get('unit');
                    if(unit == 'ELFI')	partialPaymentsW.totalMiscELFI = aggResult.get('misc') != null? (Decimal)aggResult.get('misc') : 0.00;
                    if(unit == 'Rhino')	partialPaymentsW.totalMiscRhino = aggResult.get('misc') != null? (Decimal)aggResult.get('misc') : 0.00;
                }
                
            }
            partialPaymentsW.totalPaymentsELFI = partialPaymentsW.totalPrincipalPaidELFI + partialPaymentsW.totalAdminFeePaidELFI + 
                partialPaymentsW.totalOtherELFI;
            
            partialPaymentsW.totalPaymentsRhino = partialPaymentsW.totalPrincipalPaidRhino + partialPaymentsW.totalAdminFeePaidRhino + 
                partialPaymentsW.totalOtherRhino;
            
            //if(!aggResult.isEmpty()){
                
                
                // partialPaymentsW.totalInterestPaid = aggResult[3].get('interestPaid') != null? (Decimal)aggResult[3].get('interestPaid') : 0.00;
                
                
                
                
                
                //partialPaymentsW.totalPayments = partialPaymentsW.totalPrincipalPaid + partialPaymentsW.totalInterestPaid + 
                    //partialPaymentsW.totalAdminFeePaid + partialPaymentsW.totalOther;
                
                
            //}
            
            // get the conga url
            List<Drawdown__c> congaUrlHolder = [Select Conga_Payment_Summary_Report_Print_All__c,
                                                Conga_Payment_Summary_Report_Print_All_2__c,
                                                Conga_Payment_Summary_Report_Print_All_3__c,
                                                Conga_Payment_Summary_Report_Print_All_4__c,
                                                Conga_Payment_Summary_Report_Print_All_5__c,
                                                Conga_Payment_Summary_Report_Print_All_6__c,
                                                Conga_Payment_Summary_Report_View_All__c 
                                            from Drawdown__c limit 1];
        	partialPaymentsW.congaViewAllURL = congaUrlHolder.isEmpty() ? '' 
                : congaUrlHolder[0].Conga_Payment_Summary_Report_View_All__c;
        	partialPaymentsW.congaPrintReportURL = congaUrlHolder.isEmpty() ? '' 
                : congaUrlHolder[0].Conga_Payment_Summary_Report_Print_All__c + 
                    congaUrlHolder[0].Conga_Payment_Summary_Report_Print_All_2__c +
                    congaUrlHolder[0].Conga_Payment_Summary_Report_Print_All_3__c +
                    congaUrlHolder[0].Conga_Payment_Summary_Report_Print_All_4__c +
                    congaUrlHolder[0].Conga_Payment_Summary_Report_Print_All_5__c +
                    congaUrlHolder[0].Conga_Payment_Summary_Report_Print_All_6__c ;
            
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage()+e.getStackTraceString());
        }
        return partialPaymentsW;
    }
    @AuraEnabled
    public static List < String > getPickListValues(String objectType, String field)
    {
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }
    @AuraEnabled
    public static void saveDateCustomSettings(String startDate, String endDate, String businessUnit){
        try{
            Date startDt = Date.valueOf(startDate);
            Date endDt = Date.valueOf(endDate);
            
            Payment_Summary_Report__c psr = Payment_Summary_Report__c.getOrgDefaults();
            
            psr.End_date__c = endDt;
            psr.Start_Date__c = startDt;
            psr.Business_Unit__c = businessUnit;
            update psr;
            
            
            
        }catch(Exception ex){
            
            throw new AuraHandledException(ex.getMessage());
        }
        
        
    }
    
    @AuraEnabled
    public static Payment_Summary_Report__c getCustomSetting(){
        Payment_Summary_Report__c pSR = Payment_Summary_Report__c.getOrgDefaults();
        return pSR;
    }
    
    public class PartialPaymentsWrapper{
        
        @AuraEnabled
        public Integer noOfPayoutsRhino {get;set;}
        
        @AuraEnabled
        public Integer noOfPayoutsELFI {get;set;}
        
        @AuraEnabled
        public Decimal avgNoOfDaysOutstandingRhino {get;set;}
        
        @AuraEnabled
        public Decimal avgNoOfDaysOutstandingELFI {get;set;}
        
        @AuraEnabled
        public Decimal totalPrincipalPaidRhino {get;set;}
        
        @AuraEnabled
        public Decimal totalPrincipalPaidELFI {get;set;}
        
        @AuraEnabled
        public Decimal totalInterestPaidRhino {get;set;}
        
        @AuraEnabled
        public Decimal totalInterestPaidELFI {get;set;}
        
        @AuraEnabled
        public Decimal totalAdminFeePaidRhino {get;set;}
        
        @AuraEnabled
        public Decimal totalAdminFeePaidELFI {get;set;}
        
        @AuraEnabled
        public Decimal totalPaymentsRhino {get;set;}
        
        @AuraEnabled
        public Decimal totalPaymentsELFI {get;set;}
        
        @AuraEnabled
        public Decimal totalSurplusRhino {get;set;}
        
        @AuraEnabled
        public Decimal totalSurplusELFI {get;set;}
        
        @AuraEnabled
        public Decimal totalShortfallRhino {get;set;}
        
        @AuraEnabled
        public Decimal totalShortfallELFI {get;set;}
        
        @AuraEnabled
        public Decimal totalMiscRhino {get;set;}
        
        @AuraEnabled
        public Decimal totalMiscELFI {get;set;}
        
        @AuraEnabled
        public Decimal totalOtherRhino {get;set;}
        
        @AuraEnabled
        public Decimal totalOtherELFI {get;set;}
        
        @AuraEnabled
        public String congaViewAllURL {get;set;}
        
        @AuraEnabled
        public String congaPrintReportURL {get;set;}
        
        public PartialPaymentsWrapper(){
            noOfPayoutsRhino = 0;
            avgNoOfDaysOutstandingRhino = 0;
            totalPrincipalPaidRhino = 0.0;
            totalInterestPaidRhino = 0.0;
            totalAdminFeePaidRhino = 0.0;
            totalPaymentsRhino = 0.0;
            totalOtherRhino = 0.00;
            totalSurplusRhino = 0.0;
            totalShortfallRhino = 0.0;
            totalMiscRhino = 0.0;
            
            noOfPayoutsELFI = 0;
            avgNoOfDaysOutstandingELFI = 0;
            totalPrincipalPaidELFI = 0.0;
            totalInterestPaidELFI = 0.0;
            totalAdminFeePaidELFI = 0.0;
            totalPaymentsELFI = 0.0;
            totalOtherELFI = 0.00;
            totalSurplusELFI = 0.0;
            totalShortfallELFI = 0.0;
            totalMiscELFI = 0.0;
            
            
            congaViewAllURL = null;
            congaPrintReportURL = null;
        }
    }
}