force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Lawyer, Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RDS_AccountPrintableViewCtlrTest.cls
@isTest
public with sharing class RDS_AccountPrintableViewCtlrTest {

	static testmethod void testRDS_AccountPrintableViewCtlr() {
	
        Account acc = ELUtilTest.createAccount();
        Contact con = ELUtilTest.createContact(acc.Id);

		Opportunity opp = new Opportunity(
        AccountId = acc.Id,
        Lawyer__c = con.Id,
      	Name = 'Test1',
        CloseDate = Date.today().addDays(1),
        StageName = 'ENTERED',
        Law_Firm__c = acc.id
        );
        insert opp;

        PageReference pageRef = Page.RDS_AccountPrintableView;
        Test.setCurrentPage(pageRef);

        ApexPages.StandardController sc = new ApexPages.StandardController(acc);

        RDS_AccountPrintableViewCtlr pv = new RDS_AccountPrintableViewCtlr(sc);
        
        List<String[]> lls = new List<String[]>{pv.getArrearsPaymentOptions(), pv.getBankruptcyOptions()
            ,pv.getDependentOptions(),pv.getEmploymentOptions(),pv.getLitigationOptions()
            ,pv.getMartialStatusOptions(),pv.getSpousalChildPaymentOptions()};

	}
}