force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amendment__c/Amendment__c.object-meta.xml
<CustomObject>
    <label>Amendment</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Amendment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Amendment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Amendment__c/fields/Date_Financing_Statement_Done__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Done__c</fullName>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Amendment__c/fields/Date_Financing_Statement_Expires__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Expires__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Amendment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Amendments</relationshipLabel>
    <relationshipName>Amendments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Any_SpousalChild_support_payment__c.field-meta.xml
<CustomField>
    <fullName>Any_SpousalChild_support_payment__c</fullName>
    <label>Any SpousalChild support payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Lawyer, Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_History__c/Contact_History__c.object-meta.xml
<CustomObject>
    <label>Contact History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Contact History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_History__c/fields/Alternate_Phone__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Phone__c</fullName>
    <label>Alternate Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activity_Historys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_History__c/fields/Date_of_update__c.field-meta.xml
<CustomField>
    <fullName>Date_of_update__c</fullName>
    <label>Date of update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Firm__c/Firm__c.object-meta.xml
<CustomObject>
    <label>Firm</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Firm Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Firms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Firm__c/fields/Date_of_Update__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Update__c</fullName>
    <label>Date of Update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Firm__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Lawyer__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Firm__c/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Firms</relationshipLabel>
    <relationshipName>Firms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Firm__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Firms</relationshipLabel>
    <relationshipName>Firms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Firm__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Firms</relationshipLabel>
    <relationshipName>Firms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Firm__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>Lawyer__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Lender Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Financing_Statement_Done__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Done__c</fullName>
    <label>Date Financing Statement Done</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Financing_Statement_Expires__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Expires__c</fullName>
    <label>Date Financing Statement Expires</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subsequent_Drawdowns__c.field-meta.xml
<CustomField>
    <fullName>Subsequent_Drawdowns__c</fullName>
    <label>Subsequent Drawdowns</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RDS_CustomerCtlrTest.cls
@isTest
public with sharing class RDS_CustomerCtlrTest {
    public RDS_CustomerCtlrTest() {
        
    }
    static testMethod void CustomerTest(){
        Account acc = ELUtilTest.createAccount();
        Contact con = ELUtilTest.createContact(acc.Id);
        
        //String address = 'Montreal, US, QCB, 7th Memorial Drive, W5C 8YZ';
        
        Note n = new note();
        n.parentId = acc.Id;
        n.Title = 'For Testing Notes';
        n.Body = 'Body for Account notes'; 
        //n.ContentType = 'Text';
        insert n;

        Opportunity o = new Opportunity(
          
        Name = 'Test',
        AccountId = acc.Id,
        Lawyer__c = con.id,
        CloseDate = Date.today(),
        StageName = 'ENTERED',
        Amount = 120.00,
        Subsequent_Drawdowns__c = 12.00   
        );
           
        insert o;

        List<Event> lstEvent = new List<Event>();
        Event evnt = New Event();                
        evnt.WhatId = o.Id;
        evnt.StartDateTime = date.today();
        evnt.EndDateTime = date.today().AddDays(5);
        evnt.Subject = 'Subsequent Drawdown on '+date.today()+ ' for 30';
        lstEvent.add(evnt);
        insert lstEvent;

        Amendment__c am = new Amendment__c();
        am.Opportunity__c = o.id;
        am.Amount__c = 300.00;
        am.Date_Financing_Statement_Done__c = Date.today().AddDays(3);
        am.Date_Financing_Statement_Expires__c = Date.today().AddDays(20);

        insert am;

        Firm__c  f = new Firm__c();
        f.Opportunity__c = o.id;
        f.Law_Firm__c = acc.id;
        f.Lawyer__c = con.id;
        f.Date_of_Update__c =Date.today().AddDays(10);
       
        insert f;

        Contact_History__c ch = new Contact_History__c();
        ch.Address__c = 'Montreal, US, QCB, 6th Memorial Drive, W4C 8YZ';
        ch.Alternate_Phone__c = '(90) 4000 0000';
        ch.Date_of_update__c = Date.today().AddDays(2);
        ch.Email__c = 'pierce1.ray@yopmail.com';
        ch.Phone__c = '(75) 74868907';
        ch.Contact__c = con.id;

        insert ch;  

        PageReference pageRef = Page.RDS_Customer;
        Test.setCurrentPage(pageRef); 
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(acc); 
        ApexPages.currentPage().getParameters().put('Id',acc.Id);
        RDS_CustomerCtlr Le = new RDS_CustomerCtlr(sc);

        RDS_CustomerCtlr.runFirstTime = true;
        Le.saveDb();
        Le.init();
        //Le.saveSubsequent();
        Le.saveNotesDb();
        /*List<selectOption> getLoan_Option = Le.getLoanType();
        String fetchPage = Le.fetchContactDetail().getUrl();*/
        String cancel = Le.cancel().getUrl();
        System.assertEquals('/apex/RDS_Customer?id='+acc.id,cancel);
       
        String print = Le.PrintableView().getUrl();
        System.assertEquals('/apex/RDS_AccountPrintableView?Id='+acc.Id,print);


        List<selectOption> maritalStatus_options = Le.getMaritalStatuss();
        System.AssertNotEquals(0, maritalStatus_options.size());

        List<selectOption> spousalSupportPayments_options = Le.getSpousalSupportPayments();
        System.AssertNotEquals(0, spousalSupportPayments_options.size());

        List<selectOption> arrearsPayments_options = Le.getArrearsPayments();
        System.AssertNotEquals(0, arrearsPayments_options.size());


        List<selectOption> Dependants_options = Le.getDependants();
        System.AssertNotEquals(0, Dependants_options.size());

        List<selectOption> bankruptcies_options = Le.getbankruptcies();
        System.AssertNotEquals(0, bankruptcies_options.size());
        
        List<selectOption> litigations_options = Le.getLitigations();
        System.AssertNotEquals(0, litigations_options.size());
        
        List<selectOption> employment_options = Le.getEmployments();
        System.AssertNotEquals(0, employment_options.size());

        Le.Dependant = 'yes';
        Le.getMartialStatusOptions();
        Le.getSpousalChildPaymentOptions();
        Le.getArrearsPaymentOptions();
        Le.getDependentOptions();
        Le.getBankruptcyOptions();
        Le.getEmploymentOptions();
        Le.getLitigationOptions(); 

        Le.deleteLead();       

        /*List<selectOption> getSpousalChildPaymentOptions = Le.getSpousalChildPaymentOptions();
        System.AssertNotEquals(0, Any_SpousalChild_support_payment__c.size());*/
         RDS_Util rd = new RDS_Util();
    }

    /*static testMethod void CustomerTestForNullAndDelete(){
        Account acc = ELUtilTest.createAccount();
        Contact con = ELUtilTest.createContact(acc.Id);

        Note n = new note();
        n.parentId = acc.Id;
        n.Title = 'For Testing Notes';
        n.Body = 'Body for Account notes'; 
        //n.ContentType = 'Text';
        insert n;

        PageReference pageRef = Page.RDS_Customer;
        Test.setCurrentPage(pageRef); 
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(acc); 
        ApexPages.currentPage().getParameters().put('Id',acc.Id);
        RDS_CustomerCtlr Le = new RDS_CustomerCtlr(sc);

        //Le.saveSubsequent();
        Le.saveDb();
       
    }*/
}