force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Rebate_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rebate Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/Assessment_Provider_Schedule__c.object-meta.xml
<CustomObject>
    <label>Assessment Provider Schedule</label>
    <nameField>
        <displayFormat>APS-{0000}</displayFormat>
        <label>Assessment Provider Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Provider Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assessment_provider_schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <label>Lawyer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Lawyer contact must be of type Lawyer.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lawyers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Assessment_provider_schedules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Rebate_Discount__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Discount__c</fullName>
    <label>Rebate Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Rebate_Period__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Period__c</fullName>
    <label>Rebate Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>4 months</fullName>
            </value>
            <value>
                <fullName>8 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
            <value>
                <fullName>16 months</fullName>
            </value>
            <value>
                <fullName>20 months</fullName>
            </value>
            <value>
                <fullName>24 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lawyers.recordType-meta.xml
<RecordType>
    <fullName>Lawyers</fullName>
    <active>true</active>
    <description>Use this record type to track lawyers</description>
    <label>Lawyers</label>
</RecordType>

force-app/main/default/objects/User/fields/Can_Edit_Assessment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Can_Edit_Assessment_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Edit Assessment Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AssessmentProviderScheduleCtlr.cls
public with sharing class AssessmentProviderScheduleCtlr {
    
    @AuraEnabled
    public static void createAssessmentSchedulesbyLawFirm(Id lookupId, Assessment_Provider_Schedule__c assessmentSchedule){
        
        try{
            Id lawyerRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Lawyers').getRecordTypeId();
            
            List<Assessment_Provider_Schedule__c> assessmentSchedules = new List<Assessment_Provider_Schedule__c>();
            for(Contact lawyer : [SELECT Id, Name FROM Contact WHERE AccountId = :lookupId 
                                  AND RecordTypeId =:lawyerRecordTypeId]){
                                      assessmentSchedules.add(
                                          new Assessment_Provider_Schedule__c(
                                              Assessment_Provider__c = assessmentSchedule.Assessment_Provider__c,
                                              Lawyer__c = lawyer.Id,
                                              Discount__c = assessmentSchedule.Discount__c,
                                              Rebate_Period__c = assessmentSchedule.Rebate_Period__c,
                                              Rebate_Discount__c = assessmentSchedule.Rebate_Discount__c
                                          )
                                      );
                                  }
            if(!assessmentSchedules.isEmpty())
                insert assessmentSchedules;            
            
        }catch (Exception e){
            system.debug('Error : ' + e.getMessage() + ' ' + e.getLineNumber());
            system.debug(e.getStackTraceString());
            throw new AuraHandledException('Error:'+e.getMessage());
        }        
    }
    
    @AuraEnabled
    public static void createAssessmentSchedules(Id lookupId, Assessment_Provider_Schedule__c assessmentSchedule){
        
        try{
            insert assessmentSchedule;
        }catch (Exception e){
            system.debug('Error : ' + e.getMessage() );
            throw new AuraHandledException('Error:'+e.getMessage());
        }        
    }
    
    @AuraEnabled
    public static Account getAssessmentProviderInfo(Id recordId){
        return [SELECT Id, Name FROM Account WHERE Id =:recordId];
    }
    
    @AuraEnabled
    public static User getCurrentUserInfo(){
        return [SELECT Id, Can_Edit_Assessment_Schedule__c FROM User 
                WHERE Id = :UserInfo.getUserId()];
    }
    
    @AuraEnabled
    public static List<Assessment_Provider_Schedule__c> getAssessmentSchedules(Id assessmentProviderId){
        
        return [SELECT Id, Name, Assessment_Provider__c, Assessment_Provider__r.Name, Lawyer__c, 
                Lawyer__r.Name, Discount__c, CreatedDate, CreatedBy.Name, LastModifiedDate, LastModifiedBy.Name,
                Rebate_Discount__c, Rebate_Period__c 
                FROM Assessment_Provider_Schedule__c
                WHERE Assessment_Provider__c = :assessmentProviderId];
    }
    
    @AuraEnabled
    public static List<Assessment_Provider_Schedule__c> getAssessmentSchedulesByLawyer(Id lawyerId){
        
        return [SELECT Id, Name, Assessment_Provider__c, Assessment_Provider__r.Name, Lawyer__c, 
                Lawyer__r.Name, Discount__c, CreatedDate, CreatedBy.Name, LastModifiedDate, LastModifiedBy.Name,
                Rebate_Discount__c, Rebate_Period__c 
                FROM Assessment_Provider_Schedule__c
                WHERE Lawyer__c = :lawyerId];
    }

    @AuraEnabled
    public static List<String> getPickListValues(String objectType, String field){
        return OpportunityViewComponentCtlr.getPickListValues(objectType, field);
    }

    @AuraEnabled
    public static Boolean rebateIsAllowed(String lookupId, String selectedLookup){
        Boolean result = false;

        if(selectedLookup == 'Law Firm'){
            result = [SELECT Id, Rebate_Allowed__c FROM Account WHERE Id =:lookupId].Rebate_Allowed__c;
        }else if(selectedLookup == 'recordId'){
            Id lawfirmId = [SELECT Id, Lawyer__r.AccountId FROM Assessment_Provider_Schedule__c WHERE Id =: lookupId].Lawyer__r.AccountId;
            result = [SELECT Id, Rebate_Allowed__c FROM Account WHERE Id =:lawfirmId].Rebate_Allowed__c;
        }else{
            result = [SELECT Id, Account.Rebate_Allowed__c FROM Contact WHERE Id =:lookupId].Account.Rebate_Allowed__c;
        }
        return result;
    }
}