force-app/main/default/objects/Account/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Lawyer__c)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Subsequent_Drawdowns__c.field-meta.xml
<CustomField>
    <fullName>Subsequent_Drawdowns__c</fullName>
    <label>Subsequent Drawdowns</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RDS_OpportunityCtlrTest.cls
@isTest
public class RDS_OpportunityCtlrTest {
    
    static testMethod void OpportunityTest() {
        Account acc = ELUtilTest.createAccount();
        Contact con = ELUtilTest.createContact(acc.Id);
        
        Opportunity o = new Opportunity(
          
        Name = 'Test',
        AccountId = acc.Id,
        Lawyer__c = con.id,
        CloseDate = Date.today(),
        StageName = 'ENTERED',
        Amount = 120.00,
        Subsequent_Drawdowns__c = 13.00   
        );
        insert o;
       
        /* Drawdown__c Dr = new Drawdown__c();
        Dr.Date__c = date.today();
        Dr.Amount__c = 120;
        Dr.Opportunity__c = o.Id;
        insert Dr; */

        /* List<Event> lstEvent = new List<Event>();
        Event evnt = New Event();                
        evnt.WhatId = o.Id;
        evnt.StartDateTime = date.today();
        evnt.EndDateTime = date.today().AddDays(5);
        evnt.Subject = 'Subsequent Drawdown on '+date.today()+ ' for 30';
        lstEvent.add(evnt);
        insert lstEvent; */



        PageReference pageRef = Page.RDS_Opportunity;
        Test.setCurrentPage(pageRef); 
        System.assertNotEquals(null,pageRef);
        
        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(o); 
        ApexPages.currentPage().getParameters().put('accId',acc.Id);
        ApexPages.currentPage().getParameters().put('oppId',o.Id);

        RDS_OpportunityCtlr RDS_Opp = new RDS_OpportunityCtlr(sc);

        List<selectOption> bankruptcies_options = RDS_Opp.getbankruptcies();
        System.AssertNotEquals(0, bankruptcies_options.size());

        RDS_Opp.currentOppSObj = o;
        RDS_Opp.initOpp(o.Id);
        RDS_Opp.getOpp();
        RDS_Opp.saveCurrOpp();
        //RDS_Opp.saveSubsequent();
        
        //System.assertEquals(13,RDS_Opp.saveSubsequent().ddnCount);
        //System.assertEquals(13,RDS_Opp.lstsubscDropdown.size());

    }
    static testMethod void OpportunityForDdCountEqualTest() {
        Account acc = ELUtilTest.createAccount();
        Contact con = ELUtilTest.createContact(acc.Id);
        
        Opportunity o = new Opportunity(
        Name = 'TestOpp',
        AccountId = acc.Id,
        Lawyer__c = con.id,
        CloseDate = Date.today(),
        StageName = 'ENTERED',
        Amount = 120.00,
        Subsequent_Drawdowns__c = 1.00   
        );
        insert o;

        PageReference pageRef = Page.RDS_Opportunity;
        Test.setCurrentPage(pageRef); 
        System.assertNotEquals(null,pageRef);

        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(o); 
        ApexPages.currentPage().getParameters().put('accId',acc.Id);
        ApexPages.currentPage().getParameters().put('oppId',o.Id);

        RDS_OpportunityCtlr RDS_Opp = new RDS_OpportunityCtlr(sc);
        RDS_Opp.deleteOpportunity();

        //System.assertEquals(0,RDS_Opp.lstsubscDropdown.size());
    }
    static testMethod void OpportunityfornullTest() {
        Account acc = ELUtilTest.createAccount();
        Contact con = ELUtilTest.createContact(acc.Id);
        
        Opportunity o = new Opportunity(
        Name = '+',
        AccountId = acc.Id,
        Lawyer__c = con.id,
        CloseDate = Date.today(),
        StageName = 'ENTERED',
        Amount = 120.00,
        Subsequent_Drawdowns__c = 12.00   
        );
        insert o;
        
        PageReference pageRef = Page.RDS_Opportunity;
        Test.setCurrentPage(pageRef);
        System.assertNotEquals(null,pageRef);

        ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(o); 
      
        RDS_OpportunityCtlr RDS_Opp = new RDS_OpportunityCtlr(sc);
        //RDS_Opp.saveSubsequent();
    }
}