force-app/main/default/objects/Account/fields/Loan_To_Value__c.field-meta.xml
<CustomField>
    <fullName>Loan_To_Value__c</fullName>
    <formula>IF(AND(Projected_Loan_Value__c &gt; 0,Total_Amount_Loaned__c &gt; 0),Total_Amount_Loaned__c/Projected_Loan_Value__c,0.00)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan To Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Account/fields/Projected_Loan_Value__c.field-meta.xml
<CustomField>
    <fullName>Projected_Loan_Value__c</fullName>
    <label>Projected Loan Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Custom_Approval_History__c/Custom_Approval_History__c.object-meta.xml
<CustomObject>
    <label>Custom Approval History</label>
    <nameField>
        <displayFormat>AH-{0000}</displayFormat>
        <label>Custom Approval History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Approval_History__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Approval_History__c/fields/Loan_To_Value__c.field-meta.xml
<CustomField>
    <fullName>Loan_To_Value__c</fullName>
    <label>Loan To Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Custom_Approval_History__c/fields/Process_Instance_Id__c.field-meta.xml
<CustomField>
    <fullName>Process_Instance_Id__c</fullName>
    <label>Process Instance Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Custom_Approval_History__c/fields/Value_to_Approve__c.field-meta.xml
<CustomField>
    <fullName>Value_to_Approve__c</fullName>
    <label>Value to Approve</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ApprovelProcessUnlock.cls
public class ApprovelProcessUnlock {
    
    @InvocableMethod(label='Unlock Records And Create Approval History')
    public static void unlockRecordAndCreateCustomApprovalHistory(List<ID> ids) {
        
        List<Id> recordIdsToUnlock = new List<Id>();
        
        for(Id accId : Ids){
            if(Approval.isLocked(accId))
                recordIdsToUnlock.add(accId);
        }
        
        If(!recordIdsToUnlock.isEmpty())
            List<Approval.UnlockResult> unlockList = Approval.unlock(recordIdsToUnlock);
        
        createCustomApprovalHistoryRecords(ids);
    }
    
    public static void createCustomApprovalHistoryRecords(List<ID> ids){
        
        Map<Id, ProcessInstance> accountToPIMap = new Map<Id,ProcessInstance >();
        List<Custom_Approval_History__c> toInsert = new List<Custom_Approval_History__c>();
        
        for(ProcessInstance pi : [SELECT Id, createdDate,
                                  TargetObjectId
                                  FROM ProcessInstance
                                  WHERE TargetObjectId in :ids 
                                  AND Status = 'Pending'
                                  order by createdDate]){
                                      if(!accountToPIMap.containsKey(pi.TargetObjectId))
                                          accountToPIMap.put(pi.TargetObjectId, pi);
                                  }
        
        for(Account acc : [Select Id, Projected_Loan_Value__c, Loan_To_Value__c
                           FROM Account
                           WHERE Id in :ids]){
                               toInsert.add(
                                   new Custom_Approval_History__c(
                                       Account__c = acc.Id,
                                       Process_Instance_Id__c = accountToPIMap.containsKey(acc.Id)? accountToPIMap.get(acc.Id).Id : null,
                                       Value_to_Approve__c = '' + acc.Projected_Loan_Value__c,
                                       Loan_To_Value__c = acc.Loan_To_Value__c
                                   )
                               );
                           }
        
        if(!toInsert.isEmpty()){
            insert toInsert;
        }
        
    }
}