force-app/main/default/objects/Account/fields/Outstanding_Balance_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
    <inlineHelpText>Outstanding Balance on the Reporting To date. Used for ELFI 1 report. Note that this field is just labeled &quot;Outstanding Balance&quot; on the report (label changed via report type).</inlineHelpText>
    <label>Outstanding Balance as of To Date</label>
    <summarizedField>Opportunity.Outstanding_Balance_as_of_To_Date__c</summarizedField>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reporting_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_From_Date__c</fullName>
    <inlineHelpText>The minimum Reporting From Date on all of the Drawdowns which are eligible for inclusion in the Portfolio reports.</inlineHelpText>
    <label>Reporting From Date</label>
    <summarizedField>Opportunity.Reporting_From_Date__c</summarizedField>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reporting_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_To_Date__c</fullName>
    <inlineHelpText>The maximum Reporting TO Date on all of the Drawdowns which are eligible for inclusion in the Portfolio reports.</inlineHelpText>
    <label>Reporting To Date</label>
    <summarizedField>Opportunity.Reporting_To_Date__c</summarizedField>
    <summaryForeignKey>Opportunity.AccountId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_as_of_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_From_Date__c</fullName>
    <inlineHelpText>Accrued interest on the From Date</inlineHelpText>
    <label>Accrued Interest as of From Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_as_of_Temp_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_Temp_Date__c</fullName>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF( ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),0,(Outstanding_Balance_as_of_Temp_Date__c-Amount_Adjusted_for_Payments_b4_Temp_Dt__c)+Interest_up_to_Last_Repayment_b4_Temp_Dt__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Interest Accrued up to Temp Payout Date</inlineHelpText>
    <label>Accrued Interest as of Temp Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_To_Date__c</fullName>
    <label>Accrued Interest as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_In_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_In_Reporting_Period__c</fullName>
    <formula>Accrued_Interest_as_of_To_Date__c -  Accrued_Interest_as_of_From_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accrued Interest In Reporting Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Balance_Change_In_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Balance_Change_In_Reporting_Period__c</fullName>
    <formula>Outstanding_Balance_as_of_To_Date__c -  Outstanding_Balance_as_of_From_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Change In Reporting Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
    <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
    <label>Compounding Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
    <inlineHelpText>Loan Interest Rate</inlineHelpText>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_From_Date__c</fullName>
    <inlineHelpText>Outstanding balance on the From date</inlineHelpText>
    <label>Outstanding Balance as of From Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_Temp_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_Temp_Date__c</fullName>
    <description>NOTE: Used EXP and LN as the normal exponent function does not handle fractional numbers: See: https://developer.salesforce.com/forums/?id=906F00000008vDHIAY</description>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF( ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),Sum_of_Payment_Allocations__c - Amount__c, 
IF(Compounding_Interest__c,(Amount_Adjusted_for_Payments_b4_Temp_Dt__c*(EXP(LN(1 + (Interest_Rate__c/Compounding_Frequency__c))* 
(Compounding_Frequency__c*Interest_Accrual_Years_Pymt_to_Temp_Dt__c)))),Amount_Adjusted_for_Payments_b4_Temp_Dt__c*(1+((Interest_Rate__c/365)* Interest_Accrual_Days_Pymt_to_Temp_Dt__c)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Outstanding Balance as it will be at the Temp Payout Date. This Accounts for compounding interest or Simple Interest depending on the Loan. This is set to zero when Drawdown is Payment.  For Payments this contains the unallocated payment amount.</inlineHelpText>
    <label>Outstanding Balance as of Temp Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
    <inlineHelpText>Balance on To Date</inlineHelpText>
    <label>Outstanding Balance as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reporting_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_From_Date__c</fullName>
    <inlineHelpText>Start date of reporting information</inlineHelpText>
    <label>Reporting From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reporting_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_To_Date__c</fullName>
    <inlineHelpText>End date of reporting information</inlineHelpText>
    <label>Reporting To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Temp_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Temp_Payout_Date__c</fullName>
    <inlineHelpText>Used to calculate outstanding balance and date as of a scratch date.  This field should not be updated directly on the Drawdown, instead update from Opportunity and let it replicate down.  Used for Payment Allocation and Reporting From/To amount calc.</inlineHelpText>
    <label>Temp Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/Drawdown_Payment_Allocation__c.object-meta.xml
<CustomObject>
    <description>All Payment allocations to Drawdowns.</description>
    <label>Drawdown Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdown Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/fields/Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Drawdown__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Drawdown that this applies to</inlineHelpText>
    <label>Drawdown</label>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Payments Allocated to this Drawdown</relationshipLabel>
    <relationshipName>Payments_Allocated_to_this_Drawdown</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/fields/Reporting_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_To_Date__c</fullName>
    <label>Reporting To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/fields/Temp_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Temp_Payout_Date__c</fullName>
    <inlineHelpText>The Temp Payout Date replicated down from the Opportunity.  It&#39;s required here to allow the DLRS to aggregate up to Drawdown.</inlineHelpText>
    <label>Temp Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Annual Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Outstanding_Balance_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
    <inlineHelpText>Outstanding Balance on the Reporting To date.  Used for ELFI 1 report.  Note that this field is just labeled &quot;Outstanding Balance&quot; on the report (label changed via report type).</inlineHelpText>
    <label>Outstanding Balance as of To Date</label>
    <summarizedField>Drawdown__c.Outstanding_Balance_as_of_To_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>notEqual</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reporting_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_From_Date__c</fullName>
    <inlineHelpText>The minimum Reporting From Date on all of the Drawdowns which are eligible for inclusion in the Portfolio reports.</inlineHelpText>
    <label>Reporting From Date</label>
    <summarizedField>Drawdown__c.Reporting_From_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>notEqual</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Drawdown__c.Include_in_Portfolio_Reports__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reporting_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_To_Date__c</fullName>
    <inlineHelpText>The maximum Reporting TO Date on all of the Drawdowns which are eligible for inclusion in the Portfolio reports.</inlineHelpText>
    <label>Reporting To Date</label>
    <summarizedField>Drawdown__c.Reporting_To_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>notEqual</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Drawdown__c.Include_in_Portfolio_Reports__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/PortfolioReportCalculateData.cls
global class PortfolioReportCalculateData implements Database.Batchable<sObject> {
        /*------------------------------------------------------------
        Author: Basil Dobek
        Company: Deloitte
        Description:  Calculate the interest accrued on all drawdowns as of the From date and To Date.
                      These values are saved in From and To fields.
                      Steps are:
                           1) update "Temp_Payout_Date__c" on all Drawdown ALlocations to the From Date
                           2) Update "Temp_Payout_Date__c" on all Drawdowns to the From Date
                           3) Save the interest and balance in the from date fields
                           4) update "Temp_Payout_Date__c" on all Drawdown ALlocations to the TO Date
                           5) Update "Temp_Payout_Date__c" on all Drawdowns to TO From Date     
                           6) Save the interest and balance in the from date fields     
                    I update the Drawdown allocations before the Drawdowns as the DLRS will update the Drawdowns based on the Drawdown Allocation information.         
        Inputs:   
            
        History
        <Date> <Authors Name> <Brief Description of Change>
        ------------------------------------------------------------*/  
    String query;
    public Date fromDate;  // date we are calcuating from
    public Date toDate;    // date we are calculating to
    public Boolean sinceInception;  // use this to indicate calculation since the drawdown date 
    public id portfolioReportId;  // id of the portfolio report object used to launch job
    
    global PortfolioReportCalculateData() {
    
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        query='SELECT id,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c,' +
                     'Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c,'+
                     'Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c, '+
                     'Accrued_Interest_as_of_Temp_Date__c from drawdown__c where Payment_Method__c != \'Payment\' AND ' +
                     '(Interest_Rate__c > 0) AND (Compounding_Interest__c = false or Compounding_Frequency__c >0)';


        //set the batch instance id on the portfolio report.
        portfolio_report__c pr = [select id,Business_Unit__c, status__c, errors__c,batch_Instance_id__c from portfolio_report__c where id =:portfolioReportId ];
        pr.batch_Instance_id__c=bc.getJobId();  
        pr.errors__c = 'Batch started at:' + dateTime.now().formatLong() + ',   ';
        update pr;
        List<Opportunity> oppList;
        System.debug('Business Unit: ' + pr.Business_Unit__c);
        if (pr.Business_Unit__c != 'All'){
            oppList = [select Id from Opportunity where AccountId in (select Id from Account where Business_Unit__c=:pr.Business_Unit__c)];
            System.debug('Opps: ' + oppList.size());
            return Database.getQueryLocator([select id,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c, Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c, Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c, Accrued_Interest_as_of_Temp_Date__c from drawdown__c where Payment_Method__c != 'Payment' AND  (Interest_Rate__c > 0) AND (Compounding_Interest__c = false or Compounding_Frequency__c >0) and (Opportunity__c in: oppList)]);
        }
        else return Database.getQueryLocator([select id,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c, Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c, Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c, Accrued_Interest_as_of_Temp_Date__c from drawdown__c where Payment_Method__c != 'Payment' AND  (Interest_Rate__c > 0) AND (Compounding_Interest__c = false or Compounding_Frequency__c >0)]);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        try{
            /*
                Fahad: Whole lagic is packed into a static method
                this logic needs to be executed for each opportunit while adding criticl dates to them
                instead of replicating the code, this static method would be called from 
                critical date trigger to get the fresh value of balance and accrued interest from opportunity. 
            */
            calculateDataInStatic(scope, sinceInception, fromDate, toDate);
        }
        catch (Exception e){
            portfolio_report__c pr = [select id,status__c, errors__c from portfolio_report__c where id =:portfolioReportId ];
            pr.errors__c+='The following error occurred in batch ' +BC.getJobId()+', : '+e.getMessage()+',    ';        
            update pr;  
        }
    }
    global static void calculateDataInStatic(List<Sobject> scope, boolean sinceInception, Date fromDate, Date toDate)
    {
        List<drawdown__c> dScope = (list <Drawdown__c>)scope;
        Map<Id,Drawdown__c> dMap= new Map<Id,Drawdown__c>(dScope);
        
        // get all of the drawdown allocations associated with the scope record and update Temp_Payout_Date on them first
        // this will trigger the DLRS to update the Drawdown records
        List<Drawdown_Payment_Allocation__c> allocations = [Select id,temp_payout_date__c,Reporting_To_Date__c,drawdown__r.date__c from Drawdown_Payment_Allocation__c where drawdown__c in: dmap.keySet()];
        list<Drawdown_Payment_Allocation__c> updatedAllocations = new List <Drawdown_Payment_Allocation__c> (); 
        for (Drawdown_Payment_Allocation__c a : allocations){
            if (sinceInception){
                a.Temp_payout_date__c = a.drawdown__r.date__c;
            }else{
                a.temp_payout_date__c = fromDate;
            }
            updatedAllocations.add(a);
        }
        //system.debug('xxxxxxxx update allocations with from date. updatedAllocations='+updatedAllocations);
        update updatedAllocations;
        
        // update drawdowns with from date
        list<drawdown__c> updatedDrawdowns = new List <Drawdown__c>();
        for (drawdown__c d : dscope){
            if (sinceInception){
                d.temp_Payout_date__c = d.date__c;
                d.Reporting_From_Date__c = d.date__c;
            }else{
                d.temp_payout_date__c = fromDate;
                d.Reporting_From_Date__c = fromDate;
            }
            updatedDrawdowns.add(d);
        }
        //system.debug('xxxxxxxx update drawdowns with from date. updatedDrawdowns='+updatedDrawdowns);
        update updatedDrawdowns;
        
        updatedDrawdowns = [SELECT id,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c, 
                            Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c, 
                            Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c,  
                            Accrued_Interest_as_of_Temp_Date__c from drawdown__c where id in:updatedDrawdowns];
        
        // save results for from date
        for (drawdown__c d : updatedDrawdowns){
            if (sinceInception || d.date__c> fromDate ){  //cannot be accrued interest before the drawdown or at inception
                d.Outstanding_Balance_as_of_From_Date__c = 0.00;
                d.Accrued_Interest_as_of_From_Date__c = 0.00;
            }else {
                d.Outstanding_Balance_as_of_From_Date__c = d.Outstanding_Balance_as_of_Temp_Date__c;
                d.Accrued_Interest_as_of_From_Date__c = d.Accrued_Interest_as_of_Temp_Date__c;
            }
        }
        //system.debug('xxxxxxxx update drawdowns with interest and balance at from date. updatedDrawdowns='+updatedDrawdowns);
        update updatedDrawdowns;
        
        // update temp date on allocations with to date
        for (Drawdown_Payment_Allocation__c a : allocations){
            a.temp_payout_date__c = toDate;
            a.Reporting_To_Date__c = toDate;
        }
        //system.debug('xxxxxxxx update allocations with to date. updatedAllocations='+updatedAllocations);
        update updatedAllocations;
        
        // update drawdown with to date
        for (drawdown__c d : updatedDrawdowns){
            d.temp_payout_date__c = toDate;
            d.Reporting_To_Date__c = toDate;
        }
        //system.debug('xxxxxxxx update drawdowns with to date. updatedDrawdowns='+updatedDrawdowns);
        update updatedDrawdowns;    
        
        updatedDrawdowns = [SELECT id,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c, 
                            Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c, 
                            Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c,  
                            Date_of_Last_Repayment_b4_Temp_Date__c,Accrued_Interest_as_of_Temp_Date__c from drawdown__c where id in:updatedDrawdowns];
        
        // save results for TO date
        for (drawdown__c d : updatedDrawdowns){
            if (d.date__c > toDate ){  //cannot be accrued interest after the toDate
                d.Outstanding_Balance_as_of_To_Date__c = 0.00;
                d.Accrued_Interest_as_of_To_Date__c = 0.00;
            }else {
                d.Outstanding_Balance_as_of_To_Date__c = d.Outstanding_Balance_as_of_Temp_Date__c;
                d.Accrued_Interest_as_of_To_Date__c = d.Accrued_Interest_as_of_Temp_Date__c;
                if ((d.Accrued_Interest_as_of_From_Date__c<d.Accrued_Interest_as_of_To_Date__c ) && d.Outstanding_Balance_as_of_To_Date__c == 0){
                    // In this condition interest was accrued in the reporting period but the balance at the end is $0
                    // This can only happen when the Drawdown was paid off in the period.   
                    // Therefore record the TO date as the date of last repayment
                    d.Reporting_To_Date__c = d.Date_of_Last_Repayment_b4_Temp_Date__c;
                }
            }
        }
        //system.debug('xxxxxxxx update drawdowns with interest and balance at to date. updatedDrawdowns='+updatedDrawdowns);
        update updatedDrawdowns;
    }
    /*
    global void execute(Database.BatchableContext BC, List<sObject> scope) {

        try{

            List<drawdown__c> dScope = (list <Drawdown__c>)scope;
            Map<Id,Drawdown__c> dMap= new Map<Id,Drawdown__c>(dScope);

            // get all of the drawdown allocations associated with the scope record and update Temp_Payout_Date on them first
            // this will trigger the DLRS to update the Drawdown records
            List<Drawdown_Payment_Allocation__c> allocations = [Select id,temp_payout_date__c,drawdown__r.date__c from Drawdown_Payment_Allocation__c where drawdown__c in: dmap.keySet()];
            list<Drawdown_Payment_Allocation__c> updatedAllocations = new List <Drawdown_Payment_Allocation__c> (); 
            for (Drawdown_Payment_Allocation__c a : allocations){
                if (sinceInception){
                    a.Temp_payout_date__c = a.drawdown__r.date__c;
                }else{
                    a.temp_payout_date__c = fromDate;
                }
                updatedAllocations.add(a);
            }
            //system.debug('xxxxxxxx update allocations with from date. updatedAllocations='+updatedAllocations);
            update updatedAllocations;

            // update drawdowns with from date
            list<drawdown__c> updatedDrawdowns = new List <Drawdown__c>();
            for (drawdown__c d : dscope){
                if (sinceInception){
                    d.temp_Payout_date__c = d.date__c;
                    d.Reporting_From_Date__c = d.date__c;
                }else{
                    d.temp_payout_date__c = fromDate;
                    d.Reporting_From_Date__c = fromDate;
                }
                updatedDrawdowns.add(d);
            }
            //system.debug('xxxxxxxx update drawdowns with from date. updatedDrawdowns='+updatedDrawdowns);
            update updatedDrawdowns;

            updatedDrawdowns = [SELECT id,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c, 
                     Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c, 
                     Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c,  
                     Accrued_Interest_as_of_Temp_Date__c from drawdown__c where id in:updatedDrawdowns];

            // save results for from date
            for (drawdown__c d : updatedDrawdowns){
                if (sinceInception || d.date__c<= fromDate ){  //cannot be accrued interest before the drawdown or at inception
                    d.Outstanding_Balance_as_of_From_Date__c = 0.00;
                    d.Accrued_Interest_as_of_From_Date__c = 0.00;
                }else {
                    d.Outstanding_Balance_as_of_From_Date__c = d.Outstanding_Balance_as_of_Temp_Date__c;
                    d.Accrued_Interest_as_of_From_Date__c = d.Accrued_Interest_as_of_Temp_Date__c;
                }
            }
            //system.debug('xxxxxxxx update drawdowns with interest and balance at from date. updatedDrawdowns='+updatedDrawdowns);
            update updatedDrawdowns;

            // update temp date on allocations with to date
            for (Drawdown_Payment_Allocation__c a : allocations){
                a.temp_payout_date__c = toDate;
            }
            //system.debug('xxxxxxxx update allocations with to date. updatedAllocations='+updatedAllocations);
            update updatedAllocations;

            // update drawdown with to date
            for (drawdown__c d : updatedDrawdowns){
                d.temp_payout_date__c = toDate;
                d.Reporting_To_Date__c = toDate;
            }
            //system.debug('xxxxxxxx update drawdowns with to date. updatedDrawdowns='+updatedDrawdowns);
            update updatedDrawdowns;    

            updatedDrawdowns = [SELECT id,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c, 
                     Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c, 
                     Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c,  
                     Date_of_Last_Repayment_b4_Temp_Date__c,Accrued_Interest_as_of_Temp_Date__c from drawdown__c where id in:updatedDrawdowns];

            // save results for TO date
            for (drawdown__c d : updatedDrawdowns){
                if (d.date__c > toDate ){  //cannot be accrued interest after the toDate
                    d.Outstanding_Balance_as_of_To_Date__c = 0.00;
                    d.Accrued_Interest_as_of_To_Date__c = 0.00;
                }else {
                    d.Outstanding_Balance_as_of_To_Date__c = d.Outstanding_Balance_as_of_Temp_Date__c;
                    d.Accrued_Interest_as_of_To_Date__c = d.Accrued_Interest_as_of_Temp_Date__c;
                    if ((d.Accrued_Interest_as_of_From_Date__c<d.Accrued_Interest_as_of_To_Date__c ) && d.Outstanding_Balance_as_of_To_Date__c == 0){
                        // In this condition interest was accrued in the reporting period but the balance at the end is $0
                        // This can only happen when the Drawdown was paid off in the period.   
                        // Therefore record the TO date as the date of last repayment
                        d.Reporting_To_Date__c = d.Date_of_Last_Repayment_b4_Temp_Date__c;
                    }
                }
            }
            //system.debug('xxxxxxxx update drawdowns with interest and balance at to date. updatedDrawdowns='+updatedDrawdowns);
            update updatedDrawdowns;    
        }
        catch (Exception e){
            portfolio_report__c pr = [select id,status__c, errors__c from portfolio_report__c where id =:portfolioReportId ];
            pr.errors__c+='The following error occurred in batch ' +BC.getJobId()+', : '+e.getMessage()+',    ';        
            update pr;  
        }
    }
    */
    
    global void finish(Database.BatchableContext BC) {
        portfolio_report__c pr = [select id,status__c, errors__c from portfolio_report__c where id =:portfolioReportId ];
        pr.status__c='Complete';
        pr.errors__c += 'Batch ended at:' + dateTime.now().formatLong();
        update pr;
    }
    
}