force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the key person to contact about inquiries related to this account: loan related, additional information, payments, receivables, etc.</inlineHelpText>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>There are no contacts under this account that matches the search criteria.</errorMessage>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <infoMessage>Please select the contact that will serve as primary contact for this account.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Primary Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/Opportunity_Service_Provider__c.object-meta.xml
<CustomObject>
    <label>Opportunity Service Provider</label>
    <nameField>
        <displayFormat>OSP-{00000}</displayFormat>
        <label>OSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Service Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Allowance__c.field-meta.xml
<CustomField>
    <fullName>Allowance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Allowance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Allowance_Balance__c.field-meta.xml
<CustomField>
    <fullName>Allowance_Balance__c</fullName>
    <formula>Allowance__c - Total_Paid_Non_Rejected__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Allowance Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Generate_Schedule_PDF__c.field-meta.xml
<CustomField>
    <fullName>Generate_Schedule_PDF__c</fullName>
    <formula>IF(
ISPICKVAL(Opportunity__r.Type_of_Loan__c,&quot;Treatment Loan&quot;)
, HYPERLINK(&quot;/apex/APXTConga4__Conga_Composer?id=&quot;&amp;Id&amp;&quot;&amp;TemplateId=&quot;&amp;IF(ISPICKVAL(Opportunity__r.Account.Business_Unit__c,&quot;ELFI&quot;),&quot;a0x0L00000NthIU&quot;,&quot;a0x19000000ythu&quot;)&amp;&quot;&amp;DS7=3&amp;DefaultPDF=1&amp;SC0=1&quot;,&quot;Schedule(PDF)&quot;,&quot;_blank&quot;)
, IF(
ISPICKVAL(Opportunity__r.Type_of_Loan__c,&quot;Treatment Loan 2&quot;)
, HYPERLINK(&quot;/apex/APXTConga4__Conga_Composer?id=&quot;&amp;Id&amp;&quot;&amp;TemplateId=&quot;&amp;IF(ISPICKVAL(Opportunity__r.Account.Business_Unit__c,&quot;ELFI&quot;),&quot;a0x0L00000ObHzx&quot;,&quot;a0x19000000ythz&quot;)&amp;&quot;&amp;DS7=3&amp;DefaultPDF=1&amp;SC0=1&quot;,&quot;Schedule(PDF)&quot;,&quot;_blank&quot;)
, &quot;N/A&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Generate Schedule (PDF)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <formula>IF(
ISBLANK(Service_Provider_Facility__r.Primary_Contact__c)
, HYPERLINK(&quot;/&quot;&amp; Service_Provider_Facility__r.Id &amp; &quot;/e?retURL=/&quot; &amp; Service_Provider_Facility__r.Id, &quot;Click Here to Add&quot;, &quot;_blank&quot;)
, HYPERLINK(&quot;/&quot;&amp; Service_Provider_Facility__r.Primary_Contact__r.Id ,Service_Provider_Facility__r.Primary_Contact__r.FirstName &amp;&quot; &quot;&amp; Service_Provider_Facility__r.Primary_Contact__r.LastName,&quot;_blank&quot;) 
)</formula>
    <label>Primary Contact</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Send_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Send_Schedule__c</fullName>
    <description>Conga and Docusign instructions</description>
    <formula>IF(
ISPICKVAL(Opportunity__r.Type_of_Loan__c,&quot;Treatment Loan&quot;)
, HYPERLINK(&quot;/apex/APXTConga4__Conga_Composer?id=&quot;&amp;Id&amp;&quot;&amp;TemplateId=&quot;&amp;IF(ISPICKVAL(Opportunity__r.Account.Business_Unit__c,&quot;ELFI&quot;),&quot;a0x0L00000NthIU&quot;,&quot;a0x19000000ythu&quot;)&amp;&quot;&amp;DS7=17&amp;DocuSignVisible=1&amp;DocuSignR1Id=&quot;&amp;Primary_Contact_Id__c&amp;&quot;&amp;DocuSignR1Type=Signer&amp;DocuSignR1Role=Signer+1&amp;DocuSignR1RoutingOrder=1&amp;QueryStringField=Docusign_Parameters__c&quot;,&quot;Send Schedule&quot;,&quot;_blank&quot;)
, IF(
ISPICKVAL(Opportunity__r.Type_of_Loan__c,&quot;Treatment Loan 2&quot;)
, HYPERLINK(&quot;/apex/APXTConga4__Conga_Composer?id=&quot;&amp;Id&amp;&quot;&amp;TemplateId=&quot;&amp;IF(ISPICKVAL(Opportunity__r.Account.Business_Unit__c,&quot;ELFI&quot;),&quot;a0x0L00000ObHzx&quot;,&quot;a0x19000000ythz&quot;)&amp;&quot;&amp;DS7=17&amp;DocuSignVisible=1&amp;DocuSignR1Id=&quot;&amp;Primary_Contact_Id__c&amp;&quot;&amp;DocuSignR1Type=Signer&amp;DocuSignR1Role=Signer+1&amp;DocuSignR1RoutingOrder=1&amp;QueryStringField=Docusign_Parameters__c&quot;,&quot;Send Schedule&quot;,&quot;_blank&quot;)
, &quot;N/A&quot;
)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Send Schedule</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Service_Provider_Email__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Email__c</fullName>
    <formula>IF(
ISBLANK(Service_Provider_Facility__r.Primary_Contact__r.Email)
, &quot;Not available&quot;
, Service_Provider_Facility__r.Primary_Contact__r.Email
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Provider Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Service_Provider_Facility__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Facility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider Facility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>General Business</value>
        </filterItems>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Treatment Provider Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Service_Provider_Phone__c.field-meta.xml
<CustomField>
    <fullName>Service_Provider_Phone__c</fullName>
    <formula>IF(
ISBLANK(Service_Provider_Facility__r.Phone)
, &quot;Not available&quot;
, Service_Provider_Facility__r.Phone
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Service Provider Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting to Send Schedule</fullName>
                <default>true</default>
                <label>Waiting to Send Schedule</label>
            </value>
            <value>
                <fullName>Schedule Sent</fullName>
            </value>
            <value>
                <fullName>Schedule Signed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Total_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid__c</fullName>
    <description>Field updated via DLRS</description>
    <label>Total Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CSL_OpportunityServiceProviderCtlr.cls
public with sharing class CSL_OpportunityServiceProviderCtlr {
    /**
     * Parent Opportunity ID
     */
    public String oppId {get; private set;}
    
    public Opportunity_Service_Provider__c provider {get; private set;}

    public List<Opportunity_Service_Provider__c> providers {get; set;}

    /**
     * Constructor
     */
    public CSL_OpportunityServiceProviderCtlr(ApexPages.StandardController controller) {
        init();    

        provider = new Opportunity_Service_Provider__c();
    }

    /**
     * Initialize page
     */
    public void init() {

        oppId = ApexPages.currentPage().getParameters().get('oppId');


        // load the the list of service providers
        if (oppId != null){
            providers = (List<Opportunity_Service_Provider__c>)Database.query(
                ' SELECT Id, Primary_Contact__c, Allowance__c, Allowance_Balance__c, Service_Provider_Facility__r.Name, Service_Provider_Facility__c, Service_Provider_Email__c, Service_Provider_Phone__c, Total_Paid__c, Status__c, Send_Schedule__c, Generate_Schedule_PDF__c, CreatedDate,  '+
                ' (SELECT Id, Amount__c, Date__c, CreatedDate, Payment_Method__c, Reference_Notes__c '+
                ' FROM Drawdowns__r '+
                ' ORDER BY Date__c DESC) '+
                ' FROM Opportunity_Service_Provider__c '+
                ' WHERE Opportunity__c = :oppId '+
                ' ORDER BY CreatedDate DESC ');

        }

    }


    public PageReference createNew() {
        
        try {
            provider.Opportunity__c = oppId;

            insert(provider);
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        
        // go back to the same page
        return getCurrentPage();
    }

    public PageReference deleteProvider() {

        String pId = ApexPages.currentPage().getParameters().get('pId');
        System.debug('deletee pid = '+pId);

        List<Opportunity_Service_Provider__c> delProviders = [SELECT Id FROM Opportunity_Service_Provider__c WHERE Id=:pid LIMIT 1];
        if (delProviders.size() > 0) {
            try {
                delete delProviders[0];
            } catch (DMLException e) {
                ApexPages.addMessages(e);
            }
        }


        // go back to the same page
        return getCurrentPage();
    }

    public PageReference addDrawdown() {

        String pId = ApexPages.currentPage().getParameters().get('pId');

        if (!String.isBlank(pId) && pId != null) {

            // create a blank drawdown item at the current date
            Drawdown__c newDrawdown = new Drawdown__c(
                Opportunity_Service_Provider__c = pId,
                Opportunity__c = oppId,
                Type__c = 'Treatment Loan',
                Amount__c = 0,
                Date__c= Date.today()
            );

            try {
                insert newDrawdown;
            } catch (DMLException e) {
                ApexPages.addMessages(e);
            }
        }   

        // go back to the same page
        return getCurrentPage();
    }

    public PageReference deleteDrawdown() {

        String dId = ApexPages.currentPage().getParameters().get('dId');
        System.debug('delete dId = '+dId);

        List<Drawdown__c> delDrawdown = [SELECT Id FROM Drawdown__c WHERE Id=:dId LIMIT 1];
        if (delDrawdown.size() > 0) {
            try {
                delete delDrawdown[0];
            } catch (DMLException e) {
                ApexPages.addMessages(e);
            }
        }

        // go back to the same page
        return getCurrentPage();
    }


    public PageReference saveProviderList() {

        System.debug('providers list = ' + providers);
        
        // collect drawdowns
        List<Drawdown__c> updateDrawdowns = new List<Drawdown__c>();
        for(Opportunity_Service_Provider__c sp: providers){
            if (sp.Drawdowns__r.size() > 0) {
                updateDrawdowns.addAll(sp.Drawdowns__r);
            }
        }
            
        System.debug(updateDrawdowns);
    
        try {
            
            if (updateDrawdowns.size() > 0) {
                System.debug('here = ' + updateDrawdowns);
                update updateDrawdowns;
            }
            system.debug('blahblah');
            
            Map<id,Opportunity_Service_Provider__c> pmap = new Map<id,Opportunity_Service_Provider__c>(providers);
            Map<id,Opportunity_Service_Provider__c> updatedProviders = new Map<id,Opportunity_Service_Provider__c>([select Total_Paid__c,id,name from Opportunity_Service_Provider__c where id in: pmap.keySet()]); 
            for(Opportunity_Service_Provider__c p: providers){
                p.Total_Paid__c = updatedProviders.get(p.id).Total_Paid__c;
            }
            update providers;
        
        } catch (DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        

        return getCurrentPage();
    }

    public PageReference getCurrentPage() {
        PageReference pg = new PageReference('/apex/CSL_OpportunityServiceProvider?oppId=' + oppId);
        pg.setRedirect(true);
        
        return pg;
    }
}