force-app/main/default/objects/Amendment__c/Amendment__c.object-meta.xml
<CustomObject>
    <label>Amendment</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Amendment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Amendments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Amendment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Amendment__c/fields/Date_Financing_Statement_Done__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Done__c</fullName>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Amendment__c/fields/Date_Financing_Statement_Expires__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Expires__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Amendment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Amendments</relationshipLabel>
    <relationshipName>Amendments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Amendment__c/fields/Renewal_date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_date__c</fullName>
    <formula>Date(YEAR(Date_Financing_Statement_Expires__c), (MONTH(Date_Financing_Statement_Expires__c) - 1), DAY(Date_Financing_Statement_Expires__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewal date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Amendment__c/fields/Renewal_Date_New__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date_New__c</fullName>
    <description>This field was created to store the new renewal date from the opportunity. Old version of renewal date is calculated, Dom requested to have it as an open field.</description>
    <label>Renewal Date - New</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Financing_Statement_Done__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Done__c</fullName>
    <label>Date Financing Statement Done</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Date_Financing_Statement_Expires__c.field-meta.xml
<CustomField>
    <fullName>Date_Financing_Statement_Expires__c</fullName>
    <label>Date Financing Statement Expires</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Renewal_Date__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Date__c</fullName>
    <label>Renewal Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AmendmentTriggerHandler.cls
public with sharing class AmendmentTriggerHandler {

    public static void createActivityHistory(Map<Id,Opportunity> newMap){
        
        List<Amendment__c> lstAmendment = new List<Amendment__c>();
        
        for(Opportunity opp : newMap.values()){

            Opportunity oppr = (Opportunity)Trigger.oldMap.get(opp.Id);
            
            if(opp.Date_Financing_Statement_Done__c != oppr.Date_Financing_Statement_Done__c ||
               opp.Date_Financing_Statement_Expires__c != oppr.Date_Financing_Statement_Expires__c ||
               opp.Amount != oppr.Amount ||
               opp.Renewal_Date__c != oppr.Renewal_Date__c 
               ){
                Amendment__c Amendment = new Amendment__c();
                Amendment.Date_Financing_Statement_Done__c = opp.Date_Financing_Statement_Done__c;
                Amendment.Date_Financing_Statement_Expires__c = opp.Date_Financing_Statement_Expires__c;
                Amendment.Amount__c = opp.Amount;
                Amendment.Opportunity__c = opp.Id;
                Amendment.Renewal_Date_New__c = opp.Renewal_Date__c;
                lstAmendment.add(Amendment);
            }
        }

        if(lstAmendment.size() > 0){
            insert lstAmendment; 
        }
    }
}