force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Bank Account Number</description>
    <inlineHelpText>May have spaces or dashes to group the numbers</inlineHelpText>
    <label>Account #</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that payment should be sent to (will default to Opportunity Account if not set)</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_Date__c</fullName>
    <description>Date and Time this payment was included in a banking sheet</description>
    <label>Sent to Bank Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&#39;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BankAccountsControllerTest.cls
/**
*    @description : Test class for BankAccountsController
**/
@isTest(seeAllData=false)
private with sharing class BankAccountsControllerTest {
	
    /**
	*    @description : Test get bank accounts list
	**/
	@isTest
    static void test_getBankAccounts(){
        Account[] accRecs = TestDataFactory.getAccountObjects(1);

        Bank_Account__c[] bankRecs = TestDataFactory.getBankAccountObjects(1);

    	Test.startTest();
    	// get account 
   		Map<String, Object> objectsMap = BankAccountsController.getBankAccounts(accRecs[0].Id, 'BankAccounts');
   		List<Object> recordsList = (List<Object>)objectsMap.get('records');
   		System.assertEquals(1,recordsList.size());
    	Test.stopTest();
    }

    public static testMethod void testGetUsedBankAccounts(){
        Account[] accRecs = TestDataFactory.getAccountObjects(2);

        FObject baConfig = TestDataFactory.getBankAccountConfig(2);
        Bank_Account__c[] bankRecs = TestDataFactory.getBankAccountObjects(baConfig, false);
        // Ensure we're using different accounts
        bankRecs[0].Client__c = accRecs[0].Id;
        bankRecs[1].Client__c = accRecs[1].Id;
        TestDataFactory.getBankAccountObjects(baConfig, true);

        FObject oppConfig = TestDataFactory.getOpportunityConfig(1);
        Opportunity[] oppRecs = TestDataFactory.getOpportunityObjects(oppConfig, false);
        oppRecs[0].AccountId = accRecs[0].Id;
        oppRecs = TestDataFactory.getOpportunityObjects(oppConfig, true);

        FObject spConfig = TestDataFactory.getScheduledPaymentConfig(2);
        spConfig.setDefinition('Amount__c', 'static value(1000)');
        spConfig.setDefinition('Status__c', 'static value(Scheduled)');
        Scheduled_Payment__c[] spRecs = TestDataFactory.getScheduledPaymentObjects(spConfig, false);
        spRecs[0].Account__c = accRecs[1].Id;
        spRecs[0].Sent_to_Bank_Date__c = Datetime.now();
        spRecs = TestDataFactory.getScheduledPaymentObjects(spConfig, true);

        Object results = BankAccountsController.getUsedBankAccounts(accRecs[0].Id);
    }

    public static testMethod void testRemoveBankAccount(){
        Bank_Account__c[] bankRecs = TestDataFactory.getBankAccountObjects(1);
        BankAccountsController.removeBankAccount(bankRecs[0].Id);
    }
}