force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Bank Account Number</description>
    <inlineHelpText>May have spaces or dashes to group the numbers</inlineHelpText>
    <label>Account #</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank #</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Transit__c.field-meta.xml
<CustomField>
    <fullName>Transit__c</fullName>
    <description>The transaction routing number of the
payor/payee’s financial institution</description>
    <label>Transit #</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_File__c/EFT_File__c.object-meta.xml
<CustomObject>
    <description>Stores information about generated EFT Files that are sent to the bank.</description>
    <label>EFT File</label>
    <nameField>
        <displayFormat>EFT-{0000}</displayFormat>
        <label>EFTFile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EFT Files</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EFT_File__c/fields/File_Number__c.field-meta.xml
<CustomField>
    <fullName>File_Number__c</fullName>
    <formula>RIGHT(Name, 4)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>File Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EFT_File__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EFT_File__c/fields/Transaction_Count__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Count__c</fullName>
    <label>Transaction Count</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that payment should be sent to (will default to Opportunity Account if not set)</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Can_Send_to_Bank__c.field-meta.xml
<CustomField>
    <fullName>Can_Send_to_Bank__c</fullName>
    <description>Does the current user have the permission to send this to the bank?</description>
    <formula>AND(
				$Permission.Can_Process_Scheduled_Payments,
    OR(
				    $User.Id &lt;&gt; Verified_By__c,
			    	$Permission.EFT_Permission
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Can Send to Bank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Bank_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Current_Bank_Account_Id__c</fullName>
    <description>The Id of the bank account that would be used if the payment was processed</description>
    <formula>IF(
    ISBLANK(Sent_to_Bank_Account__c),
    IF(
        Use_Primary_Bank_Account__c,
        IF(
            OR(ISBLANK(Account__c), ISBLANK(Account__r.Primary_Bank_Account__c)),
            IF(
                ISBLANK(Opportunity__r.Account.Primary_Bank_Account__c),
                NULL,
                Opportunity__r.Account.Primary_Bank_Account__c
            ),
            Account__r.Primary_Bank_Account__c
        ),
        IF(
            ISBLANK(Bank_Account__c),
            NULL,
            Bank_Account__c
        )
    ),
    Sent_to_Bank_Account__c
)</formula>
    <label>Current Bank Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Bank_Account_URL__c.field-meta.xml
<CustomField>
    <fullName>Current_Bank_Account_URL__c</fullName>
    <formula>&#39;/&#39; +
IF(
				ISBLANK(Current_Bank_Account_Id__c),
				IF(
								ISBLANK(Account__c),
								Opportunity__r.AccountId,
								Account__c
				),
				Current_Bank_Account_Id__c
)</formula>
    <label>Current Bank Account URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/EFT_File__c.field-meta.xml
<CustomField>
    <fullName>EFT_File__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EFT File</label>
    <referenceTo>EFT_File__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/File_Number__c.field-meta.xml
<CustomField>
    <fullName>File_Number__c</fullName>
    <formula>EFT_File__r.File_Number__c</formula>
    <label>File Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bank account EFT was actually sent to</description>
    <label>Sent to Bank Account</label>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments (Sent to Bank Account)</relationshipLabel>
    <relationshipName>Sent_Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_By__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User that generated the Banking Sheet this Payment was included in.</description>
    <label>Sent to Bank By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_Date__c</fullName>
    <description>Date and Time this payment was included in a banking sheet</description>
    <label>Sent to Bank Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&#39;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Transaction_Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Reference_Number__c</fullName>
    <description>Reference number to match EFT to Scheduled Payments (Date Sent + Random Digits)</description>
    <label>Transaction Reference Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EFTFile.cls
/**
 * @File Name          : EFTFile.cls
 * @Description        : 
 * @Author             : Seth Boyd
 * @Group              : 
 * @Last Modified By   : Seth Boyd
 * @Last Modified On   : 5/11/2019, 11:03:01 AM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    4/22/2019, 1:08:28 PM   Seth Boyd     Initial Version
**/
public with sharing class EFTFile {
    private Id[] spIds;
    private Scheduled_Payment__c[] spList;
    private Map<Id, Bank_Account__c> bankAccountList;
    private Decimal amountTotal = 0;
    private Integer transactionCount = 0;
    private Date dueDate;

    public EFTFile(Id[] spIds) {
        this.dueDate = DateUtil.today();
        this.spIds = spIds;
    }

    public EFTFile(Id[] spIds, Date dueDate) {
        this.dueDate = dueDate;
        this.spIds = spIds;
    }

    private void fetchData() {
        // First grab Scheduled Payments with Bank Account Info
        this.spList = [
            Select
                Id, Name, Amount__c, Status__c, Current_Bank_Account_Id__c, Can_Send_to_Bank__c, // Scheduled Payment Fields
                Opportunity__r.AccountId // Opportunity Fields
            FROM Scheduled_Payment__c
            WHERE Id in :this.spIds
            ORDER BY Current_Bank_Account_Id__c
        ];

        // Collect Account Ids
        Set<Id> bankAccountIds = new Set<id>();
        for (Scheduled_Payment__c sp : this.spList) {
            bankAccountIds.add(sp.Current_Bank_Account_Id__c);
        }

        // Fetch Accounts with Bank Account and Contact information mapped by Id for ease of use
        this.bankAccountList = new Map<Id, Bank_Account__c>([
            SELECT Id, Name, Bank__c, Transit__c, Account__c, Client__r.Name
            FROM Bank_Account__c
            WHERE Id in :bankAccountIds
            ORDER BY Id
        ]);
    }

    public class GroupedPayments {
        public Decimal total {public get; private set;}
        public Scheduled_Payment__c[] spList;
        public String referenceNumber;
        public Bank_Account__c bankAccount;

        public GroupedPayments(Bank_Account__c bankAccount) {
            this.total = 0;
            this.spList = new Scheduled_Payment__c[]{};
            this.bankAccount = bankAccount;
            Blob blobKey = crypto.generateAesKey(128);
            String key = EncodingUtil.base64encode(blobKey).remove('/');
            //String key = crypto.generateDigest('MD5', Blob.valueOf(bankAccount.Id)).toString();
            this.referenceNumber = DateUtil.now().format('ddMMyy') + '-' + key.substring(0, 11);
        }

        public void addPayment(Scheduled_Payment__c sp) {
            spList.add(sp);
            total += sp.Amount__c;
            sp.Transaction_Reference_Number__c = referenceNumber;
        }
    }

    public String generateFileText() {

        this.fetchData();

        // initilize Exception Collection
        EFTFileException[] errorList = new EFTFileException[]{};

        String eftFileData = '';
        Map<Id, GroupedPayments> groupedPayments = new Map<Id, GroupedPayments>();

        // Loop over Scheduled Payments and create detail lines
        EFTFileDetail eftFileDetail;
        Datetime now = DateUtil.now();
        for (Scheduled_Payment__c sp : this.spList) {
            // Validate User is able to send current payment (has EFT_Permission or was not the validator)
            if (!sp.Can_Send_to_Bank__c) {
                errorList.add(new EFTFileException(sp.Id, 'Can_Send_to_Bank__c', 'You are not able to send payments that you verified.'));
            }


            // Validate that Status is correctly set
            /*
            if (sp.Status__c != 'Scheduled') {
                errorList.add(new EFTFileException(sp.Id, 'Status__c', 'Scheduled Payment Status must by \'Scheduled\''));
            }
            */


            // Generate line text
            try {
                if (String.isBlank(sp.Current_Bank_Account_Id__c)) {
                    system.debug(sp.Current_Bank_Account_Id__c);
                    throw new EFTFileException(sp.Id, 'Current_Bank_Account_URL__c', 'Scheduled Payment does not have a Bank Account set');
                }
                if (sp.Amount__c <= 0) {
                    throw new EFTFileException(sp.Id, 'Amount__c', 'Scheduled Payment amount must be greater than $0');
                }
                GroupedPayments gp;
                if (groupedPayments.containsKey(sp.Current_Bank_Account_Id__c)) {
                    gp = groupedPayments.get(sp.Current_Bank_Account_Id__c);
                } else {
                    Id baId = sp.Current_Bank_Account_Id__c;
                    Bank_Account__c ba = this.bankAccountList.get(baId);
                    gp = new GroupedPayments(ba);
                    groupedPayments.put(sp.Current_Bank_Account_Id__c, gp);
                }
                sp.Bank_Account__c = sp.Current_Bank_Account_Id__c;
                gp.addPayment(sp);
                //eftFileDetail = new eftFileDetail(this.bankAccountList.get(sp.Current_Bank_Account_Id__c), this.dueDate, sp);
                //eftFileData += eftFileDetail.getFileDetailAsString() + '\r\n';
            } catch (EFTFileException e) {
                // Catch exception and set Scheduled Payment Id
                e.id = sp.Id;
                errorList.add(e);
                //throw e;
            }

            // Update status and trackers
            //this.amountTotal += sp.Amount__c;
            //this.transactionCount += 1;
            sp.Status__c = 'Sent to Bank';
            sp.Sent_to_Bank_Account__c = sp.Current_Bank_Account_Id__c;
            sp.Sent_to_Bank_Date__c = now;
            sp.Sent_to_Bank_By__c = UserInfo.getUserId();
        }

        // Generate Transaction Lines from Grouped Payments
        for (GroupedPayments gp : groupedPayments.values()) {

            try {
                eftFileDetail = new eftFileDetail(gp.bankAccount, this.dueDate, gp.total, gp.referenceNumber);
                eftFileData += eftFileDetail.getFileDetailAsString() + '\r\n';
            } catch (EFTFileException e) {
                errorList.add(e);
                //throw e;
            }
            this.amountTotal += gp.total;
            this.transactionCount += 1;
        }

        // Generate file footer
        EFTFileTrailer eftFileTrailer = new EFTFileTrailer(this.transactionCount, this.amountTotal);
        try {
            eftFileData += eftFileTrailer.getFileTrailerAsString() + '\r\n';
        } catch (EFTFileException e) {
            errorList.add(e);
        }

        if (errorList.isEmpty() == false) {
            System.debug(errorList);
            throw new EFTFileErrorListException(errorList);
        } else {
            // Generate file header
            // Do this last so any exceptions can show up before we create an EFT_File__c object
            EFT_File__c eftFileObj = getEFTFileObj(this.amountTotal, this.transactionCount);
            EFTFileHeader eftFileHeader = new EFTFileHeader(this.dueDate, eftFileObj.File_Number__c);
            try {
                eftFileData = eftFileHeader.getFileHeaderAsString() + '\r\n' + eftFileData; // Prepend header 
                for (Scheduled_Payment__c sp : spList) {
                    sp.EFT_File__c = eftFileObj.Id;
                }
            } catch (EFTFileException e) {
                errorList.add(e);
                throw new EFTFileErrorListException(errorList);
            }
        }

        // update Scheduled Payments' status
        update spList;

        // Need to rework this to utilize the EFT_File__c object now...
        return eftFileData;
    }

    private EFT_File__c getEFTFileObj(Decimal amount, Integer count) {
        EFT_File__c eftFileObj = new EFT_File__c(Total_Amount__c=this.amountTotal, Transaction_Count__c=this.transactionCount);
        insert eftFileObj;
        eftFileObj = [Select Id, Name, File_Number__c From EFT_File__c Where Id = :eftFileObj.Id];
        if (eftFileObj.File_Number__c == '0000') {
            // If File Number is 0000 it is invalid, so we must delete that object and create another so the Auto-number increments
            delete eftFileObj;
            return getEFTFileObj(amount, count);
        }
        return eftFileObj;
    }

    private void attachFile(String fileText, EFT_File__c eftFileObj) {
        Attachment att = new Attachment();
        att.Body = Blob.valueOf(fileText);
        att.Name = 'Banking_Sheet_' + eftFileObj.File_Number__c + '_' + DateUtil.now().format('yyyy_MM_dd_hh_mm_ss') + '.txt';
        att.parentId = eftFileObj.Id;
        insert att;
        String fileURL = URL.getFileFieldURL(att.Id, 'Attachment');
    }
}