force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Bank Account Number</description>
    <inlineHelpText>May have spaces or dashes to group the numbers</inlineHelpText>
    <label>Account #</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <label>Bank #</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Accounts</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Transit__c.field-meta.xml
<CustomField>
    <fullName>Transit__c</fullName>
    <description>The transaction routing number of the
payor/payee’s financial institution</description>
    <label>Transit #</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that payment should be sent to (will default to Opportunity Account if not set)</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_Id__c</fullName>
    <formula>IF(
				ISBLANK(Account__c),
				CASESAFEID(Opportunity__r.AccountId),
				CASESAFEID(Account__c)
)</formula>
    <label>Current Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_Name__c</fullName>
    <formula>IF(
    ISBLANK(Account__c),
    Opportunity__r.Account.Name,
    Account__r.Name
)</formula>
    <label>Current Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Bank_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Current_Bank_Account_Id__c</fullName>
    <description>The Id of the bank account that would be used if the payment was processed</description>
    <formula>IF(
    ISBLANK(Sent_to_Bank_Account__c),
    IF(
        Use_Primary_Bank_Account__c,
        IF(
            OR(ISBLANK(Account__c), ISBLANK(Account__r.Primary_Bank_Account__c)),
            IF(
                ISBLANK(Opportunity__r.Account.Primary_Bank_Account__c),
                NULL,
                Opportunity__r.Account.Primary_Bank_Account__c
            ),
            Account__r.Primary_Bank_Account__c
        ),
        IF(
            ISBLANK(Bank_Account__c),
            NULL,
            Bank_Account__c
        )
    ),
    Sent_to_Bank_Account__c
)</formula>
    <label>Current Bank Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Bank_Account_Name__c</fullName>
    <description>Gets the bank account name that would currently be used if the payment was processed.</description>
    <formula>IF(
    Send_Cheque__c,
    &#39;SEND CHEQUE to &#39; + IF(ISBLANK(Account__c), Opportunity__r.Account.Name, Account__r.Name),
    IF(
        ISBLANK(Sent_to_Bank_Account__c),
        IF(
            Use_Primary_Bank_Account__c,
            IF(
                OR(ISBLANK(Account__c), Account__c = Opportunity__r.AccountId),
                IF(
                    ISBLANK(Opportunity__r.Account.Primary_Bank_Account__c),
                    &#39;**NONE SELECTED**&#39;,
                    Opportunity__r.Account.Primary_Bank_Account__r.Name
                ),
                IF(
                    ISBLANK(Account__r.Primary_Bank_Account__c),
                    &#39;**NONE SELECTED**&#39;,
                    Account__r.Name + &#39; - &#39; + Account__r.Primary_Bank_Account__r.Name
                )
            ),
            IF(
                ISBLANK(Bank_Account__c),
                &#39;**NONE SELECTED**&#39;,
                IF(
                    NOT(Bank_Account__r.Client__c = Opportunity__r.AccountId),
                    Bank_Account__r.Client__r.Name + &#39; - &#39; + Bank_Account__r.Name,
                    Bank_Account__r.Name
                )
            )
        ),
        Sent_to_Bank_Account__r.Name
    )
)</formula>
    <label>Current Bank Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Send_Cheque__c.field-meta.xml
<CustomField>
    <fullName>Send_Cheque__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send a Cheque instead of an EFT</description>
    <label>Send Cheque</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <formula>NOT(ISBLANK( Sent_to_Bank_Date__c ))</formula>
    <label>Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BankAccountsController.cls
/**
*    @description : Method to fetch bank accounts
**/
public with sharing class BankAccountsController {
	
	/**
	* @description Method to fetch bank accounts
	* @param accountId Id of the account record
	* @return Map<String, Object> list of bank accounts
	**/
	@AuraEnabled
	public static Map<String, Object> getBankAccounts(Id accountId, String fieldSetName){
		Map<String,Object> objectsMap = new Map<String,Object>();
		List<String> fieldsList = SchemaHelper.getFieldsFromFieldsSet(Bank_Account__c.sObjectType.getDescribe().getName(),fieldSetName);
		// add datatable fields
		objectsMap.put('columns',SchemaHelper.getDataTableFields(Bank_Account__c.sObjectType.getDescribe().getName(),fieldsList));
		// add records
		String soqlQuery = 'SELECT Id, '+String.join(fieldsList,',')+' FROM '+Bank_Account__c.sObjectType.getDescribe().getName()+' WHERE '+Bank_Account__c.Client__c.getDescribe().getName()+' = \''+accountId+'\' ORDER BY '+Bank_Account__c.CreatedDate.getDescribe().getName()+' DESC LIMIT 15000';
		objectsMap.put('records',(List<Bank_Account__c>)Database.query(soqlQuery));
		return objectsMap;
	}
	
	/**
	* @description Method to delete bank account
	* @param bankAccountId Id of the bank account record
	* @return
	**/
	@AuraEnabled
	public static void removeBankAccount(Id bankAccountId){
		Bank_Account__c ba = [Select Id From Bank_Account__c Where Id = :bankAccountId];
		delete ba;
	}

    Class BankAccountAggregateResult {
        @AuraEnabled public Integer sentCount;
        @AuraEnabled public Decimal sentAmount;
        @AuraEnabled public Integer scheduledCount;
        @AuraEnabled public Decimal scheduledAmount;
        @AuraEnabled public String name;
        @AuraEnabled public Id bankAccountId;
        @AuraEnabled public Bank_Account__c bankAccount;
        @AuraEnabled public String accountName;
        @AuraEnabled public Id accountId;

        public BankAccountAggregateResult() {
            this.sentCount = 0;
            this.sentAmount = 0;
            this.scheduledCount = 0;
            this.scheduledAmount = 0;
        }
    }

    @AuraEnabled(cacheable=true)
    public static Object getUsedBankAccounts(Id accountId){
        /*
        Aggregate query
        Group by Bank Account
        Bank Account Info
        Sent Total
        Scheduled Total
        */
        Scheduled_Payment__c[] spList = [
            SELECT
                //COUNT(Id) paymentCount,
                Id,
                Send_Cheque__c,
                Sent__c,
                Current_Account_Id__c,
                Current_Account_Name__c,
                Current_Bank_Account_Id__c,
                Current_Bank_Account_Name__c,
                Amount__c
                //SUM(Amount__c) totalAmount
            FROM Scheduled_Payment__c
            WHERE Opportunity__r.AccountId = :accountId
            // GROUP BY
            //    Sent__c, Send_Cheque__c,
            //    Current_Account_Id__c, Current_Account_Name__c,
            //    Current_Bank_Account_Id__c, Current_Bank_Account_Name__c
            ORDER BY Current_Bank_Account_Name__c ASC
        ];

        // Get Bank Account Ids to fetch and aggregate payment numbers
        Map<String, BankAccountAggregateResult> results = new Map<String, BankAccountAggregateResult>();
        BankAccountAggregateResult currResult;
        Set<Id> bankAccountIds = new Set<Id>();

        for (Scheduled_Payment__c sp : spList) {
            if (results.containsKey(sp.Current_Bank_Account_Name__c)) {
                currResult = results.get(sp.Current_Bank_Account_Name__c);
            } else {
                currResult = new BankAccountAggregateResult();
                currResult.accountId = (Id)sp.Current_Account_Id__c;
                currResult.accountName = (String)sp.Current_Account_Name__c;
                currResult.name = (String)sp.Current_Bank_Account_Name__c;
                if (sp.Send_Cheque__c == false) {
                    currResult.bankAccountId = (Id)sp.Current_Bank_Account_Id__c;
                    bankAccountIds.add((Id)sp.get('Current_Bank_Account_Id__c'));
                }
                results.put(sp.Current_Bank_Account_Name__c, currResult);
            }
            if (sp.Sent__c == false) {
                currResult.scheduledCount += 1;
                currResult.scheduledAmount += sp.Amount__c;
            } else {
                currResult.sentCount += 1;
                currResult.sentAmount += sp.Amount__c;
            }
        }

        // Get Bank Accounts
        Map<Id, Bank_Account__c> bankAccountMap = new Map<Id, Bank_Account__c>([
            SELECT
                Id,
                Name,
                Account__c,
                Bank__c,
                Bank_Name__c,
                Transit__c
            FROM Bank_Account__c
            WHERE Id in :bankAccountIds
        ]);

        // attach bank accounts to aggregates
        for (BankAccountAggregateResult result : results.values()) {
            if (result.bankAccountId != null) {
                if (bankAccountMap.containsKey(result.bankAccountId)) {
                    result.bankAccount = bankAccountMap.get(result.bankAccountId);
                }
            }
        }

        return results.values();
    }
}