force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lump-Sum Admin Fee</fullName>
            </value>
            <value>
                <fullName>Lump-Sum Amount Paid to Borrower</fullName>
            </value>
            <value>
                <fullName>Facility Drawdown</fullName>
                <default>true</default>
                <label>Facility Drawdown</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CSL_FacilityDrawdownCtlr.cls
public with sharing class CSL_FacilityDrawdownCtlr {
    /**
     * Parent Opportunity ID
     */
    public String oppId {get; private set;}
    
    public Drawdown__c drawdown {get; private set;}

    public List<Drawdown__c> drawdowns {get; set;}

    /**
     * Constructor
     */
    public CSL_FacilityDrawdownCtlr(ApexPages.StandardController controller) {
        init();    

        drawdown = new Drawdown__c();
    }

    /**
     * Initialize page
     */
    public void init() {

        oppId = ApexPages.currentPage().getParameters().get('oppId');

        // load the the list of drawdowns
        if (oppId != null){
            Id thisOppId = this.oppId;
            drawdowns = (List<Drawdown__c>)database.query(
                'SELECT Id, Name, Amount__c, Date__c, Opportunity__c, Payment_Method__c, Reference_Notes__c, Type__c   '+
                'FROM Drawdown__c '+
                'WHERE Opportunity__c = :thisOppId '+
                'ORDER BY Date__c DESC ');

        }

    }

    public PageReference createNew() {
        
        try {
            drawdown.Opportunity__c = oppId;

            insert(drawdown);
        } catch(System.DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        
        // go back to the same page
        return getCurrentPage();
    }

    public PageReference deleteDrawdown() {

        String pId = ApexPages.currentPage().getParameters().get('pId');
        System.debug('delete pid = '+pId);

        List<Drawdown__c> delDrawdown = [SELECT Id FROM Drawdown__c WHERE Id=:pid LIMIT 1];
        if (delDrawdown.size() > 0) {
            try {
                delete delDrawdown[0];
            } catch (DMLException e) {
                ApexPages.addMessages(e);
            }
        }


        // go back to the same page
        return getCurrentPage();
    }

    public PageReference savedrawdownList() {

        try {
            
            if (drawdowns.size() > 0) {
                System.debug('here = ' + drawdowns);
                update drawdowns;
            } 

        } catch (DMLException e) {
            ApexPages.addMessages(e);
            return null;
        }
        

        return getCurrentPage();
    }
 

    public PageReference getCurrentPage() {
        PageReference pg = new PageReference('/apex/CSL_FacilityDrawdown?oppId=' + oppId);
        pg.setRedirect(true);
        
        return pg;
    }
}