force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/CHQ__c.field-meta.xml
<CustomField>
    <fullName>CHQ__c</fullName>
    <label>CHQ #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Scheduled_Payment__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Payment</label>
    <referenceTo>Scheduled_Payment__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Admin_Fee_Roll_up__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee_Roll_up__c</fullName>
    <label>Admin Fee Roll-up</label>
    <summarizedField>Drawdown__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>equals</operation>
        <value>Admin Fee, Assessment Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/Opportunity_Service_Provider__c.object-meta.xml
<CustomObject>
    <label>Opportunity Service Provider</label>
    <nameField>
        <displayFormat>OSP-{00000}</displayFormat>
        <label>OSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Service Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Payment_Factor__c.field-meta.xml
<CustomField>
    <fullName>Payment_Factor__c</fullName>
    <formula>IF(ISPICKVAL(Opportunity__r.Type_of_Loan__c, &#39;Treatment Loan 2&#39;), 0.5, 1)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Factor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Calculated_Drawdown_Date__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Drawdown_Date__c</fullName>
    <formula>IF(
				ISBLANK(First_Sent_to_Bank_Date__c),
				DATEVALUE(Sent_to_Bank_Date__c),
				DATEVALUE(First_Sent_to_Bank_Date__c)
)</formula>
    <label>Calculated Drawdown Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Calculated_Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Reference_Notes__c</fullName>
    <description>Calculates Reference Notes for Drawdown created from this payment</description>
    <formula>IF(
				Has_Been_Rejected__c,
				&#39;Payment Re-processed&#39;,
				CASE(TEXT(Payment_Type__c),
									&#39;Assessment&#39;,	&#39;Payment to Assessment Provider&#39;,
									&#39;Treatment&#39;, &#39;Payment to Treatment - Service Provider&#39;,
									&#39;Payment to Other Lender&#39;, &#39;Payment to other lender&#39;,
									IF(
												OR(
																ISBLANK(Account__c),
																Opportunity__r.AccountId = Account__c
												),
												IF(
																Bank_Account__r.Third_Party__c = TRUE,
																&#39;Payment to Third-Party&#39;,
																&#39;Payment to Client&#39;
												),
												CASE(Account__r.RecordType.Name,
												 			&#39;Client&#39;, &#39;Payment to Third-Party&#39;,
																&#39;Law Firm&#39;, &#39;Payment to Lawyer&#39;,
																&#39;General Business&#39;, CASE(TEXT(Account__r.Account_Type__c),
																				&#39;Treatment Provider Firm&#39;, &#39;Payment to Treatment - Service Provider&#39;,
                    &#39;Assessment Funding&#39;, &#39;Payment to Assessment Provider&#39;,
                    &#39;Litigation Lender&#39;, &#39;Payment to other lender&#39;,
                    &#39;Payment to Third-Party&#39;
                ),
								    				&#39;Payment to Third-Party&#39;
												)
								)
				)
)</formula>
    <label>Calculated Reference Notes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Cheque_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_Number__c</fullName>
    <label>Cheque Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Current_Account_Id__c</fullName>
    <formula>IF(
				ISBLANK(Account__c),
				CASESAFEID(Opportunity__r.AccountId),
				CASESAFEID(Account__c)
)</formula>
    <label>Current Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Drawdown__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawdown</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Drawdown__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Drawdown_Date__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Date__c</fullName>
    <formula>Drawdown__r.Date__c</formula>
    <label>Drawdown Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/EFT_Number__c.field-meta.xml
<CustomField>
    <fullName>EFT_Number__c</fullName>
    <label>EFT Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Has_Been_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Has_Been_Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Been Rejected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lump-Sum</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc</fullName>
            </value>
            <value>
                <fullName>Scheduled Facility</fullName>
            </value>
            <value>
                <fullName>Treatment</fullName>
            </value>
            <value>
                <fullName>Payment to Other Lender</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
                <isActive>false</isActive>
                <label>Loan Payout</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Send_Cheque__c.field-meta.xml
<CustomField>
    <fullName>Send_Cheque__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Send a Cheque instead of an EFT</description>
    <label>Send Cheque</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScheduledPaymentHelper.cls
/**
 * @File Name          : ScheduledPaymentHelper.cls
 * @Description        : 
 * @Author             : Seth Boyd
 * @Group              : 
 * @Last Modified By   : Seth Boyd
 * @Last Modified On   : 5/13/2019, 11:40:43 AM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    4/25/2019, 10:05:30 AM   Seth Boyd     Initial Version

**/
public with sharing class ScheduledPaymentHelper {
    private static Drawdown__c generateDrawdown(Scheduled_Payment__c sp) {
        Drawdown__c drawdown = new Drawdown__c();
        drawdown.Scheduled_Payment__c = sp.Id;
        drawdown.Amount__c = sp.Amount__c;
        drawdown.Date__c = sp.Calculated_Drawdown_Date__c;
        drawdown.Opportunity__c = sp.Opportunity__c;
        if (sp.Send_Cheque__c) {
            drawdown.Payment_Method__c = 'Cheque';
            drawdown.CHQ__c = sp.Cheque_Number__c;
        } else {
            drawdown.Payment_Method__c = 'e-Transfer';
            drawdown.EFT__c = sp.EFT_Number__c;
        }

        if (sp.Opportunity_Service_Provider__c != null) {
            drawdown.Opportunity_Service_Provider__c = sp.Opportunity_Service_Provider__c;
            drawdown.Amount__c = (sp.Amount__c / sp.Opportunity_Service_Provider__r.Payment_Factor__c) * 100.0;
        }

        drawdown.Reference_Notes__c = sp.Calculated_Reference_Notes__c;
        /*
        if (sp.Has_Been_Rejected__c) {
            drawdown.Reference_Notes__c = 'Payment Re-processed';
        } else {
            switch on sp.Payment_Type__c {
                when 'Lump-Sum', 'Ad-Hoc', 'Scheduled Facility' {
                    // Check if account is opportunity's account
                    // TODO - Should I check if it is a law firm or have some other advanced way to figure this out?
                    if (sp.Opportunity__r.AccountId == sp.Current_Account_Id__c) {
                        if ()
                        drawdown.Reference_Notes__c = 'Payment to Client';
                    } else {
                        drawdown.Reference_Notes__c = 'Payment to Third-Party';
                    }
                }
                when 'Assessment' {
                    drawdown.Reference_Notes__c = 'Payment to Assessment Provider';
                }
                when 'Treatment' {
                    drawdown.Reference_Notes__c = 'Payment to Treatment - Service Provider';
                }
                when 'Payment to Other Lender' {
                    drawdown.Reference_Notes__c = 'Payment to other lender';
                }
                when else {
                    // Throw not yet implemented exception
                    throw new NotYetImplementedException('Code has not been written to generate drawdowns for this payment type: ' + sp.Payment_Type__c);
                }
            }
        }
        */


        return drawdown;
    }

    private static Map<Id,Drawdown__c> manageAdminDrawdowns(Map<Id,Drawdown__c> adminDrawdowns, Scheduled_Payment__c sp) {
        System.debug(adminDrawdowns);
        System.debug(sp);
        if (!(
            adminDrawdowns.containsKey(sp.Opportunity__c)
            || (sp.Opportunity__r.Admin_Fee_Roll_up__c > 0
                && sp.Opportunity__r.Admin_Fee__c > 0)))
            {
            System.debug('Creating new Admin Fee Drawdown');
            // Admin Fee Drawdown needs to be created
            String reference_note = 'Admin Fee';
            if (sp.Payment_Type__c == 'Assessment') {
                reference_note = 'Assessment Fee';
            }
            if (sp.Opportunity__r.Admin_Fee__c == 0) {
                reference_note = 'Waived Fee';
            }
            adminDrawdowns.put(
                sp.Opportunity__c,
                new Drawdown__c(
                    Amount__c = sp.Opportunity__r.Admin_Fee__c,
                    Date__c = sp.Sent_to_Bank_Date__c.date(),
                    Opportunity__c = sp.Opportunity__c,
                    Payment_Method__c = 'Admin Fee',
                    Reference_Notes__c = reference_note
                )
            );
            sp.Triggered_Admin_Fee__c = true;
            sp.Triggered_Admin_Fee_Amount__c = sp.Opportunity__r.Admin_Fee__c;
        } else if (adminDrawdowns.containsKey(sp.Opportunity__c)) {
            Drawdown__c adminDrawdown = adminDrawdowns.get(sp.Opportunity__c);
            if (adminDrawdown.Date__c > sp.Sent_to_Bank_Date__c.date()) {
                adminDrawdown.Date__c = sp.Sent_to_Bank_Date__c.date();
            }
        }
        System.debug(adminDrawdowns);
        return adminDrawdowns;
    }

    /*
    private static Map<Id, Opportunity> manageOpportunityFields(Map<Id, Opportunity> oppMap, Map<Id, Drawdown__c> adminDrawdowns, Scheduled_Payment__c sp) {
        System.debug(adminDrawdowns);
        System.debug(sp);
        if (oppMap.containsKey(sp.Opportunity__c)) {
            Opportunity opp = oppMap.get(sp.Opportunity__c);
            if (( opp.First_Drawdown_Amount__c == null || opp.First_Drawdown_Amount__c == 0 ) 
                    && ( opp.Amount_Paid_to_Borrower__c == null || opp.Amount_Paid_to_Borrower__c == 0 )) {
                opp.Amount_Paid_to_Borrower__c = sp.Amount__c;
                opp.First_Drawdown_Amount__c = sp.Amount__c;
                if (adminDrawdowns.containsKey(opp.Id)) {
                    opp.First_Drawdown_Amount__c += adminDrawdowns.get(opp.Id).Amount__c;
                } else {
                    opp.First_Drawdown_Amount__c += opp.Admin_Fee__c;
                }
            }
        }
        return oppMap;
    }
    */

    private static Scheduled_Payment__c[] generateDrawdowns(Scheduled_Payment__c[] spList){
        // Method to actually create drawdowns

        if (spList.isEmpty()) {
            // Don't bother processing an empty list
            return spList;
        }

        // Create drawdowns from Scheduled Payments
        Set<Id> oppIds = new Set<Id>();
        Drawdown__c[] drawdownList = new Drawdown__c[]{};
        Map<Id, Drawdown__c> adminDrawdownMap = new Map<Id, Drawdown__c>();
        Map<Id, Scheduled_Payment__c> spMap = new Map<Id, Scheduled_Payment__c>();
        for (Scheduled_Payment__c sp : spList) {
            spMap.put(sp.Id, sp);
        }
        for (Scheduled_Payment__c sp : spMap.values()) {
            if (sp.Sent_to_Bank_Date__c == null) {
                sp.Sent_to_Bank_Date__c = DateUtil.now();
                sp.Sent_to_Bank_By__c = UserInfo.getUserId();
            }
            if (sp.First_Sent_to_Bank_Date__c == null) {
                sp.First_Sent_to_Bank_Date__c = sp.Sent_to_Bank_Date__c;
            }

            oppIds.add(sp.Opportunity__c);
            Drawdown__c drawdown = generateDrawdown(sp);
            drawdownList.add(drawdown);
            adminDrawdownMap = manageAdminDrawdowns(adminDrawdownMap, sp);
            sp.Status__c = 'Drawdown Created';
            sp.Drawdown_Created__c = true;
        }
        Map<Id, Opportunity> oppMap = New Map<Id, Opportunity>([
            Select Id, Funding_Details_Status__c, Amount_Paid_to_Borrower__c, First_Drawdown_Amount__c
            From Opportunity
            Where Id in :oppIds
        ]);
        /*
        // Blocked out for now until I can talk with Larry more about the requirements
        for (Scheduled_Payment__c sp : spList) {
            manageOpportunityFields(oppMap, adminDrawdownMap, sp);
        }
        */
        setOpportunitiesFundingStatus(oppMap, 'Populate PPSA');

        // Combine Scheduled Payment Drawdowns and any created Admin Fee Drawdowns
        drawDownList.addAll(adminDrawdownMap.values());
        System.debug(drawdownList);

        insert drawdownList;
        /*
        for (Drawdown__c dd : drawdownList) {
            if (dd.Scheduled_Payment__c != null) {
                if (spMap.containsKey(dd.Scheduled_Payment__c)) {
                    spMap.get(dd.Scheduled_Payment__c).Drawdown__c = dd.Id;
                }
            }
        }
        //update spMap.values();
        //update oppMap.values();
        */

        DrawdownTriggerHandler.mergeAdminFees(oppIds);

        return spList;
    }

	@InvocableMethod(label='Generate Drawdowns' description='Create drawdowns from scheduled payments')
    public static void invocableGenerateDrawdowns(Id[] oppIds){
        Scheduled_Payment__c[] spList = [
            Select
                Id,
                Opportunity__c,
                Opportunity__r.Admin_Fee__c,
                Opportunity__r.Admin_Fee_Roll_up__c,
                Opportunity__r.AccountId,
                Opportunity_Service_Provider__c,
                Current_Account_Id__c,
                Payment_Type__c,
                Amount__c,
                Send_Cheque__c,
                Sent_to_Bank_Date__c,
                First_Sent_to_Bank_Date__c,
                Calculated_Drawdown_Date__c,
                Has_Been_Rejected__c,
                Sent_to_Bank_By__c,
                Cheque_Number__c,
                EFT_Number__c,
                Calculated_Reference_Notes__c
            From
                Scheduled_Payment__c
            Where
                Opportunity__c in :oppIds
                AND Status__c = 'Sent to Bank'
                AND Drawdown_Created__c = false
        ];
        generateDrawdowns(spList);
    }

    @AuraEnabled
    public static Scheduled_Payment__c[] generateDrawdowns(Id[] spIds){
        try {
            Scheduled_Payment__c[] spList = [
                Select
                    Id,
                    Opportunity__c,
                    Opportunity__r.Admin_Fee__c,
                    Opportunity__r.Admin_Fee_Roll_up__c,
                    Opportunity__r.AccountId,
                    Current_Account_Id__c,
                    Payment_Type__c,
                    Amount__c,
                    Send_Cheque__c,
                    Sent_to_Bank_Date__c,
                    First_Sent_to_Bank_Date__c,
                    Calculated_Drawdown_Date__c,
                    Has_Been_Rejected__c,
                    Sent_to_Bank_By__c,
                    Cheque_Number__c,
                    Opportunity_Service_Provider__c,
                	Opportunity_Service_Provider__r.Payment_Factor__c,
                    EFT_Number__c,
                    Calculated_Reference_Notes__c
                From
                    Scheduled_Payment__c
                Where
                    Id in :spIds
                    AND Drawdown_Created__c = false // Filter out Scheduled Payments that have already had their drawdowns created
            ];

            return generateDrawdowns(spList);
        } catch (Exception e){
            System.debug(e);
            System.debug(e.getMessage());
            throw new AuraHandledException('Error: '+e.getMessage());
        }
    }

    private static void setOpportunitiesFundingStatus(Map<Id, Opportunity> oppMap, String status) {
        for (Opportunity opp : oppMap.values()) {
            opp.Funding_Details_Status__c = status;
            opp.StageName = 'Closed With Loan';
            opp.Stage_Status__c = 'Active';
        }
    }

    @AuraEnabled(cacheable=false)
    public static Bank_Account__c[] getBankAccountOptions(Id accId) {
        return [Select Id, Name, Account__c, Is_Primary_Account__c From Bank_Account__c Where Client__c = :accId Order By Is_Primary_Account__c DESC, Name ASC];
    }

    @AuraEnabled
    public static void markPaymentValidated(Id spId){
        Scheduled_Payment__c sp = new Scheduled_Payment__c(
            Id=spId,
            Status__c='Approved to Send',
            Verified_By__c = UserInfo.getUserId(),
            Verified_Date__c = DateUtil.now()
        );
        update sp;
    }

    @AuraEnabled
    public static void deletePayment(Id spId, Boolean force){
        try{
            if (force == true) {
                delete new Scheduled_Payment__c(Id=spId);
            }  else {
                Scheduled_Payment__c sp = [
                    Select 
                        Id,
                        Status__c,
                        Current_Opportunity_Schedule_Version__c,
                        Drawdown_Created__c,
                        Opportunity__r.Payment_Schedule__c
                    From Scheduled_Payment__c Where Id = : spId
                ];
                String[] errorMessages = new String[]{};
                if (Constants.PAYMENT_SCHEDULE_IN_PROCESS_STATUSES.contains(sp.Status__c)) {
                    errorMessages.add('Payment is currently being processed');
                }
                if (sp.Current_Opportunity_Schedule_Version__c == true && sp.Opportunity__r.Payment_Schedule__c == 'Yes') {
                    errorMessages.add('Payment is part of of an active payment schedule');
                }
                if (sp.Drawdown_Created__c == true) {
                    errorMessages.add('Payment has already been processed to drawdown');
                }
                if (errorMessages.isEmpty()) {
                    delete sp;
                } else {
                    system.debug(errorMessages);
                    throw new DeleteWarningException(String.join(errorMessages, '\n'));
                }
            }
        }
        catch (DMLException e){
            throw new AuraHandledException('Error:'+e.getDmlMessage(0));
        } catch (DeleteWarningException e){
            AuraHandledException newExc = new AuraHandledException('Warning: '+e.getMessage());
            newExc.setMessage('Warning: '+e.getMessage());
            system.debug(newExc.getMessage());
            throw newExc;
        } catch (Exception e){
            throw new AuraHandledException('Error:'+e.getMessage());
        }
    }

    public class DeleteWarningException extends Exception {}

    @AuraEnabled(cacheable=false)
    public static Date getDrawdownDate(Id spId) {
        return [Select Drawdown_Date__c From Scheduled_Payment__c Where Id = :spId].Drawdown_Date__c;
    }

    /*
    @AuraEnabled
    public static void markPaymentRejected(Id spId, String notes){
        Scheduled_Payment__c sp = new Scheduled_Payment__c(
            Id=spId,
            Status__c='Rejected',
            Verified_By__c = UserInfo.getUserId(),
            Verified_Date__c = DateUtil.now(),
            Hold__c = true,
            Notes__c = notes
        );
        update sp;
    }
    */

    /*
    @AuraEnabled
    public static void resetTestInfo() {
        Set<Id> oppIds = new Set<Id>();
        Scheduled_Payment__c[] sps = [Select Id, Opportunity__c FROM Scheduled_Payment__c Where Status__c != 'Scheduled'];
        for (Scheduled_Payment__c sp : sps) {
            sp.Use_Primary_Bank_Account__c = true;
            sp.Status__c = 'Scheduled';
            oppIds.add(sp.Opportunity__c);
        }
        Drawdown__c[] dds = new Drawdown__c[]{};
        Opportunity[] opps = [Select Id, (Select Id From Drawdowns__r Order By Date__c desc Limit 1) From Opportunity Where Id in :oppIds];
        //for (Drawdown__c dd : dds) {
        //}
        Boolean deleteDrawdowns = true;
        while (deleteDrawdowns) {
            dds = new Drawdown__c[]{};
            for (Opportunity opp : opps) {
                opp.Funding_Details_Status__c = '';
                for (Drawdown__c dd : opp.Drawdowns__r) {
                    dds.add(dd);
                }
            }
            if (!dds.isEmpty()) {
                delete dds;
                opps = [Select Id, (Select Id From Drawdowns__r Order By Date__c desc Limit 1) From Opportunity Where Id in :oppIds];
            } else {
                deleteDrawdowns = false;
            }
        }

        update opps;
        update sps;

        //Opportunity[] opps = [Select Id From Opportunity Where Funding_Details_Status__c != null Limit 200]; for (Opportunity opp : opps) { opp.Funding_Details_Status__c = null; } update opps;
        /*
        Database.executeBatch(
            new BatchUpdateOpportunityFields(
                'Select Funding_Details_Status__c From Opportunity Where Funding_Details_Status__c != null LIMIT 5000',
                'Opportunity',
                'Funding_Details_Status__c',
                ''
            ), 20
        );
    }
    */
}

/*
ScheduledPaymentHelper.resetTestInfo();
System.debug([Select Opportunity__r.Name, Opportunity__r.AccountId From Scheduled_Payment__c Where Id = 'a1W190000032CyqEAE'].Opportunity__r);
Scheduled_Payment__c[] sps = [Select Id FROM Scheduled_Payment__c];
for (Scheduled_Payment__c sp : sps) {
    sp.Use_Primary_Bank_Account__c = true;
}
update sps;

*/