force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/CHQ__c.field-meta.xml
<CustomField>
    <fullName>CHQ__c</fullName>
    <label>CHQ #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Drawdown_Amount__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Amount__c</fullName>
    <formula>IF(OR(ISPICKVAL(Payment_Method__c,&#39;e-Transfer&#39;),ISPICKVAL(Payment_Method__c,&#39;Cheque&#39;)), Total_Amount__c,IF(ISPICKVAL(Payment_Method__c,&#39;Admin Fee&#39;),0,(0-Principal_Repaid__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Drawdown Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_Payout_Date__c</fullName>
    <description>NOTE: Used EXP and LN as the normal exponent function does not handle fractional numbers:  See: https://developer.salesforce.com/forums/?id=906F00000008vDHIAY</description>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF(  ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),Sum_of_Payment_Allocations__c - Amount__c,
IF(Compounding_Interest__c,(Amount_Adjusted_for_Repayments__c*(EXP(LN(1 + (Interest_Rate__c/Compounding_Frequency__c))*   
(Compounding_Frequency__c*Interest_Accrual_Years__c)))),Amount_Adjusted_for_Repayments__c*(1+((Interest_Rate__c/365)* Interest_Accrual_Days__c)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Outstanding Balance as it will be at the Payout Date.  This Accounts for compounding interest or Simple Interest depending on the Loan.  This is set to zero when Drawdown is Payment.   For Payments, negative amounts represent unallocated payment amounts.</inlineHelpText>
    <label>Outstanding Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
    <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Rejection_Notes__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Notes__c</fullName>
    <label>Rejection Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Scheduled_Payment__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Payment</label>
    <referenceTo>Scheduled_Payment__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount_Available_for_Scheduled_Payments__c.field-meta.xml
<CustomField>
    <fullName>Amount_Available_for_Scheduled_Payments__c</fullName>
    <description>Calculates how much of the approved loan amount is available for new scheduled payments (does not consider &quot;Scheduled Facility)</description>
    <formula>Amount
    - IF(Admin_Fee_Roll_up__c - Admin_Fee_Reversed__c &gt; 0, 0, Admin_Fee__c)
    - Drawdown_Total_w_o_payments_and_provider__c 
    - Total_Outstanding_Previous_Loans__c
				- Scheduled_Non_Facility_Treatment_Total__c
				- Total_Service_Providers_Allowance__c
    +Principal_Reversed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount Available for Scheduled Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drawdown_Amount__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Amount__c</fullName>
    <label>Drawdown Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Temp_Payment_Received__c.field-meta.xml
<CustomField>
    <fullName>Temp_Payment_Received__c</fullName>
    <label>Temp Payment Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/Opportunity_Service_Provider__c.object-meta.xml
<CustomObject>
    <label>Opportunity Service Provider</label>
    <nameField>
        <displayFormat>OSP-{00000}</displayFormat>
        <label>OSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Service Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting to Send Schedule</fullName>
                <default>true</default>
                <label>Waiting to Send Schedule</label>
            </value>
            <value>
                <fullName>Schedule Sent</fullName>
            </value>
            <value>
                <fullName>Schedule Signed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Drawdown__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawdown</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Drawdown__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&#39;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DrawdownHelper.cls
/**
*    @description : Helper class for drawdowns
**/
public with sharing class DrawdownHelper {

    @AuraEnabled
    public static Drawdown__c[] getDrawdowns(String fields, String conditions, String extra) {
        if (String.isBlank(fields) || fields == 'all') {
            Map<String, Schema.SObjectField> allFields = Schema.SObjectType.Drawdown__c.fields.getMap();
            List<String> lstFields = new List<String>();
            for (Schema.SObjectField field : allFields.values()) {
                lstFields.add(field.getDescribe().getName());
            }
            
            // Building the query
            fields = String.join(lstFields, ',');
        }
        String strQuery = 'SELECT ' + fields + ' FROM Drawdown__c';

        if (!String.isBlank(conditions)) {
            strQuery += ' WHERE ' + conditions;
        }

        if (!String.isBlank(extra)) {
            strQuery += ' ' + extra;
        }

        //strQuery = String.escapeSingleQuotes(strQuery); // Sanitize Single Quotes

        return Database.query(strQuery);
    }

    //public static List<Scheduled_Payment__c> paymentsToUpdate = new List<Scheduled_Payment__c>();
    //public static List<Scheduled_Payment__c> paymentsToDelete = new List<Scheduled_Payment__c>();
    
    /**
    * @description Method to re-calculate payment schedules
    * @param List<Drawdown__c> drawdownsList
    * @return void
	// Replaced with process and InvocableMethod callout to consolidate work
    public static void updatePaymentScheduleForFacilityLoan(List<Drawdown__c> drawdownsList){
        Set<Id> opportunityIds = new Set<Id>();

        // loop through drawdown list 
        for(Drawdown__c drawdown : drawdownsList){
            if(drawdown.Amount__c != null){
                opportunityIds.add(drawdown.Opportunity__c);
            }
        }
    
        if(!opportunityIds.isEmpty()) adjustPaymentSchedulesForFacilityLoan(opportunityIds);
    }

    /**
    * @description Method to adjust payment schedules
    * @param List<Drawdown__c> drawdownsList
    * @return void
	// Replaced with process and InvocableMethod callout to consolidate work
    public static void adjustPaymentSchedulesForFacilityLoan(Set<Id> opportunityIds){
        Map<Id, Opportunity> opportunitiesMap = new Map<Id, Opportunity>([SELECT Id, Amount_Available_for_Scheduled_Payments__c, Drawdown_Amount__c, 
                                                                            (SELECT Id, Amount__c, Scheduled_Date__c FROM Scheduled_Payments__r WHERE Status__c =: Constants.PAYMENT_SCHEDULED_STATUS ORDER BY Scheduled_Date__c),
                                                                              (SELECT Amount__c FROM Drawdowns__r)
                                                                                FROM Opportunity WHERE Id IN: opportunityIds AND Type_of_Loan__c =: Constants.FACILITY_LOAN LIMIT 45000]);

        if(!opportunitiesMap.isEmpty()){
            for(Opportunity opportunity : opportunitiesMap.values()){
                PaymentHelper.recalculatePayments(opportunity,opportunity.Scheduled_Payments__r);
            }
        }

        if(!paymentsToUpdate.isEmpty()) update paymentsToUpdate;
        if(!paymentsToDelete.isEmpty()) delete paymentsToDelete;
    }
    **/
    
    @AuraEnabled(cacheable=false)
    public static Drawdown__c getDrawdown(Id drawdownId) {
        return [Select Opportunity__c, Date__c, Amount__c, CHQ__c, EFT__c, Payment_Method__c, Outstanding_Balance_as_of_Payout_Date__c, Rejection_Notes__c, Opportunity_Service_Provider__c From Drawdown__c Where Id = :drawdownId];
    }
    
    @AuraEnabled(cacheable=false)
    public static void updateOpportunityPayoutDate(Id opportunityId, Date payoutDate) {
        Opportunity opp = [select Id, Payout_Date__c from Opportunity where Id=:opportunityId];
        opp.Payout_Date__c = payoutDate;
        opp.Temp_Payment_Received__c = 0;
        update opp;        
    }    
}