force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
    <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
    <label>Compounding Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
    <inlineHelpText>Loan Interest Rate</inlineHelpText>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
    <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
    <label>Minimum Interest Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
    <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <label>Interest Compounding Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Compounding_Period__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Compounding_Period__c.field-meta.xml
<CustomField>
    <fullName>Interest_Compounding_Period__c</fullName>
    <label>Interest Compounding Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple Interest</fullName>
            </value>
            <value>
                <fullName>Compounding Interest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Annual Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <label>Minimum Interest Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 months</fullName>
            </value>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>2 months</fullName>
            </value>
            <value>
                <fullName>3 months</fullName>
            </value>
            <value>
                <fullName>4 months</fullName>
            </value>
            <value>
                <fullName>5 months</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
                <default>true</default>
                <label>6 months</label>
            </value>
            <value>
                <fullName>7 months</fullName>
            </value>
            <value>
                <fullName>8 months</fullName>
            </value>
            <value>
                <fullName>9 months</fullName>
            </value>
            <value>
                <fullName>10 months</fullName>
            </value>
            <value>
                <fullName>11 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LoanSimulatorControllerTest.cls
/**
*    @description : Test class for LoanSimulatorController
**/
@isTest(seeAllData=false)
private with sharing class LoanSimulatorControllerTest {
	
	/**
	*    @description : Set up Opportunity
	**/
    private static Opportunity setUpOpportynity(){
        Opportunity opportunity = new Opportunity(Name = 'Test Opportunity', RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Client Opportunity Record Type').getRecordTypeId());
        opportunity.CloseDate = Date.today().addDays(14);
        opportunity.StageName = 'Closed With Loan';
        opportunity.Stage_Status__c = 'Approved';
        opportunity.Amount = 5000.00;
        opportunity.Payout_Date__c = Date.today();
        opportunity.Type_of_Loan__c = 'Facility Loan';
        opportunity.Minimum_Interest_Period__c = '0 months';
        opportunity.Compounding_Interest__c = 'Monthly';
        opportunity.Interest_Compounding_Period__c = 'Compounding Interest';
        opportunity.Interest_Rate__c = 15.0;
        opportunity.Payout_Date__c = System.today().addMonths(15);
        return opportunity;
    }

    /**
	*    @description : Setup Opportunity
	**/
    private static List<Drawdown__c> setUpDrawdowns(){
        List<Drawdown__c> drawdownsList = new List<Drawdown__c>();
        drawdownsList.add(new Drawdown__c(Payment_Method__c='e-Transfer',Reference_Notes__c='Payment to Client',Amount__c=5000.00,Date__c=System.today()));
        return drawdownsList;
    }


    /**
	*    @description : Test Loan Simulator 
	**/
	@isTest
	static void test_calculateLoanInterestAndBalance(){
		Test.startTest();
		Map<String, Object> objectsMap = LoanSimulatorController.calculateLoanInterestAndBalance(setUpOpportynity(),setUpDrawdowns());
		System.assertEquals(4,objectsMap.size());
		Test.stopTest();
	}
}