force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Loan_Requests__c.field-meta.xml
<CustomField>
    <fullName>Loan_Requests__c</fullName>
    <label>Loan Requests</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Loan</fullName>
            </value>
            <value>
                <fullName>2nd Loan</fullName>
            </value>
            <value>
                <fullName>3rd Loan</fullName>
            </value>
            <value>
                <fullName>4th Loan</fullName>
            </value>
            <value>
                <fullName>5th Loan</fullName>
            </value>
            <value>
                <fullName>6th Loan</fullName>
            </value>
            <value>
                <fullName>7th Loan</fullName>
            </value>
            <value>
                <fullName>8th Loan</fullName>
            </value>
            <value>
                <fullName>9th Loan</fullName>
            </value>
            <value>
                <fullName>10th Loan</fullName>
            </value>
            <value>
                <fullName>11th Loan</fullName>
            </value>
            <value>
                <fullName>12th Loan</fullName>
            </value>
            <value>
                <fullName>13th Loan</fullName>
            </value>
            <value>
                <fullName>14th Loan</fullName>
            </value>
            <value>
                <fullName>15th Loan</fullName>
            </value>
            <value>
                <fullName>16th Loan</fullName>
            </value>
            <value>
                <fullName>17th Loan</fullName>
            </value>
            <value>
                <fullName>18th Loan</fullName>
            </value>
            <value>
                <fullName>19th Loan</fullName>
            </value>
            <value>
                <fullName>20th Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Monitoring__c/System_Monitoring__c.object-meta.xml
<CustomObject>
    <label>System Monitoring Log</label>
    <nameField>
        <displayFormat>SM-{0000000000}</displayFormat>
        <label>System Monitoring Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Monitoring Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Monitoring__c/fields/Monitoring_Type__c.field-meta.xml
<CustomField>
    <fullName>Monitoring_Type__c</fullName>
    <label>Monitoring Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accounts - Available Credit</fullName>
            </value>
            <value>
                <fullName>Accounts - Max Loan Approved</fullName>
            </value>
            <value>
                <fullName>Accounts - Principle</fullName>
            </value>
            <value>
                <fullName>Accounts - Total Interest</fullName>
            </value>
            <value>
                <fullName>Accounts - Total Outstanding Balance</fullName>
            </value>
            <value>
                <fullName>Drawdowns - Admin Fee</fullName>
            </value>
            <value>
                <fullName>Opportunity - Stage/Status</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Monitoring__c/fields/Report_Result_Summary__c.field-meta.xml
<CustomField>
    <fullName>Report_Result_Summary__c</fullName>
    <label>Report Result Summary</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/System_Monitoring__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&#39;New&#39;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SystemMonitoring_DrawdownsAdminFee.cls
public class SystemMonitoring_DrawdownsAdminFee {
    
    
    public void SystemMonitoring_DrawdownsAdminFee(){
        
    }
    
    public static void getListOfIssuesWithAdminFees(){
        List<AggregateResult> sumAdminFeeField = [Select Opportunity__c, Sum(Admin_Fee__c) AdminFee from Drawdown__c group by Opportunity__c];
        system.debug(sumAdminFeeField.size());
        
        List<AggregateResult> sumAdminFeeTransactions = [Select Opportunity__c, SUM(Amount__c) Amount from Drawdown__c where Reference_Notes__c = 'Admin Fee' group by Opportunity__c ];
        system.debug(sumAdminFeeTransactions.size());
        
        Map<Id, Decimal> sumMap = new Map<Id, Decimal>();
        
        for(AggregateResult a : sumAdminFeeField){
            sumMap.put((Id)a.get('Opportunity__c' ), (Decimal)a.get('AdminFee'));
        }
        
        system.debug(sumMap.size());
        
		List<Details> incorrectDrawdowns = new List<Details>();
        for(AggregateResult a : sumAdminFeeTransactions){
            
            Id oppId = (Id)a.get('Opportunity__c');
            Decimal amount = (Decimal)a.get('Amount');
            
            if(sumMap.containsKey(oppId)){
                if(sumMap.get(oppId) != amount){
                    Details d = new Details();
                    d.oppId = oppId;
                    d.FieldAdminFeeSum = sumMap.get(oppId);
                    d.DrawdownsAdminFeeSum = amount;
                    incorrectDrawdowns.add(d);
                    system.debug(' This opportunity has incorrect admin fee drawdowns >>  ' + oppId);
                }
            }
        }
        
        Map<ID, Opportunity> oppMap = new Map<ID, Opportunity>([Select Id, Loan_Requests__c, Name from Opportunity where id IN: sumMap.keyset()]);
        
        System_Monitoring__c sysMon = new System_Monitoring__c();
        sysMon.Status__c = 'New';
        sysMon.Monitoring_Type__c = 'Drawdowns - Admin Fee';
        
        String detailsText = '';
        for(Details d : incorrectDrawdowns){
          detailsText = detailsText + 'This opportunity <a href="/lightning/r/Opportunity/' + d.oppId + '/view" target="_self">' +
              oppMap.get(d.oppId).Name + ' (' + oppMap.get(d.oppId).Loan_Requests__c + ')' + '</a> has incorrect admin fee drawdowns. The sum of the admin fee field is: ' + 
              			d.FieldAdminFeeSum + ' and the sum of admin drawdowns is: ' + d.DrawdownsAdminFeeSum + '. <br/>'; 
        }
        
        sysMon.Report_Result_Summary__c = detailsText;
        insert sysMon;
        
    }
    
    public class Details{
        public String oppId {get;set;}
        public Decimal FieldAdminFeeSum {get;set;}
        public Decimal DrawdownsAdminFeeSum {get;set;}
    }

}