force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Allocate_Payment__c.field-meta.xml
<CustomField>
    <fullName>Allocate_Payment__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check to trigger payment allocation</inlineHelpText>
    <label>Allocate Payment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Frequency__c</fullName>
    <description>The Opportunity__r.Interest_Compounding_Period__c replicated down to the Drawdown to avoid hitting limits in formula calculations.</description>
    <inlineHelpText>The number of times per year that interest compounds.   Expressed as an integer.   For Daily interest this value will be adjusted to either 365 or 366 depending on the interest start date.</inlineHelpText>
    <label>Compounding Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
    <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
    <label>Compounding Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Deferral_Period__c.field-meta.xml
<CustomField>
    <fullName>Interest_Deferral_Period__c</fullName>
    <description>The Interest Deferral Period from the Opportunity, replicated here to avoid cross object formula size limitations.  Also converted to an number from a picklist value so it&#39;s readily usable in formulas.</description>
    <inlineHelpText>The months to defer interest on this Drawdown.</inlineHelpText>
    <label>Interest Deferral Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
    <inlineHelpText>Loan Interest Rate</inlineHelpText>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <description>The minimum Interest period from the Opportunity.   Replicated here to avoid exceeding cross object formula limitations.</description>
    <inlineHelpText>The number of months of interest which must be charged at a minimum.</inlineHelpText>
    <label>Minimum Interest Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_Payout_Date__c</fullName>
    <description>NOTE: Used EXP and LN as the normal exponent function does not handle fractional numbers:  See: https://developer.salesforce.com/forums/?id=906F00000008vDHIAY</description>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF(  ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),Sum_of_Payment_Allocations__c - Amount__c,
IF(Compounding_Interest__c,(Amount_Adjusted_for_Repayments__c*(EXP(LN(1 + (Interest_Rate__c/Compounding_Frequency__c))*   
(Compounding_Frequency__c*Interest_Accrual_Years__c)))),Amount_Adjusted_for_Repayments__c*(1+((Interest_Rate__c/365)* Interest_Accrual_Days__c)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Outstanding Balance as it will be at the Payout Date.  This Accounts for compounding interest or Simple Interest depending on the Loan.  This is set to zero when Drawdown is Payment.   For Payments, negative amounts represent unallocated payment amounts.</inlineHelpText>
    <label>Outstanding Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
    <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Replicated_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Replicated_Payout_Date__c</fullName>
    <label>Replicated Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Temp_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Temp_Payout_Date__c</fullName>
    <inlineHelpText>Used to calculate outstanding balance and date as of a scratch date.  This field should not be updated directly on the Drawdown, instead update from Opportunity and let it replicate down.  Used for Payment Allocation and Reporting From/To amount calc.</inlineHelpText>
    <label>Temp Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <label>Interest Compounding Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Compounding_Period__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Deferral_Period__c.field-meta.xml
<CustomField>
    <fullName>Interest_Deferral_Period__c</fullName>
    <label>Interest Deferral Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Annual Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Minimum_Interest_Period__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Interest_Period__c</fullName>
    <label>Minimum Interest Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 months</fullName>
            </value>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>2 months</fullName>
            </value>
            <value>
                <fullName>3 months</fullName>
            </value>
            <value>
                <fullName>4 months</fullName>
            </value>
            <value>
                <fullName>5 months</fullName>
            </value>
            <value>
                <fullName>6 months</fullName>
                <default>true</default>
                <label>6 months</label>
            </value>
            <value>
                <fullName>7 months</fullName>
            </value>
            <value>
                <fullName>8 months</fullName>
            </value>
            <value>
                <fullName>9 months</fullName>
            </value>
            <value>
                <fullName>10 months</fullName>
            </value>
            <value>
                <fullName>11 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Oldest_Unallocated_Payment__c.field-meta.xml
<CustomField>
    <fullName>Oldest_Unallocated_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Stores the id of the oldest payment not fully allocated.  This will be used to kick off payment allocation when a new drawdown is inserted/updated.    This field will be maintained by DLRS and should not be updated manually.</inlineHelpText>
    <label>Oldest Unallocated Payment</label>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/DrawdownPaymentAllocator.cls
public class DrawdownPaymentAllocator {
    public static Set<Id> processedAdvancesIds = new Set<Id>();    
    public static void allocate(Boolean isInsert, Map<Id, Drawdown__c> oldDrawdownsMap, List<Drawdown__c> newDrawdowns){
        updatePayoutDate(isInsert, oldDrawdownsMap, newDrawdowns);        
        deletePaymentAllocations(isInsert, newDrawdowns, oldDrawdownsMap);        
        removeLoanSetup(newDrawdowns);
        allocatePayments(isInsert, newDrawdowns, oldDrawdownsMap);
        clearPaymentAllocationFlag(newDrawdowns);
        allocateAnotherPayments(isInsert, oldDrawdownsMap, newDrawdowns);
    }
        
    public static void updatePayoutDate(Boolean isInsert,  Map<Id, Drawdown__c> oldDrawdownsMap, List<Drawdown__c> newDrawdowns){
        Map<Id, Drawdown__c> selectedOppToDrawdownMap = new Map<Id, Drawdown__c>();
        for (Drawdown__c newDrawdown : newDrawdowns){
            Drawdown__c oldDrawdown = null;
            if (!isInsert)
                oldDrawdown = oldDrawdownsMap.get(newDrawdown.Id);
            if (checkDrawdown(isInsert, newDrawdown, oldDrawdown)){
                selectedOppToDrawdownMap.put(newDrawdown.Opportunity__c, newDrawdown);
            }
        }
        if (!selectedOppToDrawdownMap.isEmpty()){
            List<Opportunity> oppsToUpdate = [select Id, Payout_Date__c from Opportunity where Id in :selectedOppToDrawdownMap.keySet()];
            for (Opportunity opp : oppsToUpdate){
                opp.Payout_Date__c = selectedOppToDrawdownMap.get(opp.Id).Date__c;
            }
            update oppsToUpdate;
        }
    }
    
    public static Boolean checkDrawdown(Boolean isInsert, Drawdown__c newDrawdown, Drawdown__c oldDrawdown){
        if (newDrawdown.Payment_Method__c == 'Payment' &&
           (isInsert || checkDrawdown(newDrawdown, oldDrawdown) )){
                return true;
            }
        
        return false;
    }
    
    public static Boolean checkDrawdown(Drawdown__c newDrawdown, Drawdown__c oldDrawdown){
        if (newDrawdown.Allocate_Payment__c)
            return true;
        if (oldDrawdown == null)
            return false;
        return (oldDrawdown.Payment_Method__c != 'Payment') || (newDrawdown.Amount__c != oldDrawdown.Amount__c) || 
            (newDrawdown.Date__c != oldDrawdown.Date__c);
    }
    
    public static void deletePaymentAllocations(Boolean isInsert, List<Drawdown__c> newDrawdowns, Map<Id, Drawdown__c> oldDrawdownsMap){
        List<Id> selectedDrawdownIds = new List<Id>();
        for (Drawdown__c newDrawdown : newDrawdowns){
            if (isInsert){
                if (newDrawdown.Payment_Method__c == 'Payment' && newDrawdown.Allocate_Payment__c)
                    selectedDrawdownIds.add(newDrawdown.Id);
            }
            else{
                Drawdown__c oldDrawdown = oldDrawdownsMap.get(newDrawdown.Id);  
                if (newDrawdown.Payment_Method__c != 'Payment' && oldDrawdown.Payment_Method__c == 'Payment'
                   || ( newDrawdown.Payment_Method__c == 'Payment' && checkDrawdown(newDrawdown, oldDrawdown) ) ) {
                        selectedDrawdownIds.add(newDrawdown.Id);                                                                
                   }
            }
        }
        if (!selectedDrawdownIds.isEmpty()){
            DeletePaymentAllocations.DeletePaymentAllocationsFromPayment(selectedDrawdownIds);
        }
    }
    
    public static void removeLoanSetup(List<Drawdown__c> drawdowns){
        List<Id> selectedDrawdownIds = new List<Id>();
        for (Drawdown__c drawdown : drawdowns){
            if (drawdown.Payment_Method__c == 'Payment' && (drawdown.Interest_Rate__c != null) &&
               (drawdown.Compounding_Frequency__c != null || drawdown.Interest_Deferral_Period__c != null ||
                drawdown.Minimum_Interest_Period__c != null || drawdown.Payout_Date__c != null) ){
                    selectedDrawdownIds.add(drawdown.Id);
                }
        }        
        if (!selectedDrawdownIds.isEmpty()){
            List<Drawdown__c> selectedDrawdowns = [select Id, Compounding_Frequency__c, Compounding_Interest__c, Interest_Deferral_Period__c, Interest_Rate__c,
                                                  Minimum_Interest_Period__c, Payout_Date__c, Temp_Payout_Date__c from Drawdown__c where Id in : selectedDrawdownIds];
            for (Drawdown__c drawdown : selectedDrawdowns){
                drawdown.Compounding_Frequency__c = null;
                drawdown.Compounding_Interest__c = false;
                drawdown.Interest_Deferral_Period__c = null;
                drawdown.Interest_Rate__c = null;
                drawdown.Minimum_Interest_Period__c = null;
                drawdown.Payout_Date__c = null;
                drawdown.Temp_Payout_Date__c = null;
            }
            update selectedDrawdowns;
        }
    }
    
    public static void allocatePayments(Boolean isInsert, List<Drawdown__c> newDrawdowns, Map<Id, Drawdown__c> oldDrawdownsMap){
        List<Id> selectedDrawdownIds = new List<Id>();
        List<Id> rejectionDrawdownIds = new List<Id>();
        for (Drawdown__c newDrawdown : newDrawdowns){
            Drawdown__c oldDrawdown = null;
            if (!isInsert)
                oldDrawdown = oldDrawdownsMap.get(newDrawdown.Id);                
            if (checkDrawdown(isInsert, newDrawdown, oldDrawdown)){            
                if (newDrawdown.Reference_Notes__c == 'Payment Rejected' || newDrawdown.Reference_Notes__c == 'Payment Halted')
                    rejectionDrawdownIds.add(newDrawdown.Id);
                else
                    selectedDrawdownIds.add(newDrawdown.Id);
            }            
        }
        if (!rejectionDrawdownIds.isEmpty()){
            PaymentAllocator.allocateRejectionDrawdowns(rejectionDrawdownIds);
        }
        if (!selectedDrawdownIds.isEmpty()){
            PaymentAllocator.AllocatePayments(selectedDrawdownIds);        
        }
    }
    
    public static void clearPaymentAllocationFlag(List<Drawdown__c> drawdowns){
        List<Id> selectedDrawdownIds = new List<Id>();
        for (Drawdown__c drawdown : drawdowns){
            if (drawdown.Allocate_Payment__c)
                selectedDrawdownIds.add(drawdown.Id);
        }
        if (!selectedDrawdownIds.isEmpty()){
            List<Drawdown__c> selectedDrawdowns = [select Id, Allocate_Payment__c from Drawdown__c where Id in :selectedDrawdownIds];
            for (Drawdown__c drawdown : selectedDrawdowns){
                if (drawdown.Allocate_Payment__c)
                    drawdown.Allocate_Payment__c = false;
            }
            update selectedDrawdowns;
        }
    }    
    
    public static void allocateAnotherPayments(Boolean isInsert, Map<Id, Drawdown__c> oldDrawdownsMap, List<Drawdown__c> newDrawdowns){
        List<Id> oppIds = new List<Id>();
        for (Drawdown__c newDrawdown : newDrawdowns){
            if (!processedAdvancesIds.contains(newDrawdown.Id) && newDrawdown.Payment_Method__c != 'Payment' && newDrawdown.Outstanding_Balance_as_of_Payout_Date__c > 0){
                oppIds.add(newDrawdown.Opportunity__c);
                //prevents recursive calls
                processedAdvancesIds.add(newDrawdown.Id);
            }
        }
        if (!oppIds.isEmpty()){           
            List<Id> unallocatedPaymentIds = new List<Id>();
            List<Opportunity> opps = [select Id, Payout_Date__c, Oldest_Unallocated_Payment__c, Oldest_Unallocated_Payment__r.Date__c from Opportunity where Id in :oppIds and Oldest_Unallocated_Payment__c != null];
            List<Opportunity> oppsToUpdate = new List<Opportunity>();
            Map<Id, Date> oppsDates = new Map<Id, Date>();
            Map<Id, Date> oppsOldDates = new Map<Id, Date>();
            oppIds.clear();
            for (Opportunity opp : opps){
                if (opp.Payout_Date__c != opp.Oldest_Unallocated_Payment__r.Date__c){ 
                    oppsOldDates.put(opp.Id, opp.Payout_Date__c);
                    opp.Payout_Date__c = opp.Oldest_Unallocated_Payment__r.Date__c;
                    oppsToUpdate.add(opp);                       
                    oppIds.add(opp.Id);
                }                
                oppsDates.put(opp.Id, opp.Payout_Date__c);
                unallocatedPaymentIds.add(opp.Oldest_Unallocated_Payment__c);                       
            }                    
            if (!oppsToUpdate.isEmpty())
                update oppsToUpdate;
            Boolean replicationFailed = false;
            if (!oppIds.isEmpty()){
                //Checks that Opportunity - Replicate Loan Setup Info to Drawdown process replicated Payout_Date__c from opp to drawdowns
                List<Drawdown__c> advances = [select Id, Payout_Date__c, Replicated_Payout_Date__c, Opportunity__c from Drawdown__c where Opportunity__c in :oppIds and Payment_Method__c != 'Payment'];            
                for (Drawdown__c advance : advances){                   
                    if (oppsDates.get(advance.Opportunity__c) != advance.Replicated_Payout_Date__c && oppsDates.get(advance.Opportunity__c) != advance.Payout_Date__c)
                        replicationFailed = true;
                }            
            }
            if (replicationFailed){
                for (Opportunity opp : oppsToUpdate){
                    opp.Payout_Date__c = oppsOldDates.get(opp.Id);
                }
                update oppsToUpdate;
            }
            else               
                PaymentAllocator.AllocatePayments(unallocatedPaymentIds);  
        }
    }    
}