force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_Payout_Date__c</fullName>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF(  ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),0,(Outstanding_Balance_as_of_Payout_Date__c-Amount_Adjusted_for_Repayments__c)+Interest_up_to_Last_Repayment__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Interest Accrued up to Payout Date</inlineHelpText>
    <label>Accrued Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Admin_Accrued_Interest__c.field-meta.xml
<CustomField>
    <fullName>Admin_Accrued_Interest__c</fullName>
    <label>Admin Accrued Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Admin_Outstanding_Balance__c.field-meta.xml
<CustomField>
    <fullName>Admin_Outstanding_Balance__c</fullName>
    <label>Admin Outstanding Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Admin_Per_Diem__c.field-meta.xml
<CustomField>
    <fullName>Admin_Per_Diem__c</fullName>
    <label>Admin Per Diem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/CHQ__c.field-meta.xml
<CustomField>
    <fullName>CHQ__c</fullName>
    <label>CHQ #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_Payout_Date__c</fullName>
    <description>NOTE: Used EXP and LN as the normal exponent function does not handle fractional numbers:  See: https://developer.salesforce.com/forums/?id=906F00000008vDHIAY</description>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF(  ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),Sum_of_Payment_Allocations__c - Amount__c,
IF(Compounding_Interest__c,(Amount_Adjusted_for_Repayments__c*(EXP(LN(1 + (Interest_Rate__c/Compounding_Frequency__c))*   
(Compounding_Frequency__c*Interest_Accrual_Years__c)))),Amount_Adjusted_for_Repayments__c*(1+((Interest_Rate__c/365)* Interest_Accrual_Days__c)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Outstanding Balance as it will be at the Payout Date.  This Accounts for compounding interest or Simple Interest depending on the Loan.  This is set to zero when Drawdown is Payment.   For Payments, negative amounts represent unallocated payment amounts.</inlineHelpText>
    <label>Outstanding Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_To_Reverse__c.field-meta.xml
<CustomField>
    <fullName>Payment_To_Reverse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment To Reverse</label>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Rejections</relationshipLabel>
    <relationshipName>Rejection_Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Per_Diem_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_as_of_Payout_Date__c</fullName>
    <description>o	The daily interest rate (using a 365 base) on the total outstanding balance (Principle + Interest) at the payout date.   The Per Diem will be adjusted to zero in two scenarios:
1.	When the payout date is less than the minimum interest date.  In this situation, the interest accrued to 6 months is already included in the payout and therefore charging Per Diem would be double charging.  
2.	When the payout date is still within the interest deferral period.</description>
    <formula>If(
    OR((Payout_Date__c&lt;(ADDMONTHS(Date__c,Interest_Deferral_Period__c))),
       (Payout_Date__c&lt;(ADDMONTHS(Date__c,Minimum_Interest_Period__c))),
	    ISPICKVAL(Payment_Method__c , &quot;Payment&quot;))   
    ,0,
	(Interest_Rate__c/365)*Outstanding_Balance_as_of_Payout_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The daily interest rate on the total outstanding balance at the payout date. The Per Diem will be adjusted to zero when the payout date is less than the minimum interest date and when payout date is within the interest deferral period.</inlineHelpText>
    <label>Per Diem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Admin_Fee__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee__c</fullName>
    <label>Admin Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/Opportunity_Service_Provider__c.object-meta.xml
<CustomObject>
    <label>Opportunity Service Provider</label>
    <nameField>
        <displayFormat>OSP-{00000}</displayFormat>
        <label>OSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Service Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DrawdownTriggerHandler.cls
public class DrawdownTriggerHandler {
    
    public static void validatePaymentChange(Map<Id,Drawdown__c> oldMap, List<Drawdown__c> newDrawdowns){
        /*------------------------------------------------------------
Author: Basil Dobek
Company: Deloitte
Description: Validate that updates to payment dates do not change order of payments.  Changing order of payments is not supported. 
Also amount changes when later payments exist is not supported. 
And finally changing from or to a payment when later payments exist is not supported.
This class works in before update and before insert.
Inputs: Trigger.OldMap and Trigger.new context variables. 

History
<Date> <Authors Name> <Brief Description of Change>
------------------------------------------------------------*/
        
        List <ID> OpportunityIds = new List <ID>();  // hold list of opportunities for which we have payments we need to validate date change on
        list <Drawdown__c> Payments = new List <Drawdown__c>();  // Will hold list of payments with potential issues
        
        for (Drawdown__c newDrawdown : newDrawdowns){
            Date OldDate = Date.newInstance(1900,01,01);
            Decimal OldAmount = 0;
            String OldPaymentMethod = '';
            if (trigger.isUpdate){
                OldDate = oldMap.get(newDrawdown.id).Date__c;
                OldAmount = oldMap.get(newDrawdown.id).Amount__c;
                OldPaymentMethod = oldMap.get(newDrawdown.id).Payment_Method__c;
            }
            
            if( (newDrawdown.Payment_Method__c =='Payment' && OldDate != newDrawdown.Date__c ) || 
               (newDrawdown.Payment_Method__c =='Payment' && newDrawdown.Amount__c != OldAmount) ||
               (newDrawdown.Payment_Method__c =='Payment' && OldPaymentMethod != 'Payment' ) ||
               (newDrawdown.Payment_Method__c !='Payment' && OldPaymentMethod == 'Payment' )) {
                   // save opportunity id in set
                   // save payment in map
                   OpportunityIds.Add(newDrawdown.Opportunity__c);
                   Payments.Add(newDrawdown);	
               }
        }
        if(!Payments.isEmpty() && !OpportunityIds.isEmpty()){
            // query for all payments under the opportunities where we have payments with changed dates
            List <Drawdown__c> allPayments = [Select id,date__c from Drawdown__c where Opportunity__c in : OpportunityIds and Payment_Method__c = 'Payment'];
            
            // Cycle throuh every payment in our map of payments which are a potential issue and verify id doesn't violate one of the other payments
            for (drawdown__c newPayment : Payments){
                for (drawdown__c otherPayment : allPayments){
                    if (Trigger.isUpdate){
                        if ((newPayment.id != otherPayment.id) && (newPayment.date__c < otherPayment.Date__c || oldMap.get(newPayment.id).date__c < otherPayment.Date__c )){
                            // throw an error as an invalid date change has occurred
                            newPayment.addError('Invalid change due to conflicting payment.  Payments dated after this record must be removed first.');
                        }
                    }
                    if (Trigger.isInsert){
                        // on insert, don't check the to date
                        if ((newPayment.id != otherPayment.id) && (newPayment.date__c < otherPayment.Date__c )){
                            // throw an error as an invalid date change has occurred
                            newPayment.addError('Invalid change due to conflicting payment.  Payments dated after this record must be removed first.');
                        }
                    }
                }
            }
        }
    }
    
    public static void validatePaymentDelete(List<Drawdown__c> Payments){
        /*------------------------------------------------------------
Author: Basil Dobek
Company: Deloitte
Description: Validate that payment deletions only occur on the last payment as changing order of payments via deletion is not supported. 
Also verify the loan is still open.   
Inputs: Trigger.OldMap context variable. 

History
<Date> <Authors Name> <Brief Description of Change>
------------------------------------------------------------*/
        
        List <ID> OpportunityIds = new List <ID>();  // hold list of opportunities for which we have payments we need to validate deletion of
        
        for (Drawdown__c p : Payments){
            OpportunityIds.Add(p.Opportunity__c);
        }
        
        // query for all payments under the opportunities where we have payments with changed dates
        List <Drawdown__c> allPayments = [Select id,date__c,Opportunity__c,Opportunity__r.Stage_Status__c from Drawdown__c where Opportunity__c in : OpportunityIds and Payment_Method__c = 'Payment'];
        
        // Cycle throuh every payment in our map of payments which are a potential issue and verify id doesn't violate one of the other payments
        for (drawdown__c paymentToDelete : Payments){
            for (drawdown__c otherPayment : allPayments){
                if (paymentToDelete.Opportunity__c==otherPayment.Opportunity__c) {
                    if ((paymentToDelete.id != otherPayment.id)  && (paymentToDelete.date__c < otherPayment.Date__c )){
                        // throw an error as an invalid date change has occurred
                        paymentToDelete.addError('Invalid payment deletion due to later payments.  Payments dated after this record must be removed first.');
                    }  
                    if (paymentToDelete.Opportunity__r.Stage_Status__c == 'Paid Off'){
                        // throw an error as an Loan cannot be closed
                        paymentToDelete.addError('Cannot delete payments from close Loans.  Please re-open first.');                        
                    }
                }
            }
        }
    }
    
    public static void updateAdminFeeOnFirstDrawdown(List<Drawdown__c> newDrawdowns, Map<Id,Drawdown__c> oldMap, Boolean isInsert){
        /*------------------------------------------------------------
Author: Fahad Khan
Company: Toptal
Description: update first drawdown of opportunity to house both admin fee and its amount

History
<Date> <Authors Name> <Brief Description of Change>
------------------------------------------------------------*/
        
        Set<Id> oppties = new Set<Id>();
        for(Drawdown__c d : newDrawdowns)
        {
            if(d.Opportunity__c != null &&
               (isInsert || (!isInsert && 
                             (/*(d.Reference_Notes__c == 'Admin Fee' ||
oldMap.get(d.Id).Reference_Notes__c == 'Admin Fee') && */
                                 (d.Per_Diem_as_of_Payout_Date__c != oldMap.get(d.Id).Per_Diem_as_of_Payout_Date__c ||
                                  d.Amount__c != oldMap.get(d.Id).Amount__c || 
                                  d.Reference_Notes__c != oldMap.get(d.Id).Reference_Notes__c || 
                                  d.Date__c != oldMap.get(d.Id).Date__c ||
                                  d.Accrued_Interest_as_of_Payout_Date__c != oldMap.get(d.Id).Accrued_Interest_as_of_Payout_Date__c ||
                                  d.Outstanding_Balance_as_of_Payout_Date__c != oldMap.get(d.Id).Outstanding_Balance_as_of_Payout_Date__c) )) ))
            {
                oppties.add( d.Opportunity__c);
            }
        }
        if(!oppties.isEmpty())
        {
            mergeAdminFees(oppties);
        }
    }
    public static void mergeAdminFees(Set<Id> opptyIds){
        system.debug('In mergeAdminFees Function');
        List<Opportunity> oppties = [Select id , Stage_Status__c,
                                     (Select Amount__c, Reference_Notes__c , Payment_Method__c,
                                      Accrued_Interest_as_of_Payout_Date__c, Admin_Accrued_Interest__c,
                                      Admin_Outstanding_Balance__c, Outstanding_Balance_as_of_Payout_Date__c,
                                      Admin_Per_Diem__c, Per_Diem_as_of_Payout_Date__c From Drawdowns__r
                                      Order by Date__c asc, Name asc)
                                     from Opportunity where id in :opptyIds];
        List<Drawdown__c> drawdownsToUpdate = new List<Drawdown__c>();
        for(Opportunity op : oppties)
        {
            if(!op.Drawdowns__r.isEmpty())
            {
				List<Drawdown__c> drawdownsRange = new List<Drawdown__c>();
                //Splitting drawdowns by Rejected Payments. Merge admin fee separately in each range
                for(Drawdown__c d : op.Drawdowns__r)
                {
                    if (d.Reference_Notes__c == 'Payment Rejected' || d.Reference_Notes__c == 'Payment Halted'){
                        if (!drawdownsRange.isEmpty()){
                            List<Drawdown__c> drawdownsToUpdateInRange = mergeAdminFeesWithDrawdown(drawdownsRange);
                            drawdownsToUpdate.addAll(drawdownsToUpdateInRange);
                            drawdownsRange.clear();
                        }
                    }
                    else{
                        drawdownsRange.add(d);
                    }
                }
                if (!drawdownsRange.isEmpty()){
                    List<Drawdown__c> drawdownsToUpdateInRange = mergeAdminFeesWithDrawdown(drawdownsRange);
                    drawdownsToUpdate.addAll(drawdownsToUpdateInRange);
                }
            }
        }
        if(!drawdownsToUpdate.isEmpty())
        {
            update drawdownsToUpdate;
        }
    }
    public static List<Drawdown__c> mergeAdminFeesWithDrawdown(List<Drawdown__c> drawdowns){
        List<Drawdown__c> drawdownsToUpdate = new List<Drawdown__c>();
        double adminFee = 0.0;
        double adminAccuredInterest = 0.0;
        double adminOutstandingBalance = 0.0;
        double adminPerDiem = 0.0;
        Drawdown__c firstDrawdown = null;
        for(Drawdown__c d : drawdowns)
        {
            if(d.Reference_Notes__c == 'Admin Fee' || d.Reference_Notes__c == 'Assessment Fee')
            {
                //system.debug('Reference Notes == Admin Fee ' + d.Id);
                adminFee += d.Amount__c;
                adminAccuredInterest += d.Accrued_Interest_as_of_Payout_Date__c;
                adminOutstandingBalance +=d.Outstanding_Balance_as_of_Payout_Date__c;
                adminPerDiem += d.Per_Diem_as_of_Payout_Date__c;
                //system.debug('sel drawdown Admin Fee ' + d.Amount__c);
                //ystem.debug('Total Admin Fee ' + adminFee);
                //system.debug('Total Admin Accrued Interest ' + adminAccuredInterest);
            }
            else if (d.Reference_Notes__c != 'Referral Fee' && firstDrawdown == null)
            {
                //system.debug('Reference Notes != Referral Fee and FDd == null ' + d.Id);
                firstDrawdown = d;
                //System.debug('firstDrawdown'+firstDrawdown);
                
            }else if (firstDrawdown != null){
                d.Admin_Fee__c = null;
                d.Admin_Accrued_Interest__c = null;
                d.Admin_Outstanding_Balance__c = null;
                d.Admin_Per_Diem__c = null;
                drawdownsToUpdate.add(d);
            }
        }
        //if(firstDrawdown != null && adminFee > 0)
        if(firstDrawdown != null)
        {
            system.debug('FDd != null admin fee ++ ' + firstDrawdown.Id);
            system.debug('Admin Fee to be assigned ' + adminFee);
            firstDrawdown.Admin_Fee__c = adminFee > 0 ? adminFee : null;
            firstDrawdown.Admin_Accrued_Interest__c = adminAccuredInterest > 0 ? adminAccuredInterest : null;
            firstDrawdown.Admin_Outstanding_Balance__c = adminOutstandingBalance > 0 ? adminOutstandingBalance : null;
            firstDrawdown.Admin_Per_Diem__c = adminPerDiem > 0 ? adminPerDiem : null;
            drawdownsToUpdate.add(firstDrawdown);
        }
        
        return drawdownsToUpdate;
    }

    public static void createAdminFeeRejections(List<Drawdown__c> newDrawdowns){
        List<Drawdown__c> rejections = new List<Drawdown__c>();
        for (Drawdown__c d : newDrawdowns){
            if (d.Payment_To_Reverse__c != null){
                rejections.add(d);
            }
        }
        if (!rejections.isEmpty()){            
            List<Id> drawdownsToReverseIds = new List<Id>();
            List<Id> oppIds = new List<Id>();
            for (Drawdown__c rejectionDrawdown : rejections){
                drawdownsToReverseIds.add(rejectionDrawdown.Payment_To_Reverse__c);
                oppIds.add(rejectionDrawdown.Opportunity__c);
            }
            List<Drawdown__c> drawdownsToReverse = [select Id, Date__c, Admin_Fee__c, Admin_Outstanding_Balance__c, Admin_Accrued_Interest__c from Drawdown__c where Id in :drawdownsToReverseIds];
            Map<Id, Drawdown__c> drawdownsToReverseMap = new Map<Id, Drawdown__c>();
            for (Drawdown__c d : drawdownsToReverse){
                drawdownsToReverseMap.put(d.Id, d);
            }
            List<Drawdown__c> adminFeeDrawdowns = [select Id, Opportunity__c, Date__c, CHQ__c, EFT__c, Opportunity_Service_Provider__c, Payment_Method__c, Amount__c,Outstanding_Balance_as_of_Payout_Date__c,Rejections_Count__c   from Drawdown__c where (Reference_Notes__c = 'Admin Fee' OR Reference_Notes__c = 'Assessment Fee') and Opportunity__c in :oppIds and (Rejections_Count__c=NULL OR Rejections_Count__c=0)];            
            Map<Id, List<Drawdown__c>> oppToAdminFeeDrawdownsMap = new Map<Id, List<Drawdown__c>>();
            for (Id oppId : oppIds){
                oppToAdminFeeDrawdownsMap.put(oppId, new List<Drawdown__c>());
            }
            for (Drawdown__c adminFeeDrawdown : adminFeeDrawdowns){
                System.debug('AF ' + adminFeeDrawdown.Id + ' ' + adminFeeDrawdown.Rejections_Count__c);
                oppToAdminFeeDrawdownsMap.get(adminFeeDrawdown.Opportunity__c).add(adminFeeDrawdown);
			}
            List<Drawdown__c> adminFeeRejectionDrawdowns = new List<Drawdown__c>();
            for (Drawdown__c rejectionDrawdown : rejections){
                Drawdown__c drawdownToReverse = drawdownsToReverseMap.get(rejectionDrawdown.Payment_To_Reverse__c);                
                if (drawdownToReverse.Admin_Fee__c != null){
                    List<Drawdown__c> adminFees = oppToAdminFeeDrawdownsMap.get(rejectionDrawdown.Opportunity__c);                    
                    for (Drawdown__c adminFeeDrawdown : adminFees){
                        if (adminFeeDrawdown.Date__c > rejectionDrawdown.Date__c)
                            continue;
                        Drawdown__c adminFeeRejectionDrawdown = new Drawdown__c();                        
                        adminFeeRejectionDrawdown.Opportunity__c = rejectionDrawdown.Opportunity__c;        
                        adminFeeRejectionDrawdown.CHQ__c = adminFeeDrawdown.CHQ__c;        
                        adminFeeRejectionDrawdown.EFT__c = adminFeeDrawdown.EFT__c;        
                        adminFeeRejectionDrawdown.Payment_Method__c = 'Payment';  
                        adminFeeRejectionDrawdown.Reference_Notes__c = rejectionDrawdown.Reference_Notes__c;
                        adminFeeRejectionDrawdown.Reason_to_Reverse_Payment__c = rejectionDrawdown.Reason_to_Reverse_Payment__c;
                        if (rejectionDrawdown.Reason_to_Reverse_Payment__c == 'Client Error'){
                            adminFeeRejectionDrawdown.Amount__c = adminFeeDrawdown.Amount__c;
                        }                   
                        else
                            adminFeeRejectionDrawdown.Amount__c = adminFeeDrawdown.Outstanding_Balance_as_of_Payout_Date__c;
                        adminFeeRejectionDrawdown.Principal_Reversed__c = adminFeeDrawdown.Amount__c;
                        adminFeeRejectionDrawdown.Date__c = rejectionDrawdown.Date__c;
                        adminFeeRejectionDrawdown.Rejection_Notes__c = rejectionDrawdown.Rejection_Notes__c;
                        adminFeeRejectionDrawdown.Payment_To_Reverse__c = adminFeeDrawdown.Id;
                        adminFeeRejectionDrawdown.Opportunity_Service_Provider__c = adminFeeDrawdown.Opportunity_Service_Provider__c;
                        adminFeeRejectionDrawdowns.add(adminFeeRejectionDrawdown);
                    }
                }
            }
            if (!adminFeeRejectionDrawdowns.isEmpty())
            	insert adminFeeRejectionDrawdowns;
        }
	}
    
    /*
    public static void reCalculateCriticalDatePayout(List<Drawdown__c> newDrawdowns, Map<Id,Drawdown__c> oldMap, Boolean isInsert){
        
        Set<Id> drawdownIds = new Set<Id>();
        for(Drawdown__c dd :newDrawdowns){        
            if((dd.Payment_Method__c != 'Payment' && dd.Interest_Rate__c > 0 && (dd.Compounding_Interest__c == false || dd.Compounding_Frequency__c > 0) ) && 
               ((isInsert && dd.Amount__c > 0) || (!isInsert && (dd.Payment_Method__c != oldMap.get(dd.Id).Payment_Method__c || 
                                                                 dd.Interest_Rate__c != oldMap.get(dd.Id).Interest_Rate__c ||
                                                                 dd.Compounding_Interest__c != oldMap.get(dd.Id).Compounding_Interest__c || 
                                                                 dd.Compounding_Frequency__c != oldMap.get(dd.Id).Compounding_Frequency__c ||
                                                                 dd.Amount__c != oldMap.get(dd.Id).Amount__c || 
                                                                 dd.Date__c != oldMap.get(dd.Id).Date__c)))){
                                                                     drawdownIds.add(dd.Id);
                                                                 }
        }
        Set<Id> accountIds = new Set<Id>();
        if(!drawdownIds.isEmpty()){
            List<Drawdown__c> ddList;
            if(Trigger.isDelete){
                ddList = [SELECT Opportunity__r.AccountId FROM Drawdown__c Where id in: drawdownIds AND IsDeleted = true ALL ROWS];
            }else{
                ddList = [SELECT Opportunity__r.AccountId FROM Drawdown__c Where id in: drawdownIds];
            }
            for(Drawdown__c dd : ddList){
                accountIds.add(dd.Opportunity__r.AccountId);
            }
        }
        
        if(!accountIds.isEmpty()){
            // Adding all critical date fields to the query
            Map<String, Schema.SObjectField> fields = Schema.SObjectType.Critical_Date__c.fields.getMap();
            List<String> lstFields = new List<String>();
            for (Schema.SObjectField field : fields.values()) {
                lstFields.add(field.getDescribe().getName());
            }       
            
            // Building the query
            String strQuery = 'SELECT ' + String.join(lstFields, ',');
            strQuery += ' FROM Critical_Date__c WHERE Account__c in: accountIds';  
            
            List<Critical_Date__c> criticalDatesList = Database.query(strQuery); 
            if(criticalDatesList.size() > 0){
                criticalDateTriggerHandler.calculatePayout(criticalDatesList, null, true, true);
            }
        }  
    }
    */
}