force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/CHQ__c.field-meta.xml
<CustomField>
    <fullName>CHQ__c</fullName>
    <label>CHQ #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reference_Notes__c.field-meta.xml
<CustomField>
    <fullName>Reference_Notes__c</fullName>
    <label>Reference Notes</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Assessment Fee</fullName>
            </value>
            <value>
                <fullName>Admin Fee charged up front</fullName>
            </value>
            <value>
                <fullName>Bad Debt</fullName>
            </value>
            <value>
                <fullName>EFT Reject</fullName>
            </value>
            <value>
                <fullName>EFT Reprocessed</fullName>
            </value>
            <value>
                <fullName>EFT to Client</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Payment Re-processed</fullName>
            </value>
            <value>
                <fullName>Payment Shortfall</fullName>
            </value>
            <value>
                <fullName>Payment Surplus</fullName>
            </value>
            <value>
                <fullName>Payment to Assessment Provider</fullName>
            </value>
            <value>
                <fullName>Payment to Client</fullName>
            </value>
            <value>
                <fullName>Payment to Lawyer</fullName>
            </value>
            <value>
                <fullName>Payment to other lender</fullName>
            </value>
            <value>
                <fullName>Payment to Third-Party</fullName>
            </value>
            <value>
                <fullName>Payment to Treatment - Service Provider</fullName>
            </value>
            <value>
                <fullName>Referral Fee</fullName>
            </value>
            <value>
                <fullName>Waived Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Payment</fullName>
            </value>
            <value>
                <fullName>Legal Fee</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Payment Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Scheduled_Payment__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Payment</label>
    <referenceTo>Scheduled_Payment__c</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/Opportunity_Service_Provider__c.object-meta.xml
<CustomObject>
    <label>Opportunity Service Provider</label>
    <nameField>
        <displayFormat>OSP-{00000}</displayFormat>
        <label>OSP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Service Providers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Service Providers</relationshipLabel>
    <relationshipName>Opportunity_Service_Providers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Service_Provider__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting to Send Schedule</fullName>
                <default>true</default>
                <label>Waiting to Send Schedule</label>
            </value>
            <value>
                <fullName>Schedule Sent</fullName>
            </value>
            <value>
                <fullName>Schedule Signed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Rejection__c/Payment_Rejection__c.object-meta.xml
<CustomObject>
    <label>Payment Rejection</label>
    <nameField>
        <displayFormat>spr-{00000}</displayFormat>
        <label>Payment Rejection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Rejections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Rejection__c/fields/Scheduled_Payment__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment__c</fullName>
    <label>Scheduled Payment</label>
    <referenceTo>Scheduled_Payment__c</referenceTo>
    <relationshipLabel>Payment Rejections</relationshipLabel>
    <relationshipName>Payment_Rejections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Rejection__c/fields/Scheduled_Payment_Action__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment_Action__c</fullName>
    <label>Scheduled Payment Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Set to Scheduled</fullName>
            </value>
            <value>
                <fullName>Set to Rejected</fullName>
                <default>true</default>
                <label>Set to Rejected</label>
            </value>
            <value>
                <fullName>Set to Won&#39;t Send</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Rejection__c/fields/Use_Original_Sent_Date_for_Interest__c.field-meta.xml
<CustomField>
    <fullName>Use_Original_Sent_Date_for_Interest__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Should the payment use the original sent date for interest calculations when it is re-processed?</description>
    <label>Use Original Sent Date for Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Banking_Verified__c.field-meta.xml
<CustomField>
    <fullName>Banking_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Banking Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/BIA_PPSA_LL_Verified__c.field-meta.xml
<CustomField>
    <fullName>BIA_PPSA_LL_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BIA/PPSA/LL Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Credit_Verified__c.field-meta.xml
<CustomField>
    <fullName>Credit_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Credit Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Documents_Verified__c.field-meta.xml
<CustomField>
    <fullName>Documents_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Documents Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Drawdown__c.field-meta.xml
<CustomField>
    <fullName>Drawdown__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Drawdown</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Drawdown__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Drawdown_Created__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Drawdown Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/First_Sent_to_Bank_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Sent_to_Bank_Date__c</fullName>
    <label>First Sent to Bank Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Has_Been_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Has_Been_Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Been Rejected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do not allow this payment to processed for now.</inlineHelpText>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Service_Provider__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Service Provider</label>
    <referenceTo>Opportunity_Service_Provider__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_Date__c</fullName>
    <description>Date and Time this payment was included in a banking sheet</description>
    <label>Sent to Bank Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PaymentRejectionTriggerHandler.cls
public class PaymentRejectionTriggerHandler extends TriggerHandler {
    private Map<Id, Payment_Rejection__c> newPRMap;
    private Map<Id, Payment_Rejection__c> oldPRMap;

    public PaymentRejectionTriggerHandler() {
        System.debug('In PaymentRejectionTriggerHandler Constructor');
        this.newPRMap = (Map<Id, Payment_Rejection__c>) Trigger.newMap;
        this.oldPRMap = (Map<Id, Payment_Rejection__c>) Trigger.oldMap;
    }

    public override void afterInsert() {
        Id[] spIds = new Id[]{};
        Map<Id, Scheduled_Payment__c> spMap;
        SObject[] insertList = new SObject[]{}; // Used to store Drawdowns and Scheduled Payments that need updated in one transaction
        SObject[] updateList = new SObject[]{}; // Used to store Drawdowns and Scheduled Payments that need updated in one transaction
        //Drawdown__c[] ddList = new Drawdown__c[]{};
        //Scheduled_Payment__c[] spList = new Scheduled

        for (Payment_Rejection__c pr : this.newPRMap.values()) {
            spIds.add(pr.Scheduled_Payment__c);
        }

        // Fetch scheduled payments and drawdowns
        spMap = new Map<Id, Scheduled_Payment__c>([
            Select 
                Id, Drawdown__c, Opportunity__c, First_Sent_to_Bank_Date__c, Notes__c,
                Drawdown__r.Amount__c,
                Drawdown__r.CHQ__c,
                Drawdown__r.Date__c,
                Drawdown__r.EFT__c,
                Drawdown__r.Opportunity_Service_Provider__c,
                Drawdown__r.Payment_Method__c
            From Scheduled_Payment__c
            Where Id in :spIds
        ]);

        SObject[] result;
        for (Payment_Rejection__c pr : this.newPRMap.values()) {
            result = calculateModifications(pr, spMap.get(pr.Scheduled_Payment__c));
            if (result[0] != null) {
                updateList.add(result[0]);
            }
            if (result[1] != null) {
                insertList.add(result[1]);
            }
        }

        if (!updateList.isEmpty()) {
            update updateList;
        }
        if (!insertList.isEmpty()) {
            insert insertList;
        }
    }

    private SObject[] calculateModifications(Payment_Rejection__c pr, Scheduled_Payment__c sp) {
        SOBject[] result = new SOBject[]{sp, null};

        // Create new Drawdown if necessary
        if (String.isNotBlank(sp.Drawdown__c)) {
            Drawdown__c dd = new Drawdown__c();
            dd.Opportunity__c = sp.Opportunity__c;
            dd.Amount__c = 0 - sp.Drawdown__r.Amount__c;
            dd.CHQ__c = sp.Drawdown__r.CHQ__c;
            dd.Date__c = sp.Drawdown__r.Date__c;
            dd.EFT__c = sp.Drawdown__r.EFT__c;
            dd.Opportunity_Service_Provider__c = sp.Drawdown__r.Opportunity_Service_Provider__c;
            dd.Payment_Method__c = sp.Drawdown__r.Payment_Method__c;
            dd.Reference_Notes__c = 'Payment Rejected';
            dd.Scheduled_Payment__c = sp.Id;
            sp.Has_Been_Rejected__c = true;
            result[1] = dd;
        }

        // Update Scheduled Payment
        sp.Banking_Verified__c = false;
        sp.BIA_PPSA_LL_Verified__c = false;
        sp.Credit_Verified__c = false;
        sp.Documents_Verified__c = false;
        sp.Drawdown__c = null;
        sp.Drawdown_Created__c = false;
        if (!pr.Use_Original_Sent_Date_for_Interest__c) {
            sp.First_Sent_to_Bank_Date__c = null;
        }
        if (String.isNotBlank(sp.Drawdown__c)) {
            sp.Has_Been_Rejected__c = true;
        }
        if (pr.Scheduled_Payment_Action__c == 'Set to Rejected') {
            sp.Hold__c = true;
        }
        if (String.isNotBlank(pr.Reason__c)) {
            if (String.isBlank(sp.Notes__c)){
                sp.Notes__c = pr.Reason__c;
            } else {
                sp.Notes__c = pr.Reason__c + '\r\n\r\n' + sp.Notes__c;
            }
        }
        sp.Sent_to_Bank_Date__c = null;
        sp.Status__c = pr.Scheduled_Payment_Action__c.remove('Set to ');
        result[0] = sp;

        return result;
    }
}