force-app/main/default/objects/Lead/fields/AC_rtName__c.field-meta.xml
<CustomField>
    <fullName>AC_rtName__c</fullName>
    <formula>BLANKVALUE(RecordType.Name,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AC Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Any_SpousalChild_support_payment__c.field-meta.xml
<CustomField>
    <fullName>Any_SpousalChild_support_payment__c</fullName>
    <label>Any SpousalChild support payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Do_you_have_any_dependants__c.field-meta.xml
<CustomField>
    <fullName>Do_you_have_any_dependants__c</fullName>
    <label>Do you have any dependants?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Employment_status_at_time_of_accident__c.field-meta.xml
<CustomField>
    <fullName>Employment_status_at_time_of_accident__c</fullName>
    <label>Employment status at time of accident</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Self-employed</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Existing_Litigation_Loans__c.field-meta.xml
<CustomField>
    <fullName>Existing_Litigation_Loans__c</fullName>
    <label>Existing Litigation Loans</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Have_you_ever_been_in_arrears_on_payment__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_been_in_arrears_on_payment__c</fullName>
    <label>Have you ever been in arrears on payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Have_you_ever_declared_bankruptcy__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_declared_bankruptcy__c</fullName>
    <label>Have you ever declared bankruptcy?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Married/Common Law</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RDS_LeadViewCtlr.cls
/**
 * RA, 06/09/2016
 * controller extension for Lead View page
 */
public with sharing class RDS_LeadViewCtlr{

    private final RDS_SObject rdsObject;
    public Lead leadObj {get; set;}
    public String ownerName {get; set;}
    public String address {get; set;}
    Id recId {get; set;}    

    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public RDS_LeadViewCtlr(ApexPages.StandardController stdController) {
        this.rdsObject= new RDS_SObject((SObject)stdController.getRecord());
        
        // read from database to make sure all fields are queried
        this.rdsObject.initFromDb(null);
        leadObj = (Lead)this.rdsObject.sObj;
        
        if(leadObj != null && leadObj.ownerId != null){
            ownerName = [Select name from User where id=:leadObj.ownerId][0].name;
            address = leadObj.Street + ' ' + leadObj.City + ' ' + leadObj.State + ' ' + leadObj.PostalCode;
        }
    }
    
    public PageReference dispatch(){
        // redirect to nooverride if it's a lawyer
        if(leadObj != null && leadObj.AC_rtName__c != null && leadObj.AC_rtName__c.contains('Lawyer')){  
            PageReference pg = new PageReference('/' + leadObj.id);
            pg.getParameters().put('nooverride', '1');
            pg.setRedirect(true);
            return pg;
        }
        return null;
    }

    public List<String> getMartialStatusOptions() {
        return RDS_Util.getPicklistOptions(Lead.Marital_Status__c.getDescribe());
    }
    public List<String> getSpousalChildPaymentOptions() {
        return RDS_Util.getPicklistOptions(Lead.Any_SpousalChild_support_payment__c.getDescribe());
    }
    public List<String> getArrearsPaymentOptions() {
        return RDS_Util.getPicklistOptions(Lead.Have_you_ever_been_in_arrears_on_payment__c.getDescribe());
    }
    public List<String> getDependentOptions() {
        return RDS_Util.getPicklistOptions(Lead.Do_you_have_any_dependants__c.getDescribe());
    }
    public List<String> getBankruptcyOptions() {
        return RDS_Util.getPicklistOptions(Lead.Have_you_ever_declared_bankruptcy__c.getDescribe());
    }
    public List<String> getEmploymentOptions() {
        return RDS_Util.getPicklistOptions(Lead.Employment_status_at_time_of_accident__c.getDescribe());
    }
    public List<String> getLitigationOptions() {
        return RDS_Util.getPicklistOptions(Lead.Existing_Litigation_Loans__c.getDescribe());
    }
    public PageReference deleteLead(){
        if(leadObj != null){
           delete leadObj; 
        }
        
        PageReference pg = new PageReference('/apex/RDS_LeadEdit');
        pg.setRedirect(true);
        return pg;
    }
    public PageReference convert() {
        return new PageReference('/lead/leadconvert.jsp?id=' + leadObj.Id + '&retURL=%2F' + leadObj.Id );
    }
    public PageReference printableView() {
        return new PageReference('/apex/RDS_LeadPrintableView?id=' + leadObj.Id);
    }
    public PageReference standardView() {
        return new PageReference('/' + leadObj.Id + '?nooverride=1');
    }
    public PageReference CancelLead() {
        return new PageReference('/00Q/o');
    }
    public PageReference cloneLead(){
        recId = ApexPages.currentPage().getParameters().get('id');
         Lead ld;
        if(leadObj != null){
            ld =(Lead)leadObj;
            Lead led = new Lead();
            led =  ld.clone(true,false);
            leadObj = led;
        }
        system.debug('>>>>>>>>>leadObj'+leadObj);
        if(recId == null) return null;
        system.debug('>>>>>>>recId '+recId);
        Pagereference targetClonePg = Page.RDS_LeadEdit;
        targetClonePg.getParameters().put('clone', '1');
        targetClonePg.getParameters().put('id', leadObj.id);
        targetClonePg.getParameters().put('retURL', recId);
        system.debug('>>>>>>>targetClonePg '+targetClonePg);
        return targetClonePg;
    }
}