force-app/main/default/objects/Lead/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Law Firm</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Funding_Requested__c.field-meta.xml
<CustomField>
    <fullName>Funding_Requested__c</fullName>
    <label>Funding Requested</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandlerTest.cls
@isTest
public with sharing class LeadTriggerHandlerTest {    
    
    static testMethod void leadTriggerHandlerTest() {
        Test.startTest();
        Lead ld = new Lead();
        ld.FirstName = 'Test';  
        ld.MiddleName = '';
        ld.LastName = 'Lead';
        ld.Company = 'ABC Pvt ltd';
        ld.DOB__c = date.today();
        ld.Phone = '456789123';
        ld.Loan_Amount__c = 200000;
        ld.Funding_Requested__c = 200000;
        ld.Account_Type__c = 'Client';
        insert ld;

        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(ld.id);

        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);

        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
        Test.stopTest();
    }

}