force-app/main/default/objects/Opportunity/fields/Amount_sent_from_current_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Amount_sent_from_current_Schedule__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Total amount of scheduled payments processed from current version of payment schedule</description>
    <label>Amount sent from current Schedule</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Day_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Month__c</fullName>
    <label>Day of Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>15th</fullName>
            </value>
            <value>
                <fullName>Last</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drawdown_Amount__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Amount__c</fullName>
    <label>Drawdown Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Payment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Default_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Default_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bank Account Scheduled Facility payments should to go if they are not going to the Primary Bank Account set on the Account</description>
    <label>Payment Default Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Allotted_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Allotted_Amount__c</fullName>
    <label>Payment Schedule Allotted Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Mode__c</fullName>
    <label>Payment Schedule Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Send_First_Immediately__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Send_First_Immediately__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send First Payment Immediately</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Version_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment Schedule Version Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Scheduled_Allotment_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Payment_Scheduled_Allotment_Remaining__c</fullName>
    <formula>MIN(
    Amount_Available_for_Scheduled_Payments__c,
				Payment_Schedule_Allotted_Amount__c - Amount_sent_from_current_Schedule__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Scheduled Allotment Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Use_Primary_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Use_Primary_Bank_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Do Scheduled Facility Payments use the Primary Bank Account?</description>
    <label>Payment Use Primary Bank Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Opportunity_Schedule_Version_Val__c.field-meta.xml
<CustomField>
    <fullName>Current_Opportunity_Schedule_Version_Val__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Had to move this away from the formula I was using for roll-up filtering</description>
    <label>Current Opportunity Schedule Version Val</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&#39;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTriggerScheduleHandler.cls
public class OpportunityTriggerScheduleHandler extends TriggerHandler {
    private Map<Id, Opportunity> newMap;
    private Map<Id, Opportunity> oldMap;
    private Opportunity[] newList;
    private Opportunity[] oldList;
    String[] paymentVersionChangeFields = new String[]{
        'Payment_Schedule_Mode__c',
        'Payment_Use_Primary_Bank_Account__c',
        'Payment_Default_Bank_Account__c',
        'Day_of_Month__c',
        'Start_Date__c',
        'End_Date__c',
        'Drawdown_Amount__c',
        'Payment_Schedule_Allotted_Amount__c',
        'Payment_Schedule_Send_First_Immediately__c'
    };
    private Id[] updatePaymentVersion = new Id[]{};
    private Id[] needsPaymentsCalculated = new Id[]{};

    public OpportunityTriggerScheduleHandler() {
        this.newMap = (Map<Id, Opportunity>) Trigger.newMap;
        this.oldMap = (Map<Id, Opportunity>) Trigger.oldMap;
        if (this.oldMap == null) {
            this.oldMap = new Map<Id, Opportunity>();
        }
        this.newList = (Opportunity[]) Trigger.new;
        this.oldList = (Opportunity[]) Trigger.old;
    }

    public override void beforeInsert() {
        for (Opportunity opp : this.newList) {
            if (opp.Payment_Schedule__c == 'Yes') {
                opp.Payment_Schedule_Version_Number__c = 1;
            }
        }
    }

    public override void beforeUpdate() {
        for (Opportunity newOpp : this.newMap.values()) {
            Opportunity oldOpp = this.oldMap.get(newOpp.Id);
            System.debug(newOpp);
            System.debug(newOpp.Payment_Schedule__c);
            if (newOpp.Payment_Schedule__c == 'Yes') {
                this.detectScheduleVersionChange(oldOpp, newOpp);
            }
        }
    }

    public override void afterInsert() {
        handlePaymentSchedule();
    }

    public override void afterUpdate() {
        setOutOfDatePayments();
        handlePaymentSchedule();
    }

    private void detectScheduleVersionChange(Opportunity oldOpp, Opportunity newOpp) {
        if (oldOpp.Payment_Schedule__c == 'No') {
            if (newOpp.Payment_Schedule_Version_Number__c == null) {
                newOpp.Payment_Schedule_Version_Number__c = 1;
            } else {
                newOpp.Payment_Schedule_Version_Number__c += 1;
            }
            newOpp.Amount_sent_from_current_Schedule__c = 0.00; // reset Sent Amount
            return;
        }
        for (String field : this.paymentVersionChangeFields) {
            if (oldOpp.get(field) != newOpp.get(field)) {
                if (newOpp.Payment_Schedule_Version_Number__c == null) {
                    newOpp.Payment_Schedule_Version_Number__c = 1;
                } else {
                    newOpp.Payment_Schedule_Version_Number__c += 1;
                }
                newOpp.Amount_sent_from_current_Schedule__c = 0.00; // reset Sent Amount
                // If this works I can stop watching Current Version manually
                if (oldOpp.Payment_Schedule__c == 'Yes') // Only update SPs if there was an active schedule to begin with
                    this.updatePaymentVersion.add(newOpp.Id);
                return;
            }
        }
    }

    private void setOutOfDatePayments() {        
        if (this.updatePaymentVersion.isEmpty())
            return;
        Scheduled_Payment__c[] spList = [Select Id From Scheduled_Payment__c Where Opportunity__c in :this.updatePaymentVersion and Current_Opportunity_Schedule_Version_Val__c = true and Status__c not in :Constants.PAYMENT_SCHEDULE_MODIFIABLE_STATUSES];
        System.debug(spList);
        for (Scheduled_Payment__c sp : spList) {
            sp.Current_Opportunity_Schedule_Version_Val__c = false;
        }
        if (!spList.isEmpty()) {
            update spList;
        }
    }


    private void handlePaymentSchedule() {
        // Need to update version on Scheduled Payments. Do I need to do this? Won't recalculate get them?
        Id[] needsRecalculated = new Id[]{};
        Map<Id, Opportunity> testMap = new Map<Id, Opportunity>();
        Opportunity oldOpp = null;
        for (Opportunity newOpp : this.newMap.values()) {
            if (newOpp.Payment_Schedule__c == 'Yes') {
                if (this.oldMap.containsKey(newOpp.Id)) {
                    oldOpp = this.oldMap.get(newOpp.Id);
                    if (oldOpp.Payment_Schedule_Version_Number__c != newOpp.Payment_Schedule_Version_Number__c) {
                        this.updatePaymentVersion.add(newOpp.Id);
                    }
                    if (oldOpp.Payment_Schedule__c == 'No' || 
                        oldOpp.Payment_Schedule_Version_Number__c != newOpp.Payment_Schedule_Version_Number__c ||
                        oldOpp.Payment_Scheduled_Allotment_Remaining__c != newOpp.Payment_Scheduled_Allotment_Remaining__c
                        ) {
                        this.needsPaymentsCalculated.add(newOpp.Id);
                    }
                } else {
                    // Insert
                    this.needsPaymentsCalculated.add(newOpp.Id);
                }
            }
        }
        setOutOfDatePayments();
        recalculatePayments();
    }

    private void recalculatePayments() {
        if (!this.needsPaymentsCalculated.isEmpty()) {
            PaymentHelper.recalculatePayments(this.needsPaymentsCalculated);
        }
    }
}