force-app/main/default/objects/Opportunity/fields/Day_of_Month__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Month__c</fullName>
    <label>Day of Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st</fullName>
            </value>
            <value>
                <fullName>15th</fullName>
            </value>
            <value>
                <fullName>Last</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drawdown_Amount__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Amount__c</fullName>
    <label>Drawdown Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>Payment End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Default_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Default_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bank Account Scheduled Facility payments should to go if they are not going to the Primary Bank Account set on the Account</description>
    <label>Payment Default Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule__c</fullName>
    <label>Payment Schedule</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Mode__c</fullName>
    <label>Payment Schedule Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Amount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Send_First_Immediately__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Send_First_Immediately__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send First Payment Immediately</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Schedule_Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Schedule_Version_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Payment Schedule Version Number</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Scheduled_Allotment_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Payment_Scheduled_Allotment_Remaining__c</fullName>
    <formula>MIN(
    Amount_Available_for_Scheduled_Payments__c,
				Payment_Schedule_Allotted_Amount__c - Amount_sent_from_current_Schedule__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Scheduled Allotment Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Use_Primary_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payment_Use_Primary_Bank_Account__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Do Scheduled Facility Payments use the Primary Bank Account?</description>
    <label>Payment Use Primary Bank Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Payment Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Previous_Loan__c/Previous_Loan__c.object-meta.xml
<CustomObject>
    <description>Stores information about a client&#39;s previous litigation loans</description>
    <label>Previous Loan</label>
    <nameField>
        <label>Previous Loan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Previous Loans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Previous_Loan__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Previous_Loan__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Previous Loans</relationshipLabel>
    <relationshipName>Previous_Loans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Previous_Loan__c/fields/Scheduled_Payment__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scheduled Payment</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>Scheduled_Payment__c.Opportunity__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Scheduled_Payment__c</referenceTo>
    <relationshipLabel>Previous Loans</relationshipLabel>
    <relationshipName>Previous_Loans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Previous_Loan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Keeps track of status automatically. &#39;Collecting Information&#39; &gt; &#39;Ready to Schedule&#39;, &#39;Payout Date Expired&#39; &gt; {Scheduled Payment&#39;s Status}</description>
    <formula>IF(
    NOT(ISBLANK(TEXT(Scheduled_Payment__r.Status__c))),
    TEXT(Scheduled_Payment__r.Status__c),
    IF(
        AND(
            NOT(ISBLANK(Lender__c)),
            Amount__c &gt; 0,
            Payout_Statement_on_File__c = TRUE,
            NOT(ISBLANK(Date_Payout_Valid_Until__c))
        ),
        IF(
            Date_Payout_Valid_Until__c &lt; TODAY(),
            &#39;Payout Date Expired&#39;,
            &#39;Ready to Schedule&#39;
        ),
        &#39;Collecting Information&#39;
    )
)</formula>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/Scheduled_Payment__c.object-meta.xml
<CustomObject>
    <label>Scheduled Payment</label>
    <nameField>
        <displayFormat>PS-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scheduled_Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Account that payment should be sent to (will default to Opportunity Account if not set)</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Bank account that we send the funds to</description>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.Client__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Current_Bank_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Current_Bank_Account_Name__c</fullName>
    <description>Gets the bank account name that would currently be used if the payment was processed.</description>
    <formula>IF(
    Send_Cheque__c,
    &#39;SEND CHEQUE to &#39; + IF(ISBLANK(Account__c), Opportunity__r.Account.Name, Account__r.Name),
    IF(
        ISBLANK(Sent_to_Bank_Account__c),
        IF(
            Use_Primary_Bank_Account__c,
            IF(
                OR(ISBLANK(Account__c), Account__c = Opportunity__r.AccountId),
                IF(
                    ISBLANK(Opportunity__r.Account.Primary_Bank_Account__c),
                    &#39;**NONE SELECTED**&#39;,
                    Opportunity__r.Account.Primary_Bank_Account__r.Name
                ),
                IF(
                    ISBLANK(Account__r.Primary_Bank_Account__c),
                    &#39;**NONE SELECTED**&#39;,
                    Account__r.Name + &#39; - &#39; + Account__r.Primary_Bank_Account__r.Name
                )
            ),
            IF(
                ISBLANK(Bank_Account__c),
                &#39;**NONE SELECTED**&#39;,
                IF(
                    NOT(Bank_Account__r.Client__c = Opportunity__r.AccountId),
                    Bank_Account__r.Client__r.Name + &#39; - &#39; + Bank_Account__r.Name,
                    Bank_Account__r.Name
                )
            )
        ),
        Sent_to_Bank_Account__r.Name
    )
)</formula>
    <label>Current Bank Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Hold__c.field-meta.xml
<CustomField>
    <fullName>Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do not allow this payment to processed for now.</inlineHelpText>
    <label>Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lump-Sum</fullName>
            </value>
            <value>
                <fullName>Ad-Hoc</fullName>
            </value>
            <value>
                <fullName>Scheduled Facility</fullName>
            </value>
            <value>
                <fullName>Treatment</fullName>
            </value>
            <value>
                <fullName>Payment to Other Lender</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Loan Payout</fullName>
                <isActive>false</isActive>
                <label>Loan Payout</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Previous_Loan__c.field-meta.xml
<CustomField>
    <fullName>Previous_Loan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Loan</label>
    <referenceTo>Previous_Loan__c</referenceTo>
    <relationshipLabel>Scheduled Payments</relationshipLabel>
    <relationshipName>Scheduled_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Sent_to_Bank_Date__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Bank_Date__c</fullName>
    <description>Date and Time this payment was included in a banking sheet</description>
    <label>Sent to Bank Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Scheduled_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Pre Send Validation</fullName>
            </value>
            <value>
                <fullName>Approved to Send</fullName>
            </value>
            <value>
                <fullName>Sent to Bank</fullName>
            </value>
            <value>
                <fullName>Processed by Bank</fullName>
            </value>
            <value>
                <fullName>Drawdown Created</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Won&#39;t Send</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentController.cls
/**
*    @description : Apex class to create payments for facility loans
**/
public with sharing class PaymentController {
    
    /**
    * @description Method to calculate payments for facility loans
    * @param opportunityId Id of the opportunity record
    * @return List<Scheduled_Payment__c> List of payments to create
    **/
    @AuraEnabled
    public static List<Scheduled_Payment__c> calculatePayments(Id opportunityId){
        if(opportunityId != null){
            List<Opportunity> opportunityList = [
                SELECT 
                    Id,
                    Payment_Schedule_Version_Number__c,
                    AccountId,
                    Payment_Scheduled_Allotment_Remaining__c,
                    Day_of_Month__c,
                    Start_Date__c,
                    End_Date__c,
                    Drawdown_Amount__c,
                    Payment_Schedule_Mode__c,
                    Payment_Use_Primary_Bank_Account__c,
                    Payment_Default_Bank_Account__c,
                    Payment_Schedule_Send_First_Immediately__c,
                    (SELECT Id FROM Scheduled_Payments__r Where Payment_Type__c = 'Scheduled Facility' AND Status__c not in :Constants.PAYMENT_SCHEDULE_MODIFIABLE_STATUSES)
                FROM Opportunity
                WHERE Id =: opportunityId LIMIT 1];
            if(!opportunityList.isEmpty()){
                if(opportunityList[0].Payment_Schedule_Mode__c == Constants.PAYMENT_MODE_AMOUNT){
                    if (opportunityList[0].Start_Date__c != null){
                        return PaymentHelper.calculatePaymentsForAmount(opportunityList[0], null, null);
                    }
                }else if(opportunityList[0].Payment_Schedule_Mode__c == Constants.PAYMENT_MODE_DATE){
                    if (opportunityList[0].Start_Date__c != null & opportunityList[0].End_Date__c != null){
                        return PaymentHelper.calculatePaymentsForDate(opportunityList[0], null, null);
                    }
                }
            }
        }
        return new List<Scheduled_Payment__c>();
    }

    /**
    * @description Method to delete payments on scheduled status
    * @param opportunityId Id of the opportunity record
    * @return void
    **/
    @AuraEnabled
    public static void deletePayments(Id opportunityId){
        if(opportunityId != null){
            delete [SELECT Id FROM Scheduled_Payment__c WHERE Opportunity__c =: opportunityId AND Status__c = 'Scheduled' AND Payment_Type__c = 'Scheduled Facility' LIMIT 30000];
        }
    }

    /**
    * @description Method to create payments
    * @param opportunityId Id of the opportunity record
    * @param paymentsList List of payments to create
    * @return Boolean returns true if payments created sucessfully
    **/
    @AuraEnabled
    public static Boolean createPayments(Id opportunityId, List<Scheduled_Payment__c> paymentsList){
        if(paymentsList != null && !paymentsList.isEmpty()){
            // update opportunity
            Opportunity opportunity = new Opportunity(Id=opportunityId,Payment_Schedule__c='Yes');
            update opportunity;
            insert paymentsList;
            return true;
        }
        return false;
    }

    /**
    * @description Method to create payments
    * @param opportunityId Id of the opportunity record
    * @return Boolean returns true if payments created sucessfully
    **/
    @AuraEnabled
    public static Map<String, Object> getPayments(Id opportunityId, String fieldSetName){
        // TODO filter based on Payment Type for Facility Payment Scheduler
        Map<String,Object> objectsMap = new Map<String,Object>();
        List<String> fieldsList = SchemaHelper.getFieldsFromFieldsSet(Scheduled_Payment__c.sObjectType.getDescribe().getName(),fieldSetName);
        // add datatable fields
        objectsMap.put('columns',SchemaHelper.getDataTableFields(Scheduled_Payment__c.sObjectType.getDescribe().getName(),fieldsList));
        // add records
        String soqlQuery = 'SELECT Id, '+String.join(fieldsList,',')+' FROM '+Scheduled_Payment__c.sObjectType.getDescribe().getName()+' WHERE '+Scheduled_Payment__c.Opportunity__c.getDescribe().getName()+' = \''+opportunityId+'\' AND Payment_Type__c = \'Scheduled Facility\' ORDER BY '+Scheduled_Payment__c.Scheduled_Date__c.getDescribe().getName()+' LIMIT 15000';
        objectsMap.put('records',(List<Scheduled_Payment__c>)Database.query(soqlQuery));
        return objectsMap;
    }


    @AuraEnabled(cacheable=true)
    public static List<Scheduled_Payment__c> getScheduledPayments(Id opportunityId) {//, String paymentType, List<String> statusChoices, Date filterDate){
        return [SELECT
                    Id,
                    Hold__c,
                    Notes__c,
                    Current_Bank_Account_Name__c,
                    Status__c,
                    Payment_Type__c,
                    Amount__c,
                    Scheduled_Date__c,
                    Sent_to_Bank_Date__c
                FROM Scheduled_Payment__c WHERE Opportunity__c = :opportunityId AND Status__c != 'Closed'];
    }

    @AuraEnabled(cacheable=true)
    public static List<Previous_Loan__c> getPreviousLoans(Id opportunityId) {//, String paymentType, List<String> statusChoices, Date filterDate){
        return [
            SELECT
                Id,
                Name,
                Amount__c,
                Lender__r.Id,
                Lender__r.Name,
                Status__c,
                Payout_Statement_on_File__c,
                Date_Payout_Valid_Until__c,
                Scheduled_Payment__c
            FROM Previous_Loan__c
            WHERE 
                (Opportunity__c = :opportunityId and Opportunity__c != NULL)
                //OR
                //(Lead__c = :leadId and Lead__c != NULL)
        ];
    }


    @AuraEnabled(cacheable=false)
    public static Bank_Account__c[] getBankAccountOptions(Id oppId) {
        Opportunity opp = [Select AccountId From Opportunity Where Id = :oppId];
        return [Select Id, Name, Is_Primary_Account__c From Bank_Account__c Where Client__c = :opp.AccountId Order By Is_Primary_Account__c DESC, Name ASC];
    }
}