force-app/main/default/objects/Contact/fields/Any_SpousalChild_support_payment__c.field-meta.xml
<CustomField>
    <fullName>Any_SpousalChild_support_payment__c</fullName>
    <label>Any SpousalChild support payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Do_you_have_any_dependants__c.field-meta.xml
<CustomField>
    <fullName>Do_you_have_any_dependants__c</fullName>
    <label>Do you have any dependants</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Employment_status_at_time_of_accident__c.field-meta.xml
<CustomField>
    <fullName>Employment_status_at_time_of_accident__c</fullName>
    <label>Employment status at time of accident</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Self-employed</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Have_you_ever_been_in_arrears_on_payment__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_been_in_arrears_on_payment__c</fullName>
    <label>Have you ever been in arrears on payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Have_you_ever_declared_bankruptcy__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_declared_bankruptcy__c</fullName>
    <label>Have you ever declared bankruptcy?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Married/Common Law</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_History__c/Contact_History__c.object-meta.xml
<CustomObject>
    <label>Contact History</label>
    <nameField>
        <displayFormat>CH-{0000}</displayFormat>
        <label>Contact History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_History__c/fields/Alternate_Phone__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Phone__c</fullName>
    <label>Alternate Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact_History__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Activity_Historys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_History__c/fields/Date_of_update__c.field-meta.xml
<CustomField>
    <fullName>Date_of_update__c</fullName>
    <label>Date of update</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Any_SpousalChild_support_payment__c.field-meta.xml
<CustomField>
    <fullName>Any_SpousalChild_support_payment__c</fullName>
    <label>Any SpousalChild support payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Do_you_have_any_dependants__c.field-meta.xml
<CustomField>
    <fullName>Do_you_have_any_dependants__c</fullName>
    <label>Do you have any dependants?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Employment_status_at_time_of_accident__c.field-meta.xml
<CustomField>
    <fullName>Employment_status_at_time_of_accident__c</fullName>
    <label>Employment status at time of accident</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Self-employed</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Existing_Litigation_Loans__c.field-meta.xml
<CustomField>
    <fullName>Existing_Litigation_Loans__c</fullName>
    <label>Existing Litigation Loans</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Have_you_ever_been_in_arrears_on_payment__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_been_in_arrears_on_payment__c</fullName>
    <label>Have you ever been in arrears on payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Have_you_ever_declared_bankruptcy__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_declared_bankruptcy__c</fullName>
    <label>Have you ever declared bankruptcy?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Married/Common Law</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Lender Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Existing_Litigation_Loans__c.field-meta.xml
<CustomField>
    <fullName>Existing_Litigation_Loans__c</fullName>
    <label>Existing Litigation Loans</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Have_you_ever_declared_bankruptcy__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_declared_bankruptcy__c</fullName>
    <label>Have you ever declared bankruptcy?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RDS_AccountPrintableViewCtlr.cls
public with sharing class RDS_AccountPrintableViewCtlr {
    ApexPages.StandardController controller;

    RDS_SObject accRSObj;
    public Account accSObj {get; set;}
    
    RDS_SObject contactRSObj;
    public Contact conSObj {get; set;}
    
    RDS_SObject oppRSObj;
    public Opportunity oppSObj {get; set;}
    String sObjId{get;set;}

    public List<Contact_History__c> lstConHistory {get;set;}

    // Begin: Code added by AppCentrica to allow parity with Lead printable view
    public List<String> getMartialStatusOptions() {
        return RDS_Util.getPicklistOptions(Contact.Marital_Status__c.getDescribe());
    }
    public List<String> getSpousalChildPaymentOptions() {
        return RDS_Util.getPicklistOptions(Contact.Any_SpousalChild_support_payment__c.getDescribe());
    }
    public List<String> getArrearsPaymentOptions() {
        return RDS_Util.getPicklistOptions(Contact.Have_you_ever_been_in_arrears_on_payment__c.getDescribe());
    }
    public List<String> getDependentOptions() {
        return RDS_Util.getPicklistOptions(Contact.Do_you_have_any_dependants__c.getDescribe());
    }
    public List<String> getBankruptcyOptions() {
        return RDS_Util.getPicklistOptions(Contact.Have_you_ever_declared_bankruptcy__c.getDescribe());
    }
    public List<String> getEmploymentOptions() {
        return RDS_Util.getPicklistOptions(Contact.Employment_status_at_time_of_accident__c.getDescribe());
    }
    public List<String> getLitigationOptions() {
        return RDS_Util.getPicklistOptions(Opportunity.Existing_Litigation_Loans__c.getDescribe());
    }
    
    // End: Code added by AppCentrica to allow parity with Lead printable view
    
    public RDS_AccountPrintableViewCtlr(ApexPages.StandardController controller) {
        /**
         * initialize on page load
         */
        this.controller = controller;
        sObjId = this.controller.getRecord().id;

        initAccountTab();
    }

    public void initAccountTab() {
        SObject sObj = controller.getRecord(); 
        List<Contact> lstcont = new List<Contact>();       
        if(sObj.id != null) {
            accRSObj = new RDS_SObject(sObj);
            accRSObj.initFromDb(null);
            accRSObj.initFromDb('(Select id from Opportunities order by createddate asc limit 1),(Select id from Contacts order by createddate asc limit 1)');
            accSObj = (Account) accRSObj.sObj;
            system.debug('1111'+accSObj);

            /**
            * query related Contact
            */
            if(accSObj.Contacts.size() > 0) {
                contactRSObj = new RDS_SObject(accSObj.Contacts[0]);
            }
            contactRSObj.initFromDb('');
            conSObj = (Contact) contactRSObj.sObj;
            system.debug('2222'+accSObj);

            /**
             * query related opportunity
             */
            // AC 2017-02-01: reversed order of && arguments to avoid list index out of bounds
            if(accSObj.Opportunities.size() > 0 && accSObj.Opportunities[0] != null) {
                oppRSObj = new RDS_SObject(accSObj.Opportunities[0]);
                // AC 2017-02-01: Brought the following two lines into the if block
                // to avoid null exceptions when no Opportunity attached
                oppRSObj.initFromDb(null);
                oppSObj = (Opportunity)oppRSObj.sObj;
            }
            //oppRSObj.initFromDb('(Select id from Opportunities order by createddate desc limit 1)');
            system.debug('3333'+accSObj);
        }
        /**
         *feedback changes 19/08/16
         */
        if(sObjId != null && sObjId != ''){
            lstcont = [Select Id,AccountId 
                              from Contact 
                              where AccountId =:sObjId];
        }

        lstConHistory = new List<Contact_History__c>();
        if(lstcont.size() > 0){
            lstConHistory = [Select id,lastmodifieddate,
                                    Address__c,
                                    Alternate_Phone__c,
                                    Date_of_update__c,
                                    Email__c,
                                    Phone__c,
                                    Contact__c
                                    from Contact_History__c 
                                    where Contact__c =:lstcont[0].Id order by lastmodifieddate desc];
        }
    }
}