force-app/main/default/objects/Contact/fields/Any_SpousalChild_support_payment__c.field-meta.xml
<CustomField>
    <fullName>Any_SpousalChild_support_payment__c</fullName>
    <label>Any SpousalChild support payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Employment_status_at_time_of_accident__c.field-meta.xml
<CustomField>
    <fullName>Employment_status_at_time_of_accident__c</fullName>
    <label>Employment status at time of accident</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Self-employed</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Have_you_ever_been_in_arrears_on_payment__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_been_in_arrears_on_payment__c</fullName>
    <label>Have you ever been in arrears on payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Have_you_ever_declared_bankruptcy__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_declared_bankruptcy__c</fullName>
    <label>Have you ever declared bankruptcy?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Married/Common Law</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Any_SpousalChild_support_payment__c.field-meta.xml
<CustomField>
    <fullName>Any_SpousalChild_support_payment__c</fullName>
    <label>Any SpousalChild support payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Employment_status_at_time_of_accident__c.field-meta.xml
<CustomField>
    <fullName>Employment_status_at_time_of_accident__c</fullName>
    <label>Employment status at time of accident</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Full-time</fullName>
            </value>
            <value>
                <fullName>Part-time</fullName>
            </value>
            <value>
                <fullName>Self-employed</fullName>
            </value>
            <value>
                <fullName>Unemployed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Existing_Litigation_Loans__c.field-meta.xml
<CustomField>
    <fullName>Existing_Litigation_Loans__c</fullName>
    <label>Existing Litigation Loans</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Have_you_ever_been_in_arrears_on_payment__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_been_in_arrears_on_payment__c</fullName>
    <label>Have you ever been in arrears on payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Have_you_ever_declared_bankruptcy__c.field-meta.xml
<CustomField>
    <fullName>Have_you_ever_declared_bankruptcy__c</fullName>
    <label>Have you ever declared bankruptcy?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lawyer_Name_new__c.field-meta.xml
<CustomField>
    <fullName>Lawyer_Name_new__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Married/Common Law</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RDS_LeadEditCtlrTest.cls
@isTest
public with sharing class RDS_LeadEditCtlrTest {
	public RDS_LeadEditCtlrTest() {
		
	}
	static testMethod void LeadEditTest() {

		Account acc = ELUtilTest.createAccount();
		Contact con = ELUtilTest.createContact(acc.Id);

		Lead l = new lead( FirstName='New Lead',LastName = 'Hussy',Title ='Developer',Company = 'Wipro',Status = 'New',Marital_Status__c = 'Single',Any_SpousalChild_support_payment__c ='Yes',Have_you_ever_been_in_arrears_on_payment__c = 'No',Have_you_ever_declared_bankruptcy__c = 'Yes',Existing_Litigation_Loans__c = 'Yes',Employment_status_at_time_of_accident__c = 'Full-time',Lawyer_Name_new__c = con.id);
		insert l; 
		PageReference pageRef = Page.RDS_LeadEdit;
		Test.setCurrentPage(pageRef); 
		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(l); 
		ApexPages.currentPage().getParameters().put('Id',l.id);
    
		
		RDS_LeadEditCtlr Le = new RDS_LeadEditCtlr(sc);
		Le.leadObj = l;

		System.debug('leadid'+l.id);

		
        System.assertNotEquals(null,pageRef);
		
		List<selectOption> spousalSupportPayments_options = Le.getSpousalSupportPayments();
		System.AssertNotEquals(0, spousalSupportPayments_options.size());
		
		List<selectOption> arrearsPayments_options = Le.getArrearsPayments();
		System.AssertNotEquals(0, arrearsPayments_options.size());
		
		List<selectOption> bankruptcies_options = Le.getbankruptcies();
		System.AssertNotEquals(0, bankruptcies_options.size());
		
		List<selectOption> litigations_options = Le.getLitigations();
		System.AssertNotEquals(0, litigations_options.size());
		
		List<selectOption> employment_options = Le.getEmployments();
		System.AssertNotEquals(0, employment_options.size());

		List<selectOption> maritalStatus_options = Le.getMaritalStatuss();
        System.AssertNotEquals(0, maritalStatus_options.size());

		string search = Le.getsearchCategory();
		Le.setsearchCategory(search);
		String nextPage = Le.saveLead().getUrl();
		System.debug('Next'+nextPage);
		//Le.cloneLead();
		Le.cancelLead();
		Le.deleteLead();
		Le.ConvertLead();
        Le.findDuplicates();

        
        RDS_LeadEditCtlr.getCreatableFieldsSOQL('lead','Id=' + '\'' + l.id + '\'');
		
		System.assertEquals('/apex/RDS_LeadView?id='+l.id,nextPage);
	}
	static testMethod void LeadEditTestForNull() {

		Account acc = ELUtilTest.createAccount();
		Contact con = ELUtilTest.createContact(acc.Id);

		Lead l = new lead( FirstName='New Lead',LastName = 'Hussy',Title ='Developer',Company = 'Wipro',Status = 'New',Marital_Status__c = 'Single',Any_SpousalChild_support_payment__c ='Yes',Have_you_ever_been_in_arrears_on_payment__c = 'No',Have_you_ever_declared_bankruptcy__c = 'Yes',Existing_Litigation_Loans__c = 'Yes',Employment_status_at_time_of_accident__c = 'Full-time',Lawyer_Name_new__c = con.id);
		insert l; 
		PageReference pageRef = Page.RDS_LeadEdit;
		Test.setCurrentPage(pageRef); 
		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(l); 
		
		RDS_LeadEditCtlr Le = new RDS_LeadEditCtlr(sc);
		Le.leadObj = l;
		
		System.assertNotEquals(null,pageRef);
	}
	static testMethod void LeadEditTestClone() {

		Account acc = ELUtilTest.createAccount();
		Contact con = ELUtilTest.createContact(acc.Id);

		Lead l = new lead( FirstName='New Lead',LastName = 'Hussy',Title ='Developer',Company = 'Wipro',Status = 'New',Marital_Status__c = 'Single',Any_SpousalChild_support_payment__c ='Yes',Have_you_ever_been_in_arrears_on_payment__c = 'No',Have_you_ever_declared_bankruptcy__c = 'Yes',Existing_Litigation_Loans__c = 'Yes',Employment_status_at_time_of_accident__c = 'Full-time',Lawyer_Name_new__c = con.id);
		insert l; 
		PageReference pageRef = Page.RDS_LeadEdit;
		Test.setCurrentPage(pageRef); 
		ApexPages.Standardcontroller sc = new ApexPages.Standardcontroller(l); 
		ApexPages.currentPage().getParameters().put('Id',l.id);
    
		
		RDS_LeadEditCtlr Le = new RDS_LeadEditCtlr(sc);
		Le.leadObj = l;

		System.debug('leadid'+l.id);

		
        System.assertNotEquals(null,pageRef);
		
		List<selectOption> spousalSupportPayments_options = Le.getSpousalSupportPayments();
		System.AssertNotEquals(0, spousalSupportPayments_options.size());
		
		List<selectOption> arrearsPayments_options = Le.getArrearsPayments();
		System.AssertNotEquals(0, arrearsPayments_options.size());
		
		List<selectOption> bankruptcies_options = Le.getbankruptcies();
		System.AssertNotEquals(0, bankruptcies_options.size());
		
		List<selectOption> litigations_options = Le.getLitigations();
		System.AssertNotEquals(0, litigations_options.size());
		
		List<selectOption> employment_options = Le.getEmployments();
		System.AssertNotEquals(0, employment_options.size());

		List<selectOption> maritalStatus_options = Le.getMaritalStatuss();
        System.AssertNotEquals(0, maritalStatus_options.size());

		string search = Le.getsearchCategory();
		Le.setsearchCategory(search);
		String nextPage = Le.saveLead().getUrl();
		System.debug('Next'+nextPage);
		Le.cloneLead();
		
		RDS_LeadEditCtlr.getCreatableFieldsSOQL('lead','Id=' + '\'' + l.id + '\'');
		
		System.assertEquals('/apex/RDS_LeadView?id='+l.id,nextPage);
	}
}