force-app/main/default/objects/Contact/fields/Approved_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Approved_Credit_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Approved Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Available_Credit__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit__c</fullName>
    <formula>Approved_Credit_Limit__c - Utilized_Credit_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Pre_approved_Amount_Roll_Up__c.field-meta.xml
<CustomField>
    <fullName>Pre_approved_Amount_Roll_Up__c</fullName>
    <label>Pre-approved Amount Roll Up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Principal_Repaid_Roll_up__c.field-meta.xml
<CustomField>
    <fullName>Principal_Repaid_Roll_up__c</fullName>
    <label>Principal Repaid Roll up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Utilized_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Utilized_Credit_Limit__c</fullName>
    <formula>(Amount_wo_Payment_Roll_up__c) - Principal_Repaid_Roll_up__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Utilized Credit Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Admin_Fee_Roll_up__c.field-meta.xml
<CustomField>
    <fullName>Admin_Fee_Roll_up__c</fullName>
    <label>Admin Fee Roll-up</label>
    <summarizedField>Drawdown__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>equals</operation>
        <value>Admin Fee, Assessment Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Available_Credit__c.field-meta.xml
<CustomField>
    <fullName>Available_Credit__c</fullName>
    <formula>IF((Amount -  Admin_Fee__c -  Amount_Paid_to_Client__c )  &lt; 0 , 0 , (Amount -  Admin_Fee__c -  Amount_Paid_to_Client__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drawdown_Total_wo_Payment__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Total_wo_Payment__c</fullName>
    <label>Drawdown Total w/o Payment</label>
    <summarizedField>Drawdown__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>notEqual</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Drawdown__c.Reference_Notes__c</field>
        <operation>notEqual</operation>
        <value>Payment Rejected, Payment Re-processed, Referral Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Principal_Repaid_Roll_up__c.field-meta.xml
<CustomField>
    <fullName>Principal_Repaid_Roll_up__c</fullName>
    <label>Principal Repaid Roll up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Can_Edit_Approved_Credit_Limit__c.field-meta.xml
<CustomField>
    <fullName>Can_Edit_Approved_Credit_Limit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Edit Approved Credit Limit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LawyerAvailableCreditComponentCtlr.cls
public with sharing class LawyerAvailableCreditComponentCtlr {
    
    @AuraEnabled
    public static User getCurrentUserInfo(){
        User currentUser = [SELECT Id, isActive, ProfileId, 
                            Can_Edit_Approved_Credit_Limit__c 
                            FROM User 
                            WHERE Id =: UserInfo.getUserId()];
        return currentUser;
    }
    
    @AuraEnabled
    public static Contact getLawyerRecordData(String recordId){
        Contact lawyerContact = [SELECT Id, Approved_Credit_Limit__c, 
                                 Utilized_Credit_Limit__c, Available_Credit__c,
                                 Pre_approved_Amount_Roll_Up__c
                                 FROM Contact 
                                 WHERE Id =: recordId];
        return lawyerContact;
    }
    
    @AuraEnabled 
    public static void updateLawyerRecord(Contact lawyerContact){
        try{
            update lawyerContact;
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage() + ' ' + e.getLineNumber());
        }
    }
    
    @auraEnabled
    public static List<Opportunity> OpportunityAssessment(String LawyerRecordId){
        List<Opportunity> LawyerOpportunityAssessmentData = [SELECT Id, Name, Principal_Repaid_Roll_up__c,
                                                             Admin_Fee_Roll_up__c, Drawdown_Total_wo_Payment__c 
                                                             FROM Opportunity 
                                                             WHERE Type_of_Loan__c = 'Assessment' 
                                                             AND lawyer__c =:LawyerRecordId];
        return LawyerOpportunityAssessmentData;
    }
    
    @auraEnabled
    public static  List<ContactHistory> CreditHistory(String recordId){
 		

        List<ContactHistory> historyList = [SELECT Field, OldValue, NewValue, 
                                            CreatedBy.Name, CreatedDate 
                                            FROM ContactHistory 
                                            WHERE Field = 'Approved_Credit_Limit__c' 
                                            AND contactId =: recordId];
        return historyList;
    }
}