force-app/main/default/objects/Contact/fields/Current_Proceedings__c.field-meta.xml
<CustomField>
    <fullName>Current_Proceedings__c</fullName>
    <label>Current Proceedings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Reviewed__c.field-meta.xml
<CustomField>
    <fullName>Date_Reviewed__c</fullName>
    <label>Date Reviewed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Next_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Review_Date__c</fullName>
    <label>Next Review Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <label>Orders</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Upcoming_Hearings__c.field-meta.xml
<CustomField>
    <fullName>Upcoming_Hearings__c</fullName>
    <label>Upcoming Hearings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Lawyers.recordType-meta.xml
<RecordType>
    <fullName>Lawyers</fullName>
    <active>true</active>
    <description>Use this record type to track lawyers</description>
    <label>Lawyers</label>
</RecordType>

force-app/main/default/classes/LawyerLawSocietyPageTabCtlr.cls
public with sharing class LawyerLawSocietyPageTabCtlr {
    
    @AuraEnabled
    public static Contact getLawyerInfo(Id recordId){
        return [SELECT Id, Name, Upcoming_Hearings__c, Current_Proceedings__c, 
                Orders__c, Date_Reviewed__c, Next_Review_Date__c
                FROM Contact 
                WHERE RecordType.DeveloperName = 'Lawyers' 
                AND Id = :recordId LIMIT 1];
    }
    
    @AuraEnabled
    public static List<Map<String,Object>> getContentNotes(Id recordId){
        
        return LawSocietyReviewController.getContentNotes(recordId);
    }
}