force-app/main/default/objects/Contact/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Payout_Date_Lawyer_Summary_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
    <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PayoutStatementControllerTest.cls
/**
*    @description : Test class for Payout Statement Controller
**/
@isTest(seeAllData=false)
private with sharing class PayoutStatementControllerTest {

	/**
	*    @description : Method to create contact map
	**/
    private static String createContactMap(){
    	return JSON.serialize(new Map<String, String>{'FirstName' => 'Test', 'LastName' => 'Test'});
    }

    /**
	*    @description : Method to create opportunity map
	**/
    private static String createOpportunityMap(){
    	return JSON.serialize(new Map<String, Object>{'Name' => 'Test', 'CloseDate' => System.today(), 'Payout_Date__c' => System.today()});
    }

    /**
	*    @description : Method to create drawdown map
	**/
    private static String createDrawdownMap(){
    	return JSON.serialize(new List<Drawdown__c>{new Drawdown__c(Amount__c=0.50),new Drawdown__c(Amount__c=0.80)});
    }
	
	/**
	*    @description : Test PayoutStatementController constructor
	**/
	@isTest
    static void test_PayoutStatementController(){
    	Test.startTest();
    	Test.setCurrentPage(new PageReference('/apex/x?contact='+createContactMap()+'&lawFirm=TestLawFirm&lawyer=SampleLawyer&principal=123.00&interest=45.00&balance=987.00&opportunity='+createOpportunityMap()+'&drawdowns='+createDrawdownMap())); 
    	PayoutStatementController cls = new PayoutStatementController();
    	System.assertEquals(2,cls.contactMap.size());
    	System.assertEquals('TestLawFirm',cls.lawFirm);
    	System.assertEquals('SampleLawyer',cls.lawyer);
    	System.assertEquals(3,cls.opportunityMap.size());
    	System.assertEquals(System.today(),cls.payoutDate);
    	System.assertEquals(2,cls.drawdownsList.size());
    	System.assertEquals(123.00,cls.principalDrawdown.Amount__c);
    	System.assertEquals(45.00,cls.accruedInterestDrawdown.Amount__c);
    	System.assertEquals(987.00,cls.outstandingBalanceDrawdown.Amount__c);
    	Test.stopTest();
    }
}