force-app/main/default/objects/Contact/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <formula>$Setup.Conga_batch_setting__c.Payout_Date_Lawyer_Summary_Report__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <description>The Payout Date pulled down from the Opportunity to work around calculated field length limitations.  Do not update directly here, update on Opportunity instead and let it replicate down.</description>
    <inlineHelpText>Expected or Actual Payout Date of the Drawdown.  Do not update directly here, update on Opportunity instead and let it replicate down to here.</inlineHelpText>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Per_Diem_as_of_Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Per_Diem_as_of_Payout_Date__c</fullName>
    <description>o	The daily interest rate (using a 365 base) on the total outstanding balance (Principle + Interest) at the payout date.   The Per Diem will be adjusted to zero in two scenarios:
1.	When the payout date is less than the minimum interest date.  In this situation, the interest accrued to 6 months is already included in the payout and therefore charging Per Diem would be double charging.  
2.	When the payout date is still within the interest deferral period.</description>
    <formula>If(
    OR((Payout_Date__c&lt;(ADDMONTHS(Date__c,Interest_Deferral_Period__c))),
       (Payout_Date__c&lt;(ADDMONTHS(Date__c,Minimum_Interest_Period__c))),
	    ISPICKVAL(Payment_Method__c , &quot;Payment&quot;))   
    ,0,
	(Interest_Rate__c/365)*Outstanding_Balance_as_of_Payout_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>The daily interest rate on the total outstanding balance at the payout date. The Per Diem will be adjusted to zero when the payout date is less than the minimum interest date and when payout date is within the interest deferral period.</inlineHelpText>
    <label>Per Diem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payout_Date__c.field-meta.xml
<CustomField>
    <fullName>Payout_Date__c</fullName>
    <label>Payout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PayoutStatementController.cls
/**
*    @description : Apex class to create payout statement
**/
public with sharing class PayoutStatementController {

	public Map<String, String> contactMap {get; private set;}
	public String lawFirm {get; private set;}
	public String lawyer {get; private set;}
	public Map<String, String> opportunityMap {get; private set;}
	public Date payoutDate {get; private set;}
	public List<Drawdown__c> drawdownsList {get; private set;}
	public Drawdown__c principalDrawdown {get; private set;}
	public Drawdown__c accruedInterestDrawdown {get; private set;}
	public Drawdown__c outstandingBalanceDrawdown {get; private set;}
	public Drawdown__c totalDiemDrawdown {get; private set;}
	public String businessUnit {get; private set;}

	/**
	* @description Constructor
	**/
	public PayoutStatementController() {
		this.contactMap = (Map<String, String>)JSON.deserialize(ApexPages.currentPage().getParameters().get('contact'),Map<String,String>.class);
		this.lawFirm =  ApexPages.currentPage().getParameters().get('lawFirm');
		this.lawyer =  ApexPages.currentPage().getParameters().get('lawyer');
		this.businessUnit = ApexPages.currentPage().getParameters().get('businessunit');
		this.opportunityMap = (Map<String, String>)JSON.deserialize(ApexPages.currentPage().getParameters().get('opportunity'),Map<String,String>.class);
		this.payoutDate = Date.valueOf(this.opportunityMap.get('Payout_Date__c'));
		this.drawdownsList = (List<Drawdown__c>)JSON.deserialize(ApexPages.currentPage().getParameters().get('drawdowns'),List<Drawdown__c>.class);
		this.principalDrawdown = new Drawdown__c(Amount__c=Decimal.valueOf(ApexPages.currentPage().getParameters().get('principal')));
		this.accruedInterestDrawdown = new Drawdown__c(Amount__c=Decimal.valueOf(ApexPages.currentPage().getParameters().get('interest')));
		this.outstandingBalanceDrawdown = new Drawdown__c(Amount__c=Decimal.valueOf(ApexPages.currentPage().getParameters().get('balance')));
		this.totalDiemDrawdown = new Drawdown__c(Amount__c=0.00);

		// loop through all the drawdowns and add Per_Diem_as_of_Payout_Date__c 
		for(Drawdown__c drawdown : this.drawdownsList){
			if(drawdown.Per_Diem_as_of_Payout_Date__c != null) this.totalDiemDrawdown.Amount__c += drawdown.Per_Diem_as_of_Payout_Date__c;
		}
	}
}