force-app/main/default/objects/Drawdown_Payment_Allocation__c/Drawdown_Payment_Allocation__c.object-meta.xml
<CustomObject>
    <description>All Payment allocations to Drawdowns.</description>
    <label>Drawdown Payment Allocation</label>
    <nameField>
        <displayFormat>PA-{00000}</displayFormat>
        <label>Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdown Payment Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown_Payment_Allocation__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <inlineHelpText>Payment associated with this Drawdown</inlineHelpText>
    <label>Payment</label>
    <referenceTo>Drawdown__c</referenceTo>
    <relationshipLabel>Drawdowns Allocated to this Payment</relationshipLabel>
    <relationshipName>Drawdowns_Allocated_to_this_Payment</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeletePaymentAllocations.cls
public with sharing class DeletePaymentAllocations {
/*------------------------------------------------------------
Author: Basil Dobek
Company: Deloitte
Description: A utility class to allocate a payment type Drawdown to an Advance type Drawdown.
             This clase creates "Drawdown Payment Allocation" objects to accomplish this.
			 Class is invokable so it can be called from Process Builder.
Inputs: 
	- 
History
<Date> <Authors Name> <Brief Description of Change>
------------------------------------------------------------*/

	@InvocableMethod(label='Delete Payment Allocations From Payment' description='Given a Drawdown of type Payment, Delete all of the Payment Allocations.  Used if amounts, dates, or types are changing')
	public static void DeletePaymentAllocationsFromPayment (List<Id> paymentIds) {

		//system.debug('xxxxxxxxxxxxxxxxxx Start Delete Payment Allocations From Payment xxxxxxxxxxxxxxxxxx');		
		//system.debug('xxxxxxxxxxxxxxxxxx Payment ID => '+paymentIds);

        List<Drawdown_Payment_Allocation__c> Payment_Allocations =[select id from Drawdown_Payment_Allocation__c
                          where payment__c in :paymentIds];
        delete Payment_Allocations;	
		//system.debug('xxxxxxxxxxxxxxxxxx Payment Allocations Deleted => '+Payment_Allocations.size());
		//system.debug('xxxxxxxxxxxxxxxxxx END Delete Payment Allocations From Payment xxxxxxxxxxxxxxxxxx');
		return;
	}
}