force-app/main/default/objects/Assessment_Provider_Schedule__c/Assessment_Provider_Schedule__c.object-meta.xml
<CustomObject>
    <label>Assessment Provider Schedule</label>
    <nameField>
        <displayFormat>APS-{0000}</displayFormat>
        <label>Assessment Provider Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Provider Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assessment_provider_schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <label>Lawyer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Lawyer contact must be of type Lawyer.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lawyers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Assessment_provider_schedules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Rebate_Discount__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Discount__c</fullName>
    <label>Rebate Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Rebate_Period__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Period__c</fullName>
    <label>Rebate Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>4 months</fullName>
            </value>
            <value>
                <fullName>8 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
            <value>
                <fullName>16 months</fullName>
            </value>
            <value>
                <fullName>20 months</fullName>
            </value>
            <value>
                <fullName>24 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessment Provider Referred Cases</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>

</CustomField>

force-app/main/default/objects/Opportunity/fields/Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Discount_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rebate_Discount__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Discount__c</fullName>
    <label>Rebate Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rebate_Period__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Period__c</fullName>
    <label>Rebate Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssessmentProviderScheduleTriggerHandler.cls
public with sharing class AssessmentProviderScheduleTriggerHandler {
    
    public static void updateAssessmentScheduleOnOpportunities(List<Assessment_Provider_Schedule__c> newSchedules, Map<Id, Assessment_Provider_Schedule__c> oldMap, Boolean isInsert){
        
        List<Assessment_Provider_Schedule__c> selSchedules = new List<Assessment_Provider_Schedule__c>();
        Map<String, Assessment_Provider_Schedule__c> assessmentScheduleMap = new Map<String, Assessment_Provider_Schedule__c>();
        Set<Id> aProviderIds = new Set<Id>();
        Set<Id> lawyerIds = new Set<Id>();
        
        for(Assessment_Provider_Schedule__c sch : newSchedules){
            if(sch.Assessment_Provider__c != null && sch.Lawyer__c != null && 
               (isInsert || (!isInsert && (sch.Assessment_Provider__c != oldMap.get(sch.Id).Assessment_Provider__c ||
                                           sch.Lawyer__c != oldMap.get(sch.Id).Lawyer__c || sch.Discount__c != oldMap.get(sch.Id).Discount__c ||
                                           sch.Rebate_Discount__c != oldMap.get(sch.Id).Rebate_Discount__c || 
                                           sch.Rebate_Period__c != oldMap.get(sch.Id).Rebate_Period__c)))){
                                               selSchedules.add(sch);
                                               aProviderIds.add(sch.Assessment_Provider__c);
                                               lawyerIds.add(sch.Lawyer__c);
                                           }
               }
        
        
        if(!selSchedules.isEmpty()){
            String key = '';
            for(Assessment_Provider_Schedule__c sch : [SELECT Id, Discount__c, Assessment_Provider__c, Lawyer__c, CreatedDate,
                                                                          Rebate_Discount__c, Rebate_Period__c
                                                                          FROM Assessment_Provider_Schedule__c
                                                                          WHERE Assessment_Provider__c in :aProviderIds
                                                                          AND Lawyer__c in :lawyerIds order by CreatedDate desc]){
                                                                              key = sch.Assessment_Provider__c + '-' + sch.Lawyer__c;
                                                                              if(!assessmentScheduleMap.containsKey(key))
                                                                                    assessmentScheduleMap.put(key, sch);

            }

            List<Opportunity> opportunities = [SELECT Id, Discount_Rate__c, Rebate_Discount__c, 
                                              Rebate_Period__c, Assessment_Provider__c, Lawyer__c
                                              FROM Opportunity 
                                              WHERE Lawyer__c in :lawyerIds AND Assessment_Provider__c in :aProviderIds
                                              AND StageName != 'Closed With Loan'
                                              AND StageName != 'Closed No Loan' AND StageName != 'TESTING'
                                              AND Type_of_Loan__c = 'Assessment'];

            for(Opportunity opp : opportunities){
                
                if(assessmentScheduleMap.containsKey(opp.Assessment_Provider__c + '-' + opp.Lawyer__c)){
                    Assessment_Provider_Schedule__c apsch = assessmentScheduleMap.get(opp.Assessment_Provider__c + '-' + opp.Lawyer__c);
                    opp.Discount_Rate__c = apsch.Discount__c;
                    opp.Rebate_Discount__c = apsch.Rebate_Discount__c;
                    String periodStr = apsch.Rebate_Period__c;
                    List<String> splited = periodStr != null? periodStr.split(' ') : new List<String>();
                    opp.Rebate_Period__c = !splited.isEmpty()? Integer.valueOf(splited[0]): null;
                }
                    
            }  
            if(!opportunities.isEmpty())    
                update opportunities;
        }
    }
}