force-app/main/default/objects/Assessment_Provider_Schedule__c/Assessment_Provider_Schedule__c.object-meta.xml
<CustomObject>
    <label>Assessment Provider Schedule</label>
    <nameField>
        <displayFormat>APS-{0000}</displayFormat>
        <label>Assessment Provider Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessment Provider Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Assessment_provider_schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <label>Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <label>Lawyer</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Lawyer contact must be of type Lawyer.</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lawyers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Assessment_provider_schedules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Rebate_Discount__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Discount__c</fullName>
    <label>Rebate Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Assessment_Provider_Schedule__c/fields/Rebate_Period__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Period__c</fullName>
    <label>Rebate Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 month</fullName>
            </value>
            <value>
                <fullName>4 months</fullName>
            </value>
            <value>
                <fullName>8 months</fullName>
            </value>
            <value>
                <fullName>12 months</fullName>
            </value>
            <value>
                <fullName>16 months</fullName>
            </value>
            <value>
                <fullName>20 months</fullName>
            </value>
            <value>
                <fullName>24 months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_wo_Payment_Roll_up__c.field-meta.xml
<CustomField>
    <fullName>Amount_wo_Payment_Roll_up__c</fullName>
    <label>Amount wo Payment Roll up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3</booleanFilter>
        <filterItems>
            <field>Account.Account_Type__c</field>
            <operation>equals</operation>
            <value>Lawyer, Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Law Firm</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clients</relationshipLabel>
    <relationshipName>Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Pre_approved_Amount_Roll_Up__c.field-meta.xml
<CustomField>
    <fullName>Pre_approved_Amount_Roll_Up__c</fullName>
    <label>Pre-approved Amount Roll Up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Principal_Repaid_Roll_up__c.field-meta.xml
<CustomField>
    <fullName>Principal_Repaid_Roll_up__c</fullName>
    <label>Principal Repaid Roll up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Assessment_Provider__c.field-meta.xml
<CustomField>
    <fullName>Assessment_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assessment Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Assessment Provider account must be of type Assessment Provider</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Assessment Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessment Provider Referred Cases</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>

</CustomField>

force-app/main/default/objects/Opportunity/fields/Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Discount_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Drawdown_Total_wo_Payment__c.field-meta.xml
<CustomField>
    <fullName>Drawdown_Total_wo_Payment__c</fullName>
    <label>Drawdown Total w/o Payment</label>
    <summarizedField>Drawdown__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>notEqual</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Drawdown__c.Reference_Notes__c</field>
        <operation>notEqual</operation>
        <value>Payment Rejected, Payment Re-processed, Referral Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Law_Firm__c.field-meta.xml
<CustomField>
    <fullName>Law_Firm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Law Firm</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lawyer__c.field-meta.xml
<CustomField>
    <fullName>Lawyer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lawyer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referred Cases</relationshipLabel>
    <relationshipName>Referred_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Principal_Repaid_Roll_up__c.field-meta.xml
<CustomField>
    <fullName>Principal_Repaid_Roll_up__c</fullName>
    <label>Principal Repaid Roll up</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rebate_Discount__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Discount__c</fullName>
    <label>Rebate Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rebate_Period__c.field-meta.xml
<CustomField>
    <fullName>Rebate_Period__c</fullName>
    <label>Rebate Period</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Stage_Status__c.field-meta.xml
<CustomField>
    <fullName>Stage_Status__c</fullName>
    <label>Stage Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>1st Week</fullName>
            </value>
            <value>
                <fullName>2nd Week</fullName>
            </value>
            <value>
                <fullName>File for Review</fullName>
            </value>
            <value>
                <fullName>Add&#39;l Docs Required</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>F/U with PC/Facility</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Assessor Declined</fullName>
            </value>
            <value>
                <fullName>Legal Representative Declined</fullName>
            </value>
            <value>
                <fullName>Non-Responsive (Legal Representative/Plaintiff)</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Contact Sheet Completed; Part I of App Sent to Lead for Signature</fullName>
            </value>
            <value>
                <fullName>Part II of App Sent to Firm w/ Request for Supporting Docs</fullName>
            </value>
            <value>
                <fullName>Waiting for Additional Supporting Documents</fullName>
            </value>
            <value>
                <fullName>Waiting for Payout From Other Lender</fullName>
            </value>
            <value>
                <fullName>File Sent to Assessors Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Client Signature</fullName>
            </value>
            <value>
                <fullName>Funds Advanced/Awaiting Signed Loan Documents</fullName>
            </value>
            <value>
                <fullName>Awaiting Final Lawyer Signature</fullName>
            </value>
            <value>
                <fullName>File Sent for EFT</fullName>
            </value>
            <value>
                <fullName>See Notes</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Partial Payment</fullName>
            </value>
            <value>
                <fullName>Closed - Bad Debt</fullName>
            </value>
            <value>
                <fullName>Closed - Paid</fullName>
            </value>
            <value>
                <fullName>Closed - Surplus</fullName>
            </value>
            <value>
                <fullName>Closed - Shortfall</fullName>
            </value>
            <value>
                <fullName>Payments Halted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Type_of_Loan__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Loan__c</fullName>
    <label>Type of Loan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facility Loan</fullName>
            </value>
            <value>
                <fullName>Lump-Sum</fullName>
                <default>true</default>
                <label>Lump-Sum</label>
            </value>
            <value>
                <fullName>Treatment Loan</fullName>
            </value>
            <value>
                <fullName>Treatment Loan 2</fullName>
            </value>
            <value>
                <fullName>Assessment</fullName>
            </value>
            <value>
                <fullName>Lawyer Loan</fullName>
            </value>
            <value>
                <fullName>Lawyer Loans</fullName>
                <isActive>false</isActive>
                <label>Lawyer Loans</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler {
    
    
    public static void setDiscountschedule(List<Opportunity> newOpps, Map<Id,Opportunity> oldMap, Boolean isInsert){
        
        List<Opportunity> selOpportunities = new List<Opportunity>();
        List<Assessment_Provider_Schedule__c> assessmentScheduleToInsert = new List<Assessment_Provider_Schedule__c>();
        Set<Id> assessmentProviderIds = new Set<Id>();
        Set<Id> lawyerIds = new Set<Id>();
        
        for(Opportunity opp : newOpps){
            if(opp.Type_of_Loan__c == 'Assessment' &&
               (isInsert || (!isInsert && (opp.Assessment_Provider__c != oldMap.get(opp.Id).Assessment_Provider__c ||
                                           opp.Lawyer__c != oldMap.get(opp.Id).Lawyer__c)))){
                                               
                                               selOpportunities.add(opp);
                                               assessmentProviderIds.add(opp.Assessment_Provider__c);
                                               lawyerIds.add(opp.Lawyer__c);
                                           }
        }
        
        if(!selOpportunities.isEmpty()){
            Map<String,Assessment_Provider_Schedule__c> discountscheduleMap = new Map<String, Assessment_Provider_Schedule__c>();
            for(Assessment_Provider_Schedule__c aps : [Select Id, Lawyer__c, Assessment_Provider__c, Discount__c, Rebate_Discount__c, Rebate_Period__c
                                                       FROM Assessment_Provider_Schedule__c 
                                                       WHERE Assessment_Provider__c in :assessmentProviderIds
                                                       AND Lawyer__c in :lawyerIds order by CreatedDate asc]){
                                                           discountscheduleMap.put(aps.Assessment_Provider__c + '-' + aps.Lawyer__c, aps);
                                                       }
            
            
            for(Opportunity opp : selOpportunities){
                opp.Discount_Rate__c = 0;
                opp.Rebate_Discount__c = 0;
                opp.Rebate_Period__c = null;
                
                String key = opp.Assessment_Provider__c + '-' + opp.Lawyer__c;
                if(discountscheduleMap.containsKey(key)){
                    opp.Discount_Rate__c = discountscheduleMap.get(key).Discount__c;
                    opp.Rebate_Discount__c = discountscheduleMap.get(key).Rebate_Discount__c;
                    string periodStr = discountscheduleMap.get(key).Rebate_Period__c;
                    List<String> splited = periodStr != null? periodStr.split(' ') : new List<String>();
                    opp.Rebate_Period__c = !splited.isEmpty()? Integer.valueOf(splited[0]): null;
                    
                }else if(opp.Assessment_Provider__c != null && opp.Law_Firm__c != null && opp.Lawyer__c != null){
                    assessmentScheduleToInsert.add(
                        new Assessment_Provider_Schedule__c(
                            Assessment_Provider__c = opp.Assessment_Provider__c,
                            Lawyer__c = opp.Lawyer__c,
                            Discount__c = 0
                        )
                    );
                } 
            }
        }

        if(!assessmentScheduleToInsert.isEmpty())
            insert assessmentScheduleToInsert;
    }
    
    public static void LawyerAvailableCreditRollUps(List<Opportunity> oppList, Map<Id,Opportunity> oldMap, Boolean isInsert){
        
        Set<Id> lawyerPrincipalRepaidRollUp = new Set<Id>();
        Set<Id> lawyerAmountWoPaymentRollUp = new Set<Id>();
        Set<Id> lawyerPreApprovedAmountRollUp = new Set<Id>();
        
        for(Opportunity opp : oppList){
            
            //Roll-up Amount without Payment from drawdown to lawyer.            
            if((opp.Lawyer__c != null || (!isInsert && oldMap.get(opp.Id).Lawyer__c != null)) && 
               (opp.Type_of_Loan__c == 'Assessment' || (!isInsert && oldMap.get(opp.Id).Type_of_Loan__c == 'Assessment')) &&
               (opp.Stage_Status__c == 'Active' || opp.Stage_Status__c == 'Invoice Pre-Approved' || (!isInsert && (oldMap.get(opp.Id).Stage_Status__c == 'Active' ||
                                                                                                                   oldMap.get(opp.Id).Stage_Status__c == 'Invoice Pre-Approved'))) &&
               (isInsert || (!isInsert && (opp.Type_of_Loan__c != oldMap.get(opp.Id).Type_of_Loan__c || 
                                           opp.Drawdown_Total_wo_Payment__c != oldMap.get(opp.Id).Drawdown_Total_wo_Payment__c ||
                                           opp.Lawyer__c != oldMap.get(opp.Id).Lawyer__c || opp.StageName != oldMap.get(opp.Id).StageName ||
                                           opp.Principal_Repaid_Roll_up__c != oldMap.get(opp.Id).Principal_Repaid_Roll_up__c ||
                                           opp.Stage_Status__c != oldMap.get(opp.Id).Stage_Status__c)))){
                                               
                                               
                                               if(!isInsert && opp.Lawyer__c != oldMap.get(opp.Id).Lawyer__c){
                                                   lawyerAmountWoPaymentRollUp.add(oldMap.get(opp.Id).Lawyer__c);
                                                   lawyerPrincipalRepaidRollUp.add(oldMap.get(opp.Id).Lawyer__c);
                                                   lawyerPreApprovedAmountRollUp.add(oldMap.get(opp.Id).Lawyer__c);
                                               }
                                               
                                               if(opp.Stage_Status__c == 'Invoice Pre-Approved' || (!isInsert && oldMap.get(opp.Id).Stage_Status__c == 'Invoice Pre-Approved')){
                                                   lawyerPreApprovedAmountRollUp.add(opp.Lawyer__c);
                                               }
                                               if(opp.Stage_Status__c == 'Active' || (!isInsert && oldMap.get(opp.Id).Stage_Status__c == 'Active')){
                                                   lawyerAmountWoPaymentRollUp.add(opp.Lawyer__c);
                                                   lawyerPrincipalRepaidRollUp.add(opp.Lawyer__c);
                                               }
                                           }
        }
        
        if(!lawyerPrincipalRepaidRollUp.isEmpty())
            CalPrincipalRepaidRollUpForLawyer(lawyerPrincipalRepaidRollUp);
        
        if(!lawyerAmountWoPaymentRollUp.isEmpty())
            CalAmountWoPaymentRollUpForLawyer(lawyerAmountWoPaymentRollUp);
        
        if(!lawyerPreApprovedAmountRollUp.isEmpty())
            CalPreApprovedAmountRollUpForLawyer(lawyerPreApprovedAmountRollUp);
    }
    
    private static void CalPrincipalRepaidRollUpForLawyer(Set<Id> lawyerIds){
        
        List<Contact> lawyersToUpdate = new List<Contact>();
        
        for(AggregateResult aggrResult : [SELECT Lawyer__c lawyerId, SUM(Principal_Repaid_Roll_up__c) amnt 
                                          FROM Opportunity 
                                          WHERE Type_of_Loan__c = 'Assessment'
                                          AND StageName = 'Closed With Loan'
                                          AND Stage_Status__c = 'Active'
                                          AND Lawyer__c in :lawyerIds
                                          GROUP By Lawyer__c]){
                                              lawyersToUpdate.add(
                                                  new Contact(
                                                      Id = (Id)aggrResult.get('lawyerId'),
                                                      Principal_Repaid_Roll_up__c = (Decimal) aggrResult.get('amnt')
                                                  )
                                              );
                                          }
        if(!lawyersToUpdate.isEmpty())
            update lawyersToUpdate;
    }
    
    private static void CalAmountWoPaymentRollUpForLawyer(Set<Id> lawyerIds){
        
        List<Contact> lawyersToUpdate = new List<Contact>();
        
        for(AggregateResult aggrResult : [SELECT Lawyer__c lawyerId, SUM(Drawdown_Total_wo_Payment__c) amnt 
                                          FROM Opportunity 
                                          WHERE Type_of_Loan__c = 'Assessment'
                                          AND Stage_Status__c != 'Invoice Pre-Approved'
                                          AND Stage_Status__c = 'Active'
                                          AND StageName = 'Closed With Loan'
                                          AND Lawyer__c in :lawyerIds
                                          GROUP By Lawyer__c]){
                                              lawyersToUpdate.add(
                                                  new Contact(
                                                      Id = (Id)aggrResult.get('lawyerId'),
                                                      Amount_wo_Payment_Roll_up__c = (Decimal) aggrResult.get('amnt')
                                                  )
                                              );
                                          }
        if(!lawyersToUpdate.isEmpty())
            update lawyersToUpdate;
        
    }
    
    private static void CalPreApprovedAmountRollUpForLawyer(Set<Id> lawyerIds){
        
        List<Contact> lawyersToUpdate = new List<Contact>();
                
        for(AggregateResult aggrResult : [SELECT Lawyer__c lawyerId, SUM(Drawdown_Total_wo_Payment__c) amnt 
                                          FROM Opportunity 
                                          WHERE Type_of_Loan__c = 'Assessment'
                                          AND Stage_Status__c = 'Invoice Pre-Approved'
                                          AND Lawyer__c in :lawyerIds
                                          GROUP By Lawyer__c]){
                                              lawyersToUpdate.add(
                                                  new Contact(
                                                      Id = (Id)aggrResult.get('lawyerId'),
                                                      Pre_approved_Amount_Roll_Up__c = (Decimal) aggrResult.get('amnt')
                                                  )
                                              );
                                          }
        if(!lawyersToUpdate.isEmpty())
            update lawyersToUpdate;
    }
}