force-app/main/default/objects/Critical_Date__c/Critical_Date__c.object-meta.xml
<CustomObject>
    <label>Critical Date</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Critical Date</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critical Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Critical_Date__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Critical Dates</relationshipLabel>
    <relationshipName>Critical_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Critical_Date__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>This field is used to copy account name when critical date trigger is fired.</description>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Critical_Date__c/fields/Account_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_Formula__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Critical_Date__c/fields/Accrued_Interest_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_To_Date__c</fullName>
    <label>Accrued Interest as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Critical_Date__c/fields/Outstanding_Balance_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
    <label>Outstanding Balance as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_as_of_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_From_Date__c</fullName>
    <inlineHelpText>Accrued interest on the From Date</inlineHelpText>
    <label>Accrued Interest as of From Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_as_of_Temp_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_Temp_Date__c</fullName>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF( ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),0,(Outstanding_Balance_as_of_Temp_Date__c-Amount_Adjusted_for_Payments_b4_Temp_Dt__c)+Interest_up_to_Last_Repayment_b4_Temp_Dt__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Interest Accrued up to Temp Payout Date</inlineHelpText>
    <label>Accrued Interest as of Temp Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_as_of_To_Date__c</fullName>
    <label>Accrued Interest as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Accrued_Interest_In_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Accrued_Interest_In_Reporting_Period__c</fullName>
    <formula>Accrued_Interest_as_of_To_Date__c -  Accrued_Interest_as_of_From_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accrued Interest In Reporting Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Balance_Change_In_Reporting_Period__c.field-meta.xml
<CustomField>
    <fullName>Balance_Change_In_Reporting_Period__c</fullName>
    <formula>Outstanding_Balance_as_of_To_Date__c -  Outstanding_Balance_as_of_From_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Change In Reporting Period</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Compounding_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Frequency__c</fullName>
    <description>The Opportunity__r.Interest_Compounding_Period__c replicated down to the Drawdown to avoid hitting limits in formula calculations.</description>
    <inlineHelpText>The number of times per year that interest compounds.   Expressed as an integer.   For Daily interest this value will be adjusted to either 365 or 366 depending on the interest start date.</inlineHelpText>
    <label>Compounding Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The opportunity__r.compounding_Interest__c field has been replicated here to avoid exceeding cross object formula lmits.   Field was transformed to a checkbox to simplify usage in formulas as well.</description>
    <inlineHelpText>Indicates if loan interest is compounding or simple.</inlineHelpText>
    <label>Compounding Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <description>The interest rate pulled down from the Opportunity.  Duplicated here to allow formulas to access without exceeding limits.</description>
    <inlineHelpText>Loan Interest Rate</inlineHelpText>
    <label>Interest Rate</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Drawdowns</relationshipLabel>
    <relationshipName>Drawdowns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_From_Date__c</fullName>
    <inlineHelpText>Outstanding balance on the From date</inlineHelpText>
    <label>Outstanding Balance as of From Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_Temp_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_Temp_Date__c</fullName>
    <description>NOTE: Used EXP and LN as the normal exponent function does not handle fractional numbers: See: https://developer.salesforce.com/forums/?id=906F00000008vDHIAY</description>
    <formula>IF (OR( ISPICKVAL(Reference_Notes__c,&quot;Referral Fee&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Refund&quot;),
		ISPICKVAL(Reference_Notes__c,&quot;Payment Re-processed&quot;)),0,
IF( ISPICKVAL(Payment_Method__c , &quot;Payment&quot;),Sum_of_Payment_Allocations__c - Amount__c, 
IF(Compounding_Interest__c,(Amount_Adjusted_for_Payments_b4_Temp_Dt__c*(EXP(LN(1 + (Interest_Rate__c/Compounding_Frequency__c))* 
(Compounding_Frequency__c*Interest_Accrual_Years_Pymt_to_Temp_Dt__c)))),Amount_Adjusted_for_Payments_b4_Temp_Dt__c*(1+((Interest_Rate__c/365)* Interest_Accrual_Days_Pymt_to_Temp_Dt__c)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Outstanding Balance as it will be at the Temp Payout Date. This Accounts for compounding interest or Simple Interest depending on the Loan. This is set to zero when Drawdown is Payment.  For Payments this contains the unallocated payment amount.</inlineHelpText>
    <label>Outstanding Balance as of Temp Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
    <inlineHelpText>Balance on To Date</inlineHelpText>
    <label>Outstanding Balance as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Fee</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>e-Transfer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reporting_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_From_Date__c</fullName>
    <inlineHelpText>Start date of reporting information</inlineHelpText>
    <label>Reporting From Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Reporting_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_To_Date__c</fullName>
    <inlineHelpText>End date of reporting information</inlineHelpText>
    <label>Reporting To Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Compounding_Interest__c.field-meta.xml
<CustomField>
    <fullName>Compounding_Interest__c</fullName>
    <label>Interest Compounding Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Interest_Compounding_Period__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Interest_Rate__c.field-meta.xml
<CustomField>
    <fullName>Interest_Rate__c</fullName>
    <label>Annual Interest Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Outstanding_Balance_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
    <inlineHelpText>Outstanding Balance on the Reporting To date.  Used for ELFI 1 report.  Note that this field is just labeled &quot;Outstanding Balance&quot; on the report (label changed via report type).</inlineHelpText>
    <label>Outstanding Balance as of To Date</label>
    <summarizedField>Drawdown__c.Outstanding_Balance_as_of_To_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>notEqual</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reporting_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_From_Date__c</fullName>
    <inlineHelpText>The minimum Reporting From Date on all of the Drawdowns which are eligible for inclusion in the Portfolio reports.</inlineHelpText>
    <label>Reporting From Date</label>
    <summarizedField>Drawdown__c.Reporting_From_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>notEqual</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Drawdown__c.Include_in_Portfolio_Reports__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reporting_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Reporting_To_Date__c</fullName>
    <inlineHelpText>The maximum Reporting TO Date on all of the Drawdowns which are eligible for inclusion in the Portfolio reports.</inlineHelpText>
    <label>Reporting To Date</label>
    <summarizedField>Drawdown__c.Reporting_To_Date__c</summarizedField>
    <summaryFilterItems>
        <field>Drawdown__c.Payment_Method__c</field>
        <operation>notEqual</operation>
        <value>Payment</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Drawdown__c.Include_in_Portfolio_Reports__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Drawdown__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/criticalDateTriggerHandler.cls
public with sharing class criticalDateTriggerHandler {    
    
	public static void calculatePayout(List<Critical_Date__c> criticalDateList, Map<Id,Critical_Date__c> oldMap, Boolean isInsert, boolean doDML)
    {
        /*
        Set<Id> accIds = new Set<Id>(); 
        Set<Id> selectedCriticalDateIds = new Set<Id>(); 
        for(Critical_Date__c cd : criticalDateList){
            if(isInsert || (!isInsert && (cd.Date__c != oldMap.get(cd.Id).Date__c || cd.Account__c != oldMap.get(cd.Id).Account__c)))
            {
                selectedCriticalDateIds.add(cd.Id);
                accIds.add(cd.Account__c);
            }
        }
        if(!accIds.isEmpty()){            
            String query='SELECT id,Opportunity__c,Opportunity__r.AccountId,date__c,Reporting_From_Date__c,Outstanding_Balance_as_of_From_Date__c,Accrued_Interest_as_of_From_Date__c,' +
                'Reporting_To_Date__c,Outstanding_Balance_as_of_To_Date__c,Accrued_Interest_as_of_To_Date__c,'+
                'Balance_Change_In_Reporting_Period__c,Accrued_Interest_In_Reporting_Period__c,Outstanding_Balance_as_of_Temp_Date__c, '+
                'Accrued_Interest_as_of_Temp_Date__c from drawdown__c where Payment_Method__c != \'Payment\' AND ' +
                '(Interest_Rate__c > 0) AND (Compounding_Interest__c = false OR Compounding_Frequency__c >0) AND Opportunity__r.AccountId in :accIds';            
            List<Drawdown__c> drawdowns = Database.query(query);
            
            Map<Id, List<Drawdown__c>> accToDrawdowns = new Map<Id, List<Drawdown__c>>();
            for(Drawdown__c dd : drawdowns){            
                if(!accToDrawdowns.containsKey(dd.Opportunity__r.AccountId)){
                    accToDrawdowns.put(dd.Opportunity__r.AccountId, new List<Drawdown__c>());
                }
                accToDrawdowns.get(dd.Opportunity__r.AccountId).add(dd);
            }
			
            //August 21 2019
            //Fahad:
            //making the following logic to async future so that it doesn't hit soql/cpu limits
            /*
            for(Critical_Date__c cd : criticalDateList){            
                if(accToDrawdowns.get(cd.Account__c) != null && selectedCriticalDateIds.contains(cd.Id)){
                    PortfolioReportCalculateData.calculateDataInStatic(accToDrawdowns.get(cd.Account__c), true, null, cd.Date__c);
                    AggregateResult agResult = [SELECT SUM(Outstanding_Balance_as_of_To_Date__c) outstandingBalance FROM Drawdown__c WHERE id in: accToDrawdowns.get(cd.Account__c)];
                    cd.Outstanding_Balance_as_of_To_Date__c = (Decimal) agResult.get('outstandingBalance');
                    cd.Account_Name__c = cd.Account_Name_Formula__c;
                }            
            }
            update criticalDateList;
            List<Critical_Date__c> qualifiedCriticalDates = new List<Critical_Date__c>();
            for(Critical_Date__c cd : criticalDateList){            
                if(accToDrawdowns.get(cd.Account__c) != null && selectedCriticalDateIds.contains(cd.Id)){
                    qualifiedCriticalDates.add(cd);
                }
            }
            if(!qualifiedCriticalDates.isempty())
            {
                List<AsyncApexJob> existingJobs = [select id, Status, jobtype, apexclass.name 
                                                   from AsyncApexJob 
                                                   where jobtype='Queueable' 
                                                   and apexclass.name = 'QueueableCricitalDateRecalculate' 
                                                   and status in ('Holding', 'Queued', 'Preparing', 'Processing')];
                if(existingJobs.isEmpty())
                {
                    QueueableCricitalDateRecalculate que = new QueueableCricitalDateRecalculate(qualifiedCriticalDates, accToDrawdowns, doDML);
                    Id jobId = System.enqueueJob(que);
                    try{	FlexQueue.moveJobToFront(jobId); }catch(Exception e){}
                }
                else
                {
                    throw new CustomException ('Critical Dates payout calculation is already in progress');
                }
            }
        }
        */
    } 
    public class CustomException extends exception{}
}