force-app/main/default/objects/Critical_Date__c/Critical_Date__c.object-meta.xml
<CustomObject>
    <label>Critical Date</label>
    <nameField>
        <displayFormat>CD-{0000}</displayFormat>
        <label>Critical Date</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Critical Dates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Critical_Date__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Critical Dates</relationshipLabel>
    <relationshipName>Critical_Dates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Critical_Date__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>This field is used to copy account name when critical date trigger is fired.</description>
    <label>Account Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Critical_Date__c/fields/Account_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Account_Name_Formula__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name Formula</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Critical_Date__c/fields/Outstanding_Balance_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
    <label>Outstanding Balance as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/Drawdown__c.object-meta.xml
<CustomObject>
    <label>Drawdown</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Drawdown</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Drawdowns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Drawdown__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Drawdown__c/fields/Outstanding_Balance_as_of_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Balance_as_of_To_Date__c</fullName>
    <inlineHelpText>Balance on To Date</inlineHelpText>
    <label>Outstanding Balance as of To Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QueueableCricitalDateRecalculate.cls
public class QueueableCricitalDateRecalculate implements queueable {
    SEt<Id> critDateIds;
    List<Critical_Date__c> criticalDateList;
    Map<Id, List<Drawdown__c>> accToDrawdowns;
    Boolean doDML;
    public QueueableCricitalDateRecalculate(List<Critical_Date__c> criticalDateList, Map<Id, List<Drawdown__c>> accToDrawdowns, boolean doDML)
    {
        this.criticalDateList = criticalDateList;
        this.accToDrawdowns = accToDrawdowns;
        this.doDML = doDML;
    }
	public void execute(System.QueueableContext qc)
    {
        for(Critical_Date__c cd : criticalDateList){            
            if(accToDrawdowns.get(cd.Account__c) != null ){
                PortfolioReportCalculateData.calculateDataInStatic(accToDrawdowns.get(cd.Account__c), true, null, cd.Date__c);
                AggregateResult agResult = [SELECT SUM(Outstanding_Balance_as_of_To_Date__c) outstandingBalance FROM Drawdown__c WHERE id in: accToDrawdowns.get(cd.Account__c)];
                cd.Outstanding_Balance_as_of_To_Date__c = (Decimal) agResult.get('outstandingBalance');
                cd.Account_Name__c = cd.Account_Name_Formula__c;
            }            
        }
        if(doDML)	update criticalDateList;
    }
}